### ISSUE TITLE
Datepicker - Multi Select multi-row range CSS does not support when start date is last day of week

### ISSUE THREAD

**Issue by djlimbs** [salesforce-ux/design-system#102]
The attached screenshot shows a multi select datepicker with a range where the start date is on Saturday. The markup looks to follow the requirements when using a range that spans 2 or more weeks (.slds-is-selected-multi applied to each selected td, and .slds-has-multi-row-selections applied to the rows). However, it looks like the Saturday cell is not getting the correct CSS.

<img width="1043" alt="screen shot 2015-11-13 at 11 51 00 am" src="https://cloud.githubusercontent.com/assets/4561661/11153293/83d3acc4-89fd-11e5-8780-1f320e20954f.png">

**Comment by brandonferrua** [comment]
I validated that this is indeed a bug. I'll look into it.

**Comment by rickschmoo** [comment]
This is on our roadmap but currently low priority.

**Comment by kaelig** [comment]
Note: this is still an issue in SLDS v2.0.2

**Comment by kaelig** [comment]
Note: this is still an issue in SLDS v2.2.1
