### ISSUE TITLE
Visual datepicker bug/question.

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#103]
Hi,

I'm using datepickers in table, for each row (record) I have 2 datepickers. Code is initialised in for-each loop where I generate whole html and init all javascript for datepickers. 

Here is my code:
```
text += '<td data-label=""><div class="slds-form-element"><div class="slds-form-element__control"><div class="slds-input-has-icon slds-input-has-icon--right"><svg aria-hidden="true" class="slds-input__icon slds-icon-text-default"><use xlink:href="{!URLFOR($Resource.SLDS0102,'assets/icons/utility-sprite/svg/symbols.svg#event')}"></use></svg><input id="install-'+item+'" onchange="changeInstallDate(this);" class="slds-input" type="text" placeholder="Install Date"></div></div></div></td>';
```

And javascript init just few lines below:

```js
$("#install-" + item).datepicker({ format: 'DD.MM.YYYY' }).val(caseItems[item].installDate);`
```

Here is a screenshot of distorted datepickers I get:

![ ](http://shrani.si/f/41/yx/1A96nm5p/screen-shot-2015-11-13-a.png)

As you can see day rows are going outside of dropdown area and there are no arrows around months. 
I don't know if that is some css bug or I have made something wrong in my code.

**Comment by brandonferrua** [comment]
To me, it looks like something is going on with your outputted HTML. Is there a way you can show me that HTML? not just the code to generate it

**Comment by matejp84** [comment]
Hi,

Here is my code:

`<td data-label=""><div class="slds-form-element"><div class="slds-form-element__control"><div class="slds-input-has-icon slds-input-has-icon--right"><svg aria-hidden="true" class="slds-input__icon slds-icon-text-default"><use xlink:href="{!URLFOR($Resource.SLDS0102,'assets/icons/utility-sprite/svg/symbols.svg#event')}"></use></svg><input id="install-'+item+'" onchange="changeInstallDate(this);" class="slds-input" type="text" placeholder="Install Date"></div></div></div></td>`

few lines after that I set format and initial date if it is present in data:
`$("#install-" + item).datepicker({ format: 'DD.MM.YYYY' }).val(caseItems[item].installDate);`

For datepicker I'm using aljs library where I also reported this bug, but they have forwarded me here as they suspect bug is somewhere in SLDS rather than in ALJS:
`<apex:includeScript value="{!URLFOR($Resource.aljs, '/jquery/jquery.aljs-datepicker.min.js')}"/>`

HTML output I get on page is (when opened):
`<td data-label=""><div class="slds-form-element"><div class="slds-form-element__control"><div class="slds-input-has-icon slds-input-has-icon--right"><svg aria-hidden="true" class="slds-input__icon slds-icon-text-default" style="cursor: pointer;"><use xlink:href="/resource/1446191712000/SLDS0102/assets/icons/utility-sprite/svg/symbols.svg#event"></use></svg><input id="install-0" onchange="changeInstallDate(this);" class="slds-input" type="text" placeholder="Install Date" data-aljs-datepicker-id="install-0"></div></div><div class="slds-dropdown slds-dropdown--left slds-datepicker" aria-hidden="false" data-selection="single"><div class="slds-datepicker__filter slds-grid"><div class="slds-datepicker__filter--month slds-grid slds-grid--align-spread slds-size--3-of-4"><div class="slds-align-middle"><button id="aljs-prevButton" class="slds-button slds-button--icon-container"><svg aria-hidden="true" class="slds-button__icon slds-button__icon--small"><use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#left"></use></svg><span class="slds-assistive-text">Previous Month</span></button></div><h2 id="month" class="slds-align-middle" aria-live="assertive" aria-atomic="true">December</h2><div class="slds-align-middle"><button id="aljs-nextButton" class="slds-button slds-button--icon-container"><svg aria-hidden="true" class="slds-button__icon slds-button__icon--small"><use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#right"></use></svg><span class="slds-assistive-text">Next Month</span></button></div></div><div class="slds-form-element"><div class="slds-form-element__control"><div class="slds-picklist datepicker__filter--year slds-shrink-none"><label><select class="slds-select select picklist__label"><option value="1965">1965</option><option value="1966">1966</option><option value="1967">1967</option><option value="1968">1968</option><option value="1969">1969</option><option value="1970">1970</option><option value="1971">1971</option><option value="1972">1972</option><option value="1973">1973</option><option value="1974">1974</option><option value="1975">1975</option><option value="1976">1976</option><option value="1977">1977</option><option value="1978">1978</option><option value="1979">1979</option><option value="1980">1980</option><option value="1981">1981</option><option value="1982">1982</option><option value="1983">1983</option><option value="1984">1984</option><option value="1985">1985</option><option value="1986">1986</option><option value="1987">1987</option><option value="1988">1988</option><option value="1989">1989</option><option value="1990">1990</option><option value="1991">1991</option><option value="1992">1992</option><option value="1993">1993</option><option value="1994">1994</option><option value="1995">1995</option><option value="1996">1996</option><option value="1997">1997</option><option value="1998">1998</option><option value="1999">1999</option><option value="2000">2000</option><option value="2001">2001</option><option value="2002">2002</option><option value="2003">2003</option><option value="2004">2004</option><option value="2005">2005</option><option value="2006">2006</option><option value="2007">2007</option><option value="2008">2008</option><option value="2009">2009</option><option value="2010">2010</option><option value="2011">2011</option><option value="2012">2012</option><option value="2013">2013</option><option value="2014">2014</option><option value="2015">2015</option><option value="2016">2016</option><option value="2017">2017</option><option value="2018">2018</option><option value="2019">2019</option><option value="2020">2020</option><option value="2021">2021</option><option value="2022">2022</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option></select></label></div></div></div></div><table class="datepicker__month" role="grid" aria-labelledby="month"><thead><tr id="weekdays"><th id="Sunday"><abbr title="Sunday">S</abbr></th><th id="Monday"><abbr title="Monday">M</abbr></th><th id="Tuesday"><abbr title="Tuesday">T</abbr></th><th id="Wednesday"><abbr title="Wednesday">W</abbr></th><th id="Thursday"><abbr title="Thursday">T</abbr></th><th id="Friday"><abbr title="Friday">F</abbr></th><th id="Saturday"><abbr title="Saturday">S</abbr></th></tr></thead><tbody><tr><td data-aljs-date="11/29/2015" headers="Sunday" class="slds-disabled-text"><span class="slds-day">29</span></td><td data-aljs-date="11/30/2015" headers="Monday" class="slds-disabled-text"><span class="slds-day">30</span></td><td data-aljs-date="12/01/2015" headers="Tuesday" class="slds-is-today"><span class="slds-day">1</span></td><td data-aljs-date="12/02/2015" headers="Wednesday"><span class="slds-day">2</span></td><td data-aljs-date="12/03/2015" headers="Thursday"><span class="slds-day">3</span></td><td data-aljs-date="12/04/2015" headers="Friday"><span class="slds-day">4</span></td><td data-aljs-date="12/05/2015" headers="Saturday"><span class="slds-day">5</span></td></tr><tr><td data-aljs-date="12/06/2015" headers="Sunday"><span class="slds-day">6</span></td><td data-aljs-date="12/07/2015" headers="Monday"><span class="slds-day">7</span></td><td data-aljs-date="12/08/2015" headers="Tuesday"><span class="slds-day">8</span></td><td data-aljs-date="12/09/2015" headers="Wednesday"><span class="slds-day">9</span></td><td data-aljs-date="12/10/2015" headers="Thursday"><span class="slds-day">10</span></td><td data-aljs-date="12/11/2015" headers="Friday"><span class="slds-day">11</span></td><td data-aljs-date="12/12/2015" headers="Saturday"><span class="slds-day">12</span></td></tr><tr><td data-aljs-date="12/13/2015" headers="Sunday"><span class="slds-day">13</span></td><td data-aljs-date="12/14/2015" headers="Monday"><span class="slds-day">14</span></td><td data-aljs-date="12/15/2015" headers="Tuesday"><span class="slds-day">15</span></td><td data-aljs-date="12/16/2015" headers="Wednesday"><span class="slds-day">16</span></td><td data-aljs-date="12/17/2015" headers="Thursday"><span class="slds-day">17</span></td><td data-aljs-date="12/18/2015" headers="Friday"><span class="slds-day">18</span></td><td data-aljs-date="12/19/2015" headers="Saturday"><span class="slds-day">19</span></td></tr><tr><td data-aljs-date="12/20/2015" headers="Sunday"><span class="slds-day">20</span></td><td data-aljs-date="12/21/2015" headers="Monday"><span class="slds-day">21</span></td><td data-aljs-date="12/22/2015" headers="Tuesday"><span class="slds-day">22</span></td><td data-aljs-date="12/23/2015" headers="Wednesday"><span class="slds-day">23</span></td><td data-aljs-date="12/24/2015" headers="Thursday"><span class="slds-day">24</span></td><td data-aljs-date="12/25/2015" headers="Friday"><span class="slds-day">25</span></td><td data-aljs-date="12/26/2015" headers="Saturday"><span class="slds-day">26</span></td></tr><tr><td data-aljs-date="12/27/2015" headers="Sunday"><span class="slds-day">27</span></td><td data-aljs-date="12/28/2015" headers="Monday"><span class="slds-day">28</span></td><td data-aljs-date="12/29/2015" headers="Tuesday"><span class="slds-day">29</span></td><td data-aljs-date="12/30/2015" headers="Wednesday"><span class="slds-day">30</span></td><td data-aljs-date="12/31/2015" headers="Thursday"><span class="slds-day">31</span></td><td data-aljs-date="01/01/2016" headers="Friday" class="slds-disabled-text"><span class="slds-day">1</span></td><td data-aljs-date="01/02/2016" headers="Saturday" class="slds-disabled-text"><span class="slds-day">2</span></td></tr></tbody></table></div></div></td>`

**Comment by kaelig** [comment]
Brandon, can you follow up on that issue?

**Comment by rickschmoo** [comment]
JS support is outside the scope of the Design System.
