### ISSUE TITLE
[React component] Should remove css style on body upon modal dismissal

### ISSUE THREAD

**Issue by leiwlotus** [salesforce-ux/design-system#105]
![screen shot 2015-11-16 at 6 29 09 pm](https://cloud.githubusercontent.com/assets/10578084/11228984/dd1f7f56-8d45-11e5-8941-627a272a33b9.png)

**Comment by leiwlotus** [comment]
This is causing scrolling issue in Matrix data pipe page.

**Comment by leiwlotus** [comment]
Moving it to design-system-react

**Comment by cosminnicula** [comment]
Yey!
