### ISSUE TITLE
Checkbox in Horizontal Form is right aligned - should be on same position as other fields

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#11]
The Checkbox and the slds-form-element__help span are right aligned in a plain horizontal form.

can be fixed by using the approach for compound form, but should I think be properly aligned on the same level as the other fields in a horizontal form.

**Comment by srohde** [comment]
Thanks for reporting, can you please add a screenshot?

**Comment by jorgjanke** [comment]
Direct checkout:
http://lightningdart.com/#/desktop
- go to "Forms"
- change to Form Type to "Horizontal"

Here the screenshot

![2015-09-15_14-11-53](https://cloud.githubusercontent.com/assets/168846/9890271/de3afe56-5bb3-11e5-926e-d8f1f15243f3.png)

**Comment by brandonferrua** [comment]
Thanks for reporting this @jorgjanke 

I'll add a checkbox and radio example to the horizontal form, these two types require additional HTML to display properly within those variations. Expect a fix soon.

**Comment by brandonferrua** [comment]
This is resolved in our 0.9.2 build
