### ISSUE TITLE
.slds-pill__remove not working

### ISSUE THREAD

**Issue by MarcBKirsch** [salesforce-ux/design-system#117]
.slds-pill__remove does not work properly. The "x" does not show up.
I was using the examples from the website https://www.lightningdesignsystem.com/components/pills.
![pill-issue](https://cloud.githubusercontent.com/assets/15914824/11378103/e87aae62-92e9-11e5-84e7-4e4a4e243033.jpg)

**Comment by stefsullrew** [comment]
Without seeing the code, it's hard to say what is wrong. But from the look of the icons above, it seems like your icons aren't showing up at all. Did you include the icon sprite? Are you linking properly to the icon path in the `<use>` element? Do you have icons showing up anywhere else?

**Comment by MarcBKirsch** [comment]
@stefsullrew Thanks for the hint. My oversight was that I didn't correctly linked it to the Static Resource in Salesforce. Thanks for the fast response!
