### ISSUE TITLE
The components in "Prototype" stage are not working.

### ISSUE THREAD

**Issue by srishty29** [salesforce-ux/design-system#12]
The components that are in "dev ready" stage have been successfully implemented in Visualforce and lightning but those components in "prototype" stage like "picklist,lookups" and many others are not working as desired using the code provided. 
Should we wait for any other release when these components will be changed to "Dev Ready" state or we are missing on implementing it using some javascript.

Kindly guide on same.

**Comment by BrunoFonzi** [comment]
Thanks for the feedback. Currently the Design System is delivering a CSS framework only and JS framework agnostic. We are considering this as feature request. Thank you again.
