### ISSUE TITLE
Select styles in Safari

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#122]
I noticed in Safari that SLDS `<select>` tags carry standard browser styles. Is this intended? I tried seeing if `-webkit-appearance: none` would fix this but it removes more styles than intended.

![screen shot 2015-11-25 at 4 33 05 pm](https://cloud.githubusercontent.com/assets/8738640/11411512/35c62c76-9396-11e5-918e-abf6a6c657c7.png)

**Comment by kaelig** [comment]
Thank you @kevinberonilla for the question. This styling is intended, but if you find an elegant way to make it look less "native" and more "Salesforce", then feel free to open a pull request.
