### ISSUE TITLE
slds-text-body--small helper class overrides theme text color

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#123]
I've created a box with the *slds-theme--error* theme, and wanted to display smaller text in it. I used the *slds-text-body--small* helper class, however this class overrides the theme color by setting text color to *#54698d*:

    <div class="slds-box slds-theme--error">
        <p class="slds-text-body--small">Trailhead is awesome.</p>
    </div>

**Comment by jina** [comment]
This utility wasn't designed to be used in the themes, but I can see that there'd be a need for this. I'll take a look at how we want to adjust this. Thanks for the heads up!

In the meantime, if you need a quick fix, here is an override you can drop in your styles:

```scss
.slds-theme--error .slds-text-body--small {
  color: inherit;
}
```

**Comment by FabienTaillon** [comment]
I wasn't sure it could be used like this, but as the "APPLIED TO" section was empty, I thought it could be used wherever we wanted.
Thanks for the tip ! :)

**Comment by stefsullrew** [comment]
Hi @FabienTaillon - I've added this fix to the themes in our utilities. It will be in your build on the next release. Cheers!
