### ISSUE TITLE
Using slds-scrollable--x class on table cuts off any lookup dropdown that is out of table bounds

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#124]
I have found a bug that when using slds-scrollable--x class on table and having lookup dropdowns in rows, dropdown gets "cut-off" at the bottom if I use it in row. It is built and everything, but it is like it is behind making it invisible and useless.

**Comment by kaelig** [comment]
Hi @matejp84, thank you for using the Salesforce Design System and for reporting this bug.

Can you please share the problematic code so we can investigate?

**Comment by kaelig** [comment]
After investigation, it looks like that the dropdown should be inserted at the very end of the document, to make sure it can be overlayed above everything else.

e.g.

```html
<!-- put overlay here -->
</body>
</html>
```

More to come on this.

**Comment by kaelig** [comment]
@matejp84 after looking into this issue further, here is our recommendation:

- Use a [popover](https://www.lightningdesignsystem.com/components/popovers), position it with JavaScript
- Inside the popover, place the Lookup component

OR

- Position the Lookup component using JavaScript just like if it were a popover

This requires a bit more work but it looks like it's the only way.

Let us know how this went!

**Comment by kaelig** [comment]
Closing this as it is almost been a month.

@matejp84: Feel free to reopen the issue if that's a problem you are still running into.
