### ISSUE TITLE
Webpack config example

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#127]
Does anyone have a work webpack config file working with the scss files?

**Comment by kaelig** [comment]
Hi @banderson5144, thank you for your interest in the Salesforce Lightning Design System.

This is something we're looking closely at, and we'll keep you updated of our progress using Webpack for compiling Sass files (if we end up doing so).

**Comment by banderson5144** [comment]
How do your currently compile?

**Comment by kaelig** [comment]
We currently compile using gulp tasks and node-sass.

Here is where the magic happens: https://github.com/salesforce-ux/design-system/blob/456d8fd149ef31361222d4076672dbec1e123441/scripts/dist.js#L90

We're looking at breaking these tasks down into a few specific ones and maybe use webpack for it.

**Comment by aputinski** [comment]
Here's a simple webpack example: https://gist.github.com/aputinski/6d685e81a075d70194a3

**Comment by mitsuruog** [comment]
@aputinski awesome :+1:

**Comment by cliffordfajardo** [comment]
I had trouble loading the `index.scss` file from the `@salesforce-ux/design-system/scss/index.scss`, but I have it working now. webpack config below:
I was able to maintain hot-reloading this way.

```js
var path = require('path');
var buildDir = path.resolve(__dirname, 'build/');
module.exports = {
  entry: [
    path.resolve(__dirname, 'client/app.module.js')
  ],
  output: {
    path: buildDir,
    publicPath: 'http://localhost:8080/',
    filename: 'app.js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        query: {
          cacheDirectory: true,
          presets: ['es2015']
        },
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css?sourceMap','resolve-url','sass?sourceMap'], //the resolve-url loader is also needed!
        exclude: /node_modules/
      },
      //needed to resolve fonts, svg's when using @Import..without this you will error. I had exclude node_modules here before & that was a big mistake that cost me hours
      {
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg)$/,
        loader: 'url-loader?limit=100000'
      }
    ]
  }

};
```
