### ISSUE TITLE
Tooltip Animations

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#129]
This is more of a question than an issue.

Under Components > Forms > Field Level Help (https://www.lightningdesignsystem.com/components/forms#field-level-help), I noticed the tooltip animates with show/dismiss CSS transitions. Is this the intended behavior of all tooltips, or just help text?

Thanks!

**Comment by brandonferrua** [comment]
This is intended behavior for all tooltips, the field level help just happens to be the only one demonstrating that at the moment.
