### ISSUE TITLE
JS - design system component interact

### ISSUE THREAD

**Issue by bikrambebarta** [salesforce-ux/design-system#13]
Hi,
  I am using this SLDS in my one of visualforce page. I was checking the picklist component. one thing i  found upon selecting any picklist value it is not reflecting means changing to the picklist value.In the documentation https://www.lightningdesignsystem.com/components/picklists/  how the picklist is properly behaving. Do i need to add any js file or what to do . And what is this attribute 'data-reactid'.Is it anything related to the above problem. Also is this script creating 'reactid' .
"LIGHTNING_DESIGN_SYSTEM.init('components/picklists/index.jsx')"
sorry for if it sounds silly. But I really need to make it work on my this VF page.
Please reply asap.

Thank You.

**Comment by santosharigi** [comment]
Hi,
I'm facing same issue with Picklist component in Lightning Page.I included "salesforce-lightning-design-system-ltng.css" in my component,but functionality was not as expected. 
1)Picklist Options should be visible only when i click on Down arrow on Picklist, but by default it is visible.
2)When clicked again on Picklist dropdown ,the Picklist Options should be hidden which is not happening.
3)Also In the example given in the documentation https://www.lightningdesignsystem.com/components/picklists the picklist options are not  hidden  when any picklist option is selected.

Is there any thing i got missed like any CSS file or any JS file.

Please help me regarding this issue.

Thank you.

**Comment by bikrambebarta** [comment]
Hi @santosharigi  I still not have found out how in the documentation page the picklist functionality is working and not in our vf page. I ll post if any solution i get.

Thanks

**Comment by stefsullrew** [comment]
Thanks for your feedback. We're currently providing CSS, but you'll need to add your own JS based on whatever framework your building on. We have a feature request for JS open now. Cheers!
