### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#132]
When I use icon like that:
`<use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#search"></use>`
it doesn't show up and I get errors in console:
`Unsafe attempt to load URL https://cs80.salesforce.com/assets/icons/standard-sprite/svg/symbols.svg#account from frame with URL https://c.cs80.visual.force.com/apex/VnosSerijskih#. Domains, protocols and ports must match.`

If I use it like this:
`<use xlink:href="{!URLFOR($Resource.SLDS0120,'assets/icons/utilitysprite/svg/symbols.svg#search')}"></use>`
It works normally.

**Comment by rickschmoo** [comment]
As per https://www.lightningdesignsystem.com/getting-started/visualforce , you must use the urlfor path syntax in Visualforce
