### ISSUE TITLE
how to use SCSS code, given by resources code? it is instead of javascript?

### ISSUE THREAD

**Issue by krrish9** [salesforce-ux/design-system#133]
Hi Guys,

I'm new to salesforce - Lightning design system. Using resources example i trying to build a static web pages. But i unable to use svg sprites. For tabs and dorpdowns  have some scss code. Where can i place?  Anyone help me...

**Comment by kaelig** [comment]
Hi @krrish9, thank you for your interest in the Salesforce Lightning Design System.

*.scss files are Sass files. You can learn more about it [Sass' official website](http://www.sass-lang.com/).

If Sass, npm or bower unfamiliar to you, we recommend downloading the packaged CSS, icons and fonts  here: https://www.lightningdesignsystem.com/resources/downloads/#framework

Once you extract the downloaded zip file, you'll find the CSS files, images, icons and fonts in the `assets/` directory.

Hope it helps, and please let us know if you need additional assistance.
