### ISSUE TITLE
Typo and missing words from docs: components/trees

### ISSUE THREAD

**Issue by mejarc** [salesforce-ux/design-system#134]
What I did:

1. run `npm run dev`
2. go to `localhost:3000/components/trees` in the browser

What I saw:
`A tree is visualization a structure heiarchy` in the Site Text Introduction

What I expected: something more like `A tree is a visualization of a structure heirarchy`

**Comment by kaelig** [comment]
Thank you @mejarc, good catch!

I'd even expect hierarchy to be spelt correctly :)

**Comment by kaelig** [comment]
Fixed in 1a18b32.
