### ISSUE TITLE
Sales path title text cut off

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#135]
The path titles (labels) of the Tab Sales Path are not rendered correctly:
![2015-12-11_14-19-27](https://cloud.githubusercontent.com/assets/168846/11757888/eafcea50-a019-11e5-8734-3586dad9ef80.png)
The left side can be improved by 
```
.slds-tabs--path__title {
  padding-left: 0.15rem;
}
```
(or increasing the padding on slds-tabs--path__link)

but did not find a solution for the **right** side.
The truncate 
text-overflow: ellipsis
on slds-tabs--path__link does not apply

**Comment by kaelig** [comment]
Thank you @jorgjanke for reporting yet another issue, this is very helpful.

Can you specify what browser (+ version) and device the bug appears in?

**Comment by jorgjanke** [comment]
has nothing to do with browser. the OS does not start it. this was Path
Finder - same happens when starting from Finder or command line

Jorg Janke - www.accorto.com - (650) 227-3271

**Comment by kaelig** [comment]
> the OS does not start it. this was Path
Finder - same happens when starting from Finder or command line

Can you clarify? I'm not sure I follow. Is this related to this issue?

**Comment by jorgjanke** [comment]
... uups very sorry - mixed up with a very different issue.

The screenshot was Chrome, but same happens in Safari and FF. Looking at the css, I think it not browser specific. Demo: 
http://lightningdart.com/#/desktop
click on / navigate to: Tabs
It's basically happening if the component is limited in width. 
It's independent from the overflow: auto on tabs--path (then it exceeds the boundary set in the parent div)

**Comment by stefsullrew** [comment]
I see the bug. Thanks @jorgjanke — I'm working on some other issues in Sales path now, so I'll fix this truncation. For now, if you need to fix it, you can move the four truncation properties from the `<a>` to the `.slds-tabs--path__title`.

**Comment by jorgjanke** [comment]
Thanks - although to keep the truncation in general would be a good feature in case the labels are very long.

**Comment by stefsullrew** [comment]
We are keeping the truncation. I just made it work properly. ;)

**Comment by kaelig** [comment]
Thanks again @jorgjanke, we've made the change on our side and the fix will be available very soon on this very repository.
