### ISSUE TITLE
Difference between CSS files in /assets/styles

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#137]
What is the difference between:

.css
ltng.css
scoped.css
vf.css

**Comment by jina** [comment]
`.css` is the standard, regular file.

`ltng` is a file has changes in it that are needed for use in lightning apps & components.

`scoped` is for use when combining with other frameworks such as Bootstrap. It helps avoid clashes.

`vf` is for use with Visualforce. :)

**Comment by banderson5144** [comment]
I guess my question is that I really don't see any difference in the file. Can you point one out?

**Comment by kaelig** [comment]
@jina looks like this is a good case for looking at clarity in our file naming conventions.

**Comment by jina** [comment]
There's definitely differences. In the regular file, we have some base styles applied on body, links, and such. But in the scoped files, everything is inside a .slds class.

Then routes of fonts are different as well. Each file is tweaked to work best in their respective environments. :)

**Comment by stefsullrew** [comment]
@banderson5144 - there are slight differences. For example, in Visualforce, we had to override the issue of VF not using a 16px base font size. So rather than using REMs for sizing, we used maths to change to pixel values (or everything was very small).

The basic scoped.css file (for use with your bespoke CSS or other framework) just allows you to protect each framework from the base element selectors that don't use classes. Here's a little piece from a document I've been writing (but isn't yet published):

>In some cases, when you don’t have full control of the DOM (for example, when integrating with Visualforce, Lightning Components or another framework), you may need to scope components built with SLDS. In this case, three different versions of the CSS framework are available in the download. 

>The components built from SLDS should have the class .slds at the highest level of the DOM where they’re included. In some cases this will be a wrapper at the component level, in other cases you may wrap several components. Do not place .slds on the body level of the application if you are including non-slds components within it. This would cause the non-slds components to be scoped and may override expected styles with negative effects.

Hope that helps!

**Comment by banderson5144** [comment]
Ok. I thought pre-pending slds to everything makes it scoped to begin with

**Comment by jina** [comment]
The classes have `.slds-` in the class name to scope, but the additional class of `slds` in the scoped files allows you to make sure your styles are only hitting areas on the page that is wrapped in that class.
