### ISSUE TITLE
Popover header is not left-aligned properly

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#138]
In 0.12.1, the popover header is not left-aligned properly. At least, it now appears differently than it did in prior versions of SLDS.

<div class="slds" style="margin: 20px">
        <div class="slds-popover slds-nubbin--left" role="dialog">
            <div class="slds-popover__content">
                <div class="slds-popover__header">
                    <p class="slds-text-heading--small">Hello World</p>
                </div>
                <div class="slds-popover__body">Salesforce Lightning is cool!</div>
            </div>
        </div>
    </div>

**Comment by brandonferrua** [comment]
The popover header was deprecated and now requires a spacing utility, see preview-panel variant
