### ISSUE TITLE
Skinning default Salesforce

### ISSUE THREAD

**Issue by marcelosomers** [salesforce-ux/design-system#139]
*Note: I'm pretty new to Salesforce, so let me know if any of this does not make sense!*

I'm working with a client who is mostly using a stock Salesforce implementation (i.e., no VisualForce pages, or standard pages are used in conjunction with VisualForce). Is it possible to update the CSS on these standard pages? I've recompiled my own SLDS CSS files by updating the design tokens and replaced the default zip file (SLDS090.zip) under static assets. However, I noticed that the standard pages do not use any of the `.slds-*` classes.

So is there any way to skin a non-VisualForce page?

Thanks for all your team is doing!

**Comment by kaelig** [comment]
Hi @marcelosomers, thank you for using the Lightning Design System!

Can you clarify what you mean by "standard pages" and "non-VisualForce page"?

**Comment by marcelosomers** [comment]
Tell me if I'm missing something here - but my client currently uses the Opportunities and Leads area, and nothing else. Everything in there is not a custom VisualForce app, but the "stock" old UI (non-Lightning).

There is an option in our Sandbox to flip the switch and see those screens in the Lightning style. I assumed I'd be able to rebuild my Sass files to update the colors on those stock screens, but it doesn't look like those screens even use the same classes from the SLDS documentation.

Is this not a scenario that's supported by SLDS? Is it only for custom VisualForce/Lightning apps?

**Comment by kaelig** [comment]
Thank you for taking the time to explain.

You are correct: SLDS is not meant to style old pages (the "Aloha" design), as it is designed to style Lightning Components and Visual Force pages.

If you'd like to update the branding to match your client's brand guidelines, you can compile the SCSS files, override the values ([design tokens](https://www.lightningdesignsystem.com/resources/tokens)) in the `design-tokens.scss` file, and then use this custom build of the SLDS in your client's installation.

I hope it helps.

**Comment by marcelosomers** [comment]
Thanks for the info, @kaelig! Very helpful.
