### ISSUE TITLE
lightning design system for horizontal form

### ISSUE THREAD

**Issue by SupriyaVenkatesh** [salesforce-ux/design-system#14]
Hi,
As this is not an issue but i had one question regarding this please check below
how to display the fields in horizontal way inside apex:repeat tag of salesforce with SLDS classes
<fieldset class="slds-box slds-container--large">
<form class="slds-form--inline">
<apex:repeat value="" var="">
                 
 <span class="slds-form-element__label"></span> <
 <apex:inputField styleclass="slds-input--small" value="" rendered="" required=""/><p></p>
 <apex:inputField styleclass="slds-input--small" value="" rendered="" />
     
 </apex:repeat>
</form>
</fieldset>

**Comment by rickschmoo** [comment]
SLDS is not yet supported by legacy <apex> tags since many of them generate incompatible markup. That said, I would expect <apex:repeat> to work since it is a simple loop. Can you include your code?

**Comment by SupriyaVenkatesh** [comment]
<apex:repeat value="{!$ObjectType.Job__c.FieldSets.OrderStep1}" var="fieldAPI">
                       <tr>  
                     
                         <apex:outputLabel rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}"><td style="padding-top: .5em;padding-bottom: .5em;"><span class="slds-form-element__helper">Currency</span></td></apex:outputLabel>
                           <div class="slds-form-element slds-has-error slds-is-required"> 
                         <td ><apex:inputField styleclass="slds-input--small" value="{!job[fieldAPI]}" onChange="changeCurrencySelection()" rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}" /></td>
                       </div>
                      </tr> 
                </apex:repeat>

**Comment by SupriyaVenkatesh** [comment]
<apex:repeat value="{!$ObjectType.Job__c.FieldSets.OrderStep1}" var="fieldAPI">
 <tr>   <apex:outputLabel rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}"><td style="padding-top: .5em;padding-bottom: .5em;"><span class="slds-form-element__helper">Currency</span></td></apex:outputLabel>
                           <div class="slds-form-element slds-has-error slds-is-required"> 
                         <td ><apex:inputField styleclass="slds-input--small" value="{!job[fieldAPI]}" onChange="changeCurrencySelection()" rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}" /></td> </div></tr> 
 </apex:repeat>

**Comment by SupriyaVenkatesh** [comment]
<apex:repeat value="{!$ObjectType.Job__c.FieldSets.OrderStep1}" var="fieldAPI">
                       <tr>  
                     
                         <apex:outputLabel rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}"><td style="padding-top: .5em;padding-bottom: .5em;"><span class="slds-form-element__helper">Currency</span></td></apex:outputLabel>
                           <div class="slds-form-element slds-has-error slds-is-required"> 
                         <td ><apex:inputField styleclass="slds-input--small" value="{!job[fieldAPI]}" onChange="changeCurrencySelection()" rendered="{!fieldAPI == 'invoiceit_s__CurrencyL__c'}" /></td>
                       </div>
                      </tr> 
                </apex:repeat>

**Comment by stefsullrew** [comment]
Since we've not heard any further on this, I'm going to close it. If the issue still exists, please reopen the issue @SupriyaVenkatesh. Cheers!
