### ISSUE TITLE
Can the SVG4Everybody.js be included with Lightning

### ISSUE THREAD

**Issue by jackiedpeacock** [salesforce-ux/design-system#140]
According to the information in the following link -https://developer.salesforce.com/trailhead/lex_dev/lightning_design_system/lightning-design-system5 -  Lightning UI's that use SVG's will always need to reference SVG4Everbody.js to be compatible with IE.

So - can SVG4Everybody.js be automatically included with Lightning?  Otherwise we'll all be adding our own static resource for this - so an org could have many duplicates of this script.

**Comment by kaelig** [comment]
Hi @jackiedpeacock, thank you for using the Salesforce Lightning Design System!

Your question is very interesting and we have been debating it for a few weeks.

On the one hand, including dependencies would ensure "it just works".

On the other hand, these included dependencies could become outdated very quickly and patching/upgrading them would require a new set of releases of the Lightning Design System. We are reticent to release buggy versions of a third party piece of software that we couldn't upgrade in an efficient way.

There are also many ways to include a JavaScript dependency in a document, and we don't want to force our users into a certain pattern.

This topic is still open for discussion, as we'd like to gather as much feedback and use cases before we make a final decision.

/cc @srohde @aputinski @stefsullrew

**Comment by kevinberonilla** [comment]
I would like to see this implemented as well, although the concerns @kaelig raised are completely legitimate ones. I don't mind managing a static resource if that's what it comes down to.

I assume IE11 won't fix this anytime soon (or ever) so including it as a dependency might actually be okay.

**Comment by scicero7932** [comment]
+1 for this implementation. I am currently including svg4everybody as a static resource in my package.

**Comment by bekos** [comment]
SVG4Everybody can be downloaded only when user is using IE. If this is going to be included in Lightning by default, you would penalty all other users, using Chrome, Firefox etc.

**Comment by kaelig** [comment]
Feature requests and questions related to Lightning should be made on the IdeaExchange: https://help.salesforce.com/articleView?id=000205453&type=1
