### ISSUE TITLE
.slds-button--brand support for .slds-button-group

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#143]
Currently, `.slds-button-group` works with brand-themed buttons although there are no borders. Is it possible to add support for white borders on brand-colored button groups?

I created my own code to support them in an app I'm working on, but something official would be nice. I haven't looked at the SCSS structure for button groups in your repo yet, but if you'd like I can submit a pull request for a solution that fits.

![screen shot 2016-01-12 at 9 09 33 am](https://cloud.githubusercontent.com/assets/8738640/12267319/2733d1a8-b90d-11e5-9c26-47b4405412c5.png)

What I'm currently using to achieve this:
https://gist.github.com/kevinberonilla/351bc553b637a1266651

**Comment by kaelig** [comment]
Closing this as the feature-request is a year old and it hasn't seen activity or support requests from other customers.
