### ISSUE TITLE
Stencils

### ISSUE THREAD

**Issue by rahulpatidar** [salesforce-ux/design-system#146]
How to use Stencils in lightning experience salesforce

![stencils](https://cloud.githubusercontent.com/assets/6771587/12294366/da76746a-ba1f-11e5-9916-d2567770518a.PNG)

**Comment by kaelig** [comment]
Thank you for asking, @rahulpatidar.

Before we come back to an answer, allow me to clarify that this refers to loading stencils. https://www.lightningdesignsystem.com/design/loading

> Stencils are placeholders that visually communicate that content is in the process of loading.

**Comment by kaelig** [comment]
Closing this as it's a duplicate of #193
