### ISSUE TITLE
React 

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#147]
I see in your repo react components so you going to release React components soon ?

**Comment by srohde** [comment]
It's very likely to happen sooner than later.
Please stay tuned. I'll update this issue...

**Comment by wes1278** [comment]
Wait what???!!! For real @srohde ? Last I heard, that wasn't happening. Safe harbor of course, but are you guys going to release "some" full blown React components JavaScript and all? Ie datepicker?

**Comment by srohde** [comment]
Please stay tuned @wes1278. I'll have more info next month.

**Comment by ButuzGOL** [comment]
I also want to mention 
https://github.com/stomita/react-lightning-design-system 
so may thinking of integration to not to do twice

**Comment by srohde** [comment]
We don't have any plans to release a React component library.
If you want to build Lightning we encourage to start here: https://developer.salesforce.com/lightning

**Comment by srohde** [comment]
Salesforce has open sourced Design System for React: https://github.com/salesforce/design-system-react

**Comment by istiti** [comment]
What about Angular Components ? 

/cc @srohde
