### ISSUE TITLE
Lightning Components Data Table issue.

### ISSUE THREAD

**Issue by fairozulla409** [salesforce-ux/design-system#148]
In the Lightning design systems, there is a problem in the data table block where they have given the layouts, but the large layouts are working great, but in the small layouts the checkbox are not displaying, i kindly request to resolve the issue as soon as possible...............Thanks 

![screen shot 2016-01-20 at 1 00 26 pm](https://cloud.githubusercontent.com/assets/11041797/12442487/5d60ab74-bf76-11e5-94c4-253651c9fafe.png)
![screen shot 2016-01-20 at 12 59 10 pm](https://cloud.githubusercontent.com/assets/11041797/12442488/5d641a02-bf76-11e5-8ffa-9996b9867da6.png)

**Comment by kaelig** [comment]
Hi @fairozulla409, thank you for using the Lightning Design System, and for reporting this issue.

We will be looking into it shortly, thank you for your patience.

**Comment by kaelig** [comment]
This issue was fixed in SLDS v2.0.0. Thank you again for reporting this @fairozulla409!
