### ISSUE TITLE
Better use of real estate for Header Action Buttons

### ISSUE THREAD

**Issue by jimpdx** [salesforce-ux/design-system#149]
As we migrate our browser, phone and tablet UI over to LDS I find it disturbing that the headerActions DIV can not show more buttons before collapsing the additional ones into the dropdown list to the right. Since this specific issue deals with the SFDC implementation of LDS (which I assume is customized) does this belong on the IdeaExchange or here?

![image](https://cloud.githubusercontent.com/assets/867051/12461789/8efc130a-bf6f-11e5-99fe-3bf8ba4dec97.png)

**Comment by rickschmoo** [comment]
Thanks for raising this! Yes, it does belong in IdeaExchange, so please add it there.
