### ISSUE TITLE
Pre-requisites required for all these components 

### ISSUE THREAD

**Issue by srishty29** [salesforce-ux/design-system#15]
Hi There,

Is there any pre-requisite javascript required for loading these components?Can you please help us on same.

**Comment by mwraith** [comment]
It's a little odd as it's stated that the framework is CSS only, but the dynamic components (e.g. tabs, picklists, popups, date pickers, etc.) won't work without javascript. I don't see it explained anywhere in the docs, but I think at the moment you have to write your own javascript to do the event bindings. Hopefully in the future they will also distribute a JS file like Bootstrap. It seems something must already exist as the demos on this site work.

**Comment by stefsullrew** [comment]
You're absolutely correct @mwraith ... We have an enhancement request for JS and we are looking at where it falls in our priorities. Stay tuned!
