### ISSUE TITLE
Selects and Input Heights Vary

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#150]
I just noticed the height of select elements and text inputs are different; selects are a few pixels shorter. This is the case for Safari, Chrome and Firefox on Mac. Is this intended?

![screen shot 2016-01-20 at 4 27 26 pm](https://cloud.githubusercontent.com/assets/8738640/12465371/4a8193c0-bf93-11e5-9359-3c417dfdd5c4.png)

**Comment by rickschmoo** [comment]
Thanks for the bug. Please can you supply some sample markup so we can investigate further?

**Comment by kevinberonilla** [comment]
Sure, it's apparent using 0.12.1 and the following markup:
https://gist.github.com/kevinberonilla/fb8f26f30931898b0dff

**Comment by wwwdata** [comment]
I can confirm this, a normal input field is 2 pixel higher than a select field. You can just click and inspect the elements on https://www.lightningdesignsystem.com/components/forms/#select and see the differences.

**Comment by kaelig** [comment]
Reopening this. We can close it when the fix makes it to the next public patch.

**Comment by kaelig** [comment]
This was fixed in v2.0.2, thank you for your patience!

**Comment by kaelig** [comment]
This should be fixed in v2.0.2, thank you again for reporting this!
