### ISSUE TITLE
Request for Mockup Tool

### ISSUE THREAD

**Issue by jnovakoff** [salesforce-ux/design-system#152]
Consider adding SLDS/Lightning Experience to a popular prototype/mockup tool and maintaining the current version there.  Very helpful for working with clients to help transition them from Aloha to LEX.

**Comment by kaelig** [comment]
The Design System now provides a [Sketch UI Kit](https://github.com/salesforce-ux/design-system-ui-kit) and a [Starter Kit](https://github.com/salesforce-ux/design-system-starter-kit) for prototyping in the browser. Enjoy!

**Comment by cedv17** [comment]
You can use [Avonni Creator](https://www.avonnicreator.com). Exclusively designed for the Salesforce Lightning UI experience.
