### ISSUE TITLE
Default text CAN'T be identical to input text.

### ISSUE THREAD

**Issue by jessemorano** [salesforce-ux/design-system#154]
When default text for blank form fields looks the exact same as text the user has input manually, then it's a recipe for confusion.  Default text IS gray and has been gray for a long time and for a very good reason.  It's NOT data and shouldn't look like data.
Or maybe I'm missing something somewhere.  But even on the lighting system site, default data and user data are identical.

**Comment by brandonferrua** [comment]
The placeholder text is a slightly lighter value than the normal text.

```
$color-text-placeholder: #54698d;
$color-text-default: #16325c;
```

If you are compiling with a pre-processor such as SASS then you can override these values.

**Comment by jina** [comment]
For context: the reason our placeholder text isn't as light as you typically see is that it fails contrast ratios, which means they fail our mandated accessibility requirements.
