### ISSUE TITLE
Help Text icon (?) is not appearing properly when using Visualforce page with SLDS

### ISSUE THREAD

**Issue by User-SS** [salesforce-ux/design-system#155]
Help Text icon (?) is not appearing properly when using Visualforce page with SLDS. Please attached the screen shot. It shows one and half icon with a field.

![image](https://cloud.githubusercontent.com/assets/17059181/12806355/65aaa552-cb59-11e5-9d65-cab95c016b1a.png)

**Comment by rickschmoo** [comment]
Thanks for reaching out, however the best place to ask this question is the Visualforce Discussion Forum https://developer.salesforce.com/forums/#!/feedtype=RECENT&dc=Visualforce_Development . Please redirect your question there.
