### ISSUE TITLE
Prompt for Touch notification not centered in Salesforce1 viewport

### ISSUE THREAD

**Issue by donmanthorr** [salesforce-ux/design-system#156]
In Salesforce1, the modal prompt is centered vertically based on the page length--not the viewport.  On a long page, this requires the user to scroll down to see the modal.

To test, I created a page that had 50 `<br />` tags and then added the HTML at the following URL:
https://www.lightningdesignsystem.com/components/notifications#prompt-for-touch-with-header-and-tagline-plus-image

The result is the modal too low on the screen--as seen in attachment.  (It works fine in a browser)
![photo 2016-02-18 11 00 24 am](https://cloud.githubusercontent.com/assets/17319351/13150682/d2f2c122-d634-11e5-80a4-b123822b6b16.png)

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this issue, @donmanthorr.

We will let the Salesforce1 App team know about this, as it looks like an issue that happens only in the app wrapper.

In the meantime, I suggest manually overriding the position of the modal or positioning it using JavaScript.
