### ISSUE TITLE
Sales Path doesn't allow for mixed stages

### ISSUE THREAD

**Issue by matturbanowski** [salesforce-ux/design-system#157]
The Sales Path feature works great if you have a completed stage, followed by current, followed by incompleted. However, if you want to mix these up, then the color of the proceeding arrow does not display correctly. e.g. Completed, incompleted, current etc.

**Comment by stefsullrew** [comment]
Hi @matturbanowski - the sales path was designed to be used in the order of the path. There is nothing in the spec to allow for a random order, so it wasn't built that way. I'm going to close this now, but you can certainly request an enhancement and we can look at it.

Cheers!
