### ISSUE TITLE
Tooltips appearing on a standard page via Lightning Components are being affected by app.css

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#158]
When the `slds-tooltip` class is used on a Lightning Component that is loaded to a standard record page, the tooltip is given a `width: 20rem` property by app.css. I found that this is being done on line 21 on one org, and on line 6054 on another org. Both orgs are already on Spring '16.

Tooltips within a Visualforce page are not affected.

![screen-shot-2016-02-23-at-6 35 55-pm](https://cloud.githubusercontent.com/assets/8738640/13271821/3cf197a2-da5d-11e5-917b-cf21540dbdc0.png)

--
  
![screen shot 2016-02-23 at 6 45 33 pm](https://cloud.githubusercontent.com/assets/8738640/13271912/e468c244-da5d-11e5-8d5f-ea6946207625.png)

**Comment by rickschmoo** [comment]
Thanks for this report. We are on it!

**Comment by kevinberonilla** [comment]
I just realized the slds-namespaced classes are available for Lightning Components outside of Visualforce pages, which is great! That explains why this is happening in the first place.

**Comment by stefsullrew** [comment]
You're going to have a fix shortly (there was some refactoring), @kevinberonilla — hold tight!

**Comment by kevinberonilla** [comment]
Awesome, thanks so much!

**Comment by stefsullrew** [comment]
You may have already seen that we've released 1.0 into open source land. That means that when you add the new scoped-VF file, it will match the CSS you get through core. Be aware that there was a bit of refactoring on tooltips, so make sure you're using the newest classes. Cheers!

**Comment by kevinberonilla** [comment]
Thanks for that note!
