### ISSUE TITLE
Unable to link to specific component examples

### ISSUE THREAD

**Issue by clintonhalpin** [salesforce-ux/design-system#159]
You should be able to link to specific sections within the docs. For instance I'd like to link to the heading. 

```
http://www.lightningdesignsystem.com/components/datepickers#time
```

Happy to help out if this sounds like a good idea! Thanks

**Comment by rickschmoo** [comment]
Thanks for the bug report!

**Comment by aputinski** [comment]
@clintonhalpin This will be available in our upcoming release

**Comment by clintonhalpin** [comment]
Solid! Thanks @rickschmoo @aputinski
