### ISSUE TITLE
anchor buttons formatting 

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#16]
According to the documentation for buttons
https://www.lightningdesignsystem.com/components/buttons
it should be possible to use html **button** or **a** elements.

It does not work for icons.
In the example, the first is a **button** slds-button--icon-border-filled
the second/third is a **a** slds-button--icon-container
same is if the **a** is a slds-button--icon-border/-filled

The exception would be that the icon is centered (as with buttons).

![2015-09-16_22-48-27](https://cloud.githubusercontent.com/assets/168846/9926042/a41e921e-5cc6-11e5-9d11-3b6b65eb9105.png)

**Comment by stefsullrew** [comment]
@jorgjanke Thanks so much for reporting this! I've got it fixed and it will be in our next release. Cheers!
