### ISSUE TITLE
Salesforce Sans Mono

### ISSUE THREAD

**Issue by TehNrd** [salesforce-ux/design-system#160]
I have no idea if it is best to submit features here or on ideas.salesforce.com but we have a need for a monospaced Salesforce font. Android has Droid Sans and Droid Sans Mono. It's be great if Salesforce Sans had the same thing.

I understand the use cases for this type of font are few and far between, but here is one. We generate little bubbles with text in them, actual png images, not html (which would make centering easy) Since we are generating actual png images we need to define the x and y coordinates of text in the image. The text should always be centered in the bubble. With a mono spaced font this is very easy to do. With regular font this can prove challenging as numbers and letters take up a different width making it very difficult to position them correctly.

I know it's a long shot and the ROI on the dev effort for this is low but I figured it couldn't hurt to start the discussion as I'm sure there are other use cases as well.

**Comment by jina** [comment]
I can send this over to see if it's in the cards. In the meantime, may I suggest Source Code Pro? It's free and open source, and that's what we use currently in the design system website — and it looks great with Salesforce Sans.

**Comment by srohde** [comment]
This is beyond the scope of the Lightning Design System.
The idea exchange is the better place for this. Thanks!
