### ISSUE TITLE
.slds-grid--vertical-align-center doesn't exist?

### ISSUE THREAD

**Issue by marcelosomers** [salesforce-ux/design-system#161]
First day using the SLDS code here, so apologies if I've missed something.

I'm using the `index-scoped.scss`, installed via npm (version 0.12.2). I can't seem to find the `.slds-grid--vertical-align-center` class. I see it working in the docs, but my generated CSS file does not have that class (or even any reference to grid--vertical-align-center or vertical-align-center).

Did this get removed somehow? The sourcemap on the docs says the class comes from `grid-system/flavors/vertical-alignment-center/index.scss`, but this file does not exist in my `npm install` version. I don't even have a `vertical-alignment-center` folder.

Not a blocker at this point, as I can use `.slds-align-content-center` on the individual grid items to get the vertical centering, but I thought I'd point it out.

Thanks!

**Comment by jina** [comment]
@brandonferrua ^

**Comment by brandonferrua** [comment]
@marcelosomers sorry for the confusion here. We released version 1.0 to the website but have not published version 1.0 to npm yet. Once that happens, you'll have the new code.

**Comment by marcelosomers** [comment]
Ah, thanks for the quick response! I did notice the website had some changes on it from the last few weeks. Any idea on the 1.0 ETA? Just so I can keep an eye out and upgrade once it's there.

**Comment by jina** [comment]
@marcelosomers ETA is RIGHT NOW. :wink:

**Comment by marcelosomers** [comment]
Congrats @jina @brandonferrua and team. 1.0 is a big milestone!
