### ISSUE TITLE
form inline 

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#162]
form inline is now with mq-large-min, which is far too big -- also a breaking change!
Inline forms are usually just a field or two and a button, intended to fit on a single line.

mq-small-min  would be more appropriate (I think).

Instead of hardcoding, I suggest to allow the user/designer to choose when it should go back to "stacked" (or actually better horizontal)

.slds-form--inline__always (i.e. pre 1.0 behavior)
.slds-form--inline__small
.slds-form--inline__large

**Comment by brandonferrua** [comment]
Thanks for reporting this and apologies for the regression. We will be changing the breakpoint to small for now and take into consideration the opt in classes for a future release.
