### ISSUE TITLE
Bad selector with tree aria level

### ISSUE THREAD

**Issue by ennoucas** [salesforce-ux/design-system#164]
The 1.0.0 ltng css is provided with this selector: `[aria-level="1"] > .slds .slds-tree__item` instead of `[aria-level="1"] > .slds-tree__item` as specified in the documentation. (same issue for all area levels)

**Comment by stefsullrew** [comment]
Hi @ennoucas - which version of the CSS did you find this in? Is it one of the scoped versions? And if so, can you let us know which one? 

Cheers

**Comment by ennoucas** [comment]
It is the _salesforce-lightning-design-system-ltng_ and _salesforce-lightning-design-system-ltng.min_ version 1.0.0

**Comment by kaelig** [comment]
Duplicate of #91

**Comment by kaelig** [comment]
Thank you for your patience, this was just fixed in the latest version of the Lightning Design System!

See full release notes: https://www.lightningdesignsystem.com/release-notes/
