### ISSUE TITLE
Spacing utility classes get overridden

### ISSUE THREAD

**Issue by marcelosomers** [salesforce-ux/design-system#166]
If I use a spacing utility class to override spacing within a component, it gets overridden. For example, if I wanted to remove the horizontal padding from an `slds-list__item`:

```
<li class="slds-list__item slds-p-horizontal--none">
  ...
</li>
```

The `slds-list__item` selector wins out. I haven't unwound to see if this is a load order issue (utilities being loaded before components) or selector specificity (probably not), but it seems like at the very least, utility classes should have `!important` on them to win out. I'm sure there's an architectural reason why you haven't done this though.

Or maybe I'm not using utility classes the way they were meant to?

**Comment by bekos** [comment]
For utility classes in general, `!important` is considered an appropriate practice. 
References: 
https://css-tricks.com/when-using-important-is-the-right-choice/
http://davidtheclark.com/on-utility-classes/

My case is when I have specified a `display` property like `inline-block` with bigger specificity than `slds-hide`, and when I apply this class element is still visible.

**Comment by stefsullrew** [comment]
No, you're correct. They should be immutable. We are currently looking at our mobile strategy in light of this. I think we're almost there. Stay tuned!
