### ISSUE TITLE
data table with resizable columns - use guidance

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#167]
Thanks!! 
Do you have some guidance on how to use/implement the data table with resizable columns?

**Comment by stefsullrew** [comment]
Hi @jorgjanke - Are you asking for instructions on implementing the JS?

**Comment by jorgjanke** [comment]
Well, just the principle - so far I did not come across that the column to be resized has a range **input** field, usually it is taking the clientWidth of the th content and set the width on the td explicitly.

E.g. in the Opportunity Home, you set the **th** style="width=Xpx" - the range input of the Opportunity Name input has min="100", but the actual minimum width is 200. Also, it seems that the value is not updated - so I was wondering what the intended purpose/use of the range input field is.

_(For sure there are different implementation choices - e.g. I find it odd that I cannot reduce the width of the Opportunity Owner Alias less than 213px - basically the width of the header column text.
Nevertheless there is a "loose coupling" between slds and the actual classes used in the Lightning UI.)_

**Comment by GusjkoA** [comment]
I would also like to know the thinking behind the examples given (not just this particular one).
