### ISSUE TITLE
Is the Lightning Design System published on a CDN?

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#169]

**Comment by stefsullrew** [comment]
Hi @3den ... it is not. 

If I could ask, how are you consuming SLDS currently? What environment are you using it in?

You should be aware that if you're building Lightning Components that will be inside one.app, SLDS is now included in app.css. You no longer need to add a static resource.

Cheers

**Comment by 3den** [comment]
Hi @stefsullrew, I will be using to build a new rails app for Salesforce Dev Marketing. We will probably be  installing it with bower but if you had it on CDN it would be nicer. 

Also I noticed that you have lots of react components on this repo but no reference to it on the docs, is some one working on documenting the components? 

btw: This project is awesome and I would love help with development.

**Comment by 3den** [comment]
@stefsullrew do you guys have any ETA of when SLDS will be available in a CDN? The current version is pretty unstable and i am needing to many hacks just to `@import` the index. :hurtrealbad:

**Comment by 3den** [comment]
Here is a couple of free options:

* http://www.jsdelivr.com/
* https://cdnjs.com/
* Any other CDN would be fine, while the new version is not released...

**Comment by 3den** [comment]
@stefsullrew is somebody working on this? if not i can do it.

**Comment by 3den** [comment]
@DrBoolean @kaelig can we commit a "/dist" directory with the compiled code? That is required for the CDN, people should be able to use SLDS with or without SCSS.

**Comment by kaelig** [comment]
I am referring your question to the product owner, as there may be security implications behind having SLDS hosted on a CDN.

**Comment by stefsullrew** [comment]
Also, you should not need to use the .scss files. You can grab the compiled CSS from the downloads area and use that instead.

**Comment by 3den** [comment]
@stefsullrew downloading the zipped slds with the compiled files is not an option, it gets outdated quickly, is harder to maintain and we would need to commit SLDS files to the repo.

If you install bootstrap, react, Rx... or pretty much any major project using npm you will notice that they do have a `dist/` directory with the compiled files, that is required for CDN and for projects that don't want to include the src directly. 

@kaelig I don't understand that can be the security implications of hosting static files, of public open source project, in a public CDN... Take a look at http://www.jsdelivr.com/ pretty much every major frontend project is hosted there.

**Comment by kaelig** [comment]
@3den I'll let @srohde get back to you about this, as he knows more about security at Salesforce. Thank you for your patience.

**Comment by kaelig** [comment]
@3den In the mean time, feel free to use this existing (and free) service that serves files directly from npm packages, but we are not officially supporting it: https://npmcdn.com/@salesforce-ux/design-system@1.0.3/

**Comment by 3den** [comment]
Thanks @kaelig that works fine 👍

**Comment by 3den** [comment]
@kaelig any update about this?

**Comment by kaelig** [comment]
No updates at the moment, Thanks for checking!

**Comment by nickforce** [comment]
great idea.. looking forward to this being implemented!

**Comment by DouglasCAyers** [comment]
You can also express your interest by voting on the IdeaExchange, https://success.salesforce.com/ideaView?id=08730000000Lf5qAAC

**Comment by kaelig** [comment]
Closing this, but please keep the discussion going on the IdeaExchange! https://success.salesforce.com/ideaView?id=08730000000Lf5qAAC

**Comment by mtetlow** [comment]
I think maybe this should be reopened or https://success.salesforce.com/ideaView?id=08730000000Lf5qAAC should be unmerged?

It looks like it was merged into an idea about external library whitelisting for lightning components within lex.

**Comment by vinhhungle** [comment]
https://cdnjs.cloudflare.com/ajax/libs/design-system/2.5.0/styles/salesforce-lightning-design-system.min.css
