### ISSUE TITLE
Select has fixed height - ignores size attribute 

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#17]
The default css ignores the **size** setting for **select** elements.
.slds-select sets the height to 2.125rem

a fix could be

    .slds-select[size] {
      height: inherit;
    }

but requires that for single selects the size attribute is not set

![2015-09-17_11-32-16](https://cloud.githubusercontent.com/assets/168846/9942451/e7b23e54-5d2f-11e5-9eed-e762cd07651c.png)

**Comment by jorgjanke** [comment]
probably better fix

    min-height: $line-height-button;
    height: inherit;

**Comment by brandonferrua** [comment]
Thanks for reporting this @jorgjanke 

We will get a fix in shortly

**Comment by brandonferrua** [comment]
This has been resolved in our 0.9.2 build.
