### ISSUE TITLE
slds-checkbox disabled state

### ISSUE THREAD

**Issue by matt-ian-thomas** [salesforce-ux/design-system#170]
Hello!

I'm trying to manage disabled/enabled states for slds-checkbox:

`<label class="slds-checkbox">`
`    <input type="checkbox"></input>`
`    <span class="slds-checkbox--faux"></span>`
`</label>`

When I apply `disabled="true"` to the input, the checkbox is properly disabled. However, when I apply `disabled="false"`, it is also disabled. I made sure to read through the docs and existing issues but unless I missed something came up empty handed. Any advice? Thanks for all of your amazing work on slds overall!

**Comment by stefsullrew** [comment]
Hi @matt-ian-thomas ... Happy to help. 

To disable an input, you simple need the `disabled` attribute. No true or false is necessary. You are welcome, hover to use `disabled="true"` if you'd like. But when it is not disabled, the attribute should be removed entirely.

Cheers!
