### ISSUE TITLE
Disabled button does not change the cursor

### ISSUE THREAD

**Issue by et** [salesforce-ux/design-system#171]
See [example](https://www.lightningdesignsystem.com/components/buttons/flavors/base/_button-brand-disabled.html?iframe).
When you hover your mouse over it, it doesn't change the cursor value. A logical setting would be `cursor: not-allowed`.

I'm happy to fix this, just following the [Contributing](https://github.com/salesforce-ux/design-system/blob/master/CONTRIBUTING.md) process of creating the issue first.

**Comment by stefsullrew** [comment]
Hi @et ... feel free to fix that right up!

**Comment by stefsullrew** [comment]
The disabled button shows a default cursor rather than a pointer. Closing this now. Cheers!
