### ISSUE TITLE
Contents of dropdown menu disappearing when orientation of the device is changed

### ISSUE THREAD

**Issue by aravindqb** [salesforce-ux/design-system#172]
I'm having an issue where the content of the dropdown menu (A normal select tag with "slds-select" class) disappears when the orientation of the device is changed from portrait to landscape or vice-versa.

Issue in detail: When the screen is in portrait mode and if i click on the dropdown menu, it displays perfectly. But, when the orientation is changed, without any other actions, the contents of the displayed dropdown is blank. If i select the dropdown again in landscape mode, it displays correctly, but again if the orientation is changed back to portrait, the same issue persists.

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for bringing this to our attention. We will be looking at mobile use cases in the next iterations of the Design System and will take your feedback into account.
