### ISSUE TITLE
Columns for lists

### ISSUE THREAD

**Issue by gavinhughpalmer** [salesforce-ux/design-system#175]
It would be nice if there were functionality where you could format a list into multiple columns.

**Comment by brandonferrua** [comment]
hey @gavinhughpalmer can you expand on that a bit? maybe a visualization would be helpful

**Comment by gavinhughpalmer** [comment]
Apologies, this was a very vague comment I will elaborate. I was implementing a page which used the Board Tile component, and for this component it seems that it must be implemented as a list. 
![image](https://cloud.githubusercontent.com/assets/17146931/14285784/b75ce7b4-fb44-11e5-87cf-d3d57c645c00.png)
But the page that I was attempting to create required them to be in more of a grid fashion, I managed to come find a solution using css but sadly if there is an odd number of elements in the list the items don't fully match up. This is the solution I have come to 
![image](https://cloud.githubusercontent.com/assets/17146931/14285896/13eab920-fb45-11e5-99e5-92c1cde253c9.png) by using this style in my lightning component 
.THIS .twocol {
    -moz-column-count: 2;
    -moz-column-gap: 20px;
    -webkit-column-count: 2;
    -webkit-column-gap: 20px;
    column-count: 2;
    column-gap: 20px;
    width: 300px;
}

.THIS .twocol li {
    -webkit-column-break-inside: avoid;
    break-inside: avoid-column;
}
But with an odd number of tiles it will look like this 
![image](https://cloud.githubusercontent.com/assets/17146931/14285982/666c780a-fb45-11e5-940c-1c185953fa8b.png)

**Comment by kaelig** [comment]
Closing this as CSS Columns are very fragile across browsers and there is no plan to leverage them for now.
