### ISSUE TITLE
Unable to install design-system-utils

### ISSUE THREAD

**Issue by et** [salesforce-ux/design-system#178]
When on the winter-16 branch, I tried to `npm install` the dependencies and it failed when trying to find [@salesforce-ux/design-system-utils](https://github.com/salesforce-ux/design-system/blob/winter-16/package.json#L30).

```
~/code/design-system (winter-16)$ npm i
npm WARN deprecated babel-core@5.8.23: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Not found : @salesforce-ux/design-system-utils
npm ERR! 404
npm ERR! 404 '@salesforce-ux/design-system-utils' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'design-system'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/et/code/design-system/npm-debug.log
```

Do you guys have a private registry or something? If so, can you publish that package (and probably the other ones prefixes with `@salesforce-ux` publicly)? Thanks

**Comment by kaelig** [comment]
Hi @et, thank you for using the Salesforce Lightning Design System!

Older versions are not supported but we still provide older versions in the form of zip files that contain all the files needed to customize the Lightning Design System. 

You should find what you need over there: http://design-system-v-0-12-2.herokuapp.com/resources/downloads

**Comment by et** [comment]
@kaelig - I think you misunderstood my request. `winter-16` is not an older version. This is the branch recommended to work off of if I want to contribute a PR (see [CONTRIBUTING](https://github.com/salesforce-ux/design-system/blob/master/CONTRIBUTING.md) doc).

Please reopen this issue.

**Comment by et** [comment]
Also pinging @stefsullrew...this is my problem when I was attempting to fix #171

**Comment by stefsullrew** [comment]
Ack! This is our fault! The Contributing doc was not updated when we released. The branch you should be using is Spring-16! Thank you for bringing this to my attention. We'll get this fixed straight away, @et ... 

Cheers

**Comment by et** [comment]
@stefsullrew - no worries! Can you also make sure that `Spring-16` is published as it's not listed under [branches](https://github.com/salesforce-ux/design-system/branches).
