### ISSUE TITLE
Webpage: Components link leads no-where

### ISSUE THREAD

**Issue by karlisup** [salesforce-ux/design-system#180]
Hi, guys!
Before saying anything I just wanted to say that you are awesome! I love your work! Not sure if this is the right place to post it. Was tabbing around the page to learn more about accessibility and found that link to [components ](https://www.lightningdesignsystem.com/components) is leading nowhere. 

Have a nice day,
Karlis
![salesforce](https://cloud.githubusercontent.com/assets/3999661/14021243/02a73800-f1db-11e5-9151-04ab4f3af0a7.png)

**Comment by stefsullrew** [comment]
How very astute of you @karlis-upitis! :) This is a holdover from before we changed the components menu item to simply open, instead of take you to a specific page. Thanks for the heads up!

**Comment by kaelig** [comment]
Thank you again for the good catch, @karlisup. We have removed the link in the last version of the website so this shouldn't be an issue anymore.
