### ISSUE TITLE
[BUG]  Inputs overlap on inline forms 

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#183]
If you create a inline form without labels the size of each input will overlap with the next.
<img width="614" alt="screen shot 2016-03-24 at 5 52 55 pm" src="https://cloud.githubusercontent.com/assets/67904/14035288/b5f68e66-f1e9-11e5-8f9d-5109b03b38de.png">

This problem happens because  `.slds-input` defines width and padding... This issue can be easily fixed by adding  `box-sizing: border-box;` to `.slds-input`.

**Comment by 3den** [comment]
cc: @kaelig @aputinski

**Comment by kaelig** [comment]
Thank you for reporting this, @3den. As always: great description! This is very helpful.

@brandonferrua: any workaround to suggest?

**Comment by 3den** [comment]
@kaelig I have added this overrides to fix the size of inputs:

```
// fix inputs
.slds-button,
.slds-select,
.slds-input {
  box-sizing: border-box;
  height: 35px;
  min-height: 35px;
}
```

**Comment by stefsullrew** [comment]
Actually, @3den, even when using a placeholder, you shouldn't remove the label altogether (for a11y reasons)... simply add the `slds-assistive-text` class to the label and it will be hidden off the page... and all will be well.

Cheers.

**Comment by 3den** [comment]
@stefsullrew the issue here is not because it is missing the label the problem is because the input classes set padding and width without the border-box sizing so they will overflow the specified width.

The inputs where taking more than 100% of the width because of that. We need to add "box-sizing; border-box;" to input classes or they will overflow the container.

**Comment by stefsullrew** [comment]
@3den... they are already set to border-box... I'm confused. And here's what I get when I visually remove the labels:

![image](https://cloud.githubusercontent.com/assets/676213/14746169/3aec63fc-08a6-11e6-97d1-ce99d3452092.png)

Here's the inspector showing the border-box setting:
![image](https://cloud.githubusercontent.com/assets/676213/14746196/5db72282-08a6-11e6-8510-ace6cbb4742b.png)

Are you using the full DOM with the divs that surround?

**Comment by 3den** [comment]
I think the bug was on a previous version seems to be good now thanks.

**Comment by kaelig** [comment]
Thanks @3den!
