### ISSUE TITLE
[BUG] Inconsistent height on form elements

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#184]
I just noticed the `.slds-select` (34px) is a few pixels smaller than the `slds-input` (36px). This issue can also be seen on the demo website https://www.lightningdesignsystem.com/components/forms too.

I think it would be nice if we used the same class for both this way is 1 less class to remember and we guarantee consistency.

**Comment by 3den** [comment]
the issue seems to be because of this style `min-height: calc(2.125rem + 2px);` that is added to the bottom of `.slds-input`

**Comment by kaelig** [comment]
Thank you for the feedback. Marking this as duplicate of #150, handled by @brandonferrua.
