### ISSUE TITLE
Textareas have extra spacing below them when not set to display: block

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#186]
Can textareas be `display: block;` by default? When they are not, elements under them are spaced differently on a stacked form (it's off by a few pixels). See the spacing discrepancy on the screenshot below:

![screen shot 2016-03-28 at 2 20 05 pm](https://cloud.githubusercontent.com/assets/8738640/14087684/cfb41a12-f4f0-11e5-8405-1bc4b4068c55.png)

Code sample here: https://gist.github.com/kevinberonilla/80cf007e815800da2e3f

**Comment by brandonferrua** [comment]
Thanks for raising this concern. Let me look into it and see if doing so will cause any regressions.
