### ISSUE TITLE
Tree Nodes don't collapse or expand

### ISSUE THREAD

**Issue by Anzle** [salesforce-ux/design-system#189]
Hi, 

I'm trying to use the sample code provided on the Lightning Design System's page to implement a Tree, but I'm a little confused by it. It appears as if the tree should be able to expand and collapse, but when I press the arrows on the Lightning Design System page, nothing happens. Just in case, I created a VF page and copy/pasted the code available on the page in, using SLDS100 and salesforce-lightning-design-system.css, but I still don't get the expand collapse functionality (or the chevron icons)  

So, I guess I'm really asking is: is the tree supposed to have the expand collapse functionality built in, or do I need to write Javascript to implement this functionality?

**Comment by Anzle** [comment]
I've realized that the package is only CSS and I feel kinda silly.

**Comment by kaelig** [comment]
Hey @Anzle, no problem at all! Thank you for using the Salesforce Lightning Design System and please keep shooting questions if you have any.

**Comment by kalidassgujar** [comment]
I have added SLDS100 and trying to create sample table however its not applying any style. i have added namespace prefix  in tag.

**Comment by kaelig** [comment]
Howdy @kalidassgujar, thank you for using the Salesforce Lightning Design System! Can you please create a new issue and describe the problem there?
