### ISSUE TITLE
get rid of dangerously SetInnerHTML in SvgIcon

### ISSUE THREAD

**Issue by Guria** [salesforce-ux/design-system#19]
[dangerouslySetInnerHTML in SvgIcon](https://github.com/salesforce-ux/design-system/blob/winter-16/app_modules/ui/svg-icon/index.jsx#L29) could be replaced with `<use xlinkHref={href}></use>` since react 0.14 has support for it.

**Comment by amyleesalesforce** [comment]
Oh awesome.
