### ISSUE TITLE
Icon download in Illustrator format

### ISSUE THREAD

**Issue by Kencopen** [salesforce-ux/design-system#190]
Hello, is it possible to get the salesforce-lightning-design-system-icons in Adobe Illustrator format instead of just .png and .svg so we can have high res versions to use for some Marketing design projects?

**Comment by jvsfdc** [comment]
SVGs are high res and are easily opened in Illustrator, no?

**Comment by kaelig** [comment]
@Kencopen thank you for using the SLDS. The SVG icons are vectors that Illustrator can read (like @jvsfdc suggested). You can download them all from https://www.lightningdesignsystem.com/resources/downloads/

Hope this answers your question.
