### ISSUE TITLE
Lookup accessibility

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#191]
Usually when user is typing inside the `<INPUT>`, the arrow keys shouldn't move focus away from the input element to the list items. This way user is still able to filter the list by typing inside the input and navigate through suggestion with arrow keys, at the same time. You can see this behaviour here: https://twitter.github.io/typeahead.js/

So, you could probably provide a `.slds-lookup__item--active` class, probably the same when item is focused or hovered, so that javascript libraries can make use of this. 

I hope I made myself clear :) Thx for the great framework!

**Comment by kaelig** [comment]
Thank you @bekos for your question.

Adding a `.slds-lookup__item--active` seems like a very legitimate ask, let us get back to you on that shortly!

**Comment by jonathanwiesel** [comment]
Any news on this one?

**Comment by kaelig** [comment]
@jonathanwiesel not yet, thank you for your patience!

**Comment by engai** [comment]
Hi @bekos, we currently have documentation on this type of interaction under our Combobox component - https://www.lightningdesignsystem.com/components/combobox/.

Notably, we add the `slds-has-focus` class to the element currently active in the listbox. Furthermore, we include documentation under 'Expected Keyboard Interactions' to help ensure that elements have to correct aria attributes.

Closing this issue, but feel free to reopen or comment if needed.
