### ISSUE TITLE
@salesforce-ux/design-system  Not Found

### ISSUE THREAD

**Issue by mdolzhko** [salesforce-ux/design-system#194]
Hi everyone!
here is a description of bug after 'npm install'

package.json dependencies:
 "dependencies": {
   ...
    "@salesforce-ux/design-system": "^0.12.1",
   ...
  },

and body of Bug:

npm ERR! 404 Not Found : @salesforce-ux/design-system
npm ERR! 404 
npm ERR! 404  '@salesforce-ux/design-system' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'audio-test'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

[npm-debug.log.zip](https://github.com/salesforce-ux/design-system/files/210269/npm-debug.log.zip)

**Comment by mdolzhko** [comment]
here is the info how to install @salesforce-ux/design-system with last v1.0.0
https://www.npmjs.com/package/@salesforce-ux/design-system
but nothing changed, the same bug: 
npm ERR! 404  '@salesforce-ux/design-system' is not in the npm registry.

**Comment by kaelig** [comment]
Hi, thank you for using the design system!

What version of npm is running on your machine?

**Comment by mdolzhko** [comment]
apple$ npm -v 
3.7.2

**Comment by mdolzhko** [comment]
The same issue with npm -v 
3.8.6

**Comment by kaelig** [comment]
Thank you for the information. I'm afraid I couldn't' reproduce this issue.

Can you try running `npm cache clear` and try again?

**Comment by mdolzhko** [comment]
Unfortunately, it doesn't resolve an issue...

**Comment by kaelig** [comment]
Looks like an issue with npm itself. Can you share what your ~/.npmrc file looks like?

**Comment by wwwdata** [comment]
I have the same problem. I noticed that all dependencies in the `package.json` of the archive on npmjs are missing, maybe theres a problem with your npm package builder?

**Comment by kaelig** [comment]
I've just tested on a clean linux box and can't reproduce the issues you are describing. Are you behind a proxy/firewall/private npm instance?

**Comment by wwwdata** [comment]
I'm using Mac OS X 10.11.4 and with version 1.0.2 I get this error:

``` 
File to import not found or unreadable: @salesforce-ux/design-tokens/dist/s1-base-large.default.scss
```

with version 1.0.0 everything is working when I import the `@salesforce-ux/design-system/scss/index` into my sass file.

**Comment by bekos** [comment]
@wwwdata See #196

**Comment by kaelig** [comment]
You may want to consider using https://github.com/kaelig/slds-starter-kit, and let me know if you manage to get it working?

**Comment by kaelig** [comment]
@mdolzhko is this still an issue you are encountering?

**Comment by mdolzhko** [comment]
Hey @kaelig  !
unfortunately yes, 5 min ago was the same issue 

mdolzhko-osx:certification-page apple$ npm i @salesforce-ux/design-system --save-dev
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@salesforce-ux/design-system" "--save-dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Not Found : @salesforce-ux/design-system
npm ERR! 404 
npm ERR! 404  '@salesforce-ux/design-system' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/WebstormProjects/CertificationPage/certification-page/npm-debug.log

**Comment by kaelig** [comment]
Hey @mdolzhko, it looks like npm is trying to find the package in other registries (I'm not sure but that's my impression).

What does `npm config get registry` return?

**Comment by mdolzhko** [comment]
it gives me only a link:

mdolzhko-osx:certification-page apple$ npm config get registry

https://registry.npmjs.org/

**Comment by kaelig** [comment]
@mdolzhko thank you for checking.

Is your company behind a npm cache / proxy?

**Comment by mdolzhko** [comment]
hi @kaelig !
Nope, my company isn't behind npm cache/proxy.

@kaelig, is the result of ''npm config get registry'' correct (https://registry.npmjs.org/) ?

**Comment by kaelig** [comment]
Yes, as far as I can tell the registry is correct.

Can you please run this and let me know what this looks like?

```
cd path/to/project-where-you-want-to-install-slds
npm config ls -l
```

**Comment by mdolzhko** [comment]
hey @kaelig !
so, what i did:

- from command line run the command npm config ls -l
- found the info:
user-agent = "npm/3.9.2 node/v4.4.4 darwin x64" ; userconfig /Users/apple/.npmrc
@salesforce-ux:registry = "http://github.com"
- than i opened .npmrc file
- deleted this line: @salesforce-ux:registry = "http://github.com"
- save

finally i tried npm i @salesforce-ux/design-system again,
aaand... can you imaging? IT WORKS!!!!!!! without any issues!!!!

@kaelig THANK YOU VERY MUCH!
think you can close this issue

**Comment by kaelig** [comment]
Fabulous, glad you found out where the issue came from. I wonder how this setting got in there in the first place!
