### ISSUE TITLE
Design tokens

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#196]
I may be wrong but since [@salesforce-ux/design-tokens](https://github.com/salesforce-ux/design-tokens) is deprecated, then their reference inside [_design-tokens.scss](https://github.com/salesforce-ux/design-system/blob/master/ui/_design-tokens.scss) should change. Right?

```css
@import
  '@salesforce-ux/design-tokens/dist/s1-base-large.default.scss',
  '@salesforce-ux/design-tokens/dist/s1-base.default.scss',
  '@salesforce-ux/design-tokens/dist/force-base.default.scss',
  '@salesforce-ux/design-tokens/dist/force-base.map.scss',
  '@salesforce-ux/design-tokens/dist/bg-actions.default.scss',
  '@salesforce-ux/design-tokens/dist/bg-custom.default.scss',
  '@salesforce-ux/design-tokens/dist/bg-standard.default.scss',
  '@salesforce-ux/design-tokens/dist/bg-actions.map.scss',
  '@salesforce-ux/design-tokens/dist/bg-custom.map.scss',
  '@salesforce-ux/design-tokens/dist/bg-standard.map.scss';
```

**Comment by kaelig** [comment]
Thank you for the great question, @bekos. The repository is deprecated, but the package still lives on npm. We install the module, and then tell Sass to go fetch those tokens in the `node_modules` directory:

1. First, install the design system

`npm install @salesforce-ux/design-system --save`

2. Then, specify `node_modules` as an include path for Sass

```bash
# With Ruby Sass:
sass --update --force node_modules/@salesforce-ux/design-system/scss/index.scss:lightning-design-system.css --load-path './node_modules/'

# With Node Sass
node-sass --force --include-path './node_modules/' node_modules/@salesforce-ux/design-system/scss/index.scss  lightning-design-system.css
```

```js
// With Gulp (code wasn't tested, but you get the idea):
import gulp from 'gulp';
import sass from 'gulp-sass';

gulp.task('styles', () =>
  gulp
    .src('node_modules/@salesforce-ux/design-system/scss/index.scss')
    .pipe(sass.sync({
      includePaths: [
        'node_modules'
      ]
    }).on('error', sass.logError))
    .pipe(gulp.dest('index.css'))
);
```

We're planning to describe those steps to make the process of consuming the Lightning Design System much easier and clearer.

Hope this helps!

**Comment by bekos** [comment]
@kaelig I see. 

So, in the first step, except installing `@salesforce-ux/design-system`, you also have to:
```bash
npm install @salesforce-ux/design-tokens --save
``` 
It may be a good idea then, to define `design-tokens` as peerDependency.

Thanks for the info! It is definitely helpful  :-)

**Comment by kaelig** [comment]
Thank you for the additional info! Yes this other step is required. It might be a good idea to publish it as a peer dependency although it's not necessary with the npm module since the tokens are embedded (inlined) directly in the design-tokens.scss file.

**Comment by zainogj** [comment]
Looks like I'm running into this issue as well, but the above steps don't seem to resolve it for me.

`npm -v
3.8.6`
Windows 7; bash

After reading #194 I've cleared cache as well.

I'm a novice with npm and sass, so room for user error.

`gazaino@garrettzw7 MINGW64 ~/Projects/PersonalSite/garrett-zaino (master)
$ npm install @salesforce-ux/design-system --save
garrett-zaino@1.0.0 C:\Users\gazaino\Projects\PersonalSite\garrett-zaino
`-- @salesforce-ux/design-system@1.0.2


gazaino@garrettzw7 MINGW64 ~/Projects/PersonalSite/garrett-zaino (master)
$ sass --update --force node_modules/@salesforce-ux/design-system/scss/index.scss:public/assets/styles/lightning-design-system.css --load-path './node_modules/'
      error node_modules/@salesforce-ux/design-system/scss/_design-tokens.scss (Line 15: File to import not found or unreadable: @salesforce-ux/design-tokens/dist/s1-base-large.default.scss.
Load path: C:/Users/gazaino/Projects/PersonalSite/garrett-zaino/node_modules)`

**Comment by kaelig** [comment]
Hi @zainogj, thank you for reporting this issue. We will fix it very soon. Thank you for your patience.

**Comment by zainogj** [comment]
Thanks @kaelig - I was able to get it to work with SLDS v0.0.12, if that helps at all.
