### ISSUE TITLE
Question: Edit Dialog For Touch - not compatible with SF1 Mobile??

### ISSUE THREAD

**Issue by MadDogMel99** [salesforce-ux/design-system#197]
Have noticed the new "NOT COMPATIBLE WITH S1 MOBILE" Label - this is really useful! 

However I have a question related to Modals?
The "Modal" is listed as not supported - but then its equivalent for a mobile is "Edit Dialog For Touch". 

Yet "Edit Dialog For Touch" is also unsupported?
Then what is the suggested replacement for modal on a touch device?

Thanks.

**Comment by stefsullrew** [comment]
The components will work perfectly in mobile outside S1. We're currently, dealing with an internal issue, being solved now, with some JS that causes the pull to refresh to stop the scrolling.

A modal will work in S1 just fine right now, if it doesn't have enough content inside to cause the body of it to have an internal scrollbar. (The same applies to all "not compatible with S1 mobile" badges.

Hope that helps @MadDogMel99!
