### ISSUE TITLE
Hard to find "Utilities" on the docs site

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#198]
Currently the see the "Utilities", we need to click on "Components" scroll all the way to the bottom and "Utilities" will be the last item nested under components, which makes it harder to find and new people can get confused, like I did, it took me a long time to find out that we had atomic styles... 

The utilities are not like other components, so can we move the "Utilities" out of the "Components" menu to make it more accessible?

**Comment by kaelig** [comment]
Thank you for this suggestion, @3den. We'll definitely consider this as we work on the next iterations of the website.

**Comment by kaelig** [comment]
Closing this as utilities are now at the top of the component navigation.
