### ISSUE TITLE
Angular 2.0 & React component libraries

### ISSUE THREAD

**Issue by lendi-au-glen** [salesforce-ux/design-system#199]
Hello, firstly I love the work Salesforce UX is doing with Lightning - it's incredible.

Are there any plans to introduce React and Angular 2.0 libraries for the components? For example, Material UI is an implementation of the Material guidelines for a number of React components. Can we expect a React and/or Angular 2.0 libraries at some point?

I think this would help to create a much larger adoption of Lightning as for now we must implement all the components ourselves, and for some projects this will mean forgetting the idea of using this framework.

Thanks again for all your great work.

**Comment by ppolyzos** [comment]
Hey lendi-au-glen,

Have you seen this project [http://ng-lightning.github.io/ng-lightning/](http://ng-lightning.github.io/ng-lightning/)?

As the title of the project states it provides "Native Angular 2 components & directives for Lightning Design System".

It is a work in project but you can have a look at the components already available [here](http://ng-lightning.github.io/ng-lightning/#/components)

**Comment by lendi-au-glen** [comment]
Oh wonderful, looks good. I had not seen that. Thank you @ppolyzos!

**Comment by ppolyzos** [comment]
No problem! It's a very interesting project and in my opinion this should be mentioned in their resources section [https://www.lightningdesignsystem.com/resources/links/](https://www.lightningdesignsystem.com/resources/links/) @salesforce-ux-bot.

**Comment by kaelig** [comment]
The http://ng-lightning.github.io/ng-lightning/ project is fantastic indeed. We're very proud to see such initiatives go open-source. Let me see what we can do to give it more visibility.

**Comment by Guria** [comment]
there is also react one https://github.com/stomita/react-lightning-design-system

**Comment by kaelig** [comment]
Thank you all for the suggestions and contributions in this thread. I'll close this, but feel free to refer other developers to this list in the future.

**Comment by bekos** [comment]
@kaelig JFYI we are getting some attention from Angular also. Check this out: https://twitter.com/bradlygreen/status/722527021272686593

**Comment by kaelig** [comment]
@bekos thank you for sharing!

**Comment by ButuzGOL** [comment]
Maybe we can add Angular and React components git repos in inside README ? if yes I can do pull request

**Comment by kaelig** [comment]
Thanks for the suggestion, @ButuzGOL. For now let's keep community projects separate, but note that we are looking into the best way to promote the community's efforts. Watch this space!
