### ISSUE TITLE
renderAs="pdf"

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#200]
The grid layout is not rendered properly in
`<apex:page ... renderAs="pdf">`

Is there a plan/hope/timeframe for support of flexbox?

**Comment by kaelig** [comment]
Thank you for reporting this, @jorgjanke.

@stefsullrew is this something you would know the answer to?

**Comment by stefsullrew** [comment]
I know that VF currently uses a service called PDF1 which is admittedly, out of date and in need of an upgrade. Currently PDF3 is being developed (forward-looking statement) which will be webkit-based and should render very nicely. However, I'm honestly unclear of when that will be completed. I will see if I can learn more.
