### ISSUE TITLE
unclosed <inputs> in the sample source.

### ISSUE THREAD

**Issue by AndyBean** [salesforce-ux/design-system#201]
Just for code cleanup, it would be good to do a search and replace on all inputs located throughout the project that are unclosed, and close them. As I copy and paste from samples while building mockups, I notice this fairly consistently. If I knew regex well enough to write the search, I would do it myself and throw you a bone. But, alas, my regex skills blow.
```
Bad
<input data="blah blah">

Good
<input data="blah blah" />
```

**Comment by kaelig** [comment]
Thanks for reporting this! Looks like our HTML pre-processors (either React or the beautifier) turn xHTML 5 into HTML 5 and remove the trailing slash. I'll investigate!

**Comment by kaelig** [comment]
This should be fixed in the latest update, thank you again for reporting this!
