### ISSUE TITLE
Input Element Styles not applying when using *-ltng.css stylesheet

### ISSUE THREAD

**Issue by rjfay** [salesforce-ux/design-system#202]
Hi folks,

Great work on SLDS - it's a pleasure to work with.

I've run into the following issue when using the -ltng.css stylesheet.  Given the following Lightning application:
https://gist.github.com/r7ay/a329de0aa57f804f328aac44f461825d

When using the *-vf.css stylesheet, things work as intended (see the Surname and Email field content):

![image](https://cloud.githubusercontent.com/assets/4855820/14610276/1c6e78c6-0585-11e6-8bfa-42a0d6fb8b88.png)

...specifically, the input styles are correctly inheriting Salesforce Sans 14px:

![image](https://cloud.githubusercontent.com/assets/4855820/14611218/ff597b74-0588-11e6-84a9-ab53ccdfa7ae.png)

However, when I switch to the *-ltng.css stylesheet, the input font is the wrong family and size:

![image](https://cloud.githubusercontent.com/assets/4855820/14610442/df18d448-0585-11e6-9c89-519435a22e07.png)

...this is because the effective (computed) style for the input is from the User Agent stylesheet, rather than the *-ltng.css stylesheet:

![image](https://cloud.githubusercontent.com/assets/4855820/14610501/13d5bac0-0586-11e6-9ed9-0626fd60ff8c.png)

This is happening across browsers, including Chrome v49.0.

Any input appreciated.

Rob

**Comment by kaelig** [comment]
Thank you Rob for using the Lightning Design System and for raising this issue!

@stefsullrew, any idea of what could cause this? Is there a missing stylesheet?

**Comment by stefsullrew** [comment]
The VF page scopes normalize and adds it in to the .slds components (since VF doesn't load normalize)... The lightning file doesn't do that because normalize and SLDS are available in core... In fact, if you're working on a component for core, you don't even need to include the SLDS css at all. 

Maybe this is related?

**Comment by kaelig** [comment]
Hi @rjfay, is this something you still need help with?

**Comment by rjfay** [comment]
@kaelig Thanks for following up.  I ended up using the VF stylesheet; I haven't had the opportunity to check whether this has been resolved in a more recent release.

**Comment by kaelig** [comment]
Thanks again, @rjfay. Our Summer ’16 being around the corner, a few things are going to change regarding font sizes so I'll just close this issue. Feel free to reopen it if you ever run into it again.
