### ISSUE TITLE
Button label not displayed after icon in Visualforce

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#204]
I've created a basic page with a button with a left icon, however, the label is not displayed.

    <apex:page showHeader="false" standardStylesheets="false" sidebar="false" applyHtmlTag="false" applyBodyTag="false" docType="html-5.0">     

    <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <apex:stylesheet value="{!URLFOR($Resource.slds102, 'assets/styles/salesforce-lightning-design-system-vf.css')}" /> 
    <div class="slds">
        <button class="slds-button slds-button--neutral">
        <svg aria-hidden="true" class="slds-button__icon slds-button__icon--left">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{!URLFOR($Resource.slds102, '/assets/icons/utility-sprite/svg/symbols.svg#download')}"></use>
        </svg>Button Neutral</button>
    </div>
    </html>    
    </apex:page>

For a strange reason, the label is rendered inside the svg tag:

    <button class="slds-button slds-button--neutral">
        <svg aria-hidden="true" class="slds-button__icon slds-button__icon--left"><use xlink:href="/resource/1461076927000/slds102/assets/icons/utility-sprite/svg/symbols.svg#download" xmlns:xlink="http://www.w3.org/1999/xlink"></use>
        Button Neutral</svg>
    </button>

I know it's a bug from the Platform and not from SLDS directly, but I don't know who should be warned about this. Should I create a Case about it ? Not sure it will lead to a fix. Or maybe add a comment in SLDS doc ?

A workaround for this is to put the label inside a span, and then the label is rendered properly.
At least writing this here may help someone else with the same problem in the future :)

**Comment by kaelig** [comment]
Bonjour Fabien, and thank you for letting us know! As you mentioned: this isn't something we provide support for. I'd recommend getting in touch with the Aura team or any other channels you usually go through to report issues with apex tags.

**Comment by stefsullrew** [comment]
This is a duplicate of issue #47, @FabienTaillon ... you may find some help in there.

**Comment by FabienTaillon** [comment]
Thanks @stefsullrew I should have looked in the closed issues before asking !
