### ISSUE TITLE
Sample code request: Record Detail subtab

### ISSUE THREAD

**Issue by dschach** [salesforce-ux/design-system#205]
Please provide sample code for displaying the record details subtab. No need to include the mouseover pencil icons for editing fields; just showing how to make a complete, read-only record page is fine.

**Comment by stefsullrew** [comment]
Hi @dschach - please go to the internal aloha tile for the SLDS and click on the bottom right for a new component request: 
![image](https://cloud.githubusercontent.com/assets/676213/14708009/dddc0d84-07bf-11e6-927a-70d6333da1a5.png)

Cheers!
