### ISSUE TITLE
Problem with re-rendering Visualforce elements containing an SVG

### ISSUE THREAD

**Issue by e-bacho** [salesforce-ux/design-system#206]
As per the documentation I've disabled the sidebar and header in my VisualForce page and I've added the **html** element as follows:

`<html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">`

The page loads initially and it renders properly, displaying the SVG. Once I try to re-render a section (managed VF element), I get an error in the developer tools console:

> prefix not bound to a namespace

The markup is as follows:

```
<apex:page docType="html-5.0" controller="MyController" action="{!Init}" sidebar="false" showHeader="false" id="page" >
	<html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
		
		<apex:includeLightning />
		
		<apex:stylesheet value="{!URLFOR($Resource.SLDS, 'assets/styles/salesforce-lightning-design-system-scoped.min.css')}" />

		<apex:form id="form">
			<apex:actionFunction name="myActionFunction" action="{!apexMethod}" rerender="myPanel" />

			<apex:outputPanel id="myPanel" layout="block">
				<div class="slds">
					<a onclick="myActionFunction();">
						<div class="sdls-icon_container">
							<svg aria-hidden="true" class="slds-icon slds-icon--medium">
								<use xlink:href="{!URLFOR($Resource.SLDS, '/assets/icons/utility-sprite/svg/symbols.svg#rows')}"></use>
							</svg>
						</div>
					</a>
				</div>
			</apex:outputPanel>
		</apex:form>
	</html>
</apex:page>
```

However, if I add the namespace attributes to a non managed html element, a **div** for an example, and wrap my SVG inside it, the re-redering works, although the DOM elements get messed up.

**Comment by e-bacho** [comment]
Closed as I just found out that there is a duplicate for this - https://github.com/salesforce-ux/design-system/issues/47

**Comment by rahulgawale** [comment]
I am still facing the issue even after 19 release. I tried all of the above workarounds. But still no luck. FInally, I decided to use PNG icons instead of slds svg icons

**Comment by AndrewNR** [comment]
Hi, I was able to fix the problem when SVG icons disappear, if we re-render some <apex:*> tag after controller's action:
    1. Add `docType="html-5.0"` attribute to the `<apex:page>` tag;
    2. Put the `xmlns="..."` and `xmlns:xlink="..."` attributes **directly on the `<use ...>` tag**, together with `xlink:href="..."` value for the SVG icon.

Please find example in this StackExchange answer:
https://salesforce.stackexchange.com/a/283032/29123
