### ISSUE TITLE
checkbox not working fine on mobile

### ISSUE THREAD

**Issue by ennoucas** [salesforce-ux/design-system#207]
Hi, 
Checkbox does not see seem to work fine on mobile, especially in dataTable with selected rows. I'm using SF1 on iOS with a lightning component tab. When I touch the checkbox it's not always checking or unchecking it.

Is there a workaround ? 

Thank you.
Lucas.

**Comment by kaelig** [comment]
Hi @ennoucas, thank you for reporting this! What version of iOS are you experiencing this issue in?

**Comment by kaelig** [comment]
I have a feeling that this is related to the touch/scroll handler in the S1 app, so I suggest you take it to the developer community and start a discussion there: https://developer.salesforce.com/forums

I am closing this as this seems to be external to the Salesforce Lightning Design System.

**Comment by stefsullrew** [comment]
I'm not sure that's it, though it's possible. 

On early versions of iOS9, they broke the `~` selector. So while the checkbox *was* receiving the check (and reporting that it was checked), the selector itself wasn't showing it. It is fixed now. (I filed a bug with Apple back when this happened.) If iOS is updated, you shouldn't see this problem anymore. And if you do, maybe @kaelig is right. 

Cheers

**Comment by ennoucas** [comment]
Thank you @kaelig and @stefsullrew. I'll update my iPad and check again.
