### ISSUE TITLE
Record Detail subtab sample code

### ISSUE THREAD

**Issue by dschach** [salesforce-ux/design-system#209]
A few customers have contacted me requesting sample code for the record detail subtab in Lightning Experience. We show in our documentation how to make all the other parts, but not this part.
None has asked me for code for the inline editing pencil icons - all have asked me for a read-only sample code for the page layout grid.
They want to know, for example, the padding we use, how we make the lines, etc. 
![recorddetailsldscode](https://cloud.githubusercontent.com/assets/636977/14798950/d2bc6c8c-0aee-11e6-9abd-488e1f9919d4.png)

**Comment by srohde** [comment]
Thanks for the feature request. Templates are on our list of things but will take a while.
