### ISSUE TITLE
Change NPM package name to "salesforce-lightning-design-system"

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#212]
Currently when we install SLDS using NPM the project is installed under `node_modules/@salesforce-ux/design-system/` which does not seem standard... Also it would be nice to have the same project name for the bower  and NPM.

**Comment by kaelig** [comment]
Thank you for the suggestion!

Good point about the difference of package naming between Bower and npm.

However, the `@salesforce-ux/design-system` notation is standard for [scoped packages](https://docs.npmjs.com/misc/scope). This makes it very clear to our users where the package comes from. The only limitation is that only scoped packages can depend on it, and global packages can't depend on it.

Did you encounter any issues with the current scoped name?

**Comment by 3den** [comment]
I think that will be an issue if we want to cdn on jsdelivr https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by kaelig** [comment]
> The limitation that global packages can't depend on it seems pretty bad,

Actually, sorry for misleading you earlier. I've just checked and it doesn't seem to be an issue at this time (I don't really understand why some threads on the topic raised this).

**Comment by 3den** [comment]
Thanks @kaelig, I think we can close this issue.
