### ISSUE TITLE
How can we use Radio Button in visualForce page with Lightning Design System

### ISSUE THREAD

**Issue by lrautela** [salesforce-ux/design-system#213]

**Comment by stefsullrew** [comment]
Hi @lrautela - can you give me a little more information? Are you in classic or Lightning experience? Are you using apex tags? 

If not, are you adding the SLDS CSS as a static resource?

**Comment by sankarkrish** [comment]
Hi Stephanie, I am facing the same issue. I am using the <apex:selectRadio> and <apex:selectOptions> to display the options and send the user selection back to the controller. Which slds css should I use to style the radio buttons and how? Also, how can I display the options in one column than the row?

**Comment by stefsullrew** [comment]
Hi folks, as mentioned in our Getting Started doc (http://www.lightningdesignsystem.com/getting-started/visualforce/) and the Trailhead unit we link to from there, apex tags are not currently supported. The Trailhead gives you some alternatives you might try however. 

Cheers!
