### ISSUE TITLE
not responsive with mobile version

### ISSUE THREAD

**Issue by nabildev711** [salesforce-ux/design-system#214]
Hello,

the lightning system grid is not completely responsive.

Regards

**Comment by stefsullrew** [comment]
Hi @nabildev711, thanks for your feedback. Can you perhaps give us a little more context around what you're trying to achieve. And perhaps a code sample?

Cheers

**Comment by kaelig** [comment]
Hi again @nabildev711, is this something you'd like to elaborate on?

**Comment by suryaiiit** [comment]
Hi,
I've an example  of grid system.
http://codepen.io/suryaiiit/pen/MejoPe

The grid system is working with respect to the window, and not with respect to the parent container.

Screenshot: https://www.dropbox.com/s/td2lrk9iqwbcyk3/Screenshot%202016-06-19%2016.02.55.png?dl=0

Boxes in MyLearning works fine in 100% width, but when you add it as a part of the page (x% width) it breaks, check the screenshot.

Regards

**Comment by kaelig** [comment]
Thanks for sharing this example, @suryaiiit. You are correct, and this is the way CSS works at the moment: media queries only allow elements to be responsive to the viewport's width (or to their parent frame).

**Comment by kaelig** [comment]
Closing this as it has a dependency on the CSS specification itself. Container queries might save us in the future!
