### ISSUE TITLE
Lightning svgIcon helper component does not work in Summer 2016

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#217]
Summer 2016 with the locker service enabled fails the setAttributeNS method used in the renderIcon helper method.

**Comment by afawcett** [comment]
Literally just found this as well, thanks!

**Comment by afawcett** [comment]
Is there a way to disable Locker Service?

**Comment by sdruckerfig** [comment]
No. All new orgs that will be created once Summer 16 goes GA will have Locker auto-enabled and there is no way to disable it.

**Comment by afawcett** [comment]
Just found [this](http://salesforce.stackexchange.com/questions/119292/unable-to-use-svg-in-lightning-components-with-lockerservice-activated).

**Comment by sdruckerfig** [comment]
Yeah, I sent Doug Chasman an email, requesting a status update on this feature.

**Comment by kaelig** [comment]
Thank you for bringing this to our attention. I appreciate that you also followed up with Doug and that there already is a discussion happening. Since it is an issue that isn't directly related to the Salesforce Lightning Design System, we will now close it. Thank you for your patience while a patch is on its way.

**Comment by FabienTaillon** [comment]
@sdruckerfig Do you had any answer for the setAttributeNS support ? For SVG, it's said to be officially supported in Summer '16, which is a great news:
http://salesforce.stackexchange.com/questions/121115/how-can-we-use-custom-svg-icons-in-lightning-component-with-lockerservice-enable

**Comment by sdruckerfig** [comment]
It's going to be fixed ... Real soon!

On Tuesday, May 17, 2016, Fabien Taillon <notifications@github.com> wrote:

> @sdruckerfig <https://github.com/sdruckerfig> Do you had any answer for
> the setAttributeNS support ? For SVG, it's said to be officially supported
> in Summer '16, which is a great news:
>
> http://salesforce.stackexchange.com/questions/121115/how-can-we-use-custom-svg-icons-in-lightning-component-with-lockerservice-enable
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/salesforce-ux/design-system/issues/217#issuecomment-219656290>
>


-- 
Regards,
Steve Drucker
Founder / President
Fig Leaf Software
http://www.figleaf.com
http://training.figleaf.com
Acquia, Adobe, Brightcove, Ektron, Google, Paperthin, Sencha
Consulting/Training/Sales/Support

"We've got you covered"

Fig Leaf Software is a Service-Disabled Veteran-Owned Small Business
(SD-VOSB) on GSA Schedule
