### ISSUE TITLE
Applying slds-hide to the Modal dialog box doesn't hide the box and background

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#218]
Seems to be a conflict with the slds-background-open.

I was only able to hide the whole box + background by applying a class like this one:

.hideModal {
  display:none !important;
}

**Comment by kaelig** [comment]
Hi @sdruckerfig, thank you for your feedback. 

Your solution is an interesting workaround, but the correct implementation is to simply remove these classes using JavaScript:

```
.slds-backdrop--open
.slds-fade-in-open
```

Once the animations are over (there's a JavaScript listener for that), you may then apply `slds-hide` to both elements or remove them entirely from the DOM.

@stefsullrew @donnieberg is this correct or is there something to add?

**Comment by sdruckerfig** [comment]
Having to write a javascript listener to remove those classes doesn't seem
to me to be as intuitive or designer/developer friendly as adding a
!important to the display:none property of the slds-hide class.

On Tue, May 17, 2016 at 7:47 PM, Kaelig <notifications@github.com> wrote:

> Hi @sdruckerfig <https://github.com/sdruckerfig>, thank you for your
> feedback.
>
> Your solution is an interesting workaround, but the correct implementation
> is to simply remove these classes using JavaScript:
>
> .slds-backdrop--open
> .slds-fade-in-open
>
> Once the animations are over (there's a JavaScript listener for that), you
> may then apply slds-hide to both elements or remove them entirely from
> the DOM.
>
> @stefsullrew <https://github.com/stefsullrew> @donnieberg
> <https://github.com/donnieberg> is this correct or is there something to
> add?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/salesforce-ux/design-system/issues/218#issuecomment-219887158>
>



-- 
Regards,
Steve Drucker
Founder / President
Fig Leaf Software
http://www.figleaf.com
http://training.figleaf.com
Acquia, Adobe, Brightcove, Ektron, Google, Paperthin, Sencha
Consulting/Training/Sales/Support

"We've got you covered"

Fig Leaf Software is a Service-Disabled Veteran-Owned Small Business
(SD-VOSB) on GSA Schedule

**Comment by donnieberg** [comment]
I guess it's a matter of where you declare the "logic" to show/hide the modal & background. I really like the solution of removing `.slds-backdrop--open` and `.slds-fade-in-open` because looking at your html, that seems to be more semantic of seeing those classes present when the modal is open but not seeing those classes when it's hidden.

I'm not 100% sure on the best way to write a js listener though. We implemented the modal in react so we're just adding/removing the entire dom element with js.

**Comment by kaelig** [comment]
Closing this as JavaScript is required to make this work.
