### ISSUE TITLE
Feature request: support button-group sizes

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#220]
I would like to be able to specify the size of each button inside a button group with one class.

Something like this: 

```html
<div class="slds-button-group slds-button-group--small" role="group">
...
</div>
```

**Comment by stefsullrew** [comment]
A button-group is a flex container. Therefore, all buttons inside will be the same height (from the `stretch` value). If you want a `.button-group--small`, you'll just need to define each button inside to be the small sized button and it will automagically happen.

**Comment by bekos** [comment]
@stefsullrew Thanks for the response :-)

What I was asking though, is not to have to define the small size on each button, but define it once on the button group. Similar to what Bootstrap is doing. See http://v4-alpha.getbootstrap.com/components/button-group/#sizing

**Comment by stefsullrew** [comment]
I don't think it's safe to mention to you that very shortly, there won't be any small sizing on buttons. There was a "tightening" effect that happened in the rev you're about to receive, so all buttons are the same as small buttons now. Hope that info helps. :)

**Comment by bekos** [comment]
@stefsullrew Thx! This is helpful. I will wait for the new revision then, before asking any new things :-)
