### ISSUE TITLE
Data Table - sorted column should always show direction arrow

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#221]
Hi,

I know there are some differences between the current design-system and whats available in Lightning Experience, but this one sounds like one that should be supported in the design system.

In short, on a data table once a column has been sorted I think the direction of the sort should be persistent like in Lightning:

![image](https://cloud.githubusercontent.com/assets/415690/15350813/682de7be-1cd3-11e6-98a8-7bfe0e6eb7bc.png)

As far as I can tell there is no built in support for this in SLDS yet. I think something like "slds-is-sorted" on a <th> should be enough for this.

Thanks,
Matt

**Comment by stefsullrew** [comment]
You're absolutely correct. And it's something we discussed just yesterday.

Cheers

**Comment by kaelig** [comment]
Thanks a lot for your suggestion!

Our examples now show this use case using an `slds-is-sorted` class on the `th`: https://www.lightningdesignsystem.com/components/data-tables/#flavor-advanced-sorted-column-desc

**Comment by felix-uncle** [comment]
but it seems that it doesn't work nice in classcial style what should I do?
