### ISSUE TITLE
Checkbox - Support tri-state (use case in data table header)

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#222]
Hi,

It'd be great if Checkbox had a third state. The use case in mind is in a Data Table header to indicate that some of the rows have been selected, but not all:

![image](https://cloud.githubusercontent.com/assets/415690/15351523/8d75c95c-1cd7-11e6-9f79-e3accba6c938.png)

For now I've mocked something out using an icon button like so:

![image](https://cloud.githubusercontent.com/assets/415690/15351548/ad0933a8-1cd7-11e6-9368-0c55845195d6.png)

But it would be great to have built in support for this.

**Comment by kaelig** [comment]
Cheers Matt, thank you for using the Lightning Design System.

This is on our radar for a future release, so watch this space!

In the mean time, feel free to share your code in this thread so other developers can benefit from it!

**Comment by stefsullrew** [comment]
I was looking at this last week. One of the issues is accessibility of that state. By nature, a checkbox doesn't have that third state, so we're discussing how to best handle it. But it is on our radar. 

Cheers

**Comment by stefsullrew** [comment]
We've worked it out, and it will be in our next full release. Closing this now.

**Comment by mattgoldspink** [comment]
Fantastic! Thanks Stef & team.

Matt
