### ISSUE TITLE
SLDS Home / Overlapping text and horizontal scrolling make content difficult to read 

### ISSUE THREAD

**Issue by seaofclouds** [salesforce-ux/design-system#223]
I think this was introduced recently. When visiting https://www.lightningdesignsystem.com, the home page has strange overflow behavior. Sub pages are not affected.

<img width="799" alt="screenshot 2016-05-19 08 56 05" src="https://cloud.githubusercontent.com/assets/708/15400680/3495f10c-1da1-11e6-9a59-1dd7c3f12255.png">

Safari Version 9.1 (11601.5.17.1)

**Comment by kaelig** [comment]
Thank you for reporting this, Todd!

I couldn't reproduce the issue when I tested in your version of Safari, as well as the latest, and the technology preview. I've also tested in iOS, with no chance.

Is there a browser extension installed that could be causing this?
Does this happen in a Private Window too?

**Comment by kaelig** [comment]
@seaofclouds can you show me how to reproduce the bug? I can't seem to be able to reproduce it myself.

**Comment by seaofclouds** [comment]
@kaelig open SLDS home page in Safari, scroll left. The bug does not appear in smaller viewports, so if you resize to a smaller viewport, the page seems to work as intended. Here's an updated screenshot. 

Safari 9.1.1

![image](https://cloud.githubusercontent.com/assets/708/16203884/4554c8d0-36d1-11e6-9424-508f0fb6a7b7.png)
