### ISSUE TITLE
Spinner not taking the full height of the screen.

### ISSUE THREAD

**Issue by SamrinS** [salesforce-ux/design-system#224]
I have visual force page where I have 2 sections. The first section fits half of the screen vertically. On click of a button I display the spinner and then  I am displaying the second section wherein my screen height increases and a vertical scroll bar is displayed. Now if I scroll down and click on the same button, the spinner is displayed but it only occupies the height of my previous screen as in screen before displaying the second section.

**Comment by stefsullrew** [comment]
@SamrinS - The container you're trying to fill with the spinner — does it have `position: relative` placed on it? In other words, not the first or second section, but their parent element?

**Comment by SamrinS** [comment]
Thanks, "position:  relative" on my container div having class "slds" works. The spinner occupies the full height.

**Comment by stefsullrew** [comment]
If you want to use a class, we've created positioning utilities, so you can add - `.slds-is-relative` to the container div. Cheers
