### ISSUE TITLE
Throw errors for Gulp

### ISSUE THREAD

**Issue by erinjerri** [salesforce-ux/design-system#225]
I've gotten all kinds of errors when installing gulp, updating, and then re-downgrading Node to Node 5 instead of the most recent release. 

I also received this error at first that has something to do with the .json file.
`npm WARN ENOENT ENOENT: no such file or directory, open '/Users/userid/package.json'
npm WARN EPACKAGEJSON userid No description
npm WARN EPACKAGEJSON userid No repository field.
npm WARN EPACKAGEJSON userid No README data
npm WARN EPACKAGEJSON userid No license field.`
Similar to what is filed `[here](https://github.com/npm/npm/issues/9161)`

Then after I updated Homebrew, to the Node version recommended [here](https://github.com/driftyco/ionic-cli/issues/960)

I think there was something with [graceful-fs](https://www.google.com/search?q=(node%3A39878)+fs%3A+re-evaluating+native+module+sources+is+not+supported.+If+you+are+using+the+graceful-fs+module%2C+please+update+it+to+a+more+recent+version.&oq=(node%3A39878)+fs%3A+re-evaluating+native+module+sources+is+not+supported.+If+you+are+using+the+graceful-fs+module%2C+please+update+it+to+a+more+recent+version.&aqs=chrome..69i57.489j0j1&sourceid=chrome&ie=UTF-8). 

I always have the worst time installing anything with Homebrew, and particularly Gulp and even ReactJS, one time my cpu just forced itself into EMACS. 

Then I got this random throw error. I'm still throwing up my hands trying to figure out how to install and run this, any help is much appreciated and I'm willing to pair with anyone on Slack to resolve

`module.js:442
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)`

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System, @erinjerry!

The package you attempted to install isn't supported by Salesforce. Allow me to redirect you directly to the repository that holds the code for this project: https://github.com/stomita/react-lightning-design-system

**Comment by erinjerri** [comment]
No my components also worked for installing react-lightning design system,
the main salesforce design system failed with npm installs, gulp installs
etc.
