### ISSUE TITLE
Tab doesn't resize properlly for mobile screen

### ISSUE THREAD

**Issue by ankushsomani09** [salesforce-ux/design-system#226]
Tab should have different style for mobile screen, 
also at most of the style, in small window text get ellipses style. 
So not able to read in mobile screen , while in desktop on hover we can read.

![snap1_desktop](https://cloud.githubusercontent.com/assets/2452618/15738477/0cdf0526-28c9-11e6-8f87-8f4c0d111f74.png)
![snap1_mobile](https://cloud.githubusercontent.com/assets/2452618/15738480/10c74108-28c9-11e6-91bb-fd7c9272b80e.png)

**Comment by stefsullrew** [comment]
Hi @ankushsomani09 — we plan to do more mobile work soon. I'll add this to the list.
