### ISSUE TITLE
x-small circle icon has oval shape

### ISSUE THREAD

**Issue by dlengyel** [salesforce-ux/design-system#228]
I stumbled upon this minor UI bug - when _.slds-icon_container_ has a circle shape _.slds-icon_container--circle_ and svg tag _.slds-icon_ has a x-small size _.slds-icon--x-small_, resulting shape is rather oval because of _line-height: 1.7142857143_ inherited from html element. 

<img width="657" alt="snimek obrazovky 2016-06-06 v 10 32 59" src="https://cloud.githubusercontent.com/assets/2807682/15816284/5957baea-2bd2-11e6-8f72-dd868a7c3aeb.png">

When **line-height attribute on .slds-icon_container is set to 0**, icon is nicely round and x-small.

**Comment by stefsullrew** [comment]
Hi @dlengyel, thanks for the feedback. We'll have a look at this. 

Cheers

**Comment by rakeshrockb** [comment]
Any update on this issue?. Thanks!.

**Comment by dmacompton** [comment]
Waiting for resolve this issue.

**Comment by ButuzGOL** [comment]
+1

**Comment by chupchap** [comment]
+1

**Comment by mattparkerls** [comment]
2 years later - any updates on this? Thanks!

**Comment by engai** [comment]
Hi all, this shouldn't be stale. Logging this as a bug and should have a fix for Winter '19. Apologies for the delay folks.

**Comment by engai** [comment]
This was resolved with https://github.com/salesforce-ux/design-system/commit/f9d359953bacf233a92188767dbd194d2b7d70a8
