### ISSUE TITLE
Feature Request: Support concurrent processes in SLDS Process component

### ISSUE THREAD

**Issue by wtf0722** [salesforce-ux/design-system#229]
We're working on a project that requires a higher view of our order process where we show the status of each step. For now, we built a breadcrumb style status bar in visualforce that is very similar to the SLDS Process component. In SLDS, assigning 2 different sequential sections as "current" causes some visual issues. Please see below:

![screen shot 2016-06-07 at 4 40 07 pm](https://cloud.githubusercontent.com/assets/1031626/15873914/c701abb2-2cce-11e6-80e5-b085a53bd9aa.png)

This is what I created using CSS, as an example without using SLDS, showing the points of the chevrons colored correctly:

![screen shot 2016-06-07 at 4 34 12 pm](https://cloud.githubusercontent.com/assets/1031626/15873948/e8babf64-2cce-11e6-904e-6f2e010d8228.png)

This shows that the order is being worked by both the Billing and Onboarding teams.

I realize some CSS can be added to make SLDS function like this, but I thought it may be valuable if SLDS supported it out of the box.

Sorry if this is already possible, but I didn't see a native way to achieve this using SLDS.

**Comment by stefsullrew** [comment]
Hi @wtf0722, nice to see you working with the Design System.

This component is built to be a progress indicator. So there is no internal pattern for having two "current" sections. That said, I can add this as an enhancement request. 

Cheers
