### ISSUE TITLE
Link to media-object doesn't work

### ISSUE THREAD

**Issue by elycom** [salesforce-ux/design-system#230]
https://www.lightningdesignsystem.com/components/media-objects

**Comment by stefsullrew** [comment]
@elycom - hey, can you tell me where in the site you saw that? We moved the media objects to utilities and apparently missed a reference. Cheers

**Comment by aputinski** [comment]
Redirect should be working now. Thanks for catching this!

**Comment by elycom** [comment]
In Trialhead Workshop-lightning-design-system-visualforce-header avatar

In Resources Media Object (yestarday it didn’t work, but today I checked and now it works)

 

https://developer.salesforce.com/trailhead/project/workshop-lightning-design-system-visualforce/slds-vf-05-page-header-avatar

 

Da: Stephanie Rewis [mailto:notifications@github.com] 
Inviato: giovedì 9 giugno 2016 01:44
A: salesforce-ux/design-system
Cc: Elena COMUNIAN; Mention
Oggetto: Re: [salesforce-ux/design-system] Link to media-object doesn't work (#230)

 

@elycom <https://github.com/elycom>  - hey, can you tell me where in the site you saw that? We moved the media objects to utilities and apparently missed a reference. Cheers
