### ISSUE TITLE
[Data Tables] Class `.slds-table--striped`does not apply the striped style to the row's <th scope="row" /> column.

### ISSUE THREAD

**Issue by konsti** [salesforce-ux/design-system#232]
If you add the class `.slds-table--striped` to a `.slds-table` the striped style is not applied to the full row. If the first element is a `<th scope="row" />` the column stays white.

![screenshot 2016-06-09 16 43 47](https://cloud.githubusercontent.com/assets/184014/15933808/73728158-2e61-11e6-816f-5846ee34f944.png)

**Comment by brandonferrua** [comment]
Thanks for reporting this, we'll look into it!

**Comment by kaelig** [comment]
Reopening this. We can close it when the fix makes it to the public.

**Comment by kaelig** [comment]
This should be fixed in v2.0.2, thank you again for reporting this!
