### ISSUE TITLE
Search! feature on website disappeared ?

### ISSUE THREAD

**Issue by ennoucas** [salesforce-ux/design-system#233]
Where is the Search! feature on your website ? It was really useful :)

**Comment by FabienTaillon** [comment]
It will be back :)
https://twitter.com/salesforceux/status/740213200365359105

**Comment by ennoucas** [comment]
Oh okay  :D !

**Comment by kaelig** [comment]
Apologies for the inconvenience, we're working on bringing it back!

**Comment by kaelig** [comment]
We brought Search back! I hope it helps, and feel free to submit feedback :)

**Comment by FabienTaillon** [comment]
Great ! :D :dancers:
