### ISSUE TITLE
Feature request: text themes

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#234]
Similar to how themes work, it would be useful to have some utility classes to colour just the text. ie slds-text--error, slds-text--warning etc

Similar to what bootstrap does here: http://v4-alpha.getbootstrap.com/components/utilities/#contextual-colors-and-backgrounds

Thank you and keep up the good work 👍

**Comment by kaelig** [comment]
Hi @bekos, and thanks again for using the Lightning Design System!

I'll tag these as a feature request, and the team will consider it in future revisions. Cheers!

**Comment by istiti** [comment]
actually we miss slds-text-color_warning by example 

cc @srohde
