### ISSUE TITLE
Nested Data Tables example dissapeared

### ISSUE THREAD

**Issue by krystiancharubin** [salesforce-ux/design-system#235]
Example of Nested Date Table no longer available under Components>DataTables>Advanced

**Comment by kaelig** [comment]
Hi @krystiancharubin, thank you for using the Lightning Design System.

I couldn't find the nested data table component, is it possible that you were referring to the Tree Grid component's grid flavor? https://www.lightningdesignsystem.com/components/trees/#flavor-grid

**Comment by krystiancharubin** [comment]
Yes, I was referring to the Tree Grid component. Sorry for the confusion, I just expected that to be under the Date Table page.

**Comment by kaelig** [comment]
That's absolutely fine, have a great day!
