### ISSUE TITLE
Developer Org not showing Lightning CSS via Visualforce

### ISSUE THREAD

**Issue by TronJavolta007** [salesforce-ux/design-system#237]
I'm going through the Lightning Design System Trailhead and adding the static resource, downloaded from the links provided, following each step exactly as it says but my org is not showing the same image as the one in the directions. I have the zip file saved as 'slds201' and copy/pasting the lines of code provided and still no luck. 

`<apex:stylesheet value="{!URLFOR($Resource.slds201, 'assets/styles/salesforce-lightning-design-system-vf.css')}" />`

I have gone ahead to another trailhead, 'Using Visualforce in Lightning Experience', to put together those pages to display the theme I'm supposed to be seeing via $User.UIThemeDisplayed global variable and related functions. On those pages it shows:

$User.UIThemeDisplayed: Theme4d

UIUtils JavaScript
ForceUI.UserUITheme: Theme4d
isSalesforce1(): false
isLightningExperience(): true
isSalesforceClassic(): false

I'm not sure what I'm doing wrong.

**Comment by kaelig** [comment]
Hi @TronJavolta007, thank you for using Trailhead and the Lightning Design System, and for asking for help here.

Apologies for the inconvenience, we're currently updating the Trailhead module.

You should have better results using this tool: https://tools.lightningdesignsystem.com/css-customizer that generates a scoped version of the Design System and does contain the `salesforce-lightning-design-system-vf.css` file.

The whole process will be reflected shortly on Trailhead. Thank you for your patience!

**Comment by TronJavolta007** [comment]
Thank you @kaelig, it is now working perfectly!
