### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by johnagan** [salesforce-ux/design-system#238]
👋  @jina @srohde @BrunoFonzi @amyleesalesforce & team

I just ran across this Design System while looking for info on ⚡  components. It's been a while since I last saw this and it looks **fantastic** and really well done! Really great job everyone 👏  

Also, I found what I was looking for here as well 😎

**Comment by jina** [comment]
Yay, Thanks! Also… how come you need ⚡ components? Intriguing… 😉

**Comment by kaelig** [comment]
:)
