### ISSUE TITLE
Unwanted padding in the outer div | Salesforce1 Lightning app | app.css |  Latest release

### ISSUE THREAD

**Issue by aravindqb** [salesforce-ux/design-system#239]
![image](https://cloud.githubusercontent.com/assets/15011890/16115684/3e40f070-33e6-11e6-945f-b2f849e97df1.png)

A padding of 0.75rem has been added to an outer div as shown in the above image in the latest Salesforce1 app. It's affecting the custom styling of the application.
Please do the needful to fix the same. In the earlier version of the app, there hasn't been any such issues.

**Comment by kaelig** [comment]
Thank you for bringing this up to our attention, @aravindqb!

As this is unrelated to the Design System, you might have a better chance to get an answer on your typical support channel for all things Salesforce, or on the Salesforce developer forums.
