### ISSUE TITLE
Sales Path Coach Enhancement

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#241]
I'd like to suggest an enhancement for the Sales Path Coach/Wizard. Currently there is formatting for Complete/Incomplete but noting for disable. A good example of this would having a RFQ stage. Large clients generally require a Formal RFQ stage while smaller ones don't. We currently handle this in general by having different Record Types, but it would be good to be able to reflect this in the Sales Path.  As implemented now, for the record Types that skip stages, we just have a empty placeholder in the path and have the path just mark it as complete. This is a little miss leading though as the stage is not Complete it was skipped as not necessary for the Sales Flow. 

We are happy to provide pull request for this if this that would help. 

I would also recommend changing the name From Sales Path Coach as well (probably best as just Path Coach). We've started to utilize it as good linear workflow path indicator. Our users really like how clear and easy to read it is. We are currently utilizing it for Sales, and even services escalation workflows.

**Comment by kaelig** [comment]
Hi @JohnHeadIV, thank you for using the Lightning Design System and for suggesting this enhancement.

I'll direct your suggestion to our designers who are always grateful to hear such constructive feedback.
