### ISSUE TITLE
Add support for plain text breadcrumb elements

### ISSUE THREAD

**Issue by pixelprodotco** [salesforce-ux/design-system#242]
Hello all,

I'm working on adding an app to the SFMC admin and the design calls for a plain text element within the breadcrumbs

![image](https://cloud.githubusercontent.com/assets/3115965/16123185/214134e0-33b8-11e6-828b-6178d105045c.png)

Currently, if we add a span in place of a link, the appropriate padding is not applied and the > divider is positioned over the right side of the span

![image](https://cloud.githubusercontent.com/assets/3115965/16123513/4407ff80-33b9-11e6-9ae0-2ce90e29d113.png)

By adding a span to the breadcrumb declarations that style the anchor tags, all is resolved.  

![image](https://cloud.githubusercontent.com/assets/3115965/16123529/573faa26-33b9-11e6-8f6f-fb07ea40deb5.png)

**Comment by pixelprodotco** [comment]
https://github.com/salesforce-ux/design-system/pull/243

**Comment by kaelig** [comment]
Closing this for the reasons mentioned in #243

**Comment by pixelprodotco** [comment]
@kaelig Thanks for your time.  I've passed this feedback along to my product owner.
