### ISSUE TITLE
Sortable table markup not functioning properly in Lightning Component for Summer 16

### ISSUE THREAD

**Issue by missymar** [salesforce-ux/design-system#245]
Hi,

In the latest data table markup, we noticed the up/down arrow functionality is not working. Please let us know if this has been looked into and if there is a remedy for this.

Thanks!

**Comment by kaelig** [comment]
Hi @missymar, thank you for reporting this!

The Lightning Design System provides CSS and HTML, and gives developers the choice of implementing interactive functionality using the JavaScript framework / library of their choice.

Feel free to share the way you implemented this functionality, I'm sure other developers in the community would appreciate it.

**Comment by missymar** [comment]
Hi @kaelig, thank you for the quick response.  To clarify, it isn't JS related, the actual slds class (slds-is-sortable) isn't functioning in a lightning component.

**Comment by kaelig** [comment]
Thank you for clarifying! Some of the SLDS 2.0.1 improvements over SLDS 2.0.0 (which is available in Lightning by default) are available to developers who install SLDS 2.0.1 (and up) as a static resource.

To get these new classes to work, you may install SLDS as a custom scoped static resource using the tool mentioned in the download page: https://www.lightningdesignsystem.com/resources/downloads/#unmanaged

**Comment by missymar** [comment]
@kaelig We inspected the slds related styles available in Lightning Components for Summer 2016 and found no styles associated with the hover states for sortable tables.  All svgs for the sort arrows are always visible and for 2.0.1 they are only visible on hover. Are the new sortable table styles available?  Attached are 2 screenshots displaying the differences for my mockup. Thanks!
<img width="1082" alt="arrows always visible" src="https://cloud.githubusercontent.com/assets/12707414/16131104/033e8776-33d2-11e6-9a45-82d35756626f.png">
<img width="1142" alt="arrows visible on hover" src="https://cloud.githubusercontent.com/assets/12707414/16131103/0339e77a-33d2-11e6-9c18-11a62802890c.png">

**Comment by kaelig** [comment]
The Summer ’16 release features the 2.0.0 CSS, and the 2.0.1 CSS (which should include the styles for sortable tables) is available to developers as an additional download that you may get using the Custom Scoped tool: https://tools.lightningdesignsystem.com/css-customizer

I hope this helps!

**Comment by missymar** [comment]
Thank you. Any idea when 2.0.1 styles without a static resource will be available to Lightning Components?

**Comment by kaelig** [comment]
I am not aware of any plans to make 2.0.1 available to Lightning Components, but if it happens we'll let you know!
