### ISSUE TITLE
New Tree Grid missing from docs in 2.0.2

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#246]
We're using the new tree grid since the 2.0.x release, but in the recent 2.0.2 release the docs for it have disappeared. There's no mention in the release notes that it's been removed, so I assume it's a mistake.

**Comment by JohnHeadIV** [comment]
I've noticed a number of rendering issues with the documentation site currently. Various components are missing but appear when searched for. They are also visible in the raw HTML but not being rendered correctly. I've specifically noticed that the Sales Path is gone as well. (The Wizard is the only component visible under process).

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this.

We have hidden a few components by default for specific reasons but we'll be bringing them back shortly. Apologies for the inconvenience and thank you for your patience.

**Comment by kaelig** [comment]
We've just restored components that were temporarily hidden. Let us know if there is anything else we can do to help you!
