### ISSUE TITLE
Lookup more examples

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#248]
It would be great if example page will have:
1. Lookup opened
2. Lookup selected
3. Lookup searching
...

**Comment by krystiancharubin** [comment]
Hello ButuzGOL,

The example page already has all the different lookup states you listed.
https://www.lightningdesignsystem.com/components/lookups/#flavor-single
If you look on the right side under VARIANTS & STATES>Single, you can select option to see example code for Default, Active, Typeahead and with Selection states.

**Comment by srohde** [comment]
Thanks for helping out @krystiancharubin

**Comment by ButuzGOL** [comment]
oh I see thanks
