### ISSUE TITLE
Compact or small alternative version of Select form field

### ISSUE THREAD

**Issue by fredboyle** [salesforce-ux/design-system#249]
On occasion a more compact version of the form field is needed to avoid situations as shown in the attached screenshot.

![screen shot 2016-06-17 at 11 10 59 am](https://cloud.githubusercontent.com/assets/32829/16160346/6cdc2b20-347c-11e6-8db0-7f3ddf273bba.png)

**Comment by kaelig** [comment]
Thanks for submitting this request, Fred! If it's an internal request you may use the official channels (see "Component requests" on the SLDS Tile page) and it will have more chance to get prioritized.
