### ISSUE TITLE
Mixed ways to load modules

### ISSUE THREAD

**Issue by Guria** [salesforce-ux/design-system#25]
I see in sources mixed ways how modules used. One file can contain both `ES6` and `CommonJS` ways.
Is it normal or should be done in consistent way?

**Comment by amyleesalesforce** [comment]
Both ways work but being consistent would definitely look more "pretty". At least the end result is still the same.

**Comment by Guria** [comment]
I plan to spent some time digging in sources to know how things done. It wouldn't hard to me to make a pr with coonsistent imports.

**Comment by Guria** [comment]
What do you say on my proposal? Should I do it?

**Comment by amyleesalesforce** [comment]
Hi @Guria! Sure, why not!

In general, it should be pretty simple. A couple of things:

* We've been importing globals as `g` now, `import g from 'app_modules/global';`
* The prefixer we've been aliasing `import { perfix as pf }` :)

Any help is awesome! Thanks!

**Comment by Guria** [comment]
How you recommend:
* 1 file per 1 commit per 1 pr
* 1 file per 1 commit, several commits in 1 pr
* collect as much as I can into 1 commit / 1 pr
* another scheme

**Comment by amyleesalesforce** [comment]
1 commit in 1 PR with all changes to all files would be best. :)
