### ISSUE TITLE
Lookup selected and start searching reseting prev value

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#250]
Now As I see when it selected with something 
and we want to reselect, it reset prev value and you start searching
is there any plans to do with not reseting prev value and do search
like in https://select2.github.io/examples.html

**Comment by kaelig** [comment]
Thank you for your question, @ButuzGOL!

I'm curious what part of the Design System you are referring to exactly. Can you please be more specific (a quote of the documentation, URLs and/or additional screenshots or screencasts would be useful).

**Comment by ButuzGOL** [comment]
Attaching gif file 
![example](https://cloud.githubusercontent.com/assets/196564/17664218/3db38cd2-62fb-11e6-97ce-eddf94bb6cab.gif)
So I can only remove to start searching but its nice to see prev value

**Comment by kaelig** [comment]
I see! Thank you for the gif. I'll mark this as a feature request and forward it to @srohde who can assess what should be done about it.

**Comment by kaelig** [comment]
Closing this as this type of interaction is a UX decision made at the platform level.
