### ISSUE TITLE
feat(datepicker): add `slds-is-active-date` class

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#252]
When navigating datepicker with the keyboard we need an extra class to show which is the currently active date, something like the one applied on `5`. (The proposed class name is not the best suggestion, I know :-) )

![my tasks salesforce](https://cloud.githubusercontent.com/assets/551595/16226332/99b3806e-37b3-11e6-9771-f5401be9c50f.png)

Thank you :-)

**Comment by kaelig** [comment]
Thank you for the suggestion, @bekos!

We'll be looking into it shortly.
