### ISSUE TITLE
Text inconsistencies in header rows

### ISSUE THREAD

**Issue by aaurrichio** [salesforce-ux/design-system#253]
Wondering whether or not LDS intentionally uses UPPERCASE text in all [Data Table](http://www.lightningdesignsystem.com/components/data-tables/) header rows, but uses Sentence Case in the [Advanced Modal Lookup](http://www.lightningdesignsystem.com/components/lookups/#flavor-advanced-modal) header row. The color treatment is off as well. All data table header rows use the 'recede' text treatment, while the one in the advanced lookup uses 'default.'

Screenshots attached. Clarity here would be much appreciated!

<img width="956" alt="advancedmodal" src="https://cloud.githubusercontent.com/assets/5330829/16245784/7702b522-37d0-11e6-92a8-461742a4ff65.png">
<img width="1067" alt="carddatatable" src="https://cloud.githubusercontent.com/assets/5330829/16245783/770227f6-37d0-11e6-968d-b1a33dc123ed.png">
<img width="1054" alt="datatable" src="https://cloud.githubusercontent.com/assets/5330829/16245785/770564c0-37d0-11e6-8e74-20f2d05e9367.png">

**Comment by kaelig** [comment]
Thank you for reporting this, @aaurrichio, good catch!

We'll check with our designers and we'll let you know what is the resolution for this discrepancy.

**Comment by kaelig** [comment]
This was recently fixed and the design settled for uppercase text across the board, thanks again for reporting this!
