### ISSUE TITLE
Multi-Select Lookup Variant

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#254]
Why was this component variant removed?

https://github.com/salesforce-ux/design-system/commit/29152bb59499f2522f9ce40d2b646d5c874abc52

**Comment by kaelig** [comment]
Hi @banderson5144, thank you for using the Lightning Design System!

This variant was renamed to "polymorphic". Keep in mind this is at a prototype stage and might change in the future.

Does this help?

**Comment by banderson5144** [comment]
Kinda.

Can you update the example to show what happens when multiple values are selected? Right now that pill fills the entire input field.

**Comment by wwwdata** [comment]
I am also missing this. If you activate for example the `Allow Users to Relate Multiple Contacts to Tasks and Events` in `Activity Settings` it's possible to select Multiple Contacts for an Event and the Component exists there and is usable.. 

Please update the example with exactly the same layout that is used on the salesforce platform. In the meantime, I guess we have to steal the markup directly from there @banderson5144

**Comment by engai** [comment]
Hi @banderson5144, we have included an "Options Selected" example in Summer '18 which should be released in early May.

**Comment by engai** [comment]
@banderson5144 This has been resolved in summer-18. Please see https://www.lightningdesignsystem.com/components/lookups/?state=options-selected&variant=multi-entity

Closing this issue, but feel free to comment/reopen if necessary.
