### ISSUE TITLE
Data Table & Picklist display issue

### ISSUE THREAD

**Issue by jbroquist** [salesforce-ux/design-system#255]
I'm having an issue with using the Data Tables and Picklists together. I can't figure out how to force the picklist menu to display over the table properly.

**Picklist Menu Closed:**
![screen shot 2016-06-22 at 5 32 27 pm](https://cloud.githubusercontent.com/assets/852476/16288328/73ad1c76-389f-11e6-8062-95649f952328.png)

**Picklist Menu Open:**
![screen shot 2016-06-22 at 5 29 22 pm](https://cloud.githubusercontent.com/assets/852476/16288304/3d6ffa2a-389f-11e6-8845-60c94fa1a4f6.png)

Any ideas on quick fixes for this?

**Comment by kaelig** [comment]
Hi @jbroquist, thank you for using the Lightning Design System!

Can you please provide a code snippet or an example in CodePen so we can investigate?

**Comment by kaelig** [comment]
Closing this as there is a lack of context.
