### ISSUE TITLE
Checkbox/Radio Group Alternative disabled rendering

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#256]
When a CheckBox Alternative or Radio Group Alternative
(i.e. rendered as button group)
has a value (i.e. selected) and the element is disabled, one cannot distinguish any existing selections.
Works well for Radio Group, "sort of" for multiple checkboxes, but not for buttons.
When hovering over the disabled Alternative Buttons, they are rendered blue.

![image](https://cloud.githubusercontent.com/assets/168846/16291940/3fc10dba-38c1-11e6-893c-be7e7c04bf9b.png)

**Comment by kaelig** [comment]
Thank you for reporting this, @jorgjanke!

This is a use case the SLDS doesn't cover yet but we'll look into it shortly.

**Comment by engai** [comment]
Hi @jorgjanke, a fix for the checked & disabled state in Checkbox and Checkbox Button Group will be released with 2.7.0 (Winter '19)

**Comment by JohnHeadIV** [comment]
@engai Should statebot be marking roadmaps as stale, or left open till delivered?

**Comment by engai** [comment]
@JohnHeadIV The latter of course. Thanks for catching this. I've updated Stalebot to ignore 'roadmap' and it should now wait 120 days to better align with our release cycle. Coming soon in our next push.

**Comment by engai** [comment]
Hey folks, this has been resolved with https://github.com/salesforce-ux/design-system/commit/8614d1c0c21430bf6be7675978b2d61689b5c040
