### ISSUE TITLE
Missing css files in 2.0.2

### ISSUE THREAD

**Issue by acarl** [salesforce-ux/design-system#258]
The following files exist in the assets/styles directory of the zip file for 2.0.0 but not for 2.0.2.
Is this just a packaging issue?

salesforce-lightning-design-system-ltng.css
salesforce-lightning-design-system-ltng.min.css
salesforce-lightning-design-system-scoped.css
salesforce-lightning-design-system-scoped.min.css
salesforce-lightning-design-system-vf.css
salesforce-lightning-design-system-vf.min.css

**Comment by kaelig** [comment]
Hi @acarl, thank you for using the Lightning Design System!

These files are now downloadable through the SLDS CSS customizer tool.

Can you follow the instructions in this [getting started page](https://www.lightningdesignsystem.com/getting-started/lightning/) and let us know if that works for you?

**Comment by acarl** [comment]
Thanks for the quick response. The generated version works great. Definitely a nice feature to have.

I would have noticed this sooner if it was in the release notes.

**Comment by jclark-dot-org** [comment]
+1 for adding to release notes.  Also, the Trailhead "Lightning Components Basics" still expects the default zip to contain "salesforce-lightning-design-system-ltng".

**Comment by kaelig** [comment]
Thank you very much for that feedback, @jclark-dot-org. We're in the process of updating our Trailhead modules, apologies for the inconvenience and many thanks for your patience. If you haven't already, you can get these badges soon :)

I'm hoping this will become much clearer when they're up to date and sorry again for the confusion.

> Could I/Should I have just removed "-ltng" from the ltng:require tag in the trailhead lightning app?

Possibly, although then the chances that your component will have styling collisions with other ones is higher. I wouldn't recommend that!
