### ISSUE TITLE
Lightning Design System Getting Started with the Design System

### ISSUE THREAD

**Issue by Pillzy** [salesforce-ux/design-system#259]
In the Trailhead 'Lightning Design System Getting Started with the Design System' it specifies the following path to get the Visualforce version of the SLDS .css:

'assets/styles/salesforce-lightning-design-system-vf.css'

However when I downloaded the latest version of the SLDS (2.0.2) there is no such file. I simply removed the '-vf' to use the Lightning Experience version of the .css and all works well.

Am I missing a .css file or were they merged into the 1 fully functional .css?

**Comment by kaelig** [comment]
Thank you for reporting this, @Pillzy! Glad you found the workaround!

We are in the process of updating the documentation. Apologies for the inconvenience, and thank you for your patience.

**Comment by ashishbt82** [comment]
I See 2 files in the zip folder 

salesforce-lightning-design-system-vf.css
salesforce-lightning-design-system-vf.mincss but this doesn't work. I followed the above work around and it works. 

Regards,
Ashish
