### ISSUE TITLE
AccessibleList doesn't set currentIndex state on first click

### ISSUE THREAD

**Issue by Guria** [salesforce-ux/design-system#26]
https://www.lightningdesignsystem.com/components/grid-system

Click any `SMALL` tab. Press right-arrow.

Expected: 
`MEDIUM` tab selected

Actual:
`SMALL` tab stays selected

React dev tools shows that currentIndex state doesn't set on first click.

**Comment by kaelig** [comment]
This was fixed in a recent release, thank you for reporting this!
