### ISSUE TITLE
Text Input has Safari shadows on Salesforce1 for iOS (Browser + App)

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#260]
When using the basic text input from SLDS in Salesforce1 for iOS (either in the browser or in the App), it displays an inner shadow:

![fullsizerender_1](https://cloud.githubusercontent.com/assets/2465122/16417948/2147c5f0-3d48-11e6-9e66-f8a066b8fd26.jpg)

This is not happening for standard pages in Salesforce1, so I also don't expect to see it on my custom input fields. 
This is working fine for other SLDS components like lookup for instance.

I've added "-webkit-appearance: none;" to remove this shadow, but I guess this should be directly added in the styles of the Desgin System.

![fullsizerender_2](https://cloud.githubusercontent.com/assets/2465122/16418177/0bb0913a-3d49-11e6-95a7-c0ccf6c6a06d.jpg)

The markup I used is the one from [SLDS documentation](https://www.lightningdesignsystem.com/components/forms/):

```
<div class="slds-form-element">
    <label class="slds-form-element__label" for="text-input-01">Input Label</label>
    <div class="slds-form-element__control">
        <input id="text-input-01" class="slds-input" type="text" placeholder="Placeholder Text" />
    </div>
</div>
```

**Comment by FabienTaillon** [comment]
Actually it's the same for lookups sorry ^^

**Comment by kaelig** [comment]
Merci @FabienTaillon for reporting yet another issue! We are going to focus on mobile very soon, and will make sure to look into this.
