### ISSUE TITLE
Tree Grid - Firefox Bug - first column vertical alignment broken when using th in tbody

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#261]
Hi,

As per the screenshot below from the docs, the first column seems to always be off by 1px when viewed in firefox.
![image](https://cloud.githubusercontent.com/assets/415690/16445489/2d7dd2ce-3de3-11e6-9097-bf4ac42481c3.png)

Matt

**Comment by mattgoldspink** [comment]
The workaround for us right now is to change the border-collapse to:

border-collapse: seperate;

However I think this is a bug in FF when using "border-collapse: collapse;" because the styles for the both the th and td in the table are identical from what I can see, but for some reason the td ignores the border-top width and applies it to border-bottom.

**Comment by kaelig** [comment]
Thank you for reporting this, @mattgoldspink, as well for proposing a workaround!

We're investigating and will provide a fix very soon.

**Comment by kaelig** [comment]
Good news, this seems to have been fixed in SLDS v2.2.1. Feel free to reopen this issue if the problem reappears.

**Comment by mattgoldspink** [comment]
Looks great! Thanks @kaelig & co 👍
