### ISSUE TITLE
slds-size overridden in Compound Form 

### ISSUE THREAD

**Issue by dsharrison** [salesforce-ux/design-system#262]
When using a compound form, any `slds-size` classes placed on `slds-form-element` elements have their width overridden because `slds-form-element` has a more specific selector for its 100% width. This does not show in the example in the docs because the example uses two `slds-size--1-of-2` elements which get equal spacing. The issue can be seen when trying to have different sized form elements such as `slds-size--3-of-4` and `slds-size--1-of-4` in the same row. These incorrectly take up 50% each instead of 75% and 25%.

**Comment by kaelig** [comment]
Thank you for reporting this, @dsharrison!

Could you please share a code example that illustrates the issue?

**Comment by dsharrison** [comment]
Sure thing @kaelig, here is the code from the doc modified so that the city should get 75% of the row and the state should get 25%.

```
<fieldset class="slds-form--compound">
  <legend class="slds-form-element__label">Location</legend>
  <div class="form-element__group">
    <div class="slds-form-element__row">
      <div class="slds-form-element slds-size--1-of-2">
        <label class="slds-form-element__label" for="input-01">Latitude</label>
        <input id="input-01" class="slds-input" type="text" />
      </div>
      <div class="slds-form-element slds-size--1-of-2">
        <label class="slds-form-element__label" for="input-02">Longitude</label>
        <input id="input-02" class="slds-input" type="text" />
      </div>
    </div>
  </div>
</fieldset>
<fieldset class="slds-form--compound">
  <legend class="slds-form-element__label">Address</legend>
  <div class="form-element__group">
    <div class="slds-form-element__row">
      <div class="slds-form-element slds-size--1-of-1">
        <label class="slds-form-element__label" for="input-03">Street</label>
        <input id="input-03" class="slds-input" type="text" />
      </div>
    </div>
    <div class="slds-form-element__row">
      <div class="slds-form-element slds-size--3-of-4">
        <label class="slds-form-element__label" for="input-04">City</label>
        <input id="input-04" class="slds-input" type="text" />
      </div>
      <div class="slds-form-element slds-size--1-of-4">
        <label class="slds-form-element__label" for="input-05">State</label>
        <input id="input-05" class="slds-input" type="text" />
      </div>
    </div>
    <div class="slds-form-element__row">
      <div class="slds-form-element slds-size--1-of-2">
        <label class="slds-form-element__label" for="input-06">ZIP Code</label>
        <input id="input-06" class="slds-input" type="text" />
      </div>
    </div>
  </div>
</fieldset>
```

**Expected Behavior**
![compount-form-expected-behavior](https://cloud.githubusercontent.com/assets/9137905/16509358/b25374fa-3ef0-11e6-8b1e-8b518507cde1.png)

**Current Behavior**
![compount-form-current-behavior](https://cloud.githubusercontent.com/assets/9137905/16509369/c48740de-3ef0-11e6-940b-172315e5d82a.png)

While this is not a practical solution, the expected behavior screenshot was achieved by adding the `!important` declaration to the `slds-size` classes.

Let me know if you have any other questions.

**Comment by kaelig** [comment]
Thank you so much @dsharrison!

**Comment by engai** [comment]
@dsharrison it looks like this has been resolved with https://github.com/salesforce-ux/design-system/commit/56384ec52a681f031493bf35eebe87c0174e243c#diff-f7673f8f4eb5c1e8baf58777b2189176L29

Closing this issue, but feel free to reopen or comment if necessary.
