### ISSUE TITLE
Support slds-min-<SIZE>-hide

### ISSUE THREAD

**Issue by dsharrison** [salesforce-ux/design-system#263]
The responsive utilities provided by SLDS are great for hiding elements, but I have been having trouble with them in respect to showing elements only to small screens. My request is to support a `slds-min-<SIZE>-hide` class that will behave much like `slds-min-<SIZE>-hide` but instead of hiding the element below a certain breakpoint will hide an element above a certain breakpoint. This would allow for rendering certain elements only for screen sizes below 480px for example.

If there is already a way to achieve this today and I am just missing something I would be happy to hear that too.

**Comment by dsharrison** [comment]
I am happy to create a pull request with this enhancement but before I do I would just like to check and see if there was a conscious reason this wasn't in the framework.

**Comment by kaelig** [comment]
Thank you for reporting this, @dsharrison!

Mobile support will be our focus very soon and we will definitely look into it.

**Comment by 3den** [comment]
👍

**Comment by 3den** [comment]
i always get confuse with the responsive show/hide classes we currently have on SLDS, we have adding the min/max prefix to all responsive show/hide classes would help a lot.

Also seems like the proper BEM naming convention for this should be `slds-show--min-<SIZE>` `slds-show--max-<SIZE>` coz the size condition is the modifier that toggles the effect on/off.

**Comment by 3den** [comment]
Any ETA of when this feature will be implemented?

**Comment by istiti** [comment]
+1
