### ISSUE TITLE
Data Table - ability to define initial sort order

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#268]
When we hover over an unsorted column, the arrow that is displayed is the one of the descending order.

There are some cases though, that we want to define the initial sort order as ascending or descending based on the type of values. Is there a way to do this now?

**Comment by kaelig** [comment]
Thank you for asking, @bekos.

At the moment the use case hasn't presented itself to us, but this is an interesting one. I'll ping the rest of the team to see if they have any suggestions for a workaround.

**Comment by kaelig** [comment]
A workaround would be to apply the `slds-is-sorted--asc` class to the `th`. This is not an officially supported use case but it works! Hope this helps.
