### ISSUE TITLE
Issue with ActionFunction when element has svg and 'use' tag 

### ISSUE THREAD

**Issue by amoralesaltimetrik** [salesforce-ux/design-system#27]
I'm currently using a icon button to fire an actionFunction. I've found that when the svg has a 'use' tag referencing to icons or images the action is fired but the page is not rerendered. There's also have a status component that is displayed but never goes out, seems like the action never end. 
   Using svg with <circle ... for example works fine.

**Comment by stefsullrew** [comment]
Hi @amoralesaltimetrik — Do you have a codepen where we can look at what's going on?

**Comment by rickschmoo** [comment]
Also - please confirm your OS and browser versions.

**Comment by amoralesaltimetrik** [comment]
I started to rebuild my original page, it seems the problem happened because I had the buttons  inside an apex:form and page block that was rerendered

**Comment by stefsullrew** [comment]
Thank you for letting us know the resolution! Cheers

On Monday, September 28, 2015, Andrea Morales <notifications@github.com>
wrote:

> I started to rebuild my original page, it seems the problem happened
> because I had the buttons inside an apex:form and page block that was
> rerendered
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/salesforce-ux/design-system/issues/27#issuecomment-143757283>
> .
>


-- 
---
Stephanie Rewis
Lead UI Developer, Design Systems, Salesforce UX
srewis@salesforce.com
