### ISSUE TITLE
Mobile:  Text does not update in an input field on Salesforce1 after moving cursor.

### ISSUE THREAD

**Issue by simspot** [salesforce-ux/design-system#270]
Steps to reproduce:

1. Create a VF page using SLDS with an input field (the sample input example works)
2. Surface the VF page in Setup | Salesforce1 Navigation
3. Open the VF page in Salesforce1 on your mobile device
4. Enter any text on the VF page
5. Move the cursor anywhere in the input field before the last character
6. Enter text
7. Does not update

**Comment by kaelig** [comment]
Thank you very much for reporting this, @simspot.

We've just started focusing on making SLDS work on mobile platforms, so watch this space!

In the mean time, let us know if you found a workaround!

**Comment by simspot** [comment]
Will do!  I'll chatter you behind the scenes too.

**Comment by simspot** [comment]
Also, this is on Salesforce1 IOS

**Comment by simspot** [comment]
@kaelig, this is an iOS specific issue that can be temporarily fixed via javascript.  See the following:

https://success.salesforce.com/issues_view?id=a1p30000000T5l1AAC

**Comment by kaelig** [comment]
Thank you for sharing! Closing this as it seems like a non-SLDS related issue.
