### ISSUE TITLE
Progress/Meter Styling

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#271]
While we heavily utilize the Spinner styling, is there a possibility to add a progress/meter companion. This would clearly be an enhancement but sometimes we are waiting on actions that have we'd like to communicate a sense of progress. The current spinners work well when communicating loading or short time server communications, but File uploads and multi-step server actions would be better served by a more linear styling.

**Comment by kaelig** [comment]
Thank you for this suggestion, @JohnHeadIV! We will be considering it in a future iteration of the Design System.

cc @srohde

**Comment by engai** [comment]
I believe this has been resolved with the introduction of:

Progress Ring - https://www.lightningdesignsystem.com/components/progress-ring
Progress Bar - https://www.lightningdesignsystem.com/components/progress-bar/

Closing this as stale. Feel free to comment or reopen if needed.

**Comment by JohnHeadIV** [comment]
I @engai thank you for this. I would add that a slds-progress-bar__value_error would also be required. This would better match the progress ring (which has a warning and error state). I'm not sure a "warning" state is also required for the progress bar but would suggest it to keep consistent with Guidelines around Messaging state State. 

I would also suggest the documentation reflect that utilization of the "success" state should reflect an update to the assistive text to reflect completion. Of key note would be that 100% != success due to rounding and other potential error states.
