### ISSUE TITLE
Dropdown menu on responsive table not visible

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#272]
I would like to have a dropdown actions menu like this:
![overflow-menu](https://cloud.githubusercontent.com/assets/551595/16759264/bdd39256-481e-11e6-864f-ea0b55d1712d.png)

But because the `.slds-max-medium-table--stacked-horizontal td` has `overflow: hidden` the dropdown menu is hidden inside the `<td>`. So the only way to achieve the above effect is to explicitly set `overflow: hidden` on that `<td>` cell. Is it something you want to address or will you give an utility class to handle this case? 

Thx :-) I hope I made myself clear!

**Comment by kaelig** [comment]
Thank you for reporting yet another issue, we appreciate your feedback!

We recommend positioning dropdowns out of the flow via JavaScript to make sure they're layered on top of the UI and don't get constrained by their parent. It is less trivial to do but it's the only solid way to achieve robust layering of menus in the UI.

**Comment by bekos** [comment]
@kaelig Thanks for your response. I understand what you say, and I see that this the way to go for handling more complex cases.

In this particular case though the menu behaves correctly when the table is on large screens but hides on small ones. Never mind I don't want to insist on this :-)

Keep up the good work and thanks for the great framework.

**Comment by kaelig** [comment]
Thank you for your understanding! This is an interesting use case and the responsive tables are actually still at a "prototype" stage, so we are aware that some use cases might be slightly suboptimal. When we refine this pattern to make it dev-ready, we might be able to get this use case to work. Although I can't make any promises, I'll make sure to bring it up.
