### ISSUE TITLE
$static-font-path / $static-image-path are not correct

### ISSUE THREAD

**Issue by Krisa** [salesforce-ux/design-system#273]
When installed through Npm, assets are actually located in a folder called "assets". Therefore the 2 variables defined in this file https://github.com/salesforce-ux/design-system/blob/master/ui/_config.scss are not correct. 

It shall be instead:
`$static-image-path: '../assets/images' !default;` and
`$static-font-path: '../assets/fonts/webfonts' !default;`

**Comment by matt-newell** [comment]
This works for me locally
`$static-font-path: '/assets/fonts/webfonts';
@import "~@salesforce-ux/design-system/scss/index.scss";`

But then fonts are broken in sfdc. Currently we are redefining the font inside the VF page to fix the url.
`            @font-face{
                font-family: "Salesforce Sans";
                src: url("{!URLFOR($Resource.supervisor, '/assets/fonts/webfonts/SalesforceSans-Light.woff2')}") format("woff2"),
                     url("{!URLFOR($Resource.supervisor, '/assets/fonts/webfonts/SalesforceSans-Light.woff')}") format("woff");
                font-weight: 300;
            }`

It is a bit hacky but does work.

**Comment by matt-newell** [comment]
Ok still working on this but I think I have some progress now.
`$slds-load-webfonts: false;
@import "~@salesforce-ux/design-system/scss/index.scss";`

Then you define the fonts / path in your VF or HTML context.

Can someone verify this is how slds works in npm and sfdc context ?

**Comment by Krisa** [comment]
Defining ahead in my scss `$static-font-path` and `$static-image-path` is eventually working because it's been defined with `!default` in the Npm package, meaning it will not been overwritten afterwards... but now, I don't see why I shall overwrite these 2 variables, while it's something defined in the Npm package, intended to be used within the very same Npm package.

While my code is ultimately intended to work in VF, bundled in a static resource, the bundle itself is done by using Webpack. But the problem is not related to Webpack or any other module bundler, that's clearly an issue in the Npm distribution.

**Comment by kaelig** [comment]
Thank you for using the design system!

I understand configuration might not seem very straightforward.

I've put together a Design System Starter Kit with a simple configuration using Gulp, node-sass and importing SLDS as an npm package:

https://github.com/salesforce-ux/design-system-starter-kit

Of course for Visualforce you could need another file (e.g. `styles-visualforce.scss`) that contains slightly different configuration settings, especially set up for your static resource.

**Comment by matt-newell** [comment]
Yes gulp is ignoring the issues by not trying to resolve the paths. In Webpack however it will try to resolve the path which is a problem when you try local development vs sfdc. The workaround we have found for webpack is $slds-load-webfonts: false; and then define your fonts inside the container i.e (VF page or HTML page)
`
            @font-face{
                font-family: "Salesforce Sans";
                src: url("{!URLFOR($Resource.StaticResourceName, '/assets/fonts/webfonts/SalesforceSans-Light.woff2')}") format("woff2"),
                     url("{!URLFOR($Resource.StaticResourceName, '/assets/fonts/webfonts/SalesforceSans-Light.woff')}") format("woff");
                font-weight: 300;
            }
`

`
        @font-face{
            font-family: "Salesforce Sans";
            src: url("/assets/fonts/webfonts/SalesforceSans-Light.woff2") format("woff2"),
                 url("/assets/fonts/webfonts/SalesforceSans-Light.woff") format("woff");
            font-weight: 300;
        }
`

**Comment by kaelig** [comment]
Have you considered not loading fonts from the SLDS CSS? 

```scss
$slds-load-webfonts: false; // disable webfonts
@import 'node_modules/@salesforce-ux/design-system/scss/index';
```

Following this, you can load webfonts using your preferred way that fits your stack.

Let me know if this works for you!

**Comment by kaelig** [comment]
Closing this as it was fixed in a recent refactor of this part of the codebase.

**Comment by abraggveeva** [comment]
I just added the lightning design system to my project and ran into the same issue when using SASS:
The static fonts path is missing the 'assets' portion of the path. It should be ./../assets/fonts/webfonts/ but is instead ./../fonts/webfonts/

**Comment by abraggveeva** [comment]
After doing a find and replace for /assets/images with ../assets/images and changing the static font path to include assets, the sass builds. Otherwise none of those resources can be resolved.

**Comment by Krisa** [comment]
@abraggveeva - that's a 2 years old issue... I suggest you define these 2 variables in your own code, that's better than making a search and replace as it allows you to download newer version of the library without having to (think to) modify it.
