### ISSUE TITLE
slds-col--rule-* only applied at 64em and above

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#274]
Hi,

I'm assuming this is intentional but it's not mentioned in the docs and we actually want to show borders on mobile devices and tablets (i.e. only below 64em). Could someone explain the reasoning for this? Is there any solution I can use for smaller resolutions?

Thanks,
Matt

**Comment by kaelig** [comment]
Hi @mattgoldspink, great to see your feedback here again!

This looks like something @brandonferrua and @jina should be able to answer.
