### ISSUE TITLE
responsive layout mobile first oriented, menu options when resizing or when on mobile

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#277]
Hi, I think the responsive menu is needed, like material design or bootstrap design  as SIDEBAR MENU LEFT or RIGHT

allow us to close open menu 

and close it alone when resizing, please add a better menu and header template with many options mobile oriented because I fall in love to your design i come from bootstrap and material-design  which is very advanced and I can't start new project with these feature already included, very awesome but not complete 

and I use it upon ng-lighning 

thanks

**Comment by kaelig** [comment]
Hi @istiti, thank you for using the Lightning Design System and for your great feedback! I'll mark this as a feature request.

It'd be great if you could provide links to examples you've seen in other CSS frameworks that would illustrate what you mean.

**Comment by istiti** [comment]
Thanks,

So I think your design is very simple and clear but the only problem is:
There is no boilerplate or admin and dashboard example or empty webapp structure just starter template to geeting starter juste to show how it is responsive and show quick what it let us have if we choose your ux design:

You can check by example here http://getbootstrap.com/getting-started/

Go down jntil title Examples and you will see different section very very important
-  using the template
- navbars in actions
- custom components

I really think these getting started template have to be in your website to show fast and directly whatt your design is 

So when we have to choose some desing ux we can only copy your template dahsboard html and pla with really fast

Please keep in mind and thanks to consideration in my comments because I really don't know salesforce ux I just want to change from bootstrap and material

Thanks in advance

PS:menu in sidebar is must have and header fixed is mist jave and table jeader fixed is must jave too features
Others are:
Image diapo


Thanks


I think if you have something lile

**Comment by kaelig** [comment]
Thank you for your extended feedback, @istiti!

I can't tell you much about what we're going to release in the next few months, but watch this space!

**Comment by istiti** [comment]
ok thanks I will come back in a few weeks, 

I really want to change my design orientation for  furthur buisness projects, I have enough of material and bootstrap design, I want change ;-)


cheers

**Comment by kaelig** [comment]
Great! I'd like to mention that the Lightning Design System is aimed at developing and designing within the Salesforce ecosystem. With this in mind, it is slightly different from Bootstrap and MDL.

**Comment by istiti** [comment]
Thank you for reply, please apologize maybe I don't understand (see quote below) that isn't goal/target when the repo in pure css exist from Salesforce. I think with this professional design you can extend to large public easy because it is nice and clear design.

> ... The Lightning Design System **is a pure CSS framework that you can use with any front-end development framework you’d like**, including Salesforce-specific technologies such as Visualforce and Lightning, **as well as third-party frameworks like for instance React or Angular.**

So
I can't stop myself put new issue to ask a must-have feature https://github.com/salesforce-ux/design-system/issues/281

**Comment by kaelig** [comment]
Closing this as responsive navigation isn't on our radar.
