### ISSUE TITLE
components > data-tables >fixed header

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#278]
Hi, I suggest new and missing feature for the furthur: fixed header, scroll into the table and keep the header fix :) thanks

**Comment by kaelig** [comment]
Thank you for the suggestion, @istiti! We'll definitely consider adding it in the future.

**Comment by istiti** [comment]
what about magical [position:sticky;](http://caniuse.com/#feat=css-sticky) here works very well for me

**Comment by kaelig** [comment]
We definitely like `position:sticky`, however it doesn't work in IE/Edge at the moment.

**Comment by istiti** [comment]
no worry for edge, please people [upvote here](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263621-position-sticky) we are in 2017 and table header row couldn't be easy to get `position:fixed` ! what a mess !!! 

> position: sticky is now on the Microsoft Edge backlog with a priority of medium. Status updates can be tracked at [dev.modern.ie/platform/status/positionsticky](dev.modern.ie/platform/status/positionsticky)

cc @kaelig

**Comment by istiti** [comment]
Dear @engai what do you thing about Dataflex table. Nead actual datatable adding something with css flex feature like grid like that we can have position:sitcky on header (most user friendly)
