### ISSUE TITLE
toggle click to show better components working

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#279]
I wonder why the components page from official website https://www.lightningdesignsystem.com/components/menus/

why we can't click to toggle by example menu or other ... open modal and so...

 BTW we can play with famous components example

juste suggestion :)

**Comment by kaelig** [comment]
Thank you for your question, @istiti. The reason elements are not clickable is that the Lightning Design System does not provide JavaScript, leaving you with the choice of using the JavaScript library or framework of your choice.

See https://www.lightningdesignsystem.com/faq/#is-any-java-script-included-as-part-of-the-framework)

> ### Is any JavaScript included as part of the framework?
> No. The Lightning Design System is a pure CSS framework that you can use with any front-end development framework you’d like, including Salesforce-specific technologies such as Visualforce and Lightning, as well as third-party frameworks like for instance React or Angular.
