### ISSUE TITLE
Lightning Design UI Kit

### ISSUE THREAD

**Issue by DustyScarpitti** [salesforce-ux/design-system#28]
Starting to begin a tablet app that incorporates the new Lightning Design System that you guy's have created.  Was looking to see if I could get my hands on a UI kit (psd or sketch) for the design system so I can closely stick to this new UI that has been designed.  Thanks!

**Comment by cargonish** [comment]
This would be extremely helpful for those of us who are designers but not CSS experts. Not only would the UI components be nice to have, but it would be great if the kit included a legend for "styling guidelines" that are baked into the LDS framework. Thanks!

**Comment by cargonish** [comment]
Really pulling for Sketch fwiw :D

**Comment by amyleesalesforce** [comment]
I hear ya. :)

**Comment by topherauyeung** [comment]
#safeharbor We would also love this for our internal design team, so you are not alone. We're looking into it!

**Comment by cargonish** [comment]
Well, I work at LiquidHub, a platinum consulting partner, so if there is anything I can do to help drive this please let me know!

**Comment by DustyScarpitti** [comment]
It looks like you guys already created it from a shot I saw on Dribbble....http://drbl.in/plwS

**Comment by topherauyeung** [comment]
@cargonish Thanks so much!

@DustyScarpitti That's a UI kit that our Analytics Cloud team created manually in Sketch, and is not generated from the live components we have in the design system. We are looking into solutions that do not require us to manually maintain several sources of truth :+1:

**Comment by DustyScarpitti** [comment]
@topherauyeung Got it.  Let us know when you've come up with something.  Would love to start using this awesome design system you guys have come up with!

**Comment by cargonish** [comment]
@topherauyeung 

Great - please let me know if we can collaborate in any way! After all, thats what partners are for :)

**Comment by topherauyeung** [comment]
@cargonish Does anyone on your team have expertise in building a Sketch plugin? :)

**Comment by cargonish** [comment]
@topherauyeung to my knowledge, we haven't built one. I believe we have the capability, however. If you would like to discuss what you have in mind, let me know, and we can link up over email.

**Comment by topherauyeung** [comment]
@cargonish Mind e-mailing me at cauyeung@salesforce.com? Would love to discuss to see if your team is able to build this!

**Comment by BurningDog** [comment]
+1 for Sketch!

**Comment by robisio** [comment]
+1 for Sketch as well. :)

**Comment by aaurrichio** [comment]
Another vote for Sketch!

**Comment by ddura** [comment]
+1 vote for this as well.

**Comment by kkmatti** [comment]
+1 for a Sketch UI Kit.

**Comment by JasonBSiegel** [comment]
+1 for Sketch kit!

**Comment by ccpoole** [comment]
+1 for a sketch kit

**Comment by cockydays** [comment]
+1

**Comment by MarvinAmador7** [comment]
+1

**Comment by sudhirjena** [comment]
+1

**Comment by derrrick** [comment]
Samsies

**Comment by lukingtn** [comment]
+1 Either sketch or Adobe XD

**Comment by srohde** [comment]
Our new release contains a Sketch UI kit. Please find the download here: http://www.lightningdesignsystem.com/downloads/

GitHub: https://github.com/salesforce-ux/design-system-ui-kit

**Comment by matejp84** [comment]
Hi, 

is it possible to get ui kit file for adobe illustrator or even better experience design?
Lately I'm more and more working on prototyping for our customers and up to now I was using sketch. Do not get me wrong, sketch is a great program, but problem is, that only runs on mac and my coworkers who are not working on macs are having hard time working with me. 
As for adobe, we have bought full CC package from them and now having this experience design XD as well so is it possible to get it for adobe XD as well?

**Comment by kaelig** [comment]
Have you tried exporting to SVG from Sketch and working with XD from there?

**Comment by matejp84** [comment]
Yes that might work, but that is a lot of work to do :) And also every new version I would need to update adobe sketch file manually. You guys already know about all changes I would need to search what has changed every version.

**Comment by petrslobodzian** [comment]
Hi, I converted the kit for Adobe XD - https://github.com/petrslobodzian/salesforce-ux-design-system-ui-kit-adobe-xd
