### ISSUE TITLE
Error State Inconsistencies 

### ISSUE THREAD

**Issue by zdanowicz** [salesforce-ux/design-system#280]
Looking for some clarification on error states and icons. In many examples, the "warning" icon is being used in error alerts/toasts and also the "ban" icon. Should the "error" icon be used for error themes while the "warning" icon is used for warning themes? Also, should the Error With Details toast have the info theme applied instead of the error theme? Some screenshots attached. Thanks! 
![error](https://cloud.githubusercontent.com/assets/5330702/17059280/6a3d8daa-4ff2-11e6-82d8-10836363c0b6.png)
![warning](https://cloud.githubusercontent.com/assets/5330702/17059278/6a3bb5ac-4ff2-11e6-9908-c75467f171e5.png)
![error w details](https://cloud.githubusercontent.com/assets/5330702/17059279/6a3d0236-4ff2-11e6-9ae4-b6dd89458bcd.png)
![error icons](https://cloud.githubusercontent.com/assets/5330702/17059281/6a42ed72-4ff2-11e6-92b1-fd30a3924207.png)

**Comment by kaelig** [comment]
Thank you for bringing this up, @zdanowicz. This type of constructive feedback is very much appreciated.

We are constantly improving our guidelines and will take your feedback into account when we update this page: https://www.lightningdesignsystem.com/guidelines/messaging/

In the mean time I'll ping our designers to see if they can help you with that.

**Comment by engai** [comment]
@zdanowicz We've been working on aligning our error messaging throughout our components and our work should be available in the next release. We'll keep you updated for when that becomes available.

**Comment by JohnHeadIV** [comment]
@engai I think some of this comes from LEX not always being 100% consistent with SLDS.

**Comment by engai** [comment]
@JohnHeadIV We've made a few clarifications on our end, which will hopefully in turn, lead to better alignment on messaging in LEX.

**Comment by engai** [comment]
@zdanowicz we've adjusted our error and warning states to use the correct icons . https://github.com/salesforce-ux/design-system/commit/cd98ab6

For more info on this see our [Release Notes](https://www.lightningdesignsystem.com/release-notes/)
