### ISSUE TITLE
layout component

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#281]
hi,

When I compare LDS with MDL, a must-have feature miss call LAYOUT: example here: https://getmdl.io/components/index.html#layout-section

and of course this too https://getmdl.io/templates/index.html

**Comment by kaelig** [comment]
Thank you for the feature request, @istiti!

**Comment by istiti** [comment]
Any update here? Any ETA?

This will show to new developer directly with what basic template we can start ! I think this is very important to avoid us to create head of new project ! 

Component are awesome just make a bundle "layout" downloadable ! 

Because this issue is 4month old and no news ! In 1month willl start new big project hope choose this design

Congrats and thanks to this work

**Comment by kaelig** [comment]
@istiti no ETA at the moment, but we have built a few examples in the Design System Starter Kit, hope this helps!

https://github.com/salesforce-ux/design-system-starter-kit

e.g. https://starter-kit-demo.herokuapp.com/example.html

**Comment by istiti** [comment]
@kaelig  I'm glad to hear there is a Starter Kit now !!! Very cool and very interessting BUT yesterday I tried with my iphone 6 and was a little bit dissapointed of what this demo is displaying, all are truncated see my screenshot : 
![img_6040](https://cloud.githubusercontent.com/assets/2789203/20743877/f3ad8e94-b6d8-11e6-935e-1bbdac7bfbe7.PNG)

**Comment by kaelig** [comment]
Glad you could have a look! The content and layout aren't optimized for mobile for now as the design system isn't fully responsive but that might be a future addition.

**Comment by istiti** [comment]
thanks you for fast response! very appreciate! 
still : awesome design for webapp and awesome starter kit :) 

and hope  full reponsive ui will come asap

**Comment by kaelig** [comment]
Fully responsive UI isn't on the roadmap but this might change one day!
