### ISSUE TITLE
SVG Icons Do Not Work Cross-Domain

### ISSUE THREAD

**Issue by jamesward** [salesforce-ux/design-system#283]
Static assets should be served from a CDN (cross-domain).  Unfortunately the SVG `<use xlink:href="">` thing does not work cross-domain, even when the host provides CORS headers.  I think this is a pretty good reason to not use SVG for icons.

**Comment by kaelig** [comment]
Thanks for mentioning that to us, @jamesward. Is that a discussion you could take on Chatter? Cheers!
