### ISSUE TITLE
slds-text-link--reset doesn't work for <a> elements

### ISSUE THREAD

**Issue by tfuda** [salesforce-ux/design-system#284]
The following does not appear to have the desired result of making the link appear as normal text:
`<a href="#" class="slds-text-link--reset">Click Me</a>`
 The link is still underlined, as seen here: http://screencast.com/t/L7aqCDNdqUC

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System, @tfuda!

And many thanks for reporting this. I'd like to help!

Allow me to clarify that this class is available as of SLDS > v2.0.1. Lightning's app.css bundles SLDS v2.0.0, which is a few small features behind. Apologies for the inconvenience. We admit it isn't clear on the SLDS website, and we'll document this type of details in future versions.

@brandonferrua @stefsullrew is there a workaround that we could suggest to @tfuda to benefit from v2.0.x class names in Lightning?

**Comment by tfuda** [comment]
Thank you for the clarification. If there is a simple workaround that would be great, but I can live without this until 2.0.1 becomes GA. 

I agree with the idea of annotating the class names in the documentation with the SLDS version in which they were introduced. That would be helpful.

**Comment by tfuda** [comment]
Yesterday, I downloaded the SLDS 2.0.2 bundle available here: https://www.lightningdesignsystem.com/downloads/ (it looks like 2.0.3 has been posted between yesterday and today). I see the same behavior with version 2.0.2 (the link is still underlined). Here are the definitions for the slds-text-link-reset classes from the 2.0.2 bundle:
`
.slds-text-link--reset {
    cursor: pointer;
    line-height: inherit
}

.slds-text-link--reset:active {
    outline: 0
}

.slds-text-link--reset,.slds-text-link--reset:active,.slds-text-link--reset:focus,.slds-text-link--reset:hover {
    color: inherit;
    text-decoration: inherit
}
`

I guess I would have expected to see "text-decoration: none" here somewhere.

**Comment by tfuda** [comment]
Same thing in version 2.0.3.

**Comment by kaelig** [comment]
Thanks, did you witness this behaviour in Visualforce, Lightning, or another environment?

Note that 2.0.x will not become "GA": at the moment Design System keeps evolving outside of the platform, which itself will keep using the 2.0.0 of SLDS until Winter ’17.

**Comment by tfuda** [comment]
I downloaded the 2.0.3 Design System Zip file from the the Lightning Design System website. I then uploaded this as a new static resource in one of my Salesforce orgs. Then I created a Visualforce page, turning off standard stylesheets, sidebar and header, and loaded my SLDS static resource and used SLDS classes to style standard HTML elements rendered by my VF page.

**Comment by kaelig** [comment]
Thank you, this will greatly help us finding a solution!

**Comment by kaelig** [comment]
@tfuda we've just released version 2.1.2, which will be GA very soon and is already available on developer orgs. I'll close this ticket, feel free to reopen if this issue comes back up!
