### ISSUE TITLE
Checkbox Toggle text isn't display correctly in IE11

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#285]
In IE11, using the [Checkbox Toggle](https://www.lightningdesignsystem.com/components/forms/#flavor-checkbox-toggle) component doesn't work correctly. The text inside the checkbox isn't vertically centered:

![ie](https://cloud.githubusercontent.com/assets/2465122/17294696/93c77574-57f8-11e6-950a-295d00f16783.png)

**Comment by kaelig** [comment]
Merci you for reporting this, Fabien. We'll be looking into it!

**Comment by stefsullrew** [comment]
Seems like this is an old bug which no longer reproduces. This is what I see:

![image](https://cloud.githubusercontent.com/assets/676213/21071727/aaaae0f6-be5e-11e6-896b-5f60117cecc1.png)
