### ISSUE TITLE
Checkbox Toggle text options

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#286]
As an enhancement to Checkbox Toggle, it would be good to have some other options (other the ability to put any text) instead of On/Off. A good example would be True/False instead of On/Off. This can be done with setting custom width for the new text, but some other standard Boolean values might want to be included.

**Comment by kaelig** [comment]
Thank you for this request, @JohnHeadIV! We'll evaluate it in the future.

**Comment by kaelig** [comment]
As per [this example](https://www.lightningdesignsystem.com/components/forms/#flavor-checkbox-toggle), you can now customize the text of Checkbox Toggle components.

Thanks again for your feature request!

**Comment by JohnHeadIV** [comment]
Sorry, should have closed this in September. Thanks follow-through.
