### ISSUE TITLE
Why is there an internal repo?

### ISSUE THREAD

**Issue by wwwdata** [salesforce-ux/design-system#287]
Hi,

I thought that the Lightning Design System, this repo, is an open source project. Today, I read the changelogs on the official homepage, and a link to an internal repo was in there: https://github.com/salesforce-ux/design-system-internal/commit/de2dc7f6bd5aff31998fb43254d438ec9cec8dc3

So it seems that this repo is just a mirror/different-version and the development is internally? Why are you doing this approach? This is a lot of overhead and leads to these mistakes witch the changelog, for example.

**Comment by srohde** [comment]
We are developing on three releases in parallel.
The open source GitHub repository reflects what has shipped in our latest Salesforce release. Today this is our Summer ’16 release.

However, we are already working on our Winter ’17 and even Spring ’17 release. Those releases will go open source when the corresponding Salesforce release is generally available.

**Comment by wwwdata** [comment]
But that could also be done in a branch in this public repo. So your process would be completely transparent and you also get feedback from Users before a new release comes out. I think both, users, and salesforce would benefit from that approach.

**Comment by FabienTaillon** [comment]
I would love that !
Well I guess the branch should be named "SafeHarbor" though ;-)

**Comment by srohde** [comment]
We can't reveal what is potentially shipping in future releases.
We really try to be as transparent as possible.

**Comment by kaelig** [comment]
Thank you all for the feedback and @wwwdata for pointing this out!

Transparency is at the core of our process, and we'll be making efforts to get as much open-sourced as we possibly/securely can, as @srohde said.

I've updated the release notes to reference the public repository instead of the internal one. Have a great day and please do report anything you see in the future, it is very helpful.
