### ISSUE TITLE
Sales Path Coach bug in Safari 9.11

### ISSUE THREAD

**Issue by marioluissc** [salesforce-ux/design-system#288]
The Sales Path Coach is not showing correctly in Safari 9.11.
<img width="1235" alt="path" src="https://cloud.githubusercontent.com/assets/1075374/17454104/81a3bbe4-5bce-11e6-9d95-2f2702795ee0.png">

The css is missing the "webkit" prefix.

I havd to add this to my page in order to fix:
.slds-tabs--path__title,
.slds-tabs--path__stage {
      -webkit-backface-visibility: hidden !important;
 }

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and reporting this bug, @marioluissc.

Marking this as a duplicate so we can continue the discussion in #291.
