### ISSUE TITLE
Enhancement: add bower.json and register "slds" bower package

### ISSUE THREAD

**Issue by richardvanhook** [salesforce-ux/design-system#29]
Should be fairly easy per these instructions: http://bower.io/docs/creating-packages/#register

Doing this would make it easier to import the design-system into stand alone web apps.  SF Foundation did this with bootstrap-sf1 as seen here: https://github.com/SalesforceFoundation/bootstrap-sf1/blob/master/bower.json and http://bower.io/search/?q=bootstrap-sf1

If it were up to me, I'd name it something short like slds, but that might be so short as to not be descriptive enough.

**Comment by aputinski** [comment]
Yeah, this sounds great! I'll get this up in the next few days.

**Comment by aputinski** [comment]
you can now officially `bower install salesforce-lightning-design-system`

**Comment by andriytyurnikov** [comment]
wow, this is so good :+1: 
separation of npm/bower repositories is a little bit unusual though, hope you guys have some magic to keep those in sync
