### ISSUE TITLE
Spinner not in the foreground in Firefox

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#290]
When using spinner on Firefox, the spinner element isn't always in front of other components:

![spinner](https://cloud.githubusercontent.com/assets/2465122/17479685/30a5fc6e-5d74-11e6-9fc7-ac3ab4fd7886.png)

This is because the z-index property isn't calculated properly on Firefox:

![spinner2](https://cloud.githubusercontent.com/assets/2465122/17479695/40078f4c-5d74-11e6-8036-6c4c79a46bc1.png)

Here is the code I used, with a custom-scoped CSS in v.2.0.3:

```html
<div class="slds-spinner_container">
    <div class="slds-spinner--brand slds-spinner slds-spinner--large" aria-hidden="false" role="alert">
        <div class="slds-spinner__dot-a"></div>
        <div class="slds-spinner__dot-b"></div>
    </div>
</div>

<div class="slds-form-element">
    <label class="slds-form-element__label" for="text-input-01">Input Label</label>
    <div class="slds-form-element__control">
        <input id="text-input-01" class="slds-input" type="text" placeholder="Placeholder Text" />
    </div>
</div>
```

I was able to make it work by either overriding the z-index property, or put the spinner markup at the bottom of the page.

**Comment by kaelig** [comment]
Bonjour @FabienTaillon, merci encore for the quality of your bug reports (and for mentioning workarounds).

We will fix this syntax bug shortly.

**Comment by stephenscholtz** [comment]
A little extra info for what it's worth: Firefox doesn't seem to support CSS calc() when defining a z-index. Might be a FF bug?  You're supposed to be able to be able to use it [where ever you find integers](https://developer.mozilla.org/en/docs/Web/CSS/calc) and z-index takes either "auto" or [integer as a value](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index).

**Comment by fspoettel** [comment]
FYI this is still happening in latest SLDS. Screenshot for reference attached.

![screenshot 2017-07-19 11 07 47](https://user-images.githubusercontent.com/1682504/28357005-40b40fd2-6c6a-11e7-97b4-ef9253f2d979.png)
