### ISSUE TITLE
Process Component has issues in Safari

### ISSUE THREAD

**Issue by nelsonra** [salesforce-ux/design-system#291]
Hi,

We are using this component : http://www.lightningdesignsystem.com/components/process/

We are seeing some strange behaviour in Safari where the tick / check icon doesn't disappear and we see the inverted text as well. See screenshot:

<img width="471" alt="screen shot 2016-08-08 at 17 32 00" src="https://cloud.githubusercontent.com/assets/7580950/17487966/19b6282e-5d8f-11e6-8a39-3d891bdab3bd.png">

I notice if I changed the following style:

```
.slds .slds-tabs--path__title, 
.slds .slds-tabs--path__stage {
display: block;
transition: transform 0.2s linear;
backface-visibility: hidden;
}

```

Change it to include (-webkit-backface-visibility)

```
.slds .slds-tabs--path__title, 
.slds .slds-tabs--path__stage {
display: block;
transition: transform 0.2s linear;
backface-visibility: hidden;
-webkit-backface-visibility: hidden; /* include this */
}
```

It fixes the issue for us. Could you please let me know if you could include that change in the next version please?

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this! This is something that was fixed in SLDS v2.0.3 by @ishakasliwal in https://github.com/salesforce-ux/design-system/commit/1ab77d655c9a61f1be1243bd17dbce0902c76943.

Which version of the Lightning Design System are you using at the moment? Have you tried upgrading to v2.0.3?

**Comment by nelsonra** [comment]
I believe we're on Lightning Design System 1.0.5. I'll try upgrading tomorrow and see if that fixes the issue. I inspected the example code in Safari and it also seems fixed in your example. Many thanks for the quick response.

**Comment by nelsonra** [comment]
Hi, thanks the upgrade fixed the issue. I didn't realise our version was so far behind.

**Comment by kaelig** [comment]
That's fantastic, great to hear.
