### ISSUE TITLE
slds-textarea adds a extra marging bottom on chrome and firefox

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#294]
On chrome and firefox the textarea adds a inconsistent bottom margin that other form fields don't have making the UI look inconsistent.

The image below shows that issue:
![screen shot 2016-08-10 at 12 41 46 pm](https://cloud.githubusercontent.com/assets/67904/17568185/8ded717a-5ef7-11e6-85c1-56735e28ef68.png)

Ideally all form elements should have the same spacing like on the example below:
![screen shot 2016-08-10 at 12 43 33 pm](https://cloud.githubusercontent.com/assets/67904/17568238/c68e4d4c-5ef7-11e6-8e06-7325f946ac83.png)

this fix was done by adding `display: block;` to `.slds-textarea` there is also a stackoverflow link about this problem http://stackoverflow.com/questions/3453959/how-do-i-fix-inconsistent-textarea-bottom-margin-in-firefox-and-chrome

**Comment by kaelig** [comment]
Thank you for the bug report, @3den! We'll investigate very soon.
