### ISSUE TITLE
[UX Issue] spacing between slds-form-element elements is too small

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#295]
Currently on `slds-form--stacked` and every other variation of the form classes, there is not enough marging between form elements. The spacing is so small that that the distance between a label and its input is exactly the same as the distance between it an the previous input, making the UI feel very suffocating when you have forms with many elements.

The image below shows the issue:
![screen shot 2016-08-10 at 12 24 57 pm](https://cloud.githubusercontent.com/assets/67904/17568869/7de5403e-5efa-11e6-9827-1a2b0c363651.png)

Bootstrap solves this problem by having a bigger margin separating each form element. Also in the small screen we currently add sightly bigger margin. I think we should increase the margin top of `slds-form--stacked` and the other forms or create a `slds-form--spaced` class with the correct spacing between elements. Like the on on the image below.

![screen shot 2016-08-10 at 1 14 32 pm](https://cloud.githubusercontent.com/assets/67904/17569216/19666244-5efc-11e6-915f-f8115c227579.png)

If we just remove the media query that gives a smaller margin o bigger screens (`@media (min-width: 30em) .slds-form--stacked .slds-form-element+.slds-form-element`) it would be nice too.

**Comment by kaelig** [comment]
Thank you for that! We'll forward this suggestion to our designers.

**Comment by 3den** [comment]
On the example above i used a margin top of `1rem`

**Comment by kaelig** [comment]
Closing this as spacing in forms might not change in the future. We aim at maximizing content density which is why we have kept it tight until now.
