### ISSUE TITLE
Need code snippet for Toasts to use parameters duration and dismissible.

### ISSUE THREAD

**Issue by vijayaknu** [salesforce-ux/design-system#296]
Toasts accept two parameters: duration and dismissible.
Could you please share an example to use the above parameters using salesforce lightning design system ?

**Comment by kaelig** [comment]
Thank you for using the design system and for your question, @vijayaknu.

@stefsullrew is this something you could help @vijayaknu with? Do we need to update the documentation?

**Comment by rmillsdev** [comment]
I can't seem to get the duration parameter to work.
`var resultsToast = $A.get("e.force:showToast");
	resultsToast.setParams({
		type: 'success',
		duration: 1000,
		message: 'SAVED'
	});
resultsToast.fire();`
This still shows the toast for the default 5 seconds. An example might help

**Comment by oobarbazanoo** [comment]
The issue is still there. It is impossible to show the toast just for one second.
