### ISSUE TITLE
Spinners do not allow for label text

### ISSUE THREAD

**Issue by kyleheddon** [salesforce-ux/design-system#298]
Though the [guidelines allow for adding some text in order to label your spinner](https://www.lightningdesignsystem.com/guidelines/loading/), such as "Loading...", the css does not:

<img width="273" alt="screen shot 2016-08-19 at 10 41 39 am" src="https://cloud.githubusercontent.com/assets/1839152/17813524/ae0fe01a-65f9-11e6-931e-a05cb7dbc136.png">

There does not seem to be any consideration for text with spinners in the source code for spinners 😢 .

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this, @kyleheddon!

That's a good catch, I will pass this on to the team as a feature-request. Watch this space!

**Comment by stefsullrew** [comment]
You're correct, @kyleheddon — the component was built before the guidelines (I believe) and though internally I haven't seen examples with text, I can understand that it could be useful. We will create a ticket to update the component to match the guidelines. Cheers!

**Comment by ajith007** [comment]
I've noticed the same issue. Below is the workaround I'm using for now, but would prefer to set the text within the spinner control itself and would be nice if we could specify where the loading text should appear(top, left, right or bottom). 

```
<div class="slds-container">
       <div class="slds-container--fluid">
            <div class="slds-grid slds-grid--align-center">
			<div style="height:80px;width:80px;">
			      	<img src="/resource/slds_bundle/assets/images/spinners/slds_spinner_brand.gif" alt="" />
			</div>
	    </div>
	</div>

        <div class="slds-container--fluid slds-m-top--large">
            <div class="slds-grid slds-grid--align-center slds-text-heading--small">
               	Creating Case, please wait ...
	    </div>
	</div>
</div>
```

**Comment by JohnHeadIV** [comment]
Any word on this?

**Comment by Sreethak** [comment]
I want to display spinner along with message , is <lightning:spinner /> will  give that option?
I am not able to do that using <lightning:spinner alternativeText="Loading" />
