### ISSUE TITLE
Downloadable Layouts

### ISSUE THREAD

**Issue by lukeed** [salesforce-ux/design-system#3]
Everything in the styleguide has downloadable counterparts, except the layouts.
I imagine it would be nice to have these available (including responsive versions) as well.

**Comment by srohde** [comment]
Thanks for the feedback. We are looking into it.

**Comment by emir** [comment]
+1

**Comment by caiotarifa** [comment]
:+1:

**Comment by cdcarter** [comment]
+1

**Comment by istiti** [comment]
+1

**Comment by ronnyek** [comment]
does looking into it mean working on it, or does it mean "thinking about it"?

**Comment by kaelig** [comment]
ping @srohde ^

**Comment by silentmouth** [comment]
+1

**Comment by zokito** [comment]
+1
