### ISSUE TITLE
Trying to do active navigation.

### ISSUE THREAD

**Issue by Bergvin** [salesforce-ux/design-system#300]
I am trying to do something simular to this https://www.lightningdesignsystem.com/components/navigation/.
But all my `<li>` are active since i am loading in the content, how can i do this so only the contect clikced on is active ?. 

This is what i have so far.

    <ul class="slds-navigation-list--vertical slds-has-block-links--space">
        <li class="slds-is-active">
            <a class="slds-navigation-list--vertical__action slds-text-link--reset" aria-describedby="entity-header" href="javascript:void(0);" onclick="{!c.handleSidebarFolderListEvent}">
               <ui:outputText value="{!v.folder.Name}"/>
            </a>
        </li>
    </ul>

And it looks like this 

![list](https://cloud.githubusercontent.com/assets/2762162/17898591/e1cda67a-6947-11e6-8532-973940c27610.PNG)

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System, @Bergvin!

As this question is related to the templating side of Lightning, allow me to close this issue and redirect you to the developer forums: https://developer.salesforce.com/forums

**Comment by stefsullrew** [comment]
@Bergvin - the `is-active` class should *only* be placed on when someone clicks and loads that section. That's what indicates it's active. It should not be placed on all of them at page load. HTH
