### ISSUE TITLE
SVG Icon not rendering in IE11 from Lightning component in SF Classic view

### ISSUE THREAD

**Issue by TronJavolta007** [salesforce-ux/design-system#301]
I am trying to use the svg4Everybody js file, from trailhead link to github [here](https://github.com/jonathantneal/svg4everybody),  but it doesn't seem to be working properly. I am looking at both MS Edge, Chrome, and IE11. The issue is only apparent in IE11. This app was built with lightning components but our users will continue to use Salesforce Classic as they are not fond of change.

I searched for answers elsewhere and found that adding this bit of code to the controller where I'm loading the script worked for others but is not working for me.

```
({
	loadScripts : function(cmp, evt, hlp) {
		// add meta-http-equiv to the <head>
		$('head').append('<meta http-equiv="x-ua-compatible" content="ie=edge">');
		// start the svg4everybody helper
		$('body').append('<script>svg4everybody();</script>');
	}
})
```

With my component looking like this:
```
<aura:component implements="force:appHostable">
    <ltng:require scripts="{!join(',',$Resource.JQuery224,
                                      $Resource.JQueryUI1pt11pt4 + '/jquery-ui-1.11.4/jquery-ui.min.js',
                                      $Resource.svg4Everybody)}"
                  styles="{!$Resource.JQueryUIcss}" 
                  afterScriptsLoaded="{!c.loadScripts}"/>

<html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<head title="headTitle">

</head>
<body>
    <!-- REQUIRED SLDS WRAPPER -->
    <div class="slds slds-theme--alert-texture">
        <!-- PRIMARY CONTENT WRAPPER -->
        <c:AthenaBody />
        <!-- / PRIMARY CONTENT WRAPPER -->
    </div>
    <!-- / REQUIRED SLDS WRAPPER -->
</body>
</html>
</aura:component>

```

I have confirmed the library is getting loaded. Any help is appreciated!

**Comment by kaelig** [comment]
Thank you for your detailed report, @TronJavolta007.

I'm curious why you load svg4everybody by injecting a script tag? Why not execute the function directly?

**Comment by kaelig** [comment]
Also, as this is more directly related to Aura itself, I'd like to redirect you to the [Salesforce Developer Forums](https://developer.salesforce.com/forums). I am confident that you'll get quality help over there. I hope that it's okay with you!

**Comment by TronJavolta007** [comment]
Thank you for your reply kaelig! I have spoken to Salesforce support and it turns out the issue is not with Salesforce but with IE11. Hence they are removing IE from their supported browsers. A complete breakdown can be found here for those interested:

https://help.salesforce.com/apex/HTViewSolution?urlname=Retirement-of-Support-for-Microsoft-Internet-Explorer-version-11-with-Lightning-Experience

**Comment by jpmonette** [comment]
It seems like Salesforce has extended IE11 support, so still an issue.

@TronJavolta007 Have you found a workaround?
