### ISSUE TITLE
add milestones

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#303]
Hi,
I asked some feature I think "must have nowadays" to approach better material design lite or bootstrap or so... here https://github.com/salesforce-ux/design-system/issues/281 and here https://github.com/salesforce-ux/design-system/issues/277

That's because we can't choose actually this poor but beautifull design-system ui in our next big project.

Therefore, here I just want to ask if it's possible to add "milestones" just to know what and when do you implement something new.... what is your short list for the furthur developement.

thanks in advance if Milestone's section born asap.

**Comment by kaelig** [comment]
Thank you for the suggestion, we are currently looking at how to better communicate our roadmap internally and externally. Watch this space!

**Comment by istiti** [comment]
Please do something robust. Exceptations are high when we know HOW others projects communicate example: https://github.com/Microsoft/vscode/issues/10145

good job
