### ISSUE TITLE
Use of svg icons without static resource

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#305]
In [SLDS doc](http://lightningdesignsystem.com/platforms/lightning/), it's now mentioned that "It is no longer necessary to add a static resource for Lightning Components running within these environments".

However, the related [Trailhead module](https://trailhead.salesforce.com/project/slds-lightning-components-workshop/slds-lc-4) still make use of a static resource for svg.

I couldn't find the right url for svg on the platform, so I don't know if they are available or if I should use the static resource for svg icons.
I tried to look at LEX icons but they are still png.

**Comment by kaelig** [comment]
Thanks for raising this, it's a good point!

Starting in Winter ’17, you'll be able to use a dedicated lightning component for icons (you should already be able to do so in your developer preview instance).

In the mean time… @stefsullrew is this something we've encountered before?

**Comment by FabienTaillon** [comment]
Do you know the name of the component ? I can't find anything new in auradocs, but I've heard that some new components are supposed to be added soon (crossing fingers) to the pre-release orgs, so maybe this one will be part of it.

**Comment by kaelig** [comment]
The component is called `<lightning:icon>`.

Usage:

```xml
    <lightning:icon iconName="action:approval" size="large" />
    <lightning:icon iconName="doctype:audio"   size="large" />
    <lightning:icon iconName="standard:event"  size="large" />
    <lightning:icon iconName="utility:connected_apps" size="large" />
    <lightning:icon iconName="utility:warning" size="large" variant="warning"/>
    <lightning:icon iconName="utility:error" size="large" variant="error"/>
```

Hope it helps!

**Comment by FabienTaillon** [comment]
Thanks Kaelig. The components under the lightning namespace are still not released in the pre-release orgs, hope it will be there soon ! :)

**Comment by kaelig** [comment]
There is a patch coming up very soon, I'm pretty confident it will include it!

**Comment by stefsullrew** [comment]
@FabienTaillon - forget everything @kaelig said for now. ;)  I wrote a really poor paragraph that led you astray.

"The **Lightning Design System CSS** is now automatically included for Lightning Components running in the Lightning Experience and Salesforce S1 mobile application (via app.css). It is no longer necessary to add a static resource for Lightning Components running within these environments."

That paragraph is specifically referring to the CSS, not things like icons and fonts. I'll try to make it more clear. Thanks for the heads up.

**Comment by FabienTaillon** [comment]
@stefsullrew That's true it's clearly written CSS, sorry about that. I'll use the static resource until the secret components are released :)
Thanks :)

**Comment by FabienTaillon** [comment]
lightning:icon component is now available in Winter '17 pre-release orgs :)
https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_icon.htm?search_text=lightning:badge

**Comment by stefsullrew** [comment]
Boom! There ya go!
