### ISSUE TITLE
Nervous resizing in chrome

### ISSUE THREAD

**Issue by rvlieshout** [salesforce-ux/design-system#307]
I was using Chrome version 53.0.2785.89

Go to

https://www.lightningdesignsystem.com/components/utilities/sizing/

Select MEDIUM or SMALL. The screen will keep flickering as it keeps resizing.

**Comment by kaelig** [comment]
I've noticed the same thing happening, thank you for confirming it wasn't just me!

We're on it…

**Comment by stefsullrew** [comment]
Oddly, I'm using Chrome  52.0.2743.116 ... so they must have just introduced something (if I restart, it will upgrade, but SO many tabs... lol). I'll test the new one shortly.

**Comment by kaelig** [comment]
Looks like this is gone in recent versions of Chrome. Closing this.
