### ISSUE TITLE
Right-to-Left(RTL) Language Support

### ISSUE THREAD

**Issue by jaan** [salesforce-ux/design-system#308]
Hello SLDS Team,
First of all, big thanks for the great work on SLDS. Finally, I'm sure enterprise user experience got sexy with SLDS. 

We have built most of our apps on SLDS and there is a need to support the Right-to-Left(RTL) language in a project. Have you considered supporting RTL in the near future?
Any plans or updates would be much appreciated.

Thanks,
Janardhan

**Comment by srohde** [comment]
Thanks for the great feedback. Where do you see bugs with RTL?

**Comment by mattgoldspink** [comment]
Hi @srohde - there's a few cases we see

- For example Button groups:
![image](https://cloud.githubusercontent.com/assets/415690/18378097/22cbcbf4-766b-11e6-8d7d-ac918064eb05.png)

- the th cell used for the first cell in each row
![image](https://cloud.githubusercontent.com/assets/415690/18378135/66d3d274-766b-11e6-8708-c377f8616ae8.png)

- tree's don't have correct indentation
![image](https://cloud.githubusercontent.com/assets/415690/18378168/a310aac8-766b-11e6-8352-89c05b22d35c.png)

- Modal footer buttons (I'm not 100% sure if these should be pushed to the left, the buttons are at least flipped, but still floated to the right)
![image](https://cloud.githubusercontent.com/assets/415690/18378201/e958e0f4-766b-11e6-8c9f-1090f02378d0.png)

To be honest a lot of things do seem to work out of the box which is great, but these are things I could see after a quick test of some of our core screens.

Matt

**Comment by mattgoldspink** [comment]
@stefsullrew @srohde - I've cut our own branch to start work on this as it's a high priority for one of our clients. I'd like to contribute back whatever we produce but I want to make sure I start off in a way that is likely to be easily acceptable for you.

From past experiences there's usually 2 approaches:

1 - add override rules to the existing CSS files that target [dir=rtl] on the html element in the same file.
2 - generate separate .rtl.css files that contain specific rtl rules.

I personally prefer the latter approach to keep the css more concise and also makes it easy to use variables to easily switch as shown here - http://matanich.com/2013/09/06/rtl-css-with-sass

Can you please let me know what would be the best approach for you guys and I'll contribute our work back following that.

Thanks,
Matt

**Comment by mattgoldspink** [comment]
I went ahead with creating a PR for this - Let me know what next steps are needed.

Thanks,
Matt

**Comment by mattgoldspink** [comment]
I’d like to keep this open please. We still add rtl support to every release on our fork. This is a blocker for a number of clients in Israel for example being able to move to Lightning. I’m happy to share our version of the code or work with the team to add rtl support in a different way. We have real clients who need this.

**Comment by mattgoldspink** [comment]
We'd like to keep this open.

**Comment by Dottenpixel** [comment]
Thanks @jann! Closing this as RTL has now been supported in the Lightning Design System for several releases. Look for `@include rtl()` entries in the Sass files to see what components and selectors are supported.
