### ISSUE TITLE
first and last icons 

### ISSUE THREAD

**Issue by RatanPaul** [salesforce-ux/design-system#309]
hey guys, is there any first and last icons? 

![alt tag](http://i.imgur.com/O3DzIXql.png)

**Comment by kaelig** [comment]
@RatanPaul thank you for using the design system, and for asking! I'll pass this on to the designers and let you know of any useful feedback from them.

**Comment by kaelig** [comment]
Since the example shows a pagination pattern, and SLDS discourages this pattern, so I'll close the feature-request as there is little chance we'll introduce this use case.

**Comment by JohnHeadIV** [comment]
Do you think these could be added back to the road-map as their use case also applies to media (aka audio/video)? A full set of media control icons would be nice but "1st"/"Last" plus what already exist would suffice.

**Comment by kaelig** [comment]
Good point, thanks for bringing that up!

I'll make sure to mention this to the team and I've looked around if that was something that was on our radar but unfortunately I can't make a commitment for now.

An alternative (less pretty but useful) would be to use:

- ⇤⇥
- ⏮ ⏭

…or another icon library of your choice.

**Comment by JohnHeadIV** [comment]
@RatanPaul Another more consistent workaround might be a 90deg rotate of the jump_to_bottom and jump_to_top icons. Should be able to do the rotate purely in CSS so no need for additional icons. Not prefect but should work out of the box.

**Comment by kaelig** [comment]
@RatanPaul clever workaround, thanks for sharing!
