### ISSUE TITLE
Visualforce slds-is-required not working

### ISSUE THREAD

**Issue by tpaxton** [salesforce-ux/design-system#31]
I'm noticing an issue where slds-is-required isn't working with Visualforce pages. I believe this has to do with .slds being specified after the >. For example:

    .slds-is-required > .slds .slds-radio

...should be...

    .slds-is-required > .slds-radio

**Comment by stefsullrew** [comment]
Is this in the salesforce-lightning-design-system-vf.css file? Have you scoped your component?

But meanwhile, yes. You're right that either both should have the scoped `.slds` class or neither should. Please verify the file and I'll have a look. Cheers!

**Comment by tpaxton** [comment]
I'm using salesforce-lightning-design-system-vf.css correct. Here's a condensed copy of the page I'm constructing:

    <apex:page standardController="Contact" extensions="DemoSchedulerExtension" docType="html-5.0" sidebar="false">
        <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <apex:stylesheet value="{!URLFOR($Resource.SLDS090, 'assets/styles/salesforce-lightning-design-system-vf.css')}" />
            <apex:form styleClass="slds">
                <div role="form" class="slds-form--stacked slds-grid slds-wrap slds-m-around--small">
                    <div class="slds-col--padded slds-size--1-of-1 slds-medium-size--1-of-2">
                        <div class="slds-form-element slds-is-required">
                            <label class="slds-form-element__label" for="{!$Component.numberOfEmployees}">Employees</label>
                            <div class="slds-form-element__control">
                                <apex:inputField styleClass="slds-input" id="numberOfEmployees" html-placeholder="Employees" value="{!contact.Account.NumberOfEmployees}" />
                            </div>
                        </div>
                    </div>
                    <div class="slds-col--padded slds-size--1-of-1 slds-medium-size--1-of-2">
                        <div class="slds-form-element slds-is-required">
                            <label class="slds-form-element__label" for="{!$Component.state}">State</label>
                            <div class="slds-form-element__control">
                                <apex:selectList size="1" id="state" value="{!contact.Account.BillingState}" styleClass="slds-select">
                                    <apex:selectOptions value="{!states}"></apex:selectOptions>
                                </apex:selectList>
                            </div>
                        </div>
                    </div>
                </div>                
            </apex:form>
        </html>
    </apex:page>

**Comment by stefsullrew** [comment]
Yep. Thanks for logging this. It's a bug. It should actually be `.slds .slds-is-required > .slds .slds-radio` -- we'll get it fixed straight away!

**Comment by mspeder** [comment]
Apparently scoped/ltng/vf slds-has-error suffers from the same problem
CSS has .slds-has-error .slds xxxxxx instead of .slds .slds-has-error xxxxxx

**Comment by brandonferrua** [comment]
@mspeder you are correct. I've determined whats causing the issue. We will work to get this into next build.

**Comment by amyleesalesforce** [comment]
@matejp84 has a related issue

**Comment by matejp84** [comment]
I also have issue with lookups, but this is probably not implemented yet as it is marked as prototype. 
Problem is that whatever I do I cannot hide dropdown menu and `aria-expanded="true/false"` has no effect on dropdown menu visibility. 
Do we have to manually hide/show with javascript or this `aria-expanded`should handle this?

**Comment by brandonferrua** [comment]
@matejp84  The `aria-expanded` is purely for accessibility. To show/hide the dropdown, you'll need to toggle the visibility classes, `slds-show` and `slds-hide`.

**Comment by msrivastav13** [comment]
@brandonferrua Is this fixed ?And just curious to know when will be next build for this issue so that we can pull latest ...
