### ISSUE TITLE
Colspan on Responsive Layout

### ISSUE THREAD

**Issue by jmdohn** [salesforce-ux/design-system#310]
Using a colspan for a header on the responsive layout (prototype), results in the page not snapping when the groups are larger than the width of the page.   Multiple columns are past the edge of the page.

![notspanningcorrectly](https://cloud.githubusercontent.com/assets/12724534/18424831/f5782f0c-7878-11e6-99b9-07212acc0c0e.JPG)

**Comment by kaelig** [comment]
Thank you @jmdohn for reporting this. We're not supporting responsive table fully at the moment but this is something we'll make sure to investigate.

**Comment by jmdohn** [comment]
Yep.  I'm not surprised.  I may end up tweeking the media queries / the way
that it handles colspans.  If so, I may end up contributing in the future.
Thanks for the prompt response!

**Comment by kaelig** [comment]
Closing this as responsive data tables are very tricky subject that we have decided to get away from for now.
