### ISSUE TITLE
Document slds-image__actions

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#311]
The Figure component added in `1.2.x` is documented to provide an optional `slds-image__actions` ButtonGroup. The usage is not documented in the code examples and it is not clear to me where and how this should be added to the markup. Is it supposed to render in the overlay? If not, how does it work together with the overlay? Is it supposed to go into `slds-image__title`? Please document the implementation somewhere.

Thank you!

**Comment by kaelig** [comment]
Thank you, this is great feedback! Seems like this part of the documentation could use some clarity. @tsheiner is this something your team can look into?

**Comment by tsheiner** [comment]
@jina can you please take a look at this one? Thx!
