### ISSUE TITLE
Duplicate ID in Lookup

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#313]
The Lookup examples currently have a duplicate ID on `input` and `slds-lookup__menu`, see: https://www.lightningdesignsystem.com/components/lookups/

**Comment by kaelig** [comment]
Thank you for reporting this. It was caught by our automated tests and we are going to fix it very soon!

**Comment by kaelig** [comment]
Closing this as this is something that will be fixed in the Summer ’17 release. Thanks again for reporting it!

**Comment by kaelig** [comment]
Closing this as this is something that will be fixed in the Summer ’17 release. Thanks again for reporting it!
