### ISSUE TITLE
Should text utilities set the color?

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#314]
If I want to apply a text transformation in a specific section/label etc using some of the text utility classes, ie slds-text-body--small, slds-text-title--caps I have to always override the color since these classes always apply their own color value. Is this on purpose or color could be removed?

**Comment by kaelig** [comment]
This is a very good question, thanks for asking @bekos!

It looks like @stefsullrew should have useful information about this.

**Comment by engai** [comment]
Hi @bekos, this is on purpose. Our intention here is to maintain a predictable set of type styles within our system.

By enforcing these styles, we're able to help designers and devs to maintain a consistent type hierarchy when using our system and components.
