### ISSUE TITLE
Issue in trying to use SLDS in Lightning Apps

### ISSUE THREAD

**Issue by pbattisson** [salesforce-ux/design-system#317]
I am trying to use the design system in a Lightning Application as per the instructions (extending force:slds) I get the following error.

<img width="1135" alt="screen shot 2016-09-19 at 11 41 46" src="https://cloud.githubusercontent.com/assets/795556/18629553/301d9062-7e5e-11e6-9544-9e9691755f3d.png">

**Comment by kaelig** [comment]
Sorry you are encountering this error, are you using a Winter ’17 developer org?

**Comment by pbattisson** [comment]
@kaelig no it is still Summer 16 - is that the issue then? It doesn't state anywhere on the slds page that it must be Winter 17 (may want to update the instructions at https://www.lightningdesignsystem.com/platforms/lightning/)

**Comment by kaelig** [comment]
This is correct, the site is documenting SLDS for Winter ’17.

@srohde is this something we should consider a documentation bug?

**Comment by srohde** [comment]
Good point, we'll add it.

**Comment by banderson5144** [comment]
How would you use Icon from SLDS when using force:slds?

**Comment by stefsullrew** [comment]
Hi @banderson5144 - have you tried using the new lightning:icon component?

**Comment by banderson5144** [comment]
@stefsullrew Yes and it does work. I just want to make sure we still have granular control. Also

img/slds-icons/v5.2.0/action-sprite/svg/symbols.svg

Where do you get the version number from?

**Comment by stefsullrew** [comment]
Ummm... where does that path come from? :)

**Comment by banderson5144** [comment]
When using <lightning:icon> the constructed <svg> in the actual browser has that path to the Icon

**Comment by stefsullrew** [comment]
Gotcha. You can't use SVGs outside of the component. So you'll need to use the lightning:icon component to use the SVG icons.

**Comment by banderson5144** [comment]
I understand that. That wasn't my question, how is the version number determined?

**Comment by FabienTaillon** [comment]
@banderson5144 Maybe you'll be able to find how the version number is set, but I'm not sure this is something you want to use as it's part of lightning:icon component and could change at any time. As a general rule in Salesforce development: If it's not documented, don't use it.

If you need to reference SVGs directly, ou can still add SLDS as a static resource.

@kaelig As this issue was a documentation bug related to orgs that were not yet on Winter '17 (which should be a number around 0 now), maybe this issue can be closed ?

**Comment by kaelig** [comment]
@banderson5144 the version number is determined by the version of the icons npm package: https://www.npmjs.com/~salesforce-ux/icons

@FabienTaillon good point, I'll close it!
