### ISSUE TITLE
Data Tables header with sort icon jumping

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#318]
If we will remove class slds-table--fixed-layout header with sort icon on hover start jumping
![untitled](https://cloud.githubusercontent.com/assets/196564/18665967/4df0b9fa-7f32-11e6-9c80-2b68d4a0d230.gif)

**Comment by kaelig** [comment]
Thank you for reporting this and for providing this useful animation!

@stefsullrew what would be your recommendation to avoid this issue?
