### ISSUE TITLE
Toast too big for mobile client

### ISSUE THREAD

**Issue by dangmai** [salesforce-ux/design-system#319]
Hi,

It seems that the toast component is too big for mobile clients. When I go to the [LDSD page](https://www.lightningdesignsystem.com/components/notifications/#flavor-toast) for Toast on my phone, the Close button is off to the right of the viewport and cannot be clicked.

When I implemented it in a Visualforce page and go there from the Salesforce1 Android client, the same thing happens. 

If I take out the `min-width` on `.slds-notify--toast`, the toast shows correctly. Not sure if that's intentional or not though.

Thanks!

**Comment by kaelig** [comment]
Hi @dangmai, thank you for using the Lightning Design System and for reporting this to us!

The toast isn't a pattern that's tailored for the mobile experience (at the moment, at least).

@jina is there another pattern better suited for mobile with the same type of notification?

**Comment by dangmai** [comment]
I'm actually using the Alert component in place of Toast, which works correctly on mobile apps.

Maybe it's a documentation issue, since I assumed it's going to work on mobile clients because it doesn't have the "Not Compatible with S1 Mobile" badge. Should there be another badge that warns developers against using a component in generic mobile applications?
