### ISSUE TITLE
SVG Icon not rendering in LEx/Iframe in Edge

### ISSUE THREAD

**Issue by mtetlow** [salesforce-ux/design-system#321]
It looks like Edge is having a problem with cross domain svg sprite resolution
![edge iframe svg problem](https://cloud.githubusercontent.com/assets/1168845/18761051/aeb4c6ca-80c0-11e6-8cd0-65c3df24bc4c.png)

JS Fiddle minimal reproduction: http://jsfiddle.net/ovqqmL09/

This impacts Salesforce devs + slds users because the issue presents itself when a VisualForce page is displayed in LEx. Immediate impact for me is I have a customer with the icons displaying in classic, but they don't display in LEx.

I understand this is probably a Edge Bug + svg4everybody feature request but thought it would be helpful to post.

**Comment by bbaker2** [comment]
We also have encountered this issue. Thanks for posting it here,

**Comment by mtetlow** [comment]
Here's the edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8323875/
![screen shot 2016-09-22 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/1168845/18765151/a86ed77c-80d1-11e6-926a-a5f40635ab04.png)

**Comment by kaelig** [comment]
This is definitely a major annoyance. Let's hope Microsoft fixes this very soon.

Not sure it is helpful for your use case, but have you tried using the `lightning:icon` global component? See https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_icon.htm for documentation.

Let me know if this helps!

**Comment by stefsullrew** [comment]
In order to use the lightning:icon (or any lightning components) in VF, you'll need to use a LC4VF Container. Then it will work perfectly. Check https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/components_visualforce.htm?search_text=lc4vf for more information about LC4VF.

**Comment by kanwalpreet-singh** [comment]
It hit in my application also and i logged it [Here](https://github.com/salesforce-ux/design-system/issues/247)

**Comment by mtetlow** [comment]
Well, since nobody was really doing this on the MS side I did this: https://github.com/jonathantneal/svg4everybody/pull/139 . Will update again if it gets merged.

**Comment by kaelig** [comment]
Thanks @mtetlow for keeping on top of this, we appreciate it. Note that we've also been in touch with the platform team here at Salesforce to ensure icons work across all supported browsers in Spring ’17 - fixes should come mid-Feb if everything goes well.

**Comment by mtetlow** [comment]
it's merged!

**Comment by gunda223** [comment]
I still have the same issue in IE 11, Is this fixed?
