### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#322]
Is there a way to determine what version of SLDS is being utilized by one.app? 

We would prefer to utilize the provided style sheets. However, its is clear that SLDS moves forward faster then production systems do. We are even a little unclear on which versions is provided in sandbox. I've check the release notes and can not see were it says the deployment status. 

Being able to tell versions is becoming more needed as the system matures and items are add/depreciated.

**Comment by srohde** [comment]
It depends on your Salesforce org which should still be on Summer '16 which has SLDS 2.0.
When your org upgrades to Winter '17 you'll get SLDS 2.1.2 which is already on http://getslds.com.
