### ISSUE TITLE
Docked Form Footer does not work on Salesforce1 iOS

### ISSUE THREAD

**Issue by Lukvang** [salesforce-ux/design-system#323]
It doesn't look like the Docked Form Footer is working in Salesforce1 web browser on iOS devices. It works on android, desktop, full desktop on iOS, and iOS simulators. The Docked Form Footer, moves along in all the other devices if you scroll, but on the Salesforce1 web browser app on iOS its static and stays at the bottom of the screen.

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and letting us know about this!

@jina is this something that we have a workaround for?

**Comment by Lukvang** [comment]
Is this something that will be fixed in the future? Or is there a work around?

**Comment by saltimas** [comment]
This is still an issue on iOS. Does anyone have a workaround?

**Comment by lukevang** [comment]
Any update on this yet? It seems like the docked form footer works if your in desktop view on a iOS device but once you view it in Salesforce1 it will not work.

**Comment by brandonferrua** [comment]
Hi there, please update this bug per our contributing guidelines so we can investigate this issue. https://github.com/salesforce-ux/design-system/blob/master/CONTRIBUTING.md#bug-reports

**Comment by stefsullrew** [comment]
We have marked this component desktop only in the next release. We couldn't get it into this one. That said, like Brandon, anyone that would like to contribute a fix, we're open to it.
