### ISSUE TITLE
standard "email_IQ" icon removed between 2.0.3 and 2.1.3?

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#325]
Hi,

This isn't an issue for us, but our build tool that compiles our the SVG into our resources broke when we switched to 2.1.3 release because the email_IQ icon no longer exists. I checked the release notes and couldn't see any mention of this, so wanted to check if this is an oversight in the release notes or should it still exist?

![image](https://cloud.githubusercontent.com/assets/415690/19162973/dc810c8c-8bae-11e6-8569-c292c8db991f.png)

**Comment by kaelig** [comment]
Good catch!

As you highlighted, icon release notes are not available publicly. They are currently in a private repository, and we're looking at how we could surface changes to our external users easily.

The `email_IQ` wasn't being used by any of our products so we decided to remove it without warning from the set.

Note: I've published a patch version of the [@salesforce-ux/icons npm package](https://www.npmjs.com/package/@salesforce-ux/icons), where you'll see the release notes: https://unpkg.com/@salesforce-ux/icons@5.2.1/ – Hope it helps!

**Comment by mattgoldspink** [comment]
Got it - thanks @kaelig. I think for additions it's not a problem - but a removal should probably get a mention as it has the potential to break something. We read the release notes to make sure we know what areas to focus our testing on when upgrading- I love that you guys make such comprehensive release notes, it makes it a lot easier for us to do that! I was just surprised this one wasn't mentioned, but given we don't use it it's not an issue for us.
