### ISSUE TITLE
Remove link to lightning:tooltip documentation

### ISSUE THREAD

**Issue by dianawidjaja** [salesforce-ux/design-system#327]
The [tooltip docs](https://www.lightningdesignsystem.com/components/tooltips/) contains a link to the lightning:tooltip documentation in the LC Dev Guide. However, the lightning:tooltip component has been removed from the Winter '17 release.

**Comment by kaelig** [comment]
Thank you for letting us know, @dianawidjaja! For internal matters, can you please get in touch via the appropriate internal channels? Many thanks.

cc @srohde @tsheiner
