### ISSUE TITLE
apex:commandButton and Lightning Design System

### ISSUE THREAD

**Issue by mamplo** [salesforce-ux/design-system#328]
I am having an issue when using the lightning design system CSS and applying it to apex:commandButton. For some reason the styles are not rendering correctly leaving me with an ugly gray button.

Whenever I use the CSS on any of the other Visual Force tags I don't have any issues.

Any help would be greatly appreciated.

**Comment by force2b** [comment]
I use the following on my commandButtons, which works just fine:
`styleClass="slds-button slds-button--brand slds-button--neutral slds-not-selected"`

**Comment by mamplo** [comment]
That didn't work. Here is my block of code.

<div class="slds-col slds-no-flex slds-grid slds-align-top">
<apex:outputPanel>
<apex:commandButton styleClass="slds-button slds-button--brand slds-button--neutral slds-not-selected" value="A" />
<apex:commandButton styleClass="slds-button slds-button--brand slds-button--neutral slds-not-selected" value="B"  />
</apex:outputPanel>
</div>

**Comment by mamplo** [comment]
That didn't work. This is my code snippet.

div class="slds-col slds-no-flex slds-grid slds-align-top"
apex:outputPanel
apex:commandButton styleClass="slds-button slds-button--brand slds-button--neutral slds-not-selected" value="A" /
apex:commandButton styleClass="slds-button slds-button--brand slds-button--neutral slds-not-selected" value="B" /
/apex:outputPanel
/div

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this, @mamplo!

I've used the snippet you provided, and I can't reproduce the issue on my end.

Can you confirm that your snippet was inserted between the SLDS custom scoping class for your org?

This works for me:

```
<apex:page showHeader="false" standardStylesheets="false" sidebar="false" applyHtmlTag="false" applyBodyTag="false" docType="html-5.0">
    <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" lang="en">
        <head>
            <meta charset="utf-8" />
            <meta http-equiv="x-ua-compatible" content="ie=edge" />
            <title>Test buttons</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <apex:stylesheet value="{!URLFOR($Resource.REPLACE_WITH_NAME_OF_YOUR_STATIC_RESOURCE, 'assets/styles/salesforce-lightning-design-system-vf.min.css')}" />
        </head>
        
        <apex:remoteObjects >
            <apex:remoteObjectModel name="Contact" fields="Id,Name,Title,LastModifiedDate,PhotoUrl"/>
        </apex:remoteObjects>
        
        <body>
            <!-- REQUIRED SLDS WRAPPER -->
            <div class="REPLACE_WITH_NAME_OF_YOUR_CUSTOM_SCOPING_CLASS">
                <apex:form>
                    <div class="slds-col slds-no-flex slds-grid slds-align-top">
                        <apex:outputPanel>
                          <apex:commandButton styleClass="slds-button slds-button--brand slds-not-selected" value="A" />
                          <apex:commandButton styleClass="slds-button slds-button--brand slds-not-selected" value="B" />
                        </apex:outputPanel>
                    </div>
                </apex:form>
            </div>
        </body>
    </html>
</apex:page>
```

Let me know if this works, or if I can be of further assistance!

Also: `slds-button slds-button--brand slds-button--neutral` won't work correctly when combined as it's applying styles both for brand and neutral button appearances. You'll want to use either `slds-button slds-button--brand` or `slds-button slds-button--neutral`.

**Comment by mamplo** [comment]
That solution worked perfectly. I was missing the DIV tag with the scoping class.

**Comment by kaelig** [comment]
Fabulous, glad it is resolved.
