### ISSUE TITLE
Toggle width 100%

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#329]
I find out that toggle has width 100% to check/uncheck action

![screen shot 2016-10-19 at 4 04 27 pm](https://cloud.githubusercontent.com/assets/196564/19519848/4d593314-9616-11e6-981c-1f15d8935548.png)

**Comment by kaelig** [comment]
Thank you @ButuzGOL, did you have a question about this?

**Comment by JohnHeadIV** [comment]
Is this the intended effect or should toggle happen only upon click on the Toggle itself? After looking at this we've gone back a put another div around all our toggle to ensure the clickable area is not so large around each toggle.  Its kinda funny to be able to change to toggle by clicking the label but the out div means that the significant white-space to the right of Toggle isn't also clickable.

**Comment by ButuzGOL** [comment]
Yes I think click should be only on label and toggle

**Comment by FabienTaillon** [comment]
I must admit that when I tried playing with the related base component, I found it pretty strange to be able to toggle it from the opposite side of the screen. Looks like something where users will toggle the field without seeing they did.

![toggle](https://cloud.githubusercontent.com/assets/2465122/19563832/bffe0982-96e1-11e6-8773-753fd8bc853d.gif)

**Comment by kaelig** [comment]
Let me redirect the question to our form expert @brandonferrua!

**Comment by kaelig** [comment]
Closing this - a workaround is to wrap the toggle in a div (e.g. using the grid utility classes). Hope this helps!

**Comment by george-norris-salesforce** [comment]
Can also change the label with surrounds the toggle to:
```
    display: inline-block;
    width: auto;
```
