### ISSUE TITLE
SLDS.com / Grid / Order

### ISSUE THREAD

**Issue by Diamundo** [salesforce-ux/design-system#330]
https://www.lightningdesignsystem.com/components/utilities/grid/#flavor-order

There's a bug with the example:
- large: orders correctly (reversed: 3, 2, 1)
- medium: orders correctly (1, 2, 3)
- small: orders the same as medium instead of (3, 1, 2)...

(Using Chrome 53.0.2785.143, Firefox 45.0.1, Opera 40.0.2308.81)

_I have no idea how to add labels or anything, but it should be labeled as a bug._

**Comment by Diamundo** [comment]
I copied the example code into my own project and there it does work correctly, so it's most definitely only a problem on the website.

**Comment by kaelig** [comment]
Hi @Diamundo, thank you for using the Lightning Design System and for reporting this. Great catch!

This looks like a form factor issue in the documentation. Let me redirect this towards the team so we can take action.

**Comment by kaelig** [comment]
Hi @Diamundo, we just fixed this, thank you for your patience!
