### ISSUE TITLE
Feature request: Save Icon

### ISSUE THREAD

**Issue by Diamundo** [salesforce-ux/design-system#331]
Hi there,

I've been looking up and down https://lightningdesignsystem.com/icons looking for a Save Icon, but I can't seem to find it.
There's multiple variants of cut, copy, paste, new, edit, clone, file, open folder, select folder and whatnot, but not one floppy disk...

Could you please make a save icon as well?
Thank you :heart:

**Comment by et** [comment]
`update_status` maybe?
![screen shot 2016-11-01 at 10 24 09 am](https://cloud.githubusercontent.com/assets/58678/19897371/74780310-a01d-11e6-993d-26be6ef73625.png)

**Comment by Diamundo** [comment]
Thank you, but as you say that's an update icon. I am specifically looking for an icon to show 'Hey, you're about to create an entirely new sObject with the info you just supplied!' and old-fashioned I may be, I feel like a floppy-disk conveys that message better than a box with a checkmark :)

**Comment by kaelig** [comment]
The save icon is now on our roadmap, watch this space!

**Comment by engai** [comment]
Hi @Diamundo, we now have a 'save' icon under Utility Icons.
