### ISSUE TITLE
Hidden table leaving white line

### ISSUE THREAD

**Issue by bsansone** [salesforce-ux/design-system#332]
I've got a data table that is on my page and hidden by default but it is leaving a strange white line under the button, where it is hidden at. If I remove the class `slds-table--bordered` from my table the white line is not there when hidden, but I lose the bordered table. Is there a fix to this that doesn't require me to remove the `slds-table--bordered` class?

![screen shot 2016-10-21 at 9 35 48 am](https://cloud.githubusercontent.com/assets/16868336/19602409/c5a1579a-9772-11e6-89e3-2774ecad241f.png)

**Comment by FabienTaillon** [comment]
Maybe can you share a little bit more details ?
I tried using the Basic Data Table component and hide it using the _slds-hide_ class, and I don't have the issue. How are you hiding the table ?

**Comment by bsansone** [comment]
So after looking at it some more, the table is actually there, it just doesn't have any values in it. When I hit the `Load Items` button it has an action attached to it that will render the items in the table if items > 0.

**Comment by FabienTaillon** [comment]
Maybe you should add the _slds-hide_ class to your table if there are no items returned then.
If you're working on a Lightning Component, you can use [toggleClass](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_cb_show_hide_markup.htm) to do that, otherwise just use the JavaScript you're used to.

**Comment by bsansone** [comment]
I fixed it by removing the `slds-table--bordered` class and adding `tr { border: solid 1px #d8dde6
;}` to head of my page
