### ISSUE TITLE
Color themes and badges—are they supported?

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#333]
Is using color themes on badges no longer supported? Documentation states that color themes should only be used on box themes, toasts, and alerts.

While they still work for badges in the current release, I was wondering if this is a deprecated feature and achieving colored badges this way should be avoided.

**Comment by kaelig** [comment]
Thanks for asking! I just confirmed with the team that themes are and will still be supported. We might add additional examples later on!
