### ISSUE TITLE
SLDS Icons not resizing correctly

### ISSUE THREAD

**Issue by Diamundo** [salesforce-ux/design-system#334]
Hi there,

I am using lightning icons and found the following issue:
 - when I set the size on medium or large, the icons are perfectly round (or at least, the bounding box is a perfect square -> the height and with are equal)
 - when I set the size on small (or xx- or x-), the icons inside are still correctly scaled down but the circle around it is not: the circle is larger in height than in width.

This leads to disproportionally sized buttons when I want to use them as small, because I think the medium-sized icons are too big.

Sizes:
- Large: slds-icon = 48x48, icon-container--circle = 64x64, button = 66x66
- Medium: slds-icon = 32x32, icon-container--circle = 48x48, button = 50x50
- Small: slds-icon = 24x24, icon-container--circle = 40x46, button = 42x48
- x-small: slds-icon = 16x16, icon-container--circle = 32x46, button = 34x48
- xx-small: slds-icon = 14x14, icon-container--circle = 30x46, button = 32x48

It seems, looking at the above "table", that the `slds-icon-container--circle` width is correctly scaled, but the height is locked.

What could cause this, if the problem is non-reproductible on your end?

**Supplied Code:**

```html
<div class="slds-p-around--medium"> 
  <!-- This is the top-level div, directly called in the app file. -->

  <div id="list" class="row"> 
    <!-- This is in the List-items component, containing an aura:iteration -->

    <div class="slds-p-top--small"> 
      <!-- this tag is inside the aura:iteration, and inside this tag is a different component (the single item that list-items component iterates) where the grid is placed -->

      <div class="slds-grid">
          <div class="slds-p-right--small">
            <button class="slds-button" onclick="{!c.function}">
              <lightning:icon iconName="action:edit" size="small" alternativeText="Do something" />
            </button>

          </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by kaelig** [comment]
Thank you for your question, @Diamundo! 

Have you tried adding `slds-button--icon` to the `<button />` element? Let me know how that looks for you.

**Comment by Diamundo** [comment]
That worked, thank you!
