### ISSUE TITLE
How to modal?

### ISSUE THREAD

**Issue by Diamundo** [salesforce-ux/design-system#335]
[See this question on the Developer Forums](https://developer.salesforce.com/forums/ForumsMain?id=9060G000000XdcPQAS), but given that reaction time is a bit quicker here than over there I decided to repost it here.

I have no idea how to work with modals. I copied the code from [LDS.com/components/modals/](https://www.lightningdesignsystem.com/components/modals/) into my code, a few componentlayers into my app, but (after commenting out the _svg_ part) the modal shows up on loading the app and I can't get it to go away...

Given that I can't find any examples on how to work with it using javascript I come to you for help.

P.S. I believe, reading #305, you might want to update the example code given that SVG is now included in _lightning:icon_.

**Code:**
```html
<aura:component >
    <aura:handler name="init" value="{!this}" action="{!c.doInit}" />

    <div class="slds-grid slds-p-vertical--small">
               
        <div class="slds-p-horizontal--small">
            <lightning:button variant="brand" label="Save" onclick="{!c.save}" />
          <!-- No save icon, so for now we have this button. (see github issue #331 -->
        </div>

        <div class="slds-p-horizontal--small">
            <button class="slds-button" onclick="{!c.export}">
                <lightning:icon iconName="action:share" size="medium" alternativeText="Export" />
            </button>
        </div>
        
    </div>
    
<!-- Here begins the example code from LDS.com/components/modals/ -->

    <div role="dialog" tabindex="-1" aria-labelledby="header43" class="slds-modal slds-fade-in-open">
        <div class="slds-modal__container">
            <div class="slds-modal__header">
                <button class="slds-button slds-modal__close slds-button--icon-inverse">

<!-- 
SVG Doesn't work, missing component or something. 
That's no biggie though. I don't think I'm keeping the button.

                    <svg aria-hidden="true" class="slds-button__icon slds-button__icon-!-large">
                        <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#close"></use>
                    </svg>
-->
                    <span class="slds-assistive-text">Close</span>
                </button>
                <h2 id="header43" class="slds-text-heading--medium">Modal Header</h2>
            </div>
            <div class="slds-modal__content slds-p-around--medium">
                <div>
					HERE COMES SOME DYNAMICALLY CREATED TEXT                    
                </div>
            </div>
            <div class="slds-modal__footer">
                <button class="slds-button slds-button--neutral">Cancel</button>
                <button class="slds-button slds-button--brand">Save</button>
            </div>
        </div>
    </div>
    <div class="slds-backdrop slds-backdrop--open"></div>
    
</aura:component>
```

**Comment by kaelig** [comment]
Modals are a tricky beast for sure, thank you for asking for help!

This is something we encourage developers to build themselves with what is best for their own needs. There are plenty of JavaScript implementations of modals that you can find if you search a little. The best place to discuss this is on the developer forum as you initially did! Good luck in your search!

**Comment by Diamundo** [comment]
Hello kaelig,

So you provide the code for modals, but then don't support it when people ask for help, instead saying to make my own things with javascript and without the LDS? Why even include it at all then.

Also, if you hadn't noticed yet: this is the standard code from the documentation. I expect the code to then also function out-of-the-box. It might not do a lot, it might be filled with latin scrabblings, but it should do its primary function.. 
And right now, it doesn't work. It's primary function, to show up when told to and to hide when told to, does not work. I am hereby asking for help on how to achieve this, with the effect being that you note the documentation is not complete and either mark it as 'should be worked on' or improve it directly.

I would like to hear your thoughts on this.

Sincerely, Diamundo

**Comment by Diamundo** [comment]
Well, well, well.
I finally got it to work, and am posting my workaround here for others who just like me want to use a modal but can't get the standard one from the documentation to work.

**COMPONENT** (embed this somewhere in an aura:component, I have it in the one where the button is that calls the modal)
```html
<div role="dialog" tabindex="-1" aria-labelledby="header43" class="slds-modal" 
                             aura:id="shitModal">
    <div class="slds-modal__container">
        <div class="slds-modal__header">
            <button class="slds-button slds-modal__close slds-button--icon-inverse" 
                                      onclick="{!c.closeModal}">
                <lightning:icon iconName="utility:close" size="medium" />
                <span class="slds-assistive-text">Close</span>
            </button>
            <h2 id="header43" class="slds-text-heading--medium">Modal Header</h2>
        </div>
        <div class="slds-modal__content slds-p-around--medium">
            <div aura:id="modalContent" />                    
        </div>
        <div class="slds-modal__footer">
            <button class="slds-button slds-button--neutral">Cancel</button>
            <button class="slds-button slds-button--brand">Save</button>
        </div>
    </div>
</div>
<div aura:id="modalBackdrop" class="slds-backdrop"></div>
```
Note:
- Line 1: I added an aura:id to look up the div with
- Line 1: I removed the class "slds-fade-in-open"
- Line 4: I added an onclick function to close the modal when it is opened.
- Line 5: Instead of the svg stuff that's hard to implement I put a lightning:icon here which does the same but using the proper LDS classes and stuff. (see #336 why, and #337 for nice buttons when you only use utility icons)
- Line 11: I am going to dynamically put some text there, which is generated when I click the button to open the modal. Not in the scope of this issue, and also not yet fixed :sweat_smile: 
- Line 19 (last line): I added an aura:id to look up the div with
-Line 19: I removed the class "slds-backdrop--open"

**CONTROLLER**
```javascript
({
    export : function(component, event, helper) {
        var content = helper.generateContent( /* generate arguments */ );
                        
        $A.util.addClass(component.find("shitModal"), "slds-fade-in-open");
        $A.util.addClass(component.find("modalBackdrop"),  "slds-backdrop--open");
//        component.set(component.find("modalContent"), content); 
                              // This is when I am going to fill the modal with content.        
	},

    closeModal : function(component, event, helper) {
        $A.util.removeClass(component.find("shitModal"), "slds-fade-in-open");
        $A.util.removeClass(component.find("modalBackdrop"),  "slds-backdrop--open");
    }
})
```
Note:
- when I init the page, no modal seen anywhere. This is because the modal div does not have the class "slds-fade-in-open"
- when I init the page, there is also no gray background disabling the rest of my page. This is because the backdrop div does not have the class "slds-backdrop--open"
- When I want the modal to appear, I find that div and give it its needed class. Same with the backdrop.
- When I want the modal to close (I click the button, or possibly when I press ESC or outside the modal), I find the div's again and remove the classes.

**HELPER** (for completeness)
```javascript
({
    generateContent : function( /* needed arguments */ ) {
        return ("Lorum ipsum, I don't know the rest by heart");
    }
})
```

**Comment by Diamundo** [comment]
@kaelig 
See the above. Perhaps an idea to add this to https://www.lightningdesignsystem.com/components/modals/ to make it more clear how to work with modals?

**Comment by Diamundo** [comment]
Oh, and I do have a bug: it looks like the icon on the documentation site is correctly inverted (a white cross) but I have the same cross and a gray cross (i.e. not inverted).

**Comment by Diamundo** [comment]
```html
        <lightning:ButtonIcon class="slds-modal__close" iconName="utility:close" size="large" 
                              variant="bare-inverse" alternativeText="Close" onclick="{!c.closeModal}" />
```

Replace the close button with an icon, with the above buttonIcon. The cross will be slightly smaller but it'll be inverted (i.e. white, thus better visible than gray) just like the example.

**Comment by kaelig** [comment]
I understand your frustration! Thank you very much for sharing your solution (profanity excluded!), this should be useful to other developers.

**Comment by Diamundo** [comment]
Ah yes, I forgot to alter that after exporting from my code. I have changed it in the above comment.
