### ISSUE TITLE
SLDS.com Icons documentation: still requires SVG's instead of lightning:icon

### ISSUE THREAD

**Issue by Diamundo** [salesforce-ux/design-system#336]
#305 

https://www.lightningdesignsystem.com/components/icons/

You might want to update that page, given that currently it still says to use custom SVG classes.

**Comment by kaelig** [comment]
Thank you for pointing this out!

The reason the icon markup in the SLDS documentation uses SVG elements is that `<lightning:` components are available on the platform, whereas the Lightning Design System aims to provide markup that is platform-agnostic and can work outside of the platform.
