### ISSUE TITLE
Question: Responsive Mobile Friendly Version?

### ISSUE THREAD

**Issue by tyrollins** [salesforce-ux/design-system#338]
Are there any plans to create a responsive mobile friendly version of the design system? Currently, there seem to be some elements that are "responsive" such as the grid, some panels, etc... However there does not seem to be a mobile first approach such as that of bootstrap. 

The menu is a major pain point when developing for mobile friendly sites, as currently the menu is not natively mobile friendly, or at least I have not been able to make it be. Any advice or suggestions would be greatly appreciated.

**Comment by srohde** [comment]
@tyrollins, by menu do you mean the Global Navigation?
Some of our components are for desktop only at this point.
Did you look at the Components -> Touch section? There you'll find a Menu component for mobile.

**Comment by tyrollins** [comment]
@srohde appreciate the quick response. I see, yes, I was referring to the Global Navigation component. I must have missed the touch / mobile section, I will definitely take a look. Thanks again.
