### ISSUE TITLE
Tabs Component Expected Markup

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#34]
I played with the [Tabs Component](https://www.lightningdesignsystem.com/components/tabs), and I used the Expected Markup section to make it work using JS. This section mentions 3 markups:
* aria-selected
* tabindex
* aria-labelledby 

As this was not working, I easily found that I need to change *slds-show* and *slds-hide*, which are described in [another page](https://www.lightningdesignsystem.com/components/utilities/visibility).

Lastly, I also had to switch the *slds-active* class.

I know all this seems obvious once understood, but all this is pretty new, and also most of us are back-end apex developers that have been relying on apex tags to manage all this CSS stuff for us.

So my point is:
* Maybe the *slds-active* class should be documented in the Expected Markup section (otherwise I'm pretty sure some guys will forget to switch it)
* I understand the *slds-show* and *slds-hide* because that's true it's pretty obvious and writing about it on all component wouldn't be the best choice, but maybe having a way to search true the whole documentation would be great. I guess there will be more and more components, and having a search engine would be a nice way to find information on classes that are explained somewhere else.

**Comment by stefsullrew** [comment]
I completely agree with you. That's a miss in the documentation and I'll file an enhancement request to get it added. Thanks for calling this out!

**Comment by stefsullrew** [comment]
I've added this further documentation for the next release. Thanks for the suggestion!
