### ISSUE TITLE
SLDS not rendering CSS styling when VF renderAs PDF

### ISSUE THREAD

**Issue by matthew-whaley** [salesforce-ux/design-system#341]
Does the LDS work when a visualforce page is renderAs PDF? I am not able to get any css styling on backgrounds, font color, etc.

**Comment by kaelig** [comment]
Thank you for your question!

This isn't something we've been looking into so far, but we'll keep it in the back of our minds and keep you updated if we have any updates!

**Comment by matthew-whaley** [comment]
Thanks @kaelig , do you happen to know if you can currently use the Lightning Design System for styling when rendering as a PDF? It seems the positioning works but I cannot get the colors or anything to work when the VF page is rendered as a PDF.

**Comment by kaelig** [comment]
Sorry to hear that. I'm not familiar with this use case, sorry!

Could you ask this question on the developer forums? You might get better answers there.

**Comment by mouttaqui** [comment]
Visualforce PDF support only inline CSS

**Comment by SyedMoosaNazirTN** [comment]
Hi Team,

Visualforce pdf supports internal and external css files. But the issue is SLDS css file is not supporting in Visualforce PDF for some reason.
The below URL works fine with internal CSS file(stored CSS file in Static resource)
https://developer.salesforce.com/page/Creating_Professional_PDF_Documents_with_CSS_and_Visualforce

**Comment by FabienTaillon** [comment]
Are you using SLDS as a static resource or the one provided by the Platform ?

**Comment by SyedMoosaNazirTN** [comment]
@FabienTaillon Downloaded the SLDS ZIP file provided by Platform and stored in static resource.

**Comment by wdci-dev** [comment]
Is this resolved,  getting internal server error with VF page having <apex:slds/> and renderAs="pdf" , any workarounds please?

**Comment by bishwambhar-sen** [comment]
> Is this resolved, getting internal server error with VF page having apex:slds/ and renderAs="pdf" , any workarounds please?

We had a similar issue and we reached out to SF support. They asked us to remove the apex:slds tag. Now we are thinking of ways to use slds in our VF page. Perhaps by using static resources.
