### ISSUE TITLE
Section Title icon in Firefox is not aligned

### ISSUE THREAD

**Issue by stephenscholtz** [salesforce-ux/design-system#343]
From the SLDS example of a [collapsible section](https://lightningdesignsystem.com/components/utilities/text/#flavor-section-title-section-title-open), as viewed in Chrome (Version 54.0.2840.71 m)

![image](https://cloud.githubusercontent.com/assets/10414292/19817487/b9a4b796-9d19-11e6-80a0-6d3bfdc3111c.png)

And Firefox (Version 47.0.1)...

![image](https://cloud.githubusercontent.com/assets/10414292/19817563/0e492d18-9d1a-11e6-9388-55258151ec51.png)

Sorry, haven't had time to figure out a work around just yet, at least not one that doesn't use "float: left" ;P

**Comment by kaelig** [comment]
Thank you for the feedback and for using the Lightning Design System, @stephenscholtz!

We'll have a look and publish a fix very soon!

**Comment by stephenscholtz** [comment]
For what it's worth, I did a small work around that seems to make FF display consistently w/ the intention of SLDS' design (Chrome displays consistently, no change; have not tested in Safari, IE, others)

I wrapped the svg in a span and floated it left, and this seemed to get FF to display this item correctly, including the spacing, height, etc.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10414292/20195329/17deb5c4-a764-11e6-977d-9b8026952b7e.png)


Code:
```HTML
<div class="slds-section slds-is-open">
  <h3 class="slds-section__title">
    <button class="slds-button slds-section__title-action">
      <span style="float:left"><svg aria-hidden="true" class="slds-section__title-action-icon slds-button__icon slds-button__icon--left">
        <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#switch"></use>
        </svg></span>Section Title</button>
  </h3>
  <div class="slds-section__content">
    <p>Aenean .....</p>
  </div>
</div>
```

Not at all sure why the svg and text don't appear inline together in FF.  I looked through all the inherited styles and didn't see anything out of the ordinary, but there must be something in the chain, because doing a very simple on frills example you get the intended alignment results:

![image](https://cloud.githubusercontent.com/assets/10414292/20195575/22f671bc-a765-11e6-8156-bdb6c109e91f.png)


```HTML
<div style="display:flex; background-color: #f00">
<div style="background-color: #0f0; display:block">blah
</div>
<div style="background-color: #00f; display:block">blah 2
</div>
</div>
```

**Comment by engai** [comment]
Hi @stephenscholtz, I believe this has been resolved as I am no longer able to reproduce the issue in FF. 'Section Title' is also now its own component under 'Expandable Section' https://www.lightningdesignsystem.com/components/expandable-section/

Closing this issue, but please feel free to reopen or comment.
