### ISSUE TITLE
Modal close button has white color in examples 

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#344]
Modal close button has white color in examples but in framework it has #54698d (blue) color
<img width="1440" alt="screen shot 2016-10-31 at 12 28 32 pm" src="https://cloud.githubusercontent.com/assets/196564/19851309/f2ef003a-9f65-11e6-807e-3e5165ec100f.png">
If remove white color
<img width="1044" alt="screen shot 2016-10-31 at 12 28 59 pm 1" src="https://cloud.githubusercontent.com/assets/196564/19851312/fb4c2758-9f65-11e6-8069-299bcaa96f4e.png">

So as I understand #54698d (blue) is right am I right ?

**Comment by kaelig** [comment]
Thank you for reporting this, @ButuzGOL.

Can you clarify what you mean by "framework"?

**Comment by stefsullrew** [comment]
No. Button icons, by default have the blue color. The inverse version (to be used on dark backgrounds) is white (using the inverse class). I'm confused by what you mean by "if remove white color?" It's there for a specific purpose and shouldn't be removed.

**Comment by ButuzGOL** [comment]
Oh I see I thought it was applied by site styles closing
