### ISSUE TITLE
Data Table in Grid

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#345]
Does Data Table not respect the width of the grid size? So if I put a Data Table in a grid of 1-12, it still expands outside of the grid. Any way to keep it within?

**Comment by kaelig** [comment]
Thank you for your question, @banderson5144.

Have you tried wrapping the table with an horizontally scrollable container, or adding truncation helpers to all fields on the table?

**Comment by banderson5144** [comment]
Yes I am currently using slds - truncate on the header row and header cells. I will try the horizontal scrolling container.

**Comment by stefsullrew** [comment]
@banderson5144 - did this fix your issue? I'd like to close this if so. 

Cheers

**Comment by kaelig** [comment]
Closing this issue as it hasn't seen any activity in the past 3 months.
