### ISSUE TITLE
TimePicker component?

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#346]
Hi

We have several forms that need a time picker component. I noticed in the source code there is some classes related to a timepicker but there is no component listed in the docs:

https://github.com/salesforce-ux/design-system/tree/master/ui/components/datepickers/flavors/time

Is this safe for us to use at all? If not is there a timepicker component on the roadmap or at least any guidance on what one should look like at the moment?

Thanks,
Matt

**Comment by brandonferrua** [comment]
I highly recommend not using anything you find that isn't surfaced as an example on the site.

A standard `select` element who be my recommendation for a time picker.

**Comment by mgarf** [comment]
+1 would be great to see a DateTime Picker skin that we can use (hopefully later would become a out of the box component reference for lightning).

**Comment by engai** [comment]
Hey @mattgoldspink, I believe this has been resolved with the introduction of the Datetime Picker https://github.com/salesforce-ux/design-system/commit/43f64955b838f4b7b046d2048c67a15fc34fe382

https://www.lightningdesignsystem.com/components/datetime-picker/

Closing this issue, but feel free to reopen if needed.

**Comment by JohnHeadIV** [comment]
@engai 
I don't believe this solves this issues. The Timepicker would map to a Time type field in SFDC while a datetime picker would map to Date/Time field type. Its not very hard to modify the datetime picker to match the field but to not be part of the standard should still be considered an open issue.  You can use a input of with a type of Time but that doesn't get the picker option as expected.

**Comment by SiTaggart** [comment]
The time picker on its own can be found here https://www.lightningdesignsystem.com/components/timepicker/
