### ISSUE TITLE
Input type="range" component

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#348]
Would love to see a SLDS version of this

http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_range

**Comment by kaelig** [comment]
Thank you for your feature request, @banderson5144! We'll add it to our backlog.

**Comment by stefsullrew** [comment]
Hi @banderson5144 - thanks for your question. The `input` with `type=range` is simply an HTML5 input, styled differently in the various browsers. You can use it yourself now. There is nothing needed from SLDS to do this.

Cheers

**Comment by banderson5144** [comment]
@stefsullrew While I agree I can just use it, I guess what I am trying to say is that SLDS has applied its own styling for other form elements (I.e. Checkboxes, Radio, etc.). I thought maybe you would want to make it SLDS nice
