### ISSUE TITLE
SLDS Picklist Styles Inconsistent with Select Styles

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#349]
Hello,

We are using SLDS Picklists to render styled options in a dropdown instead of the standard browser styles provided with select options. In a stacked form, there are clear style inconsistencies between selects and Picklists: `font-size`, `padding`, and icon `fill` color, to name the more visually impactful ones.

Are we using Picklist in a supported way (in a form, alongside other form elements) and if so, are there plans to style Picklist closer to its select counterpart?

![screen shot 2016-11-15 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/8738640/20318630/923d3500-ab30-11e6-83d3-c3d24c0d4932.png)

**Comment by kaelig** [comment]
This is a very good remark, thanks for pointing this out Kevin!

Let me get this through to our design team.
