### ISSUE TITLE
removing border in sectionTitle

### ISSUE THREAD

**Issue by mshanemc** [salesforce-ux/design-system#352]
docs link:
https://www.lightningdesignsystem.com/components/utilities/text/#flavor-section-title-section-title-closed

Section Title, as implemented in slds, has a border around the button that's coming from slds-button--neutral.

Non-slds class in Salesforce LEX is finding: `.forcePageBlockSection .sectionHeader .sectionHeaderButton` and removing the border by adding `border:none`

`.slds-section__title-action` should also have a `border:none` to achieve styling that matches Salesforce.

**Comment by kaelig** [comment]
Thank you for your feedback, @mshanemc!

I couldn't find any references to `slds-button--neutral` in the example you mention. Can you be more specific?

**Comment by mshanemc** [comment]
Oops, sorry. That was lightning:button doing that, not the SLDS sample code.  Thanks!
