### ISSUE TITLE
Lookup control z-index problem inside modal

### ISSUE THREAD

**Issue by teyc** [salesforce-ux/design-system#353]
I'm not sure if you might classify this as a bug or not. 

The look up control's list is hidden behind the footer in a modal control. If the control is the last in the list, then most of the list is hidden behind the footer, which is poor UX.

See https://plnkr.co/edit/KaGVOG4oRIfXzzzgB1WJ?p=info for an example.

![image](https://cloud.githubusercontent.com/assets/2076/20344614/33e60896-ac3f-11e6-9e69-aa1bf529089a.png)

**Comment by PurvaA** [comment]
Hi @teyc, This is not a bug.
If lookup control is placed at the end of Modal, then you can scroll up to see lookup items.

I am attaching screen shots. Please have alook
Let me know in case of any concerns/ queries

![bottomlookupcontrol](https://cloud.githubusercontent.com/assets/15212429/20474267/db83dac4-afeb-11e6-8136-ec75b6761c2e.jpg)
![scroll_lookupcontrol](https://cloud.githubusercontent.com/assets/15212429/20474268/dbb031d2-afeb-11e6-8598-ae82795e0359.jpg)

**Comment by teyc** [comment]
Thank you for replying. Can close this issue.

-----Original Message-----

**Comment by PurvaA** [comment]
Fixes #353
