### ISSUE TITLE
Enable select prev/next month days

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#354]
Do you have ideas to enable select prev/next month days
https://www.lightningdesignsystem.com/components/datepickers/
?

**Comment by kaelig** [comment]
Thanks for your question, we already have a discussion about this in https://github.com/salesforce-ux/design-system/issues/306

**Comment by ButuzGOL** [comment]
its quite different question its about 
![screen shot 2016-11-24 at 11](https://cloud.githubusercontent.com/assets/196564/20592570/fac69b54-b236-11e6-837b-3ee193f5d068.png)
