### ISSUE TITLE
DateTime Picker Component

### ISSUE THREAD

**Issue by wasimbeniwale** [salesforce-ux/design-system#355]
Can we have a datetime component like this: http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_datetime-local

**Comment by bohdan-dovhan** [comment]
I believe it is possible to use usual html components in Lightning.

So probably we can just incorporate code 
<input type="datetime-local" name="bdaytime"> into lightning code.

Also there is datepicker in Lightning <ui:inputDate value="{!v.value}" displayDatePicker="true" />  but it doesn't always work as expected

**Comment by stefsullrew** [comment]
What you're viewing @wasimbeniwale is Chrome's rendering of a regular `type=datetime-local` `input`. There would be nothing for us to add to this as there's no styling being added to create this.

Cheers
