### ISSUE TITLE
Modal overflow issue

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#358]
Hi :-) 
When a modal contains a dropdown, a picklist or lookup, the menu opens inside the body causing it to scroll instead of overflowing outside of it. 

This is related to https://github.com/ng-lightning/ng-lightning/issues/279 and #353.
I know user can scroll but this is not the best solution. We could probably add a class that will allow modal body to overflow.

**Comment by kaelig** [comment]
This issue can be fixed by implementations.

Ideally dropdowns and such should be placed at the root of the document (or in a special container), outside of the flow.

e.g.

```html
    <!-- place dropdowns here, position absolute them in JavaScript -->
  </body>
</html>
```
