### ISSUE TITLE
slds-dropdown-trigger hover doesn't work for touch

### ISSUE THREAD

**Issue by chriswoolcott** [salesforce-ux/design-system#36]
Hi There, I am trying to get slds-dropdown-trigger to work on touch in the Salesforce1 mobile application.  From what I can tell this doesn't seem to be supported/documented?

**Comment by srohde** [comment]
The Design System doesn't include any JavaScript. You need to implement the actual dropdown behavior.

**Comment by chriswoolcott** [comment]
Interestingly enough this seems to be working out the box now in the salesforce1 app (iOS)

**Comment by stefsullrew** [comment]
@chriswoolcott - Did you change the place you were putting it? Did you change how you were adding it? Could something have changed at all?

**Comment by chriswoolcott** [comment]
@stefsullrew, I have several sections on my page using drop downs, all of which didn't seem to work before.  I hadn't changed anything and now they all are working.  I had checked my SF1 version prior to logging this as an issue and I was already on the latest version, as this was my initial thought.  All of this was tested using SLDS 0.9.1

**Comment by SukruthaSingri** [comment]
@chriswoolcott - does slds-dropdown-trigger work on hover or to dropdown closes when clicked outside the lightning component?
