### ISSUE TITLE
VF Page Trailhead_SLDS_Basic - SLDS not rendering CSS styling

### ISSUE THREAD

**Issue by rfcorcoranSFDC** [salesforce-ux/design-system#361]
![image](https://cloud.githubusercontent.com/assets/16845507/20872537/4d7fddf4-ba54-11e6-8969-5eb5d3dcd832.png)

I am doing the Lightning Design System : Getting Started with the Design System  
I completed the coding, and the page preview is missing the styling. I see no errors in Dev console and
when I inspect the code I seem to get to the CSS reference fine. 

Why no font, no shading, no styling, just boring text, with a simple font size change.? 
[SDLS214.txt](https://github.com/salesforce-ux/design-system/files/630054/SDLS214.txt)

**Comment by rfcorcoranSFDC** [comment]
<apex:page showHeader="false" standardStylesheets="false" sidebar="false" applyHtmlTag="false" applyBodyTag="false" docType="html-5.0">

<html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Salesforce Lightning Design System Trailhead Module</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <apex:stylesheet value="{!URLFOR($Resource.SLDS214, 'assets/styles/salesforce-lightning-design-system-vf.min.css')}" />
</head>
<body>

  
  <div class=".rfcorcoran">

    
    <p class="slds-text-heading--label slds-m-bottom--small">
      Salesforce Lightning Design System Trailhead Module
    </p>
    

    
    <div class="myapp">

      
      <section aria-labelledby="badges">
        <h2 id="badges" class="slds-text-heading--large slds-m-vertical--large">Badges</h2>
        <div>
          <span class="slds-badge">Badge</span>
          <span class="slds-badge slds-theme--inverse">Badge</span>
        </div>
      </section>
      

    </div>
    

  </div>
  

</body>
</html>
</apex:page>

**Comment by kaelig** [comment]
Thank you for learning about the design system!

I notice there is a `.` preceding the `rfcorcoran` wrapper class name. Can you try getting rid of this dot and see what happens?

**Comment by rfcorcoranSFDC** [comment]
OMG! That was it! 

I am new to CSS (obvioulsy) and didn't understand not to use the period. 

Thank you!!!

**Comment by kaelig** [comment]
Glad we figured it out!
