### ISSUE TITLE
I am unable to download pdf file from mobile browser

### ISSUE THREAD

**Issue by khadhar1690** [salesforce-ux/design-system#363]

**Comment by jina** [comment]
PDFs are not downloadable from mobile unless you use iBooks or if you have an application (like Dropbox) installed. This is not something we can fix on our end.

**Comment by khadhar1690** [comment]
The requirement is to download the files.How can i do?

**Comment by jina** [comment]
If you're just needing a PDF, you can download them from iBooks or from Dropbox (or a similar app). :)
