### ISSUE TITLE
I am unable to download the pdf file from mobile browser

### ISSUE THREAD

**Issue by khadhar1690** [salesforce-ux/design-system#364]
Hi All,

I am downloading pdf files from web based and it's running in mobile browser it will throws error **"You can't view this page ,because you don't have permissions or because the page is not supported on mobile devices".**
Actually file are put on static resources and we will navigate the static resource file.

Download files could download in web(Laptop) and Couldn't download the files when testing in mobile browser.
Please help me any one known this.

Thanks
Khadhar

**Comment by kaelig** [comment]
Hi @khadhar1690, what PDF of the Lightning Design System website do you get this error with?

**Comment by kaelig** [comment]
Closing this after a lack of context and information.
