### ISSUE TITLE
Left/Right button in a modal

### ISSUE THREAD

**Issue by mekoux** [salesforce-ux/design-system#365]
Is this left/right button in a modal a standard component in SLDS?

I saw these in Sales Cloud Dashboard when I expanded a chart into a modal.
https://drive.google.com/a/salesforce.com/file/d/0B_srHPFyI-W-YXp3dVYwdnFvMUU/view?usp=sharing

**Comment by kaelig** [comment]
Thanks for asking, @mekoux! This is not a standard component in SLDS but you should be able to reproduce this effect using grid utility classes and button icons.
