### ISSUE TITLE
Can I use this CSS to create Cordova Lightning Starter template ?

### ISSUE THREAD

**Issue by wasimbeniwale** [salesforce-ux/design-system#366]
Just curious, is it appropriate that I fork this repository and make some changes to the CSS and use this to create a Cordova template? And upload it as a npm package so that anyone can use it as a starter project.

**Comment by tyrollins** [comment]
You should be fine provided you obey the terms of the licenses. Please pay special attention to the Salesforce Sans Font License, as it appears to be more restrictive than the Sass & Icon licenses.

The Scss source code is licensed under [BSD License Clause 2](https://opensource.org/licenses/BSD-2-Clause) and the icons are licensed under [Creative Commons Attribution-NoDerivatives 4.0](https://creativecommons.org/licenses/by-nd/4.0/). The font is licensed under the Salesforce [Font License](https://lightningdesignsystem.com/assets/licenses/License-for-font.txt) which states - 

"...use the Font solely to create applications with the Salesforce Lightning Design System
that run in Salesforce or on a Salesforce platform (e.g., Lightning, Heroku,
Visualforce) (“Applications”)." 

*note: I do not work for Salesforce & obtained this information from the Salesforce Lightning Design System [download page](https://lightningdesignsystem.com/downloads/).

**Comment by wasimbeniwale** [comment]
Thank you very much @tyrollins  for the font license attention, and yes SF's font license looks very restrictive, I've dropped my idea as the Cordova template will violate their platform terms. Thanks again.
