### ISSUE TITLE
Easy theming using Sass variables

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#369]
Enhancement: actually in scss folder to change primary color or secondary we have a lot of color variable , we can't easy change look and feel of the app! The difference with material design by example is that we define 4 main colors primary secondary lighter darker that's all! and others generated automatically with opacity ! 

What do you think about, how you achieve this requirement ?

**Comment by kaelig** [comment]
Thank you for your question, @istiti. We're looking into it at the moment and can't announce anything yet, but watch this space!

**Comment by kaelig** [comment]
Duplicate of #185
