### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by viveks-m** [salesforce-ux/design-system#37]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'salesforce-ux/design-system' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of /Users/vivekmanoharan/Sites/lightning/package.json
5 verbose readDependencies loading dependencies from /Users/vivekmanoharan/Sites/lightning/package.json
6 silly cache add args [ 'salesforce-ux/design-system', null ]
7 verbose cache add spec salesforce-ux/design-system
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'salesforce-ux/design-system',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'salesforce-ux/design-system',
8 silly cache add   spec: 'github:salesforce-ux/design-system',
8 silly cache add   type: 'hosted',
8 silly cache add   hosted:
8 silly cache add    { type: 'github',
8 silly cache add      ssh: 'git@github.com:salesforce-ux/design-system.git',
8 silly cache add      sshUrl: 'git+ssh://git@github.com/salesforce-ux/design-system.git',
8 silly cache add      httpsUrl: 'git+https://github.com/salesforce-ux/design-system.git',
8 silly cache add      gitUrl: 'git://github.com/salesforce-ux/design-system.git',
8 silly cache add      shortcut: 'github:salesforce-ux/design-system',
8 silly cache add      directUrl: 'https://raw.githubusercontent.com/salesforce-ux/design-system/master/package.json' } }
9 verbose addRemoteGit caching salesforce-ux/design-system
10 verbose addRemoteGit salesforce-ux/design-system is a repository hosted by github
11 silly tryGitProto attempting to clone git://github.com/salesforce-ux/design-system.git
12 silly tryClone cloning salesforce-ux/design-system via git://github.com/salesforce-ux/design-system.git
13 verbose tryClone git-github-com-salesforce-ux-design-system-git-019fd4aa not in flight; caching
14 info git [ 'clone',
14 info git   '--template=/Users/vivekmanoharan/.npm/_git-remotes/_templates',
14 info git   '--mirror',
14 info git   'git://github.com/salesforce-ux/design-system.git',
14 info git   '/Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-019fd4aa' ]
15 verbose mirrorRemote salesforce-ux/design-system git clone git://github.com/salesforce-ux/design-system.git
16 verbose setPermissions salesforce-ux/design-system set permissions on /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-019fd4aa
17 verbose resolveHead salesforce-ux/design-system original treeish: master
18 info git [ 'rev-list', '-n1', 'master' ]
19 error git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
19 error git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
19 error git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
20 silly tryHTTPS attempting to clone git+https://github.com/salesforce-ux/design-system.git
21 silly tryClone cloning salesforce-ux/design-system via git+https://github.com/salesforce-ux/design-system.git
22 verbose tryClone https-github-com-salesforce-ux-design-system-git-176b616a not in flight; caching
23 info git [ 'clone',
23 info git   '--template=/Users/vivekmanoharan/.npm/_git-remotes/_templates',
23 info git   '--mirror',
23 info git   'https://github.com/salesforce-ux/design-system.git',
23 info git   '/Users/vivekmanoharan/.npm/_git-remotes/https-github-com-salesforce-ux-design-system-git-176b616a' ]
24 verbose mirrorRemote salesforce-ux/design-system git clone https://github.com/salesforce-ux/design-system.git
25 verbose setPermissions salesforce-ux/design-system set permissions on /Users/vivekmanoharan/.npm/_git-remotes/https-github-com-salesforce-ux-design-system-git-176b616a
26 verbose resolveHead salesforce-ux/design-system original treeish: master
27 info git [ 'rev-list', '-n1', 'master' ]
28 error git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
28 error git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
28 error git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
29 silly trySSH attempting to clone git@github.com:salesforce-ux/design-system.git
30 silly tryClone cloning salesforce-ux/design-system via git@github.com:salesforce-ux/design-system.git
31 verbose tryClone git-github-com-salesforce-ux-design-system-git-5b98b807 not in flight; caching
32 info git [ 'clone',
32 info git   '--template=/Users/vivekmanoharan/.npm/_git-remotes/_templates',
32 info git   '--mirror',
32 info git   'git@github.com:salesforce-ux/design-system.git',
32 info git   '/Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807' ]
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: Cloning into bare repository '/Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807'...
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: Permission denied (publickey).
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: fatal: Could not read from remote repository.
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807:
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: Please make sure you have the correct access rights
33 error git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807: and the repository exists.
34 verbose stack Error: Command failed: git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807
34 verbose stack Cloning into bare repository '/Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807'...
34 verbose stack Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
34 verbose stack Permission denied (publickey).
34 verbose stack fatal: Could not read from remote repository.
34 verbose stack
34 verbose stack Please make sure you have the correct access rights
34 verbose stack and the repository exists.
34 verbose stack
34 verbose stack     at ChildProcess.exithandler (child_process.js:203:12)
34 verbose stack     at emitTwo (events.js:87:13)
34 verbose stack     at ChildProcess.emit (events.js:172:7)
34 verbose stack     at maybeClose (internal/child_process.js:817:16)
34 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
34 verbose stack     at emitOne (events.js:77:13)
34 verbose stack     at Socket.emit (events.js:169:7)
34 verbose stack     at Pipe._onclose (net.js:469:12)
35 verbose cwd /Users/vivekmanoharan/Sites/lightning
36 error Darwin 14.0.0
37 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "salesforce-ux/design-system"
38 error node v4.1.1
39 error npm  v2.14.4
40 error code 128
41 error Command failed: git clone --template=/Users/vivekmanoharan/.npm/_git-remotes/_templates --mirror git@github.com:salesforce-ux/design-system.git /Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807
41 error Cloning into bare repository '/Users/vivekmanoharan/.npm/_git-remotes/git-github-com-salesforce-ux-design-system-git-5b98b807'...
41 error Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
41 error Permission denied (publickey).
41 error fatal: Could not read from remote repository.
41 error
41 error Please make sure you have the correct access rights
41 error and the repository exists.
42 error If you need help, you may report this error at:
42 error     <https://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]

**Comment by amyleesalesforce** [comment]
Hi Vivek,

How are you trying to install this? What is the command line you typed in and what kind of computer + OS do you have? Are you using a GitHub UI?

We do not have a "master" branch. Our current branch is "winter-16".

**Comment by viveks-m** [comment]
Apologies, I thought i typed in the comment before pasting the debug log. I followed the link and command specified below

https://www.npmjs.com/package/@salesforce-ux/design-system
npm i @salesforce-ux/design-system

I use Mac OS X Yosemite.

**Comment by amyleesalesforce** [comment]
@viveks-m What version of `npm` are you using? I'm using v3.3.4. And I'm on Node.js v4.1.0. I just ran the `npm install` command for the package and it looks fine to me in a test project I created in "/Incoming/b" on my computer:

%
% npm -v
3.3.4
%
% nvm use v4.1.0
Now using node v4.1.0 (npm v3.3.4)
%
% npm install @salesforce-ux/design-system
npm WARN prefer global node-gyp@3.0.3 should be installed with -g

> node-sass@3.3.3 install /Incoming/b/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Incoming/b/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> spawn-sync@1.0.13 postinstall /Incoming/b/node_modules/spawn-sync
> node postinstall


> node-sass@3.3.3 postinstall /Incoming/b/node_modules/node-sass
> node scripts/build.js

` /Incoming/b/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
b@1.0.0 /Incoming/b
└── @salesforce-ux/design-system@0.9.1  extraneous

npm WARN EPACKAGEJSON b@1.0.0 No description
npm WARN EPACKAGEJSON b@1.0.0 No repository field.
%
%

**Comment by viveks-m** [comment]
As in the logs above, its 

2 info using npm@2.14.4
3 info using node@v4.1.1

**Comment by amyleesalesforce** [comment]
Hm. Could we try in a clean repo?

mkdir test
cd test
npm init
npm install @salesforce-ux/design-system

**Comment by mbeard** [comment]
I was able to install via npm successfully.  However, I do not have all directories outlined [here](https://www.npmjs.com/package/@salesforce-ux/design-system#contents).  The icons and images directories are not included.
