### ISSUE TITLE
Web Link loading Issue

### ISSUE THREAD

**Issue by GuptaPathi** [salesforce-ux/design-system#371]
https://www.lightningdesignsystem.com/components/feeds/
This link was not loading properly.
Kindly check and update the issue.

Regards
P S Gupta

**Comment by kaelig** [comment]
Thank you for reporting this, @GuptaPathi!

I'm afraid I couldn't reproduce the issue.

May I ask what operating system / browser you are using?

**Comment by kaelig** [comment]
Closing this as I couldn't reproduce the issue.
