### ISSUE TITLE
Samples of Different Layouts (please)

### ISSUE THREAD

**Issue by andymans** [salesforce-ux/design-system#373]
Samples....they a wonderful new thing :-)

**Comment by kaelig** [comment]
Hi @andymans, thank you for using the Lightning Design System!

Thanks for the feature request. Templates are on our todo list, watch this space!

**Comment by andymans** [comment]
Wonderful news! This is excellent work btw - nice job!

**Comment by kaelig** [comment]
Duplicate of #3
