### ISSUE TITLE
Sketch file

### ISSUE THREAD

**Issue by stevejwikeley** [salesforce-ux/design-system#375]
## First of all thanks for supplying a Sketch file. Was a great start to using the design framework. 

I've got a couple of questions on the development of the file.

- Do you intend to develop the sketch file with all of the components available?
- Will you be updating the symbols so they're in your design framework structure?
- Will the symbols be setup properly?
- Or will this eventually become open source and community driven? ie. Will you add this to the repo and get the community to improve it for you?

My key issues with the file is with the symbol sizing. 

![image](https://cloud.githubusercontent.com/assets/6689692/21935250/be59ae82-d9a4-11e6-8146-7613a2d5af5f.png)

None of the symbols are setup for this.

**Comment by jina** [comment]
Hi @stevejwikeley — this repo might be the more appropriate place to ask. https://github.com/salesforce-ux/design-system-ui-kit — and it's open source! :)

**Comment by stevejwikeley** [comment]
@jina perfect - thanks

![image](http://i.giphy.com/GfAD7Bl016Gfm.gif)
