### ISSUE TITLE
row detail in datatable

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#376]
ENAHCNEMENT : 
Is there or will it be here : row detail of DataTable component ? 
What is the best and correct approach to achieve this ?

**Comment by kaelig** [comment]
Thanks for asking, @istiti!

@tsheiner would know if this feature on our radar. Tim, can you confirm?

**Comment by tsheiner** [comment]
I am not sure what you mean by "row detail of DataTable."

Can you explain the functionality you are seeking?

**Comment by istiti** [comment]
![image](https://cloud.githubusercontent.com/assets/2789203/22141487/97aa8b46-def2-11e6-8a65-526dda5a793b.png)

**Comment by kaelig** [comment]
@srohde this is an interesting feature request, who would be best to advise?

**Comment by jina** [comment]
cc @owenschoppe

**Comment by interactivellama** [comment]
@istiti Is this just another visual format for a column--almost like a hidden column(s)? Is the reason that it is hidden a side effect of the width of the table?

Just trying to understand the request and context.

**Comment by owenschoppe** [comment]
That was Elizabeth Clarke's response as well (she owns tree grid). And I tend to agree, why not just add a column. What's the use case here?

**Comment by FabienTaillon** [comment]
On my side I could see a use case on mobile, to do something like this:
http://fooplugins.github.io/FooTable

![footable](https://cloud.githubusercontent.com/assets/2465122/22501398/dfa51270-e868-11e6-916b-613e82163170.jpg)

**Comment by owenschoppe** [comment]
Interesting way to condense a table on mobile. 

@SiTaggart Would something like this meet a11y specs?

**Comment by SiTaggart** [comment]
I'll admit, I'm not too hot on my table knowledge and Assistive Technology, but I'm fairly sure nested tables are very confusing and are generally avoided. You lose the programmatic relationship between the expansion trigger and the newly expanded row completely in that example.

**Comment by engai** [comment]
@istiti Due to accessibility concerns with the proposed feature request, our team does not plan on adopting this pattern.

Please check out our [Tree Grids](https://www.lightningdesignsystem.com/components/trees/?state=expanded&variant=grid) component which offers something similar to what you're looking for.
