### ISSUE TITLE
ToolTip Positioning

### ISSUE THREAD

**Issue by banderson5144** [salesforce-ux/design-system#377]
https://lightningdesignsystem.com/components/tooltips/ "The tooltip should be positioned with JavaScript." Is there some sort algorithm you can provide to calculate the position?

**Comment by kaelig** [comment]
@banderson5144 thank you for asking!

There isn't a recommended algorithm but I believe the best way is to position tooltips is to put them out of the document's flow (e.g. before `</body>`) and position them depending on the parent's coordinates.

This seems to be a good example for React: https://github.com/react-component/tooltip
