### ISSUE TITLE
slds-scrollable max-height max-width

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#379]
hi I add to my div 

> .slds-scrollable

 but no overflow because this selector class not contains these property in css:
```
max-width:100%;
max-height:100%
```

is this relevant that your 
`scss/utilities/scrollable/flavors/base/_index.scss` file have become: 
```

.#{$css-prefix}scrollable {
  @include scrollbar;
  @include enable-ios-momentum-scrolling;
  overflow: auto;
  max-width:100%; //this 
  max-height:100% //and this
}


```

**Comment by kaelig** [comment]
It is required for implementers to specify dimensions on the scrollable element or its surrounding div (like here: https://www.lightningdesignsystem.com/utilities/scrollable/flavors/vertical/_default.html?iframe&initial).

e.g.

```html
<div class="slds-scrollable" style="height:240px;padding:1rem;">
```

Let us know if that worked out for you!

**Comment by istiti** [comment]
@kaelig yes I know if we specify height it works but when we want height 100%  we can avoid to specify height if we add  here: scss/utilities/scrollable/flavors/base/_index.scss file have become:

```
.#{$css-prefix}scrollable {
  @include scrollbar;
  @include enable-ios-momentum-scrolling;
  overflow: auto;
  max-width:100%; //this 
  max-height:100% //and this
}
```

this works when only  add class 
`slds-scrollable--x this have css max-width:100%;`
`and slds-scrollable--y have max-height:100%;`

Only when I want vertical and horizontal scroll using ".slds-scrollable" this don't have max-height and max-width if you add this we don't need specify height if we want use 100% of disponible space

**Comment by kaelig** [comment]
Merci for the additional explanation. This doesn't seem to be an issue we ran into so far but we'll take it into account if you put a solid use case together!
