### ISSUE TITLE
How to resolve "Unsafe attempt to load URL" ?

### ISSUE THREAD

**Issue by webtop** [salesforce-ux/design-system#38]
When developing in my sandbox and using the SLDS framework, referencing a SVG throws a console error of "Unsafe attempt....".

My developer console will be: https://cs41.salesforce.com/...
And my actual sandbox URL will be: https://c.cs41.visual.force.com/...

I assumed that added a whitelisted CORS URL would resolve this, but it does not. I ASSUME that all will be well in production, but how do I actually know?

Browser: Chrome (latest)
Graphics that fails: <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use> but ALL of them do

Any guidance?

Thanks,
Paul

**Comment by kaelig** [comment]
Closing this as it is 2 months old with no updates in this issue. Feel free to reopen if the problem persists.

**Comment by maximelets** [comment]
Hey guys. Just fyi. When I create a page with API version 42 I facing with this issue.

> Unsafe attempt to load URL https://xxxxx-dev-ed.my.salesforce.com/_slds/assets/icons/utility-sprite/svg/symbols.svg from frame with URL https://xxxxx-dev-ed--csplay1.na50.visual.force.com/apex/ForTestingPage. Domains, protocols and ports must match.

Code attached.
`<apex:page>
    <apex:slds />
    <div xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <div class="slds-media__figure">
        <span class="slds-icon_container slds-icon-standard-contact">
            <svg class="slds-icon slds-icon_small" aria-hidden="true">
                <use xlink:href="{!URLFOR($Asset.SLDS)}/assets/icons/utility-sprite/svg/symbols.svg#office365"></use>
            </svg>
        </span>
    </div>
    </div>
</apex:page>`

**Comment by kishoreramkumar** [comment]
i am also face the same issue
