### ISSUE TITLE
Issue noticed in Salesforce1 with Menus in VF only

### ISSUE THREAD

**Issue by jmanchester41** [salesforce-ux/design-system#382]
We have a customer Case where they have reported using the Menu in Salesforce1 does not work if this is a VF page. Seems to work fine when this is used in a Lightning Component.

Ref:
https://www.lightningdesignsystem.com/components/menus/

Simple repro using the provided example. Clicking the list never makes the dropdown visible. I have this setup in a Dev org and can Email you credentials if this helps speed things up.

**Comment by kaelig** [comment]
Thank you for reporting this, @jmanchester41! I see you are a Salesforce employee - can you please reach out through the internal channels, e.g. on our Lightning Design System Chatter page?
