### ISSUE TITLE
loading label text

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#383]
In this page of guidline [Loading](https://www.lightningdesignsystem.com/guidelines/loading/) we can read:

> If necessary, you can use a text label to communicate what the system is doing, such as “Uploading data …”

But in [Spinners Component](https://www.lightningdesignsystem.com/components/spinners/) there isn't example how to add this text under spinner or something like that.... 

How achieve this correctly? 
 
Many thanks.

**Comment by kaelig** [comment]
Duplicate of #298
