### ISSUE TITLE
.slds-border--top not available in Lightning experience

### ISSUE THREAD

**Issue by dapearce** [salesforce-ux/design-system#384]
I'm developing custom lightning components for use inside of the lightning experience. The `.slds-border` classes does not appear to be available for me. I see that these are from a recent 2.2.x release and, considering I can use other slds classes without `force:slds`, it seems like maybe the organization is not updated to the latest SLDS release. Is there a way to verify what release our organization is referencing, and/or force our organization to use the latest release?

**Comment by kaelig** [comment]
Hi @dapearce, thanks for using the Lightning Design System!

May I ask what version is your org running at the moment (Winter ’17 or Spring ’17)?

**Comment by dapearce** [comment]
I believe Winter '17 but I'm not sure how I confirm that? Is there a way to trigger the update?

**Comment by kaelig** [comment]
@dapearce Spring ’17 will be available to all Salesforce customers in the next few weeks.

In the mean time, you may refer to the archived version of the design system for Winter ’17 here: https://www.lightningdesignsystem.com/downloads/#archives
