### ISSUE TITLE
Unable to have multiple drop downs in a button group

### ISSUE THREAD

**Issue by nelsonra** [salesforce-ux/design-system#385]
I can't have multiple drop downs or position a drop down anywhere in the button group. See Example here:

<img width="282" alt="multiple_drop_down_example" src="https://cloud.githubusercontent.com/assets/7580950/22469194/0f470fca-e7c3-11e6-8369-b62ecd895c20.png">

  ```
<div class="slds-button-group" role="group">
    <button class="slds-button slds-button--neutral">Refresh</button>
    <button class="slds-button slds-button--neutral">Edit</button>
<div class="slds-dropdown-trigger slds-dropdown-trigger--click slds-button--last">
      <button class="slds-button slds-button--icon-border-filled" aria-haspopup="true" title="Show More">
        <svg class="slds-button__icon" aria-hidden="true">
          <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
        </svg>
        <span class="slds-assistive-text">Show More</span>
      </button>
      <div class="slds-dropdown slds-dropdown--right">
        <ul class="slds-dropdown__list" role="menu">
          <li class="slds-dropdown__item" role="presentation">
            <a href="javascript:void(0);" role="menuitem" tabindex="0">
              <span class="slds-truncate">Overflow Item One</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <button class="slds-button slds-button--neutral">Save</button>
    <div class="slds-dropdown-trigger slds-dropdown-trigger--click slds-button--last slds-is-open">
      <button class="slds-button slds-button--icon-border-filled" aria-haspopup="true" title="Show More">
        <svg class="slds-button__icon" aria-hidden="true">
          <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
        </svg>
        <span class="slds-assistive-text">Show More</span>
      </button>
      <div class="slds-dropdown slds-dropdown--right">
        <ul class="slds-dropdown__list" role="menu">
          <li class="slds-dropdown__item" role="presentation">
            <a href="javascript:void(0);" role="menuitem" tabindex="0">
              <span class="slds-truncate">Overflow Item One</span>
            </a>
          </li>
          <li class="slds-dropdown__item" role="presentation">
            <a href="javascript:void(0);" role="menuitem" tabindex="-1">
              <span class="slds-truncate">Overflow Item Two</span>
            </a>
          </li>
          <li class="slds-dropdown__item" role="presentation">
            <a href="javascript:void(0);" role="menuitem" tabindex="-1">
              <span class="slds-truncate">Overflow Item Three</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
```

I would like to be able to do something similar to this:
<img width="178" alt="icon_group_example" src="https://cloud.githubusercontent.com/assets/7580950/22469397/c9c5deee-e7c3-11e6-87a9-ce7c99b529bc.png">

```
<div class="slds-button-group" role="group">
  <button class="slds-button slds-button--icon-border" title="Charts">
    <svg class="slds-button__icon" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#chart"></use>
    </svg>
    <span class="slds-assistive-text">Charts</span>
  </button>
<button class="slds-button slds-button--icon-more" aria-haspopup="true" title="More Actions">
    <svg class="slds-button__icon" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#settings"></use>
    </svg>
    <svg class="slds-button__icon slds-button__icon--x-small" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
    </svg>
    <span class="slds-assistive-text">Settings</span>
  </button>

  <button class="slds-button slds-button--icon-border" title="Filter List">
    <svg class="slds-button__icon" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#filterList"></use>
    </svg>
    <span class="slds-assistive-text">Filter List</span>
  </button>
  <button class="slds-button slds-button--icon-more" aria-haspopup="true" title="More Actions">
    <svg class="slds-button__icon" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#settings"></use>
    </svg>
    <svg class="slds-button__icon slds-button__icon--x-small" aria-hidden="true">
      <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
    </svg>
    <span class="slds-assistive-text">Settings</span>
  </button>
</div>
```

**Comment by kaelig** [comment]
Ideally, dropdowns should be positioned using JavaScript. This would allow you to build what you want as the dropdown menu markup would be put outside of the flow (e.g. before `</body>`).

**Comment by nelsonra** [comment]
@kaelig thanks for the reply but I am not concerned with positioning of the dropdown. 

Maybe I am not clear in describing the issue.

I would like to be able to use the dropdown (slds-dropdown-trigger) in a button group. This can't be done if the dropdown is somewhere in the middle of the button group.

**Comment by kaelig** [comment]
@nelsonra oh, I see!

Have you tried taking off `slds-button--last` from the first dropdown?

**Comment by nelsonra** [comment]
Hi @kaelig,

Using slides-button--last didn't help.

However I see there is a button group list coming down the line : https://www.lightningdesignsystem.com/components/button-groups/#flavor-list-button-group-more-open

Do you have an ETA when this feature will be released?

The button group list option seems to do what I want and the dropdown works as expected:

![screen shot 2017-02-20 at 09 34 33](https://cloud.githubusercontent.com/assets/7580950/23119389/f0391226-f74f-11e6-8dce-5ac430aef219.png)


`<ul class="slds-button-group-list">
    <li>
      <button class="slds-button slds-button--neutral">Refresh</button>
    </li>
    <li>
      <button class="slds-button slds-button--neutral">Edit</button>
    </li>
    <li>
      <div class="slds-dropdown-trigger slds-dropdown-trigger--click slds-button--last">
        <button class="slds-button slds-button--icon-border-filled" aria-haspopup="true" title="Show More">
          <svg class="slds-button__icon" aria-hidden="true">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
          </svg>
          <span class="slds-assistive-text">Show More</span>
        </button>
        <div class="slds-dropdown slds-dropdown--right">
          <ul class="slds-dropdown__list" role="menu">
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="0">
                <span class="slds-truncate">Overflow Item One</span>
              </a>
            </li>
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="-1">
                <span class="slds-truncate">Overflow Item Two</span>
              </a>
            </li>
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="-1">
                <span class="slds-truncate">Overflow Item Three</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </li><li>
      <button class="slds-button slds-button--neutral">Save</button>
    </li>
    
  <li>
      <div class="slds-dropdown-trigger slds-dropdown-trigger--click slds-button--last slds-is-open">
        <button class="slds-button slds-button--icon-border-filled" aria-haspopup="true" title="Show More">
          <svg class="slds-button__icon" aria-hidden="true">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#down"></use>
          </svg>
          <span class="slds-assistive-text">Show More</span>
        </button>
        <div class="slds-dropdown slds-dropdown--right">
          <ul class="slds-dropdown__list" role="menu">
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="0">
                <span class="slds-truncate">Overflow Item One</span>
              </a>
            </li>
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="-1">
                <span class="slds-truncate">Overflow Item Two</span>
              </a>
            </li>
            <li class="slds-dropdown__item" role="presentation">
              <a href="javascript:void(0);" role="menuitem" tabindex="-1">
                <span class="slds-truncate">Overflow Item Three</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </li></ul>`
