### ISSUE TITLE
Error accessing SLDS

### ISSUE THREAD

**Issue by alvinfromhawaii** [salesforce-ux/design-system#386]
When accessing site via chrome on Mac I get this error.
<img width="726" alt="screen shot 2017-02-01 at 10 15 02 am" src="https://cloud.githubusercontent.com/assets/4428172/22520183/3025018e-e868-11e6-811e-2efba7a57991.png">

**Comment by kaelig** [comment]
Hi,

We don't have an https certificate for this URL yet. However, http://www.getslds.com should work!

**Comment by engai** [comment]
Hi @alvinfromhawaii, I believe this has been resolved as I am no longer able to reproduce the issue.

Closing this, but feel free to reopen and comment as needed.
