### ISSUE TITLE
separate icon svg (no sprite)

### ISSUE THREAD

**Issue by JurajVajda** [salesforce-ux/design-system#389]
It would be great to have separate icon svg's so we can create font collection out of them and be more flexible in front-end also this way. Current svg icons approach is not working with dynamically rendered svg's and have more challenges then fonts would have. Is possible to provide separate svg files/icons or the whole icon fonts collection ?

**Comment by kaelig** [comment]
Thanks for using the design system, @JurajVajda!

Two things:

1. The icon font was removed from the design system - however you can build an icon font yourself using the individual SVG sources.
2. Individual SVGs are available in:
  - The design system downloadable zip file (see https://www.lightningdesignsystem.com/downloads/)
  - The `@salesforce-ux/design-system` npm package
  - The `@salesforce-ux/icons` npm package

Hope this helps.

**Comment by JurajVajda** [comment]
1. yes that is what i would like to achieve but need the individual svg files - not a sprites
2. 
- the design system zip file have individual png files but not svg (still sprites)
- @salesforce-ux/icons points me to non-existing repository https://github.com/salesforce-ux/icons.git
- @salesforce-ux/design-system is also not containing individual svg files

**Comment by kaelig** [comment]
> FYI: @salesforce-ux/design-system is pointing to non-existing repository

Not sure what you ran into. These both seem to work:

- https://www.npmjs.com/package/@salesforce-ux/design-system
- https://github.com/salesforce-ux/design-system

**Comment by JurajVajda** [comment]
Sorry i meant this one git clone https://github.com/salesforce-ux/icons

**Comment by kaelig** [comment]
Oh right, this is expected as repository is private.

**Comment by JurajVajda** [comment]
ok, well since we can downloaded it from (https://www.lightningdesignsystem.com/downloads/) then its ok, thanks again
