### ISSUE TITLE
Notifications/Toast Messages in Salesforce1 app.

### ISSUE THREAD

**Issue by chriswoolcott** [salesforce-ux/design-system#39]
Hi There

I have used Toast Messages for various notifications in my app (VF page with JS remoting using SLDS), this all works fine in the browser, but in the Salesforce1 app the alerts appear at the top of the document regardless of where on the page the user is currently scrolled.

I assume this is due to the way the pages are framed in, as I've had problems with this in SF1 app before, just wondering if their are any suggested workarounds?

Cheers
Chris

**Comment by srohde** [comment]
Can you please add a screenshot to clarify?

**Comment by chriswoolcott** [comment]
![img_0142](https://cloud.githubusercontent.com/assets/848705/10295310/96a9f96c-6c0b-11e5-8783-2394800f6d4f.PNG)

**Comment by sdruckerfig** [comment]
Try throwing a force:showToast event in S1 instead of using SLDS.

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/events_one.htm

**Comment by stefsullrew** [comment]
@chriswoolcott - Does @sdruckerfig's fix work for you? Or do you have further questions for us?

**Comment by chriswoolcott** [comment]
Thank you @sdruckerfig, I got pulled on to another project so haven't had a chance to review yet, but certainly looks like this will do the trick.

**Comment by stefsullrew** [comment]
I'm going to close this for now. Let us know if you come into problems. Cheers.
