### ISSUE TITLE
Icon Request: Message Read Icon

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#392]
In the vain of other icon requests, may I suggest a read message/email Icon. The existing email icons all show a closed message. I don't see a good "Read" state icon. Further to this there is already a "mark all as read" icon, but nothing really to mark individual listings as having been opened/read. 

I should add their already is a open_folder and companion opened_folder. This sort of works but feel very different from something that would target opened/read messages (or emails). 

My two cents would probably suggest something along the lines of an open envelope design (similar to the existing email utility icon)

**Comment by kaelig** [comment]
Thank you for the request, I'll forward it to our design team.
