### ISSUE TITLE
Suggestion: Compound Fields

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#393]
I'd like to suggest a form layout design for compound fields. A Good use example would be Height where you have select or input for Foot and Inches separate from each other. Both of these fields would be under the same Field Label (Height in the example) and I would expect to be under the same slds-form-element__control. Another good use case would be for form fields that allow for multi-unit types, for example travel distance where the form would also for selection of Mi/KM. The currently designed input with fixed Text works well for static unit types (ie all inputs are of type Miles) but doesn't seem to really be designed around allow for the selection of unit types. 

We are currently achieving this though the use of an inline that is sandwich between compound forms but its the cleanest solution.  We are happy to provide a suggested PR as starting point if that would help.

**Comment by kaelig** [comment]
Thank you for the feature request, we'll look into it. Could you show a prototype of how you're currently achieving this?

e.g. by building a quick prototype using the Starter Kit (that you can host for free on Heroku)? https://github.com/salesforce-ux/design-system-starter-kit
Let me know if you need any help setting it up.

**Comment by JohnHeadIV** [comment]
Here is a possible sample. This is based upon one of our actual modals. (Removed a bunch of other fields in order to simplify) But you can see 2 types of "compound" fields we use, Height with separate In/Ft fields and Weight which allows for unit selection. The Height uses two separate input fields.
 
From a UI perspective it makes sense that both of these are under the "Height" label with the use of the fixed Addon to add the In/Ft marker. Having to break this up into separate fields seem very ugly and unnecessary.  The unit selection also seems a very logical construction. No separate Label is required for the units select. The sample includes a lbs/Kg/Stone example but this could also be a currency switcher as well. 

This example uses a much of the base classes but does need some more to size correctly. (We do this currently on an ad-hoc basis, but are happy to submit PR if will help) 

This may require some more back-end java-script to handle the dual field nature but that would clearly be something outside SLDS. 

https://fms-sldstesting.herokuapp.com/compoundinputExample.html

As a side note, compound fields are one of our end users biggest issues with the current native layouts as it hard to make sure that both parts are completed.

**Comment by kaelig** [comment]
Thanks a lot for the prototype, that's awesome and gives us a much better view inside your use case.

I've asked @srohde about what would be the best course of action and he'll get back to you.

**Comment by JohnHeadIV** [comment]
Now that lightning:inputName and lightning:inputAddress are added. Would is be possible to add their styling/component to the SLDS. I would suggest the compound field component be addresses in general with Name/Address being Samples.
