### ISSUE TITLE
slds-align-middle on ie11 only

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#394]
I use `slds-align-middle` and on chrome/firefox/edge are good

but in ie11 strange behavior:
![slds middle](https://cloud.githubusercontent.com/assets/2789203/22784898/31a247cc-eed2-11e6-876a-1790d189211b.PNG)

**Comment by kaelig** [comment]
Thank you for reporting this @istiti. Could you please create some example code / a reduced test case reproducing this issue so we can investigate?

**Comment by istiti** [comment]
@kaelig of course here you are: http://plnkr.co/edit/TheIZ9pMIBBtwuUvKl3B?p=preview
with firefox/chrome/erdge  **it's ok** but with  ie11 not very nice display too tiny

**Comment by kaelig** [comment]
Merci !

I'm not entirely sure why the class `slds-align-middle` is in there, however if you use `slds-col slds-grow` on the same element it should work in IE11.

Closing this, let me know if you require further help on this!

**Comment by istiti** [comment]
@kaelig you mean http://plnkr.co/edit/7UCR5bOoxVgRO1Km4riP?p=preview ? same behavior on ie11 

and the reason I use slds-align-middle is that I need to put my content in the middle vertically and horizontally, any better way to achieve this ? ^ and here you are ... it is aligned in the middle but not works on ie11 http://plnkr.co/edit/2SKsjBP7p0Gmpe9yazLS?p=preview

**Comment by kaelig** [comment]
SLDS doesn't support IE11 anymore. Sorry if my workaround doesn't work in your code (as per my tests it worked). However if you find a workaround please post it here!

**Comment by istiti** [comment]
@kaelig ok thanks, then can you update browser support here 
https://www.lightningdesignsystem.com/faq/#what-browsers-are-supported

**Comment by JohnHeadIV** [comment]
How does this then related to SLDS's use in Napili based templates for Communities?

**Comment by kaelig** [comment]
@istiti: I should have been more specific: we are dropping support for IE11 slowly until December. Starting in December, the design system will completely stop supporting IE11.
