### ISSUE TITLE
<apex:slds /> on API 39 sandbox loads version 2.1.2

### ISSUE THREAD

**Issue by dcinzona** [salesforce-ux/design-system#395]
I understood that `<apex:slds />` would load the latest version of the slds VF stylesheet, but it appears to load version 2.1.2 on our sandbox which is on Spring '17 preview.

Is the the expected behavior? Several components / rules are missing between 2.1.2 and 2.2.1 (which is what https://www.lightningdesignsystem.com/ is using)

```
<apex:page showHeader="false" sidebar="false" standardStylesheets="false">
    <apex:slds/>
    <div class="slds-border--bottom">
      <p>This should have a bottom border</p>
    </div>
</apex:page>
```
Screenshot:
![screen shot 2017-02-09 at 11 07 10 am](https://cloud.githubusercontent.com/assets/52411/22791600/f3a3f020-eeb7-11e6-9af4-a2dc6926dd4e.png)

![screen shot 2017-02-09 at 11 08 25 am](https://cloud.githubusercontent.com/assets/52411/22791677/337ff3ce-eeb8-11e6-92be-b62a8eef15ff.png)

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and for reporting this, @dcinzona.

We're investigating - I'll keep you posted on this.

**Comment by tadeuszhyzy-abb** [comment]
Hi there, in my case <apex:slds /> adding SLDS in version 2.2.1 but newest version is 2.3.0. Maybe we could get additional params inside <apex:slds />. Something like this <apex:slds version="2.3.0" /> so that we could stay stable even if salesforce updated slds.

**Comment by anurag-m** [comment]
Hi there, I am getting an error when the code is executing future method calling .getContentAsPDF(). Now the page it is getting as pdf has apex:slds tag which provides the required SLDS CSS on the page. This was working pre Summer 17 but post the release it has been failing with the following error message.

First error: [UNKNOWN_EXCEPTION] Failed on parsing CSS sheet at https://cs6.salesforce.com/apexpages/slds/latest/assets/styles/salesforce-lightning-design-system-vf.min.css

Version is "2.3.0" and even after changing the page's API to 40.0, it not fix the error.

**Comment by ihabo01** [comment]
I have the exact same problem.

If I try to generate a pdf from a visualForcePage that has the the <apex:slds />  the error Failed on parsing CSS Sheet at...throws the exact error mentionned above.

Can somebody points us towards a solution please?

Objective is to be able to style a custom visualforce page using SLDS.

Many thanks

**Comment by Dottenpixel** [comment]
@dcinzona @tadeuszhyzy-abb 
Try updating the API version on your Visualforce page to 42 or 43 (Summer '18). The SLDS version of the CSS imported with is currently set to v2.3 for pages with API versions up through 41. From API v42 and above, the latest SLDS CSS version is served.

@anurag-m @ihabo01 
We'll alert the appropriate team about the PDF generation errors with Visualforce pages with `<apex:slds>`.
