### ISSUE TITLE
Typo on this page (missing apostrophe)

### ISSUE THREAD

**Issue by tvjames2007** [salesforce-ux/design-system#4]
http://www.lightningdesignsystem.com/components/activity-timeline/#role=regular&status=all

"The activity timeline displays each of the users upcoming, current, and past activities"

Typo (missing apostrophe).  Depending on intent, should be 

a. "The activity timeline displays each of the users' upcoming, current, and past activities"
or
b. "The activity timeline displays each of the user's upcoming, current, and past activities"

**Comment by aputinski** [comment]
Fixed in 0f827f304bf9ac1939d370708ae239d64cfd2689
