### ISSUE TITLE
add sidenav

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#400]
Bonjour!

Donno your list planned  for furthur component. I think a good feature will be "sidenav"

if you think about mobile design, this is geat feature 

fyi: https://material.angularjs.org/latest/demo/sidenav

**Comment by kaelig** [comment]
Thank you for your feature request, @istiti!

**Comment by akcorp2003** [comment]
I definitely agree this is a great idea. Not only for mobile, but also for desktop browsers. Right now, I have to implement my own and it gets clunky needing to shift some elements around manually.

**Comment by istiti** [comment]
what about this? asked 6 months ago?!?! @kaelig

**Comment by engai** [comment]
Hi @istiti & @akcorp2003, I believe this has been resolved with https://github.com/salesforce-ux/design-system/commit/1278531a297496678c3be825795c31bd96d1ee85
