### ISSUE TITLE
Valid Input Styling?

### ISSUE THREAD

**Issue by akcorp2003** [salesforce-ux/design-system#401]
Is there a CSS styling for a valid input? 

Currently, there is a styling for error field [input error](https://www.lightningdesignsystem.com/components/forms/#flavor-input-input-error). However, I would like a style where the input box is surrounded with green, similar to the input error. This is to give feedback to the user that they have inputed correct information.

**Comment by istiti** [comment]
For me if it isn't in error mode that meaninout it OK

**Comment by akcorp2003** [comment]
@istiti That's definitely true. But would a visual green be more impactful to a user?

**Comment by istiti** [comment]
Donno maybe yes when requestin ajax...i'm divided, can an ux expert tell something about this?

**Comment by akcorp2003** [comment]
Yeah, I don't know what's the best design. A UX expert input would be appreciated!

**Comment by JohnHeadIV** [comment]
I think there are good use cases for a "valid" input styling. I would argue that the default use of no styling = valid should be used in most cases for simplicity. That being said, I would think "valid" styling would be helpful in cases were validation is intentionally held until then end of user input. An example of this would be confirmation boxes. Telling a user that the email they are in the middle of typing doesn't match seems annoying and counter productive. At the same time, you need a way to signify that the emails do match upon completion. This could be done with a check box icon and slds-form-element__addon but this seems counter to invalid being displayed via bordering and color. 

 Is this something what was being described? 

![image](https://cloud.githubusercontent.com/assets/18658298/23168320/c5b65c2c-f815-11e6-8540-4c669e8c31f1.png)

**Comment by akcorp2003** [comment]
Yeah! That's exactly what I'm imagining that SLDS could include!

**Comment by kaelig** [comment]
Thank you for asking, @akcorp2003, and thank you for using the Lightning Design System!

I'm marking this as a feature request and will notify the team about it.

**Comment by JohnHeadIV** [comment]
Are PR being accepted on this? Or are all on hold?

**Comment by kaelig** [comment]
I'll let @srohde answer this question!
