### ISSUE TITLE
_design_tokens.scss can no longer be imported via sass-resouces loader

### ISSUE THREAD

**Issue by gpascale** [salesforce-ux/design-system#404]
Sometime between version 2.1.3 and the current version, the contents of _design-tokens.scss were changed such that it is now doing a bunch of relative imports of other files, whereas before it was a simple list of tokens.

This has the effect that it can no longer be included via the sass-resources loader in webpack - a loader which automatically loads given scss files into any file in your project - because that loader doesn't work with imports. This may not seem like a big deal, but a list of commonly used tokens exactly the kind of file you'd like to always have available without constantly having to import, so projects using webpack are likely to run into this issue.

https://github.com/shakacode/sass-resources-loader

**Comment by kaelig** [comment]
Thanks for bringing this to our attention. Could you build a project showing it in action so we can look into it more closely?
