### ISSUE TITLE
Weird box-shadow on slds-button

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#405]
The `.slds-button` which is suppose to be the reset style for button adds a weird box-shadow when the button is clicked (":focus").

<img width="152" alt="screen shot 2017-02-24 at 4 36 11 pm" src="https://cloud.githubusercontent.com/assets/67904/23326095/6bbbacd0-faaf-11e6-97cc-745c411d774a.png">

**Comment by kaelig** [comment]
Hi @3den, this outline is there for accessibility, as keyboard users need to have a focus indicator at all times.
