### ISSUE TITLE
Request lightning-design-system docs to be available as a dash docset or on devdocs

### ISSUE THREAD

**Issue by sudhirjena** [salesforce-ux/design-system#406]
I have been using lightning design system in various prototypes. One of the main issue I face is of referencing docs. While the docs are well documented, the same is not available for offline download in tools like dash app or devdocs.io. This leads to opening up the browser everytime you want to refer something on lightning design system and navigating a huge tree of sub pages.

Is there any possibility of publishing the docs as a docset on dash app or on devdocs.io?

**Comment by kaelig** [comment]
This is a great request, thank you @sudhirjena! We'll be putting this under consideration.

**Comment by sudhirjena** [comment]
Thanks @kaelig for considering this as a feature-request. Atleast this should be a good feature to give SLDS a visibility in dash app or devdocs.io at par with Bootstrap or Foundation.
