### ISSUE TITLE
SVG Icon Component Helper still visible on purpose ?

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#407]
In the [Lightning Component section](https://www.lightningdesignsystem.com/platforms/lightning/), the doc now recommends using `lightning:icon` base component:
_The Design System uses SVG icons. You can use them in your Lightning components by using one of the new Base Lightning Components called lightning:icon._

The SVG Icon Component Helper isn't available in the left menu anymore, but is still available on the search bar. Is it on purpose ?

<img width="441" alt="svghelper" src="https://cloud.githubusercontent.com/assets/2465122/23362178/cd9d015a-fcf4-11e6-8215-de1d70883a53.png">

**Comment by kaelig** [comment]
Merci Fabien for asking. We've discovered that this content is linked to from multiple sources so we didn't remove it but we'll definitely have to update it to reflect the latest best practices.

**Comment by kaelig** [comment]
I added a deprecation warning at the top of [the svg helper page](https://www.dropbox.com/s/t1w4e2m48s6k23d/Screenshot%202017-04-26%2014.04.10.png?dl=0) a while ago and forgot to follow up on that.

![screenshot 2017-04-26 14 04 10](https://cloud.githubusercontent.com/assets/85783/25456930/3bdca1ae-2a89-11e7-988d-4c0d63508e5c.png)

Thanks again for reporting this!

**Comment by JohnHeadIV** [comment]
Is lightning:icon now fully functional across all Salesforce platforms? I
know for a while it didn't work in communities (believe since fixed). I
would ask for this to stay up if there platforms( lightning out, lightning
for vf...) that have issues with lightning:icon.

**Comment by kaelig** [comment]
That's a good point, thank you for raising it!

ping @ishakasliwal

**Comment by FabienTaillon** [comment]
@JohnHeadIV FYI there is also the need for an `iconClass` attribute in `lightning:icon`, as discussed [here]( https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009NQx&fId=0D53A000031jrZX). But that's not on the SLDS team side.
