### ISSUE TITLE
Position:fixed does not work in lightning component

### ISSUE THREAD

**Issue by yaoyiyao** [salesforce-ux/design-system#408]
When trying to fixed A `<div>` at bottom of screen, normally we set `position: fixed`  to make it happen. But in the lightning component, this way doesn't work properly but display the `div` at the bottom of the body.

**Comment by FabienTaillon** [comment]
@yaoyiyao I've used `position: fixed` in Lightning Components and it works fine (except in Salesforce1).

If your question is more related to Lightning Component than Lightning Design System, you should ask it on [StackExchange](http://salesforce.stackexchange.com/). Add some code sample to help us reproduce, and I'll have a look.

**Comment by kaelig** [comment]
Thank you @yaoyiyao for using the Lightning Design System and for reporting this.
(and thanks @FabienTaillon for chipping in!)

As Fabien mentioned, a code example and steps to reproduce the issue would be welcome so we can look into the issue more closely.

**Comment by mvcmania** [comment]
Are there any update on this issue?

**Comment by engai** [comment]
Hi @yaoyiyao, were you able to resolve this in the StackExchange?

**Comment by sangryal** [comment]
Any update on this issue?
