### ISSUE TITLE
Select with [size] followup

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#41]
I saw your solution to #17 in 0.9.2

just to note that 
```
  &[size] {
    ....
    option {
      padding: $spacing-x-small;
    }
  }
```
- the actual select layout _height_ depends on how many options there are 
(e.g. with size=4 and two selects side-by-side the height is different, if the first contains 3 and the second has 4 options)
- causes the select list and window to resize/re-render, when fewer as the [size] options are displayed (e.g. dynamically setting/removing options)

the options I think are either
- calculating/setting the height in px of the **select** element based on the [size] value
- remove the padding as the (mobile) browser handles it natively (my suggestion)

**Comment by jorgjanke** [comment]
... as attr() in calc() does not work, seems one has to set the height manually.

**Comment by stefsullrew** [comment]
We have sizing classes on their way in a later release. I'm going to close this for now. Cheers!
