### ISSUE TITLE
Maybe animations?

### ISSUE THREAD

**Issue by ku8ar** [salesforce-ux/design-system#412]
Do you plan to add transitions, which will work with slds-show and slds-hide classes?

**Comment by kaelig** [comment]
Great question, thanks for asking! We're definitely looking at animations and how to integrate them as part of the CSS Framework but have no specific timeline on that front.

**Comment by ku8ar** [comment]
It is a pity that this is distant future :( Apart from "position: fixed" in table headers, keyframes are the only CSS, which practically I'm adding to the code in every app...
