### ISSUE TITLE
Cards have unnecessary margin?

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#413]
I have no custom CSS. I've made a card component. When I have multiple of the components together, this happens.

![screen shot 2017-03-03 at 5 11 22 pm](https://cloud.githubusercontent.com/assets/1011888/23574594/b3846310-0034-11e7-8bcb-2c15bbe59e95.png)

This is caused by

![screen shot 2017-03-03 at 5 11 34 pm](https://cloud.githubusercontent.com/assets/1011888/23574599/c3c9ff14-0034-11e7-93c6-6515ae67908e.png)

Why does that extra margin get applied when more than one card is next to each other?

**Comment by kaelig** [comment]
Thanks for asking, have you considered putting those cards in grid columns instead?

**Comment by tylerzika** [comment]
They are, I think...

```
        <div className="slds-grid slds-wrap slds-grid--pull-padded">
          <NewSurveyCard />
          <SurveyCard />
          <SurveyCard />
          <SurveyCard />
          <SurveyCard />
          <SurveyCard />
        </div>
```

**Comment by kaelig** [comment]
Thanks, is each card inside an `slds-col`?

**Comment by tylerzika** [comment]
oh they are not. Let me try that out.

**Comment by tylerzika** [comment]
I'm using this https://lightningdesignsystem.com/components/utilities/sizing/#flavor-widths-two-column

`slds-size`

![screen shot 2017-03-07 at 10 37 48 am](https://cloud.githubusercontent.com/assets/1011888/23672011/27b6b298-0322-11e7-840a-ffe03aef332d.png)

It's working out nicely. I'm having a hard time making a unique card to create surveys.

**Comment by kaelig** [comment]
Awesome, looks good! If you have additional questions, maybe ask the developer community? Someone probably can help you achieve these advanced layouts.
