### ISSUE TITLE
Lookup component uses multiple nodes with the same ID

### ISSUE THREAD

**Issue by mk0x9** [salesforce-ux/design-system#414]
I was studying [Lookup element] and noticed that there are two elements with the same id `lookup-65`: input and `div.slds-lookup__menu`. Is this is a typo?

[Lookup element]: https://www.lightningdesignsystem.com/components/lookups/#flavor-single-default

**Comment by kaelig** [comment]
Hi @mk0x9, this is definitely an error.

This will be fixed in the Summer ’17 documentation (SLDS 2.3.0).
