### ISSUE TITLE
Modular lodash?

### ISSUE THREAD

**Issue by evgenyrodionov** [salesforce-ux/design-system#415]
Hey, guys, I see you import lodash entirely.
I can make PR where I replace all `import _ from 'lodash'` to import lodash's modules: `import isArray from 'lodash/isArray'`.

It will dramatically reduce bundle size.

**Comment by kaelig** [comment]
Thanks for proposing some help!

I couldn't find an example of lodash being imported in full on the client. We only do that on our server side pages, unless I've missed something?

**Comment by evgenyrodionov** [comment]
I talking about future (?) React-components like [Tabs](https://github.com/salesforce-ux/design-system/blob/master/ui/components/tabs/index.react.jsx)

**Comment by kaelig** [comment]
Oh, those are server-side rendered so importing lodash in full doesn't impact the bundle size. 

Thanks again!

**Comment by evgenyrodionov** [comment]
I see, thanks. 
By the way, will you develop react components based on your design system? If not, can I made unofficial version?

**Comment by kaelig** [comment]
This is something we're looking at, and there already are some unofficial versions but suit yourself!

**Comment by bondz** [comment]
@evgenyrodionov an official react components will be really cool. Have you seen [react-lightning-design-system](https://github.com/mashmatrix/react-lightning-design-system)?

**Comment by evgenyrodionov** [comment]
@bondz looks pretty good, will dig into
