### ISSUE TITLE
slds-form--compound--horizontal does not exist

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#419]
Am I right class [.slds-form--compound--horizontal](https://www.lightningdesignsystem.com/components/forms/#description-components-forms-compound-form)  not exist on design

**Comment by kaelig** [comment]
That's correct, good catch!

**Comment by istiti** [comment]
How can we controbute to slds scss?

Cc @kaelig

**Comment by engai** [comment]
Hi @istiti, this has been resolved. The correct class name is `slds-form_horizontal` 

For more info, see https://www.lightningdesignsystem.com/components/form-element/#Horizontal
