### ISSUE TITLE
Documentation demo responsive size options include a duplicative active class that remains even if not the current screen size selected

### ISSUE THREAD

**Issue by geebru** [salesforce-ux/design-system#428]
The default selected screen size (typically Large) includes two classes that do the same thing: `slds-active` and `slds-is-active`. It appears the dynamic class should be `slds-is-active` but since `slds-active` is hard-coded on the default option, it remains selected regardless of which screen size you're viewing.

Removing `slds-active` from these demos would properly indicate which screen size is being demoed.

**Initial state**:
![Initial demo load state](https://cl.ly/0T1S3Y1d3W0I/Screen%20Shot%202017-03-17%20at%2010.59.43%20AM.jpg)

**Interacted state**:
![Interacted demo state](https://cl.ly/021F340R1F28/Screen%20Shot%202017-03-17%20at%2010.59.51%20AM.jpg)

**Comment by ishakasliwal** [comment]
Thank you for reporting this, we'll look into it.
