### ISSUE TITLE
Should button icons change color when the button is disabled?

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#43]
It seems like any button icon's color should match the text color IF the button is disabled. Is the intent to have the icon be the same blue all of the time?

**Comment by stefsullrew** [comment]
Yes, it should. And when I test it, it does. Can you show me a case where this doesn't happen so I can see what's going on?

**Comment by kevinberonilla** [comment]
Currently messing around with the CSS framework here (running 0.9.2): https://dl.dropboxusercontent.com/u/43912228/_TO/app/prototype-lightning/prototype_view-applicants.html

![screen shot 2015-10-08 at 3 34 12 pm](https://cloud.githubusercontent.com/assets/8738640/10379067/24d7299a-6dd2-11e5-956f-50dc5f1b0552.png)

**Comment by stefsullrew** [comment]
Ahhh, good catch. I tested on a button using slightly different markup. Thanks, I'll fix this. It should make the next release.

**Comment by stefsullrew** [comment]
Ahhh, I just realized this was fixed with an update I did for a different bug this week (using the currentColor value). I'm going to close this one and you'll have what you need in the next release.
