### ISSUE TITLE
slds-text-align--justify

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#431]
We already have the classes to for some text alignments (left, right, center) but seems like we are missing one for justify. 

Can we add `slds-text-align--justify`?

**Comment by jina** [comment]
It's not missing. We don't offer it because it's bad for usability/readability.

**Comment by jina** [comment]
Resources:
https://mrwweb.com/no-justification-dont-use-right-center-and-full-justification-on-the-web/
https://dmjcomputerservices.com/blog/why-you-shouldnt-align-html-justify/
https://www.quora.com/Why-is-justified-text-alignment-so-rare-on-the-web
