### ISSUE TITLE
Kanban View

### ISSUE THREAD

**Issue by madmax983** [salesforce-ux/design-system#432]
The Kanban View in Lightning Experience is awesome. It also appears to be made up of many different parts of SLDS, but tweaked slightly to work in that view (Grid, Process, Cards). 

This is a request to add the kanban view as a component in the SLDS proper.

**Comment by ishakasliwal** [comment]
Thank you for reporting this, we'll look into it.

**Comment by elvisbegovic** [comment]
@ishakasliwal thanks for lookin into it
