### ISSUE TITLE
What files do I need from the contents?

### ISSUE THREAD

**Issue by akcorp2003** [salesforce-ux/design-system#435]
I downloaded the SLDS design system and all its contents. This includes the assets, design-tokens, scss, and swatches folders. 

I'm only using the style sheets and a few icons in the assets folder. I don't want to carry around the entire SLDS folder. What can I delete without breaking dependencies?

**Comment by ishakasliwal** [comment]
@akcorp2003 Thanks for the question! Unfortunately, we offer the whole bundle and that’s it, we currently don't support that level of customization. But if you want they can try deleting stuff at your own risk!
