### ISSUE TITLE
Slds button group, Last child not getting border-radius curve.

### ISSUE THREAD

**Issue by ankushsomani09** [salesforce-ux/design-system#436]
![last_btn_border-radius-not working](https://cloud.githubusercontent.com/assets/2452618/24493819/ba7a2596-154d-11e7-9c55-d8fe7a0cb5fc.png)

Hi Team,
I have noticed that Border radius on `Slds-button-group :  Last child` is not getting applied. Please have a look.
Thanks
Ankush

**Comment by ishakasliwal** [comment]
Thank you for reporting this, we'll look into it.

**Comment by engai** [comment]
Hey @ankushsomani09, are you still experiencing this issue? Not sure what may be causing this without any context on what could be overriding that `:last-child` selector.

**Comment by engai** [comment]
Closing as stale. Feel free to reopen & comment if needed.
