### ISSUE TITLE
Unwanted padding bottom in app.css inside Lightning Experience overriding SLDS styling

### ISSUE THREAD

**Issue by aravindxz** [salesforce-ux/design-system#437]
![image](https://cloud.githubusercontent.com/assets/7611254/24496551/31553be4-1556-11e7-8026-0d959be5c6d9.png)
The above screenshot shows an **unwanted padding-bottom of 2.5rem** in a class named flexipagePage in the Lightning Experience[Desktop].
Because of this, I'm unable to give full height to my component.

**Comment by ishakasliwal** [comment]
@aravindxz Thanks for the question. Unfortunately that does not fall under the lightning design system. Please check out the developer success community at: developer.salesforce.com/forums.

**Comment by aravindxz** [comment]
@ishakasliwal  May I please know why is **Lightning Design System** styles are **not being applied** in SALESFORCE LIGHTNING EXPERIENCE?

There actually **NO POINT IN LIGHTNING DESIGN SYSTEM IF USERS ARE NOT ABLE TO USE THE SLDS (due to your app.css styling which overrides the SLDS**)
