### ISSUE TITLE
<apex:slds> not loading lightning CSS when opening VF page in console application 

### ISSUE THREAD

**Issue by minhajksm** [salesforce-ux/design-system#439]
I have created a VF page which is lightning CSS enabled. It works fine when opening the page in Classic.

I added the tab of the VF page to Service Console app, but this time the page appears without any lightning css at all. 

Can someone please tell me if I am missing something here.

Appreciate any help!

**Comment by ishakasliwal** [comment]
@minevskiy Thanks for the question. Unfortunately that does not fall under the lightning design system. Please check out the developer success community at: developer.salesforce.com/forums.

**Comment by FeiyangGao** [comment]
https://www.lightningdesignsystem.com/platforms/visualforce/
the code as below.
`<apex:page >

      <apex:slds/> 
    <div class="slds-scope">
      
    <button class="slds-button slds-button_neutral">Button</button>
    </div>

    </apex:page>`
