### ISSUE TITLE
Picklist multi-select overflows container when 6+ items added and no scroll

### ISSUE THREAD

**Issue by diverted247** [salesforce-ux/design-system#44]
In using the picklist-multi-select, the ul lacks overflow: auto which allows child scrolling.

`<ul class="slds-picklist__options slds-picklist__options--multi shown" style="overflow: auto;">`

## without overflow:auto
![without overflow:auto](https://www.dropbox.com/s/oj0j6fau66toqi0/Screenshot%202015-10-08%2020.51.50.png?raw=1)

## with overflow:auto
![with overflow:auto](https://www.dropbox.com/s/wukqaqhiwyjsuqa/Screenshot%202015-10-08%2020.54.11.png?raw=1)

**Comment by stefsullrew** [comment]
I've fixed this and it will be included in the next release. Thanks @diverted247. Closing for now.
