### ISSUE TITLE
Datepicker widget doesn't popup when wrapped in slds-truncate div

### ISSUE THREAD

**Issue by lrazov** [salesforce-ux/design-system#441]
We use SDLS datepicker in a resizable table. If we use the slds-truncate class on an outer div container the datepicker popup doesn't work. If we remove the slds-truncate class, it works. We need to use the slds-truncate class otherwise when a page is resized, the calendar icon doesn't stay within the input box and gets pushed out.

    <td role="gridcell">
      <div class="slds-truncate">
        <div class="slds-form-element">
          <div class="slds-form-element__control">
             <div class="slds-input-has-icon slds-input-has-icon--right dateDiv">
    	        <svg aria-hidden="true" class="slds-input__icon input-text-default"  style="cursor: pointer;">
                    <use xlink:href="{!URLFOR($Resource.SLDS202, '/assets/icons/utility-sprite/svg/symbols.svg#event')}"></use>
                </svg>
                <input id="mydate" class="slds-input" type="text" value="{!opt.endDate}" />
            </div>
          </div>
        </div>
      </div>
    </td>

**Comment by ishakasliwal** [comment]
@lrazov Thanks for the question. Could you provide us with a working Codepen of this test case?

**Comment by engai** [comment]
Closing this as stale.

If this is still an issue, please feel free to reopen and provide a working Codepen of this use case.
