### ISSUE TITLE
allign input left when override size of slds-form-element__control

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#445]
Actually I have
![image](https://cloud.githubusercontent.com/assets/2789203/25526965/81c80f30-2c16-11e7-8c11-424190027d35.png)

Is there a way to align all input ro left instead right, in a right way ? to not conflict with others things in form component ? Actually for instance I have class "slds-form-element__control size-date" which override 66% to  100px; and I don't understand it's aligned right instead left, how can I have choice ? thanks

I want keep my 100px max size, but juste align left instead right ? 

cc @kaelig

**Comment by ishakasliwal** [comment]
@istiti Thanks for posting your question. Can you please provide us with a Codepen with a working test case? Thank you!

**Comment by istiti** [comment]
@ishakasliwal ok
