### ISSUE TITLE
Request: Mention the $Asset global variable in the Visualforce Getting Started page

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#446]
https://lightningdesignsystem.com/platforms/visualforce/

The page highlights the ability to use the new `<apex:slds />` tag but I find myself having to search elsewhere for a reminder on how to use the `$Asset` global variable for retrieving images and SVG icons. It would be nice to mention it on the same page with an example similar to the one in the release notes (https://releasenotes.docs.salesforce.com/en-us/spring17/release-notes/rn_vf_asset_variable.htm).

**Comment by stefsullrew** [comment]
Great suggestion, @kevinberonilla!
