### ISSUE TITLE
License of the design system, icons and fonts

### ISSUE THREAD

**Issue by vhfrock2015** [salesforce-ux/design-system#447]
We are planning to work on a product, which some may call in same domain as Salesforce. Since this opensource project is from Salesforce, do you know what are the licensing terms for Css Modules, Iconography and Fonts?

Btw you guys have done one of the best looking components design. Kudos to the team.

**Comment by daveespo** [comment]
It's obscurely covered by a sentence on this page down in the 'Design System Zip' section

https://lightningdesignsystem.com/downloads/

**Comment by srohde** [comment]
Correct, the licenses are also mentioned on our GitHub page: https://github.com/salesforce-ux/design-system#licenses
