### ISSUE TITLE
SLDS 'slds-scrollable' seems to be not getting applied on User Interface of scrollbar

### ISSUE THREAD

**Issue by vc4u** [salesforce-ux/design-system#449]
The previous SLDS versions were not showing browser scrollbars in native interface. Currently the display of scrollbars is like this:
[https://www.screencast.com/t/Jgh3Zwsnhw](url)

Whereas previously till version 2.0.x, the scrollbars are displayed like this:
[https://www.screencast.com/t/qk2LHXLxl](url)

Is the native scrollbar display the new normal or an issue in css? Personally, I liked the minimum screen real-estate consumed by scrollbars of version 2.0.x.

**Comment by ishakasliwal** [comment]
@vc4u Thanks for pointing this out.

@brandonferrua Are you able to speak to this?

**Comment by engai** [comment]
Closing this as stale. Feel free to re-open or comment (with updated screenshots) if this is still an issue.

**Comment by vc4u** [comment]
Well, it is still an issue. the "scrollbars" do appear but the styling does not get applied to them anymore. They are plain native browser scrollbars, previously they were styles with minimum width and colored appearance.

**Comment by engai** [comment]
@vc4u This was an intentional change made in v2.2.0.
