### ISSUE TITLE
Some of the CSS is missing

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#45]
I have found out, that some of the CSS is missing in 0.9.2 even when we have working example under components section.
For example there is validation example under forms section, but when I use the same exact classes nothing works until I manually copy CSS from example page into my page.

**Comment by amyleesalesforce** [comment]
Hi @matejp84, thanks for trying out the Lightning Design System. I just tried to repro the issue and can't quite do that. I did a quick check of the Git history and validation states look largely unchanged. Did you put the `has-error` class on the containing element around your `input`?

I did a quick Gist to test this out too:
https://gist.github.com/amyleesalesforce/61f21341ea7c142f38c3

**Comment by matejp84** [comment]
Working by this trailhead: I installed this design system as unmanaged package. https://developer.salesforce.com/trailhead/lightning_design_system/lightning-design-system2
Where it says to import CSS file with: <apex:stylesheet value="{!URLFOR($Resource.SLDS090, 'assets/styles/salesforce-lightning-design-system-vf.css')}" />, the only thing I changed here is Resource name as it is now SLDS092. 

My code is as follows:
`<div class="slds-form-element slds-is-required">
                                        <label class="slds-form-element__label" for="dProductName">Product Name</label>
                                        <div class="slds-form-element__control">
                                            <input id="dProductName" class="slds-input" type="text" placeholder="Product Name" required="" aria-describedby="errorSample1"/>
                                            <span id="dProductNameError" class="slds-form-element__help" style="display: none;">This field is required</span>
                                        </div>
                                    </div>`

Class `slds-has-error` is assigned dynamically with javascript and when I inspect element in browser it has all classes that are and are also included in this example: https://www.lightningdesignsystem.com/components/forms , but input doesn't get highlight and error message under input isn't visible. 

After some inspection of CSS file that is used I discovered that there is no `.slds-has-error .slds-input` code there and this is why this doesn't work. But for span element that is under input element there is CSS in file: `.slds-has-error .slds .slds-form-element__help`. 

So I don't know now, but do I miss something here or is there really missing code in CSS file we are supposed to be using? 

My solution for this to work correctly is to put CSS into my page file:
`.slds-has-error .slds-input {
            background-color: #fff;
            border-color: #c23934;
            box-shadow: #c23934 0 0 0 1px inset;
            background-clip: padding-box
        }
        .slds-has-error .slds-form-element__help {
            color: #c23934
        }`

This part here is missing one in CSS file.

**Comment by amyleesalesforce** [comment]
What is the stylesheet import line you're using? And are you on Visualforce or Lightning Components?

Try doing this: can you put a wrapper DIV really high up in the DOM hierarchy that is:

  <div class="slds">
    ... the rest of your page ...
  </div>

**Comment by matejp84** [comment]
My import line is:
`<apex:stylesheet value="{!URLFOR($Resource.SLDS092, 'assets/styles/salesforce-lightning-design-system-vf.css')}" />`
I installed unmanaged package as it is noted here: https://www.lightningdesignsystem.com/getting-started/visualforce

My page is old VF page with new design system, no lightning components. 

I also have div with slds class, without that nothing works. 

Have also noticed that checkboxes aren't working, looks like more missing CSS. 
It is strange, that if I check CSS from https://www.lightningdesignsystem.com it has all the code necessary for everything to work. If I search for certain classes or class states in my CSS file, they are missing. Can you please confirm with CSS on that page and CSS from that unmanaged package if they are the same?

**Comment by amyleesalesforce** [comment]
I think the checkboxes issue is known and we're fixing that.

Good on the .slds class---the SLDS VF CSS you're using does require that. Let me play around with the code a little...

**Comment by amyleesalesforce** [comment]
... OK you're right it's broken. Let me talk to the team.

**Comment by amyleesalesforce** [comment]
@brandonferrua tag, you're it!

**Comment by amyleesalesforce** [comment]
@matejp84 Hi. I just talked to Brandon and this issue is related to:
https://github.com/salesforce-ux/design-system/issues/31

I'm closing this one and we'll use the other issue as the tracking mechanism.
