### ISSUE TITLE
Visibility Utility Classes missing new BEM convention

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#452]
**What the bug?**
Missing new BEM styling versions of the the responsive visibility classes. Older style still is usable but the new version (reflective of updated documentation) does not seem to be provided. This includes classes such as slds-show--x-small being found while slds-show_x-small is not found. 

**Impacts?**
Found to impact all new(2.3.0) and old (pre 2.3.0) utility responsive visibility classes.  

**Where Found?** 
Found in app with <extends="force:slds"> provided version of 2.3.0 as well as version currently rendering at www.lightningdesignsystem.com. This was found in sandbox running summer 17. 

![image](https://cloud.githubusercontent.com/assets/18658298/26280906/aa9eed30-3db3-11e7-8b0e-c960a87e48ff.png)

**Comment by brandonferrua** [comment]
Thank you for reporting! This has been fixed in our 2.3.1 release today.

**Comment by jovabe** [comment]
slds include tag on visualforce is still loading 2.3.0 on a summer 17 developer org. What can I do to make it reference the latest version?
