### ISSUE TITLE
IE - Modal Progress Issue

### ISSUE THREAD

**Issue by jmdohn** [salesforce-ux/design-system#453]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![modalprogressissue](https://cloud.githubusercontent.com/assets/12724534/26403537/4184e4fa-4054-11e7-97d9-9d349d89ad51.PNG)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Since Salesforce will be supporting LEX in IE11 until 2020, it would be important for styles to also be IE11 compatible. Below is an example of a style that I had to add for IE11 to render the progress indicator properly inside of the modal container. Otherwise, it gets shifted to the right about half of the screen over.

```
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {  
           .slds-scope .slds-progress{
               max-width: 100% !important;
           }
}
```
This was added in VF with `<apex:slds>` but I have not worked out a good way to fix with an aura:component with `force:slds`.

IE seems to be the only browser that uses `-ms-high-contrast`, which allows this to work.  I likely need to increase the specificity to make it so I don't need to use the important tag, but it'll let you see the issue / contrary to expected behavior.

> Are any specific browsers impacted by this bug?

IE

> Which version of the Salesforce Lightning Design System are you using?

Summer '17

> What steps and/or code are needed to reproduce this issue?

Make a modal app with progress indicator

> What did you expect to happen?

Progress bar should be contained in the modal.

> What actually happened?

Progress bar is not contained in modal.  When expanded, it goes off the screen and forces the right button off as well.

**Comment by ishakasliwal** [comment]
Thanks for bringing this to our attention @jmdohn.

@stefsullrew, would you be able to speak to this?
