### ISSUE TITLE
Lightning component action modal and select display problems

### ISSUE THREAD

**Issue by up2go-rsoesemann** [salesforce-ux/design-system#454]
I'm a CSS newbie, so this might be a trivial question. Nonetheless I need help.

I have this Lightning component used as action on a button.

    <aura:component controller="..." access="GLOBAL" implements="force:lightningQuickActionWithoutHeader,force:hasRecordId">
        <div class="slds-page-header" role="banner">
            <p class="slds-text-heading--label">{!v.record.Name}</p>
            <h1 class="slds-page-header__title slds-m-right--small slds-truncate slds-align-left">Add new year</h1>
        </div>
        
       <c:strike_select value="{!v.selected}" placeholder="Select Template" onchange="{!c.doSelect}">
            <aura:renderIf isTrue="{!v.showBlank}">
                <c:strike_option value="" label="No Template (Create blank record)" />
            </aura:renderIf>
            
            <aura:iteration items="{!v.templates}" var="tmpl">
                <c:strike_option value="{!tmpl.id}" label="{!tmpl.label}" />
            </aura:iteration>
        </c:strike_select>
        
        <lightning:button label="Cancel" onclick="{!c.doCancel}" variant="neutral"  />
        <lightning:button label="Continue" onclick="{!c.doContinue}" variant="brand" /> 
    </aura:component>

But as you see in the screenshots there are three display problems.

 1. The select **options are auto-opened** on page load
 2. The select **options are hidden** outside of the modal (showing 2 ugly scrollbars
 3. **Insufficient spacing** between header, select and buttons. How can I make it look like a real modal. I read everything about mimicing modals but I could make it work.

Note: I am using [Strike Components][1] here as making it work with pure Design System is not what I want and Base Components also don't style properly.

[![enter image description here][2]][2]

[![enter image description here][3]][3]

  [1]: https://github.com/appiphony/Strike-Components
  [2]: https://i.stack.imgur.com/H938y.png
  [3]: https://i.stack.imgur.com/e4sYN.png

**Comment by ishakasliwal** [comment]
@up2go-rsoesemann thanks for posting your question. This looks like it's either an issue for the Strike components team, or with Lightning Components. Please check out the developer success community at: developer.salesforce.com/forums.
