### ISSUE TITLE
Missing closing / in documentation

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#456]
This is a documentation note rather then one on the underlying system. The currently documentation has a number of malformed XHTML usages. Generally this is due to single items not be completed closed. 

See the <input> on 
https://www.lightningdesignsystem.com/components/form-element/?variant=base

See the <img> on 
https://www.lightningdesignsystem.com/components/avatar/?variant=base

In general this is not a major issues; however, a large use case for SLDS is within the aura framework (IE lightning components) the lack of closing / makes the samples a little less copy/pastable.

**Comment by ishakasliwal** [comment]
@JohnHeadIV Thanks for bringing this to our attention.

@brandonferrua @DrBoolean is this something that you are both aware of?

**Comment by brandonferrua** [comment]
@JohnHeadIV Thanks for pointing this out. Looks like the code thats generating the code example is removing it, even though its in the code. You'll notice its there for a quick second right when the page loads.

**Comment by DrBoolean** [comment]
Good catch! I'll have to checkout our beautifier and syntax highlighter
