### ISSUE TITLE
Documentation: SLDS-modal__header List twice in Header Empty Sample

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#457]
Per the documentation for 2.3.1 the Modal with an empty head should have: 

      <header class="slds-modal__header slds-modal__header slds-modal__header_empty">

https://www.lightningdesignsystem.com/components/modals/?example=headless&variant=base

I believe this is incorrect and should only have 1 slds-modal__header before the slds-modal__header_empty. If this is intentional/required, I couldn't figure out why and would suggest documenting such in the implementation Notes.

**Comment by ishakasliwal** [comment]
@JohnHeadIV Thank you for pointing this out! We've made changes on our end and will push the updates accordingly 👍
