### ISSUE TITLE
Suggestion: Progress Bar Error/Complete States

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#458]
For 2.3.1 per 
https://www.lightningdesignsystem.com/components/progress-bar/?state=zero&variant=base

There is no stated method for demonstrating complete/error states. This can (and should be) complement by other UI feature on a page but I would recommend the need for both of these states. (Suggestion can be provided if there is interest). 

The error state is key for larger file movement (a clear use-case for progress bars) where errors/failure can happen during a transfer. 

The complete state would be key for demonstrating to the use the the action indicated by the progress bar has finished. On Mobile/tablet layouts the difference between 90% and 100% can be unclear even though a distinct background is provided. As their is no inverse or shade version the background does not always provide adequate clarity towards completion level/state. 

If interested, I can provide a codepen with our implementation of these states.

**Comment by ishakasliwal** [comment]
@JohnHeadIV Thanks for pointing this out. Please provide us a Codepen with your use case.

**Comment by JohnHeadIV** [comment]
@ishakasliwal Notice that the Green color variant (.slds-progress-bar__value_success) was added. I believe this is a good step and thank you. Can I ask why a red(error) variant was not also added at the same time? Going to mark this as closed either way.
