### ISSUE TITLE
Grid inputs required format

### ISSUE THREAD

**Issue by jmdohn** [salesforce-ux/design-system#462]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

Codepen - current required inputs with grid:
https://codepen.io/anon/pen/OmeaNL

Codepen - desired future state:
https://codepen.io/anon/pen/ybdZXL

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Feature request:
Currently the input uses a * to denote that a field is required.  Unfortunately this is not good for table format type displays.  As a result, a new class should be added to SLDS Input components to add a vertical bar to the input.
I've called it required-horizontal__input & required-horizontal_inputEle.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Input

> Which version of the Salesforce Lightning Design System are you using?

2.3.1

**Comment by ishakasliwal** [comment]
@jmdohn Thanks so much for suggesting this feature request, our team is looking into it!
