### ISSUE TITLE
Scroll issue in Salesforce1 

### ISSUE THREAD

**Issue by aravindxz** [salesforce-ux/design-system#463]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
https://salesforce.stackexchange.com/q/173467/29317

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I'm using ui:scrollerWrapper to implement scrolling functionality in Salesforce1 application as the default SLDS-SCROLL is still not compatible in Salesforce1 app.
And now, you've removed that information from your SLDS website. (**Earlier there was a warning which said Scrollable is NOT compatible in Salesforce1**)

Recently, I'm facing scrolling issues in all the devices, when scrolling is enabled using the ui:scrollerWrapper.

The scrolling is not at all smooth in devices. Also, sometimes, the scrollbar disappears while scrolling!

I've tested out the same in the latest iOS version (10.3.1) and the Salesforce1 app version 12.3 (Build #3031793) in iPad as well as in iPhone.

I've created an unmanaged package so that it's easier to replicate the issue.

Here's the link to install the unmanaged package:- https://login.salesforce.com/packaging/installPackage.apexp?p0=04t28000000qnoC

Is there anything wrong in which I've enabled scrolling functionality using ui:scrollerWrapper? It would be great if anyone could provide any workarounds to fix the scroll issue.

I'm just posting the code as well so that people who don't have time to install the package could just skim through the code and provide any valuable feedback for the same.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.
SCROLL functionality 

> Are any specific browsers impacted by this bug?
All the mobile devices including iPads.

> Which version of the Salesforce Lightning Design System are you using?
Spring '17 org

> What steps and/or code are needed to reproduce this issue?
Here's the link to the package to replicate the issue.
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t28000000qnoC

> What did you expect to happen?
SMOOTH scrolling

> What actually happened?
Scroll issue in Salesforce1.

**Comment by ishakasliwal** [comment]
@aravindxz Thank you for pointing this out. Unfortunately, we cannot address this issue as SLDS is not involved. We'd encourage you to check into developer.salesforce.com or Salesforce Stack Exchange.

**Comment by aravindxz** [comment]
Even the SLDS-SCROLL IS NOT STILL COMPATIBLE. @ishakasliwal

May I know what do you expect us to do? I've even provided you the issue which is PRESENT as an unmanaged package. Even after seeing the issue, how can you say it is not an SLDS issue?!
