### ISSUE TITLE
CSS for checkbox - grid styling

### ISSUE THREAD

**Issue by jmdohn** [salesforce-ux/design-system#465]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

Checkbox label to left should be on SLDS website.

Working codepen:
https://codepen.io/anon/pen/WONJrr

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

New component on SLDS site for checkbox.  The reason for changing this to have the label prior to the checkbox is that the label typically denotes the action to take.  While a right label makes sense for a checkbox group, a vertical or left label makes more sense for grid like information.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Checkbox component

> Which version of the Salesforce Lightning Design System are you using?

3.2.1

**Comment by ishakasliwal** [comment]
@jmdohn Thank you for your contribution. The team will take a look at this and assess if it's an example we need to surface on our site, and take necessary action from there.
