### ISSUE TITLE
Old Documentation Not Working

### ISSUE THREAD

**Issue by mvcmania** [salesforce-ux/design-system#466]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
![slds_issue](https://user-images.githubusercontent.com/3177104/26885876-815411e2-4bac-11e7-9c96-3cc1628fcb32.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I went to the documentation page of SLDS 2.2.2, via the link on the main page (Spring 17).
I was able to view the page successfully after that i did a search on left side bar and clicked the items that i searched for and i got the error on screenshot. Please support old slds version documentation.
> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?
Chrome latest

> Which version of the Salesforce Lightning Design System are you using?
2.2.2

> What steps and/or code are needed to reproduce this issue?
Go to :https://www.lightningdesignsystem.com/
then click the Spring 17 link on top.
Do a search and click the item that appeared under search box.
I did a search for "alert" if you want it specifically. 

> What did you expect to happen?

> What actually happened?

**Comment by ishakasliwal** [comment]
@mvcmania Thanks for bringing this to our attention.

@aputinski @DrBoolean Could you look into why this is happening?

**Comment by aputinski** [comment]
So it looks like we're using the wrong search index. I'll do some digging to see how we can fix this.

**Comment by DrBoolean** [comment]
We have since fixed this index
