### ISSUE TITLE
compatibility for minor version ?!? 

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#467]
**HAVE YOU HEART ABOUT "LTS" ?**
I'm using 2.2.1 totally incomptabile with 2.3.1.
 This is anti-productif. Very dissapointed!
**Please never do this again !**   
How can I update my BIG project and use new slds, does someone try regexp to replace all -- to __ inside class="" any help ?

**Comment by ishakasliwal** [comment]
@istiti Thanks for your concern. We're still supporting all of the CSS classes that use `--` for another 18 months, so you don't have to change anything yet, and nothing should be broken on account of it. Once we fully drop support via CSS, we'll make sure to offer something else to help you stay afloat.

**Comment by istiti** [comment]
is this reason why file size of summer17 version is 3x bigger than 2.2.1 ?  because all is selectors are dusplicated. 
ex.
> .tsab .slds-tree_container > .slds-text-heading_label,
> .tsab .slds-tree_container > .slds-text-heading--label{}

It is very important to think now how we can convert our html class to the new syntax with a regexp maybe matching all string begin with "slds-" and end with a space character " " replace them to your new syntax, please cause this new size make my css so big

cc @ishakasliwal

**Comment by istiti** [comment]
Why this issue is closed ? According to what you said

> we'll make sure to offer something else to help you stay afloat.

please apologize, I'm lookin for solution, because of one character change (dash -- vs underscore _ ) we have 2 version css (size is duplicated) 

We can't  call it "18month support", if user want both version he can add old version and new version in their html document.

Do you have temporary solution "regexp to change whole my html, or tell me how tings are different, I will do this regexp on my IDE"

last question: if I succeed with replacing all css class, where can I download last slds css version  without old one and have little size of css, thanks

cc @ishakasliwal
