### ISSUE TITLE
Rich Text Editor Functionality

### ISSUE THREAD

**Issue by loran-saggu** [salesforce-ux/design-system#469]
Are there any functional examples of the SLDS Rich Text Editor (specifically for use in Visualforce)? Could any functional examples be created/shared? The examples here, [Rich Text Editor Documentation](https://archive-2_2_2.lightningdesignsystem.com/components/rich-text-editor), are not functional. For example, the text is not bolded when the bold option is selected.

**Comment by ishakasliwal** [comment]
@loran-saggu If you look in the app at docked composer, notes, or feeds, you should be able to see a working example of rich text editor. Cheers!

**Comment by loran-saggu** [comment]
@ishakasliwal - Thanks for your response. Do you mean in the LDS [documentation](https://archive-2_2_2.lightningdesignsystem.com/components/docked-composer/?variant=base#flavor-email)? I did not find a working example looking at the documentation for the items you mentioned. Or did you mean in an Org in Lightning Experience? 

I understand if this is not the correct place to ask this considering it may require more JavaScripting and customization, but I am looking for how to build a functioning Rich Text Editor using LDS? Is there a simple way to do this, or will it require creating the JS?

**Comment by ishakasliwal** [comment]
@loran-saggu I'd recommend looking at an Org in Lightning Experience. Unfortunately, we cannot help you with any JS, so I'd also recommend looking into https://developer.salesforce.com/.

**Comment by loran-saggu** [comment]
@ishakasliwal - I'll take a look. Thanks for your time and for your help!
