### ISSUE TITLE
close button outside modal

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#471]
> Describe the issue?

Hi there, we are two developers,we use SLDS in our project and design is beautiful. We desagree about one salesforce specs "Close icon button outside Modal". 

He said to me this is a bug and so ugly, the **X** (close button) need and always been inside modal. 

I'm saying to him it's very beautiful. It's not bug, it's desired. I think close button outside modal show to user that when you click  everywhere on shaded backdrop around the modal you can close it.  

Do you have seen this design somewhere else (another company) ? And Can you give us more inputs here please? 

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Modal Specs

> Which version of the Salesforce Lightning Design System are you using?

All

cc @brandonferrua @stefsullrew @aputinski

**Comment by ishakasliwal** [comment]
@istiti Thanks for your concern. The reason we keep the close button outside of our modal is for accessibility reasons.

@SiTaggart might be able to give you more insight.
