### ISSUE TITLE
Inconsistent styling between button themes. 

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#472]
The brand

![screen shot 2017-06-16 at 10 04 29 am](https://user-images.githubusercontent.com/1011888/27236796-3e4bb0f0-527b-11e7-9551-b6ce9b93b135.png)
and destructive
![screen shot 2017-06-16 at 10 04 36 am](https://user-images.githubusercontent.com/1011888/27236805-49a247d4-527b-11e7-8a8a-2be740a8dad2.png)
buttons both have white text, but the success does not.
![screen shot 2017-06-16 at 10 05 39 am](https://user-images.githubusercontent.com/1011888/27236835-618a7ce0-527b-11e7-9610-9e7590792132.png)
Was that intended? It's obvious why the other buttons have blue/grey text, cause they have white background colors.
![screen shot 2017-06-16 at 10 07 22 am](https://user-images.githubusercontent.com/1011888/27236892-a5a8ef74-527b-11e7-8723-19efa02e6691.png)
![screen shot 2017-06-16 at 10 07 29 am](https://user-images.githubusercontent.com/1011888/27236893-a7e4c15a-527b-11e7-8006-b87ef11f5d10.png)

https://lightningdesignsystem.com/components/buttons/

**Comment by ishakasliwal** [comment]
@tylerzika The color on the success button was made blue for accessibility reasons.
