### ISSUE TITLE
Chatter Feed in Visualforce Page with <apex:slds /> and <apex:details showChatter="true" />

### ISSUE THREAD

**Issue by matt-ian-thomas** [salesforce-ux/design-system#473]
![box-sizing](https://user-images.githubusercontent.com/9135884/27307929-dbed4c40-5511-11e7-805e-d7593164d823.png)

A visualforce page (api version 40.0) with the following markup will render the above Chatter feed at the top of the page:

```
<apex:page docType="html-5.0" showHeader="true" sidebar="true" standardController="Account">
  <head>
    <apex:slds />
  </head>
  <div class="slds-scope">
    <apex:detail showChatter="true" />
  </div>
</apex:page>
```

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

`<div class="feedpage zen">` generated by the apex:detail component has its `box-sizing` property set to `border-box` by `.slds-scope *, .slds-scope :after, .slds-scope :before` which causes the funky alignment. I reversed this by resetting the `box-sizing` property in my own stylesheet to the default `content-box` value for the `.feedpage` class.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Chatter Feed rendered by `<apex:detail>`

> Are any specific browsers impacted by this bug?

Not to my knowledge, but I'm using the latest version of Chrome.

> Which version of the Salesforce Lightning Design System are you using?

The bug happens in Visualforce when importing SLDS via `<apex:slds />`. The page is api version 40.0

> What did you expect to happen?

This is what it looks like when I override the `box-sizing` property to its original value of `content-box`.

![screen shot 2017-06-19 at 5 20 17 pm](https://user-images.githubusercontent.com/9135884/27308345-9a75b7a0-5513-11e7-9bc9-639b8092be86.png)

**Comment by ishakasliwal** [comment]
@matt-ian-thomas Thanks so much for bringing this to our attention. Unfortunately, we do not handle apex bugs. However, you can head to developer.salesforce.com for more information, or email slds-support@salesforce.com and we can send your question to an appropriate party.
