### ISSUE TITLE
slds-scrollable not works ?!

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#474]
REPRODUCE : https://jsfiddle.net/cubwr7en/ (please read css section line 15)

1. `.slds-scrollable` doesn't scroll

2. Related to **Scrollable** feature

3. chrome  v59.0.3071.86

4. slds v.2.3.1

**Comment by ishakasliwal** [comment]
@istiti Thanks for pointing this out. It looks like everything is working on our end, here is a working test case: https://cl.ly/1e193M47413v

Please let me know if you continue to have issues.

**Comment by istiti** [comment]
you add hardcoding height200px that's why it works. 
my question/reaction is if we don't want to specify height why not have default max-height to 100% this is what im saying, we can ovveride if we want but i think here need to be default to 100%  thanks
