### ISSUE TITLE
Size of Visual Picker

### ISSUE THREAD

**Issue by akcorp2003** [salesforce-ux/design-system#478]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="1147" alt="screen shot 2017-07-03 at 11 13 17 am" src="https://user-images.githubusercontent.com/12402936/27803887-ad3f6a8e-5fe0-11e7-95c3-d85ffd62f135.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Feature Request - new CSS class or adjusting an existing CSS class

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Visual Picker

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

2.3.2

I was wondering if the size of the visual picker can be adjusted. Currently, there are only medium and large sizes and sometimes, especially for larger lists, they occupy too much room on the page. If there were more classes like small, x-small, that would give more flexibility to the designer.

**Comment by ishakasliwal** [comment]
@akcorp2003 Thanks for your suggestion. We agree that having more sizing classes for the visual picker would be a great improvement. We'll work to see if we can prioritize this enhancement; in the meantime, if you or your team come up with a solution that you think can be added to our design system, we encourage you to make a pull request and share your work!
