### ISSUE TITLE
code sample snippets aren't wrapped properly

### ISSUE THREAD

**Issue by daminisatya** [salesforce-ux/design-system#479]
**Bug**

<img width="1677" alt="screen shot 1939-04-13 at 9 29 46 am" src="https://user-images.githubusercontent.com/6227784/27815111-546fdffa-609f-11e7-81ad-d35f214a2dff.png">
<img width="1673" alt="screen shot 1939-04-13 at 9 36 08 am" src="https://user-images.githubusercontent.com/6227784/27815114-562cf9b8-609f-11e7-9560-fdda54ffc0d9.png">
<img width="1678" alt="screen shot 1939-04-13 at 9 29 28 am" src="https://user-images.githubusercontent.com/6227784/27815132-7ed4e81c-609f-11e7-8c19-2173547e4b66.png">

**Steps to reproduce**

1. Navigate to any component. 
2. Click on the "</>" icon to view the sample snippet. 
3. By default you will be on monitor view. click on either tab or mobile view.
4. You will observe the overflow of code snippet. 

- This is observed on Mac OS, Google Chrome 59.0.3071.86 (Official Build) (64-bit)
- I took the latest code and set it up on my local machine. 
- I would like to send a PR for this bug.

**Comment by ishakasliwal** [comment]
@daminisatya Thanks so much for pointing this out. Our team is investigating the issue.

@DrBoolean @aputinski - wanted to bring this to your attention!

**Comment by engai** [comment]
Hey @daminisatya, I believe this bug has been resolved as I can no longer reproduce the issue.

Closing this, but please feel free to reopen or comment if you still think it is an issue.
