### ISSUE TITLE
font not visible on bgColor=inverse-alt

### ISSUE THREAD

**Issue by daminisatya** [salesforce-ux/design-system#480]
**Bug**

Text is visible only when hovered over it. ( This is observed when the background color is set to "inverse-alt" )

**Screenshots**

<img width="812" alt="screen shot 1939-04-13 at 10 10 45 am" src="https://user-images.githubusercontent.com/6227784/27815383-62f01df4-60a1-11e7-9d48-89932e8153ee.png">
<img width="889" alt="screen shot 1939-04-13 at 10 10 34 am" src="https://user-images.githubusercontent.com/6227784/27815384-634393d0-60a1-11e7-9c0b-2e2a16471d7d.png">

**Steps to reproduce**

1. Click on accordion component, and click on the third color on the palette shown. 
2. Observe the text go hidden and hover over the text. 

- This is observed on MAC OS, Google Chrome	59.0.3071.86 (Official Build) (64-bit). 
- Would like to work on this issue.

**Comment by ishakasliwal** [comment]
@daminisatya Thanks for sharing this issue. That's an intended testing mechanism of the previewer and if it doesn't display as intended when changing colors then the component doesn't support those colors. We understand that the UX is a little tricky, so we'll work on our end to improve the experience.
