### ISSUE TITLE
Release Notes to 2.3.2

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#481]
Issue: Release notes reflect changes through 2.3.1 but page says current version is 2.3.2. 

https://www.lightningdesignsystem.com/release-notes
![image](https://user-images.githubusercontent.com/18658298/28070523-35abf820-661b-11e7-9653-fe30591fcd1d.png)

Footer of page says release is 2.3.2

![image](https://user-images.githubusercontent.com/18658298/28070566-5a8c64d6-661b-11e7-8f24-80577a5cda6a.png)

Main page: getslds.com says version 2.3.1

Expected behavior: Release notes for version 2.3.2 provided. 

Also, since the main page has changed it hard to find the release notes. It would be much more intuitive if the release notes were added to the navigation.

**Comment by ishakasliwal** [comment]
@JohnHeadIV Thanks for bringing this to our attention. We'll work towards updating this.
