### ISSUE TITLE
List Builder example code uses <th> rather than <td>for data rows.

### ISSUE THREAD

**Issue by FishOfPrey** [salesforce-ux/design-system#482]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The example code for the List Builder component has invalid HTML markup. In particular, there are **th** elements where **td** would otherwise be expected.

![image](https://user-images.githubusercontent.com/2396092/28296896-0f134e1c-6bbf-11e7-8f19-b8e347830762.png)

I believe this is coming from [line 133 of example.jsx](https://github.com/salesforce-ux/design-system/blob/d29bd96b98fd77e4e12d446b2c0321fb450cf857/ui/components/list-builder/base/example.jsx#L133) for the list-builder component.

`    </td>
      <th scope="row">
        <div className="slds-truncate" title={props.name}>{ props.name }</div>
      </th>
      <td role="gridcell">`

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Specific to the List Builder Lightning Component

> Are any specific browsers impacted by this bug?

No

> Which version of the Salesforce Lightning Design System are you using?

  e.g. 2.3.2

> What steps and/or code are needed to reproduce this issue?

View example code at https://lightningdesignsystem.com/components/list-builder/#component-slds-tabs--tab-2

> What did you expect to happen?

Valid HTML markup in the example.

> What actually happened?

Unexpected tr element.

**Comment by jakranz33** [comment]
<th> can be used as a row header, no? 

Note the scope attribute set to "row"

**Comment by FishOfPrey** [comment]
Thanks @jakranz33 for the clarification. A misunderstanding on my part. 

The issue can be Closed #482

**Comment by istiti** [comment]
@fishofprey close it yourself
