### ISSUE TITLE
Can't remove indent/whitespace on Visualforce page embedded in Lightning standard layout

### ISSUE THREAD

**Issue by JeanGrey52** [salesforce-ux/design-system#484]
I can't get rid of the white space above the Visualforce page that is embedded on my page layout. The Visualforce markup has conditional rendering depending on the user's display theme. The whitespace is only showing in Lightning, not in Classic (see screenshots). 

`<apex:page standardController="Event" standardStylesheets="{!isClassic}" applyBodyTag="{!isClassic}" extensions="TZTranslateController" >

    <apex:outputPanel rendered="{! !isClassic}">
        <apex:slds />
    </apex:outputPanel>
    <div class="slds-scope">
            
    <apex:outputPanel rendered="{!isClassic}">
        <div style="font-size: 10;padding-left: 38%">
        Director's Time
        </div>
       
    </apex:outputPanel>
    
    <apex:outputPanel rendered="{! !isClassic}">
        <div class="slds-grid slds-m-top_none">
        Director's Time
        </div>
        
    </apex:outputPanel>    

    </div>
</apex:page>
`
![classic](https://user-images.githubusercontent.com/31323092/29684799-44198470-88e1-11e7-85cd-487d07dc909a.JPG)
![lightning2](https://user-images.githubusercontent.com/31323092/29684938-c7553b90-88e1-11e7-8f38-fc9ad0a0c594.jpg)

**Comment by stefsullrew** [comment]
Hi @JeanGrey52 ... I'm not sure we can help you with this without being able to inspect the page. Is there somewhere we can see this?

**Comment by engai** [comment]
Hey @JeanGrey52, are you still experiencing this issue? As @stefsullrew said, we could better assist if we were able to inspect the page.
