### ISSUE TITLE
Sass exception when compiling

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#485]
When trying to compile, we get the error `1.375rem*rem isn't a valid CSS value` caused by this line:
https://github.com/salesforce-ux/design-system/blob/master/ui/components/trees/grid/_index.scss#L15

I believe this should change from `($line-height-text * 1rem)` to just `$line-height-text`.
Happy to send a PR for this :)

**Comment by ishakasliwal** [comment]
@bekos Thanks for the catch. Please send us a PR :)

**Comment by DrBoolean** [comment]
Hi @bekos 

While i fully agree that multiplying by `1rem` doesn't seem to be right and a PR is welcome, I can't reproduce the compilation error.

Two questions:
1) Have you changed the `line-height-text` token locally?
2) How are you compiling the system?

**Comment by bekos** [comment]
hi @DrBoolean. 

1. No I haven't.
2. I am using webpack to import the sources, but I will try to narrow it if this helps.

**Comment by bekos** [comment]
False alarm! I was actually overriding the `line-height-text` variable with a non-unitless value, that was causing this issue. Thanks and sorry for the noise.
