### ISSUE TITLE
Is there a public access available to SLDS library released in a pre-release GS0 organizations?

### ISSUE THREAD

**Issue by vc4u** [salesforce-ux/design-system#487]
I wasn't sure where can I ask this question or report it as an issue? I'm trying to work with some development in Lightning Component with SLDS, but the library at https://www.lightningdesignsystem.com does not point to what we currently have in Winter '18 pre-release organizations. 

For example, DataTables css is different in Summer '17 and Winter '18. The responsiveness is differently handled. Wrapping/Clipping additional options also exist in new Winter '18 pre-release.

So is there a chanel/stream where we can download an in-progress SLDS version, like we can with Archived past versions?

**Comment by engai** [comment]
Hi @vc4u, we currently don't have future versions available to the public since they are still in production. There's no perfect solution as of now, but we're looking into ways we can close this gap in the future.

**Comment by stefsullrew** [comment]
@vc4u The Spring '18 SLDS release should be available within a day or so of customer sandboxes. 

@engai is correct that we don't have "in-progress" yet... but we're working on a plan to make it earlier.
