### ISSUE TITLE
Details about how to support content density

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#488]
I've seen talk about different density modes in Lightning and I'm wondering if that's now available in SLDS? I see with 2.4.0 the data table density is now in place, but there's no setting to provide a less dense version. Is that still on the roadmap? Available now but not documented?

**Comment by engai** [comment]
Hey @mattgoldspink, content density is not available yet, but is still on our roadmap. It should be available soon in a future release.

**Comment by andreev-artem** [comment]
@engai Is it released in Winter ‘19? How should it be properly used?
