### ISSUE TITLE
Grid manual sizing not working with slds-grid--vertical

### ISSUE THREAD

**Issue by mspeder** [salesforce-ux/design-system#49]
Using manual sizing like `slds-size--1-of-2` with `slds-grid--vertical` does not work.
Apparently `slds-size--xxxx` is implemented using `width : xxxx` which obviously does not work with column (should be `height : xxxx` in that case...).
Maybe a more generic approach using `flex-basis : xxxx` could solve the problem ?

**Comment by kaelig** [comment]
Closing this as vertical sizing in vertical grids isn't on the roadmap.
