### ISSUE TITLE
/design_tokens/dist is missing from npm build in 2.4.1

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#490]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Importing `_design_tokens.scss` directly to use in custom scss stylesheet is not possible when installing lds via npm

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Not related to a specific component

> Are any specific browsers impacted by this bug?

Not related to specific browsers

> Which version of the Salesforce Lightning Design System are you using?

2.4.1

> What steps and/or code are needed to reproduce this issue?

Reproduce:

1. Install npm via LDS
2. import `~@salesforce-ux/design-system/ui/design-tokens` in a scss file (~ is a sass-loader webpack shortcut to resolve styles in node_modules)
3. Fails.

> What did you expect to happen?

I used to be able to import and use the design_tokens in my scss project

**Comment by fspoettel** [comment]
There is an open issue related to design_tokens #404, it does not seem to be connected though

**Comment by jonnii** [comment]
I'm facing the same issue here too which is that i'm trying to import `ui/index.scss` as part of a build and the design tokens are missing (as they have not yet been built).

The branch where I'm upgrading to 2.4 is here:

https://github.com/jonnii/ember-cli-lightning-design-system/pull/26

**Comment by jonnii** [comment]
@fspoettel also fwiw i think you can get by for now with `2.4.0-rc.3` as I believe it contains almost all of the changes in 2.4 without any of the build related changes.

**Comment by jonnii** [comment]
I have resorted to importing the pre-built assets in `ember-cli-lightning-design-system` for now until we can use the sass design tokens =(

**Comment by stefsullrew** [comment]
@DrBoolean Do you know what might be happening here?

**Comment by DrBoolean** [comment]
Hi! Use @2.4.2 please. Thanks!

**Comment by jonnii** [comment]
@DrBoolean @stefsullrew this looks good now, I think we can close this.
