### ISSUE TITLE
2.4.1 does not support current node release, fails to install

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#491]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Installing via `yarn` fails when using the current node version (8.x) because `package.json > engines` is locked to ">=6.5.0 <7.0.0".

> Which version of the Salesforce Lightning Design System are you using?

2.4.1

> What steps and/or code are needed to reproduce this issue?

1. Use the current node version
2. Try to install design-system
3. Fails

> What did you expect to happen?

I expect LDS to not be the only package that fails when installing node dependencies

**Comment by jonnii** [comment]
This is very annoying, in the mean time you can tell yarn to skip the engines check:

```
yarn install --ignore-engines
```

**Comment by fspoettel** [comment]
Fixed with 2.4.5
