### ISSUE TITLE
IE11 Box not sizing based on Children

### ISSUE THREAD

**Issue by TonyWhiteSMS** [salesforce-ux/design-system#492]
It would appear that slds-box in IE11 is NOT getting the size of the children elements.
This code is working in Salesforce Community Summer17 but NOT Winter18.

**Issue as seen in IE11 (with inclusion of v2.3.1 version of SLDS via static resource)**
![ie11_orderscreen](https://user-images.githubusercontent.com/12590114/30527201-90990e2e-9c69-11e7-8f30-df725f5153bc.JPG)

**Same page in Chrome 60 (with inclusion of v2.3.1 version of SLDS via static resource)**
![chrome_orderscreen](https://user-images.githubusercontent.com/12590114/30527200-908ce342-9c69-11e7-9518-1df18f2454e3.JPG)

--
We have tested this in Chrome, Firefox and Edge without issue on Windows 10/7.
Also on Chrome on Mac - no issue
ONLY IE11 seems to have issue AFTER W18 release to sandbox.

The lightning component pulls in a set version of SLDS stylesheet from static resources as well - 2.3.1, but I believe the community is ALSO providing a newer version of this stylesheet.
If I comment out the inclusion of our static resource stylesheet from the base component it looks even WORSE in IE11, the outline of the box is completely missing.

Below is code that demonstrates the issue WITHOUT including the Static Resource.

> Which version of the Salesforce Lightning Design System are you using?
Salesforce Winter 18 Communities

> What steps and/or code are needed to reproduce this issue?
This is normally part of a lightning component but I have managed to isolate the HTML code and replicate with that alone:

Create a page in Salesforce Customer Community (Lightning)

Add HTML Component and put this code as the source

```
<div class="slds">
	<div class="slds-align--absolute-center slds-m-top--xx-large" data-aura-rendered-by="29:291;a">
		<div class="slds-grid slds-wrap slds-m-top--large slds-box slds-box--small slds-theme--shade slds-grid--align-end"
				 data-aura-rendered-by="30:291;a">
			<div class="slds-size--1-of-2 slds-p-bottom--medium slds-text-heading--medium" data-aura-rendered-by="31:291;a">
				Total
			</div>
			<div class="slds-size--1-of-2 slds-text-heading--medium slds-text-align--right" data-aura-rendered-by="33:291;a">
				<span data-aura-rendered-by="36:291;a">$29.70</span></div>
			<div class="slds-size--1-of-2 gstInc" data-aura-rendered-by="38:291;a">
				*GST Included
			</div>
			<div class="slds-size--1-of-2 slds-text-align--right gstInc" data-aura-rendered-by="40:291;a"><span
					data-aura-rendered-by="43:291;a">$0.00</span></div>
			<div class="slds-size--1-of-1 slds-m-top--large slds-align--absolute-center" data-aura-rendered-by="45:291;a">
				<div data-aura-rendered-by="46:291;a">
					<button name="payBtn" class="slds-button slds-button--brand" type="button"
									data-aura-rendered-by="49:291;a"><!--render facet: 50:291;a-->Pay Now
						<!--render facet: 53:291;a--></button>
				</div>
				<div>
					<button name="cancelBtn" class="slds-button slds-button--brand" type="button"
									data-aura-rendered-by="56:291;a"><!--render facet: 57:291;a-->Cancel
						<!--render facet: 60:291;a--></button>
				</div>
			</div>
		</div>
	</div>
</div>
```
> What did you expect to happen?

Box is displayed around a data grid of title and amount with 2 buttons as per
![chrome_orderscreen](https://user-images.githubusercontent.com/12590114/30527200-908ce342-9c69-11e7-9518-1df18f2454e3.JPG)

> What actually happened?
All title/value text is displayed in a column 1 char wide and the buttons are not pretty eg

![ie11_orderscreen](https://user-images.githubusercontent.com/12590114/30527201-90990e2e-9c69-11e7-8f30-df725f5153bc.JPG)

**Comment by TonyWhiteSMS** [comment]
@stefsullrew

**Comment by TonyWhiteSMS** [comment]
I have spun up a community in a SF W18 preview org and replicated it there without interference of any customisations - https://w18prev.force.com/s/test
Looks fine in Chrome (Mac), looks bad in IE11 on Win 7.

**Comment by TonyWhiteSMS** [comment]
As a work around I have added a the following to the community branding css
```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
	/* IE10+ CSS styles go here */
    .ieBox {
        min-width: 336px;
    }
}
```

and then added the ieBox class to the div, this way it ONLY sets the min width for IE.  I found this over here - https://philipnewcomer.net/2014/04/target-internet-explorer-10-11-css/
I am not a CSS dev so thanks Google!

**Comment by TonyWhiteSMS** [comment]
Work around update - realised on my way home that if you name the css class as .slds-box instead of .ieBox then NO other code change is required.

**Comment by stubbornella** [comment]
@amyleesalesforce @DrBoolean this is the kind of bug where having them submit a codepen instead of screenshots and then auto-validating the markup and css would be amazing.

**Comment by TonyWhiteSMS** [comment]
@stubbornella - Had not heard of Codepen before as do Salesforce development not pure html etc.
But here is the code copied from this bug into the html, unfortunately I have no where to put the css from winter18....
https://codepen.io/tonyfwhite/pen/qPZmXq

Perhaps you can fork it and test...

**Comment by DrBoolean** [comment]
Thanks for helping us to test out our workflow @TonyWhiteSMS 

We have a test suite that assures the markup is correct usage of SLDS so in the future it'd help us weed out any user error :)

Of course, that's certainly not the case here. There seems to be a bug in IE that we need to address.

We'll check out the issue. Appreciate the help.

**Comment by TonyWhiteSMS** [comment]
@DrBoolean Happy to assist as much as I can, spotted this issue in trying to check the slds doco - https://github.com/salesforce-ux/design-system/issues/497

Unfortunately IE11 won't die anytime soon so we still have to cater for users that are stuck on it due to SOE...

**Comment by stubbornella** [comment]
Thanks Tony! It seems like we should make a default codepen that already includes the right CSS. Then our users could focus on copying the HTML only.

**Comment by JohnHeadIV** [comment]
@stubbornella This would be great. Mocking stuff up in Heroku for an issue is a great deal more work. ( I'll admit I've skipped reporting minor bugs with obvious work around because of the time involved). When you are intentionally trying to demonstrate a bug and interactive space like codepen (or fiddler ...) is vastly better.  Also unlike heroku, codepen is designed for large number of quick use projects.  The fact that the contribution guideline no longer reference Heroku should be clear the codepen must be support to get the best quality bug reports. 

 Would this be best as a separate issue?

**Comment by stubbornella** [comment]
John, A separate issue would be great, thanks! Can you @ mention Amy and I
so it bubbles up?

**Comment by stubbornella** [comment]
We could do something like this: http://jsbin.com/lefey/1/edit?html,output

Which is linked from their docs in this way:
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
