### ISSUE TITLE
Request: Assets icon

### ISSUE THREAD

**Issue by modestfake** [salesforce-ux/design-system#493]
Salesforce uses new Assets icon (.png). But there's no asset icon in this package. It would be great to have it here in SVG format.

![image](https://user-images.githubusercontent.com/16977959/30541280-5bda7d84-9c83-11e7-822a-c0a8fe946b9e.png)

**Comment by ishakasliwal** [comment]
@erlswtshrt Would you happen to know if this icon will be in the next release?

**Comment by modestfake** [comment]
Any updates on this issue?

**Comment by ayeshakmaz** [comment]
Hi @modestfake, thanks for reaching out. This icon is actually listed on the site and included in the Icons download as Product, not Assets. You can find it on the site [here](https://www.lightningdesignsystem.com/icons#standard) under the title Product. You can also find the SVG in the Icons download. Let us know if you have any further questions.
