### ISSUE TITLE
NPM install hangs and fails at style-loader

### ISSUE THREAD

**Issue by dandenney** [salesforce-ux/design-system#495]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

On a new install, `npm install` hangs and exits on enter with an error related to the `style-loader` package. 

> What steps and/or code are needed to reproduce this issue?

- Clone the repo
- `npm install`
- Enter out of hanging install

> What did you expect to happen?

I expected installation of packages to complete.

> What actually happened?

I received an error, pasting the log entry below. While I can't recommend it because I'm not sure of the necessary dependencies, replacing the location-based source of `style-loader` (`"style-loader": "0.18.2",`) in the package.json with the current version number allowed installation to complete.

```
3369 silly fetchPackageMetaData exited with error code: 128
3370 verbose stack Error: exited with error code: 128
3370 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
3370 verbose stack     at emitTwo (events.js:125:13)
3370 verbose stack     at ChildProcess.emit (events.js:213:7)
3370 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
3371 verbose cwd /Users/dandenney/Repos/resources/design-system
3372 verbose Darwin 16.6.0
3373 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "install"
3374 verbose node v8.4.0
3375 verbose npm  v5.3.0
3376 error Error while executing:
3376 error /usr/bin/git ls-remote -h -t ssh://git@github.com/webpack-contrib/style-loader.git
3376 error
3376 error Permission denied (publickey).
3376 error fatal: Could not read from remote repository.
3376 error
3376 error Please make sure you have the correct access rights
3376 error and the repository exists.
3376 error
3376 error exited with error code: 128
3377 verbose exit [ 1, true ]
```

**Comment by ishakasliwal** [comment]
Thanks for reporting this @dandenney . Is this still an issue you're experiencing?

cc: @aputinski @DrBoolean

**Comment by engai** [comment]
@dandenney we've recently updated the version of style-loader in `packages.json`. Please let us know if you're still experiencing issues!

**Comment by dandenney** [comment]
@ishakasliwal @engai Thank you, I really thought I replied on Oct 30 that the issue was resolved.
