### ISSUE TITLE
The card lost it's border when putting it inside a tab in Winter '18. This was previously working on Summer'17 release.

### ISSUE THREAD

**Issue by oek2** [salesforce-ux/design-system#496]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

Missing Border with Winter 18
<img width="1195" alt="screen shot 2017-09-19 at 10 33 59 am" src="https://user-images.githubusercontent.com/22981228/30598089-e4bbd366-9d26-11e7-8695-bb5e5c41da8a.png">

Border show in Spring/Summer 17
<img width="1195" alt="screen shot 2017-09-19 at 10 38 23 am" src="https://user-images.githubusercontent.com/22981228/30598128-f6ac8520-9d26-11e7-8dd7-03a64d602edf.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
I believe it is a bug.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.
Card component inside a tab component

> Are any specific browsers impacted by this bug?
Chrome 60 in Mac but it happened in Window 10

> Which version of the Salesforce Lightning Design System are you using?
Winter'18

> What steps and/or code are needed to reproduce this issue?
Use this in Winter 18, it will lost it's border

<aura:component >
   <div class="slds-tabs_default">
       <ul class="slds-tabs_default__nav" role="tablist">
           <li class="slds-tabs_default__item slds-is-active" title="Item One" role="presentation"><a class="slds-tabs_default__link" href="javascript:void(0);" role="tab" tabindex="0" aria-selected="true" aria-controls="tab-default-1" id="tab-default-1__item">Item One</a></li>
           <li class="slds-tabs_default__item" title="Item Two" role="presentation"><a class="slds-tabs_default__link" href="javascript:void(0);" role="tab" tabindex="-1" aria-selected="false" aria-controls="tab-default-2" id="tab-default-2__item">Item Two</a></li>
           <li class="slds-tabs_default__item" title="Item Three" role="presentation"><a class="slds-tabs_default__link" href="javascript:void(0);" role="tab" tabindex="-1" aria-selected="false" aria-controls="tab-default-3" id="tab-default-3__item">Item Three</a></li>
       </ul>
       <div id="tab-default-1" class="slds-tabs_default__content slds-show" role="tabpanel" aria-labelledby="tab-default-1__item">
           <article class="slds-card">
               <div class="slds-card__header slds-grid">
                   <header class="slds-media slds-media_center slds-has-flexi-truncate">
                       <div class="slds-media__figure">
                           <span class="slds-icon_container slds-icon-standard-contact" title="description of icon when needed">
                               
                           </span>
                       </div>
                       <div class="slds-media__body">
                           <h2>
                               <a href="javascript:void(0);" class="slds-card__header-link slds-truncate" title="[object Object]">
                                   <span class="slds-text-heading_small">Card Header</span>
                               </a>
                           </h2>
                       </div>
                   </header>
                   <div class="slds-no-flex">
                       <button class="slds-button slds-button_neutral">New</button>
                   </div>
               </div>
               <div class="slds-card__body slds-card__body_inner">Card Body (custom goes in here)</div>
               <footer class="slds-card__footer">Card Footer</footer>
           </article>
       </div>
       <div id="tab-default-2" class="slds-tabs_default__content slds-hide" role="tabpanel" aria-labelledby="tab-default-2__item">Item Two Content</div>
       <div id="tab-default-3" class="slds-tabs_default__content slds-hide" role="tabpanel" aria-labelledby="tab-default-3__item">Item Three Content</div>
   </div>
</aura:component>

> What did you expect to happen?
The border should shows

> What actually happened?
The border missing.

**Comment by stefsullrew** [comment]
Hi @oek2 - That is by default. There are many cases where a component in a card can be stand alone (it gets card styling) or inside a tabset, modal, or another card (it renders invisibly by default). 

However, we created a class that will be in patch next time called `.slds-card_boundary`. You can place this on the `.slds-card` node to define your card with rounded, bordered cards.

Cheers

**Comment by mk0x9** [comment]
@stefsullrew thanks!

But Card component probably should preserve border styling inside Tabs

**Comment by stefsullrew** [comment]
No, in fact it was purposely removed. (Since everything needs to be in a card, and components are reusable in many situations, this is the decision UX made.) But you can add it back in where you want to have it show up.

**Comment by mk0x9** [comment]
Oh, thanks!

Sorry for offtopic but there is second issue, `slds-theme--alert-texture` isn't applied anymore on Card inside Tabs too

**Comment by mk0x9** [comment]
@stefsullrew that's how I was using it. Thanks for clarification!
