### ISSUE TITLE
Lightning Design Website not viewable in IE11

### ISSUE THREAD

**Issue by TonyWhiteSMS** [salesforce-ux/design-system#497]
The https://lightningdesignsystem.com/ website does not work under IE11

![lightningdesignie11](https://user-images.githubusercontent.com/12590114/30618390-82b3e8e0-9ddd-11e7-860c-b1bb51c5c749.JPG)

> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

**Comment by stefsullrew** [comment]
Thanks for this. It's already been fixed in our latest deploy. Let me know if you still see it!
