### ISSUE TITLE
Disabled Tabs

### ISSUE THREAD

**Issue by nelsonra** [salesforce-ux/design-system#5]
Hi,

I was using 'tabs--scoped' and noticed that there currently isn't a style for disabled tabs. I think this would be a nice feature (style) going forward. I know some may say just remove the tabs but in some cases you may not want to completely hide the tab. 

Example : enable tabs when an action has been completed

Any thoughts for or against this style?

Thanks
Nelson Ramalho

**Comment by topherauyeung** [comment]
Thanks for the recommendation Nelson! We hadn't yet encountered this use case when designing the Lightning Experience, which is why it's not currently in the system, but we'll definitely look at bringing in styles for disabled tabs.

**Comment by rickschmoo** [comment]
Thanks for the request. After consideration, this does not fit with our Lightning Design patterns.
