### ISSUE TITLE
svg not ALWAYS displayed 💡

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#503]
I'm using angular 4.4.4 (with cli 1.4.5) and slds design css with svg icon.

and trough whole my app I always have problem to display my svg correctly, sometimes it show all icon, sometime nothing, and sometimes 50% of them are displayed. Dont' understand why, any idea?

here is an example when I come on my page : 
![image](https://user-images.githubusercontent.com/2789203/31384927-6615a8f6-adc1-11e7-8021-bf8c32a67af0.png)

then when I refresh page here's result: 
![image](https://user-images.githubusercontent.com/2789203/31384970-984e02c8-adc1-11e7-8773-a4e52c662fb1.png)

another GIF in action: here I just switch  tab inside my app : 
![svg error2](https://user-images.githubusercontent.com/2789203/31385296-0fc55abc-adc3-11e7-919c-260994261eda.gif)

very strange don't know if it's angular OR angular-cli and it's `ng s` dev mode, or browser problem or slds and of course I can't reproduce on plunker, here I have plunker https://embed.plnkr.co/dQJIX2lMw8WOl9rQepGX/ but it works everytime! when you switch betwen Home and ABOUT menu. I specify it works in firefox all the time !

> Are any specific browsers impacted by this bug?
actually tested on chrome last version

> Which version of the Salesforce Lightning Design System are you using?
v2.3.1

**Comment by engai** [comment]
@istiti Not sure why this may be happening without being able to inspect your app. Seems like assets are coming in. Would it be possible to provide a Codepen with this issue reproduced?

**Comment by engai** [comment]
@istiti any updates on this? Closing soon if this is no longer an issue.
