### ISSUE TITLE
.slds-text-link_faux is either wrong in docs or not implemented

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#505]
Go to: https://lightningdesignsystem.com/utilities/interactions
And choose "Faux Link On A Span"
Notice nothing happens to the span/link.

From checking the source code it looks like the old BEM format has the class implemented:

.slds-text-link--faux

But the newer one isn't - however there is a new this a new class 'slds-type-focus'

So I'm assuming the docs should describe this class instead.

**Comment by engai** [comment]
@mattgoldspink Hey Matt, looks like you've caught another bug. We'll go ahead and update the our styles and docs. Thanks!

**Comment by engai** [comment]
@mattgoldspink the docs are correct and we've added the new BEM format to our styles. Fix should be available in our next release. Thanks again for pointing out the bug!

**Comment by mattgoldspink** [comment]
Awesome - thanks @engai
