### ISSUE TITLE
Picklists missing border when moving between 2.2.2 and 2.4.3

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce-ux/design-system#506]
I'm updating some of our templates from 2.2.2 to 2.4.3 and our Picklist's stopped rendering correctly. This is in all browsers:

2.2.2
![image](https://user-images.githubusercontent.com/415690/31596705-8056e3ce-b244-11e7-9f23-b1c0b37413e6.png)

2.4.3 
![image](https://user-images.githubusercontent.com/415690/31596690-733bd3ca-b244-11e7-96c8-eedde1979f4f.png)

I've setup an example in JSBin: http://jsbin.com/wuxanez/edit?html,css,output

This uses the older 2.2.2 slds-picklist example code from here: https://archive-2_2_2.lightningdesignsystem.com/components/picklist#flavor-base-picklist-open

We can upgrade our templates since we ship our own copy of SLDS but I'm sure this may affect others and wanted to flag it.

I'd assume there would be a list of breaking changes more clearly highlighted in the docs if this break is intentional?

**Comment by engai** [comment]
@mattgoldspink thanks for surfacing this issue. This break was not intentional and is a bug on our end. We'll make the fix and will be sure to update you when it is released.

**Comment by engai** [comment]
This is still on our roadmap and an issue we look forward to fixing. Thanks for your patience.

**Comment by alexiscordova** [comment]
This fix should be coming in a future release. Thanks for the report!
