### ISSUE TITLE
Custom Scope to the CSS in your Static Resource

### ISSUE THREAD

**Issue by mamplo** [salesforce-ux/design-system#509]
When will Winter '18 be added as a Custom Scope to the CSS in your Static Resource

**Comment by AnzeKovac** [comment]
Same question from my side, unscoped 2.4.4 release breaks classic header and sidebar

**Comment by jason-paperculture** [comment]
Are there any updates on when it will be updated?

**Comment by dreamforce-ux-demo** [comment]
The issue is being worked on. cc: @brandonferrua @DrBoolean

**Comment by mamplo** [comment]
Any updates on when Winter '18 will be added to the picklist for the css customizer.
https://tools.lightningdesignsystem.com/css-customizer

**Comment by DrBoolean** [comment]
Hi, we're adding it now and should deploy here in the hour.

Let me recommend https://github.com/salesforce-ux/design-system-compiler as a more automatable solution if you need scoped css.

**Comment by DrBoolean** [comment]
deployed

**Comment by engai** [comment]
@mamplo we've added Winter '18 to the css customizer. Moving forward, we recommend using our `design-system-complier` to generate a scoped css file. This way you'll have an updated file in your project for each release.

https://github.com/salesforce-ux/design-system-compiler

**Comment by istiti** [comment]
Can we download slds static ressouce without old deprecated syntax — ? To significatly reduce file size? Thanks
