### ISSUE TITLE
Uneven border width on High DPI screens

### ISSUE THREAD

**Issue by marceloatg** [salesforce-ux/design-system#510]
I have notice this pattern since SLDS 2.3.1 (when I started heavily using SLDS). Some components present uneven border widths when displayed on high DPI screens due to OS scaling.

It's a small detail, I know, but lightning is so beautiful that it should aim for perfection. Below some examples, taken from a 1920X1080 display with 100% scaling on Windows 10 and 3840X2160 with 150% scaling on Windows 10.

**Page Header**

![fhd](https://user-images.githubusercontent.com/3721845/31679393-bba381ce-b34f-11e7-8ca8-17c4a7f378a9.png)

![uhd](https://user-images.githubusercontent.com/3721845/31679622-726a24a8-b350-11e7-8960-d77a370a0905.png)

**App Launcher**

![fhd](https://user-images.githubusercontent.com/3721845/31679772-f931c824-b350-11e7-93c4-5517e24b7497.png)

![uhd](https://user-images.githubusercontent.com/3721845/31679892-541768e8-b351-11e7-9d61-0221c1901de2.png)

**Comment by marceloatg** [comment]
A small update, I noticed that Firefox 56.0.1 (64-bit) works with scaling differently, and thus not show this problem. I have tried chrome, Edge, and Firefox, and so far Firefox is the only browser able to render it flawlessly.

**Comment by engai** [comment]
@marceloatg Unfortunately, as you said, this is an issue with how different browsers and devices scale borders. We'll look into any possible solutions for this. Thanks for pointing this out!
