### ISSUE TITLE
IconButton with state warning

### ISSUE THREAD

**Issue by skorenuk** [salesforce-ux/design-system#513]
In SLDS icon buttons have state error `slds-button_icon-error` but it doesn't have warning state.
In some cases, it would be necessary to have the ability to use warning state like `slds-button_icon-warning`

https://www.lightningdesignsystem.com/components/button-icons/

**Comment by engai** [comment]
@skorenuk thank you for your feedback. Our team will discuss whether a warning state would be a good fit for our design system.
