### ISSUE TITLE
Inline Combobox does not resize properly and looks poorly on multiple lines

### ISSUE THREAD

**Issue by nhazar** [salesforce-ux/design-system#515]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
<img width="1060" alt="screen shot 2017-11-09 at 11 15 04 am" src="https://user-images.githubusercontent.com/1245611/32624829-4b1527a8-c53f-11e7-951c-323beefd222f.png">
<img width="1062" alt="screen shot 2017-11-09 at 11 15 16 am" src="https://user-images.githubusercontent.com/1245611/32624832-4c821bbe-c53f-11e7-96b7-eeae450abb4c.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
it's a bug with how the inline combobox adjusts its input width where there are multiple elements.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?
design-system@2.3.0-rc.1

> What steps and/or code are needed to reproduce this issue?
just create a combobox with inline=true

> What did you expect to happen?
to see selected items aligned properly and the input fields width adjusts accordingly

> What actually happened?
items would move to the next line but the input field will shrink.

**Comment by engai** [comment]
@nhazar thank you for bringing up this issue. The inline variant of combobox was not designed to handle more than one line as you have shown. If you expect more than 1 line of pills in your particular use case, we suggest using the base combobox.

We'll discuss as a team whether we want to change the inline variant or update the docs to make it more clear how the variant behaves. Thanks again for bringing this to our attention and we'll keep you updated!
