### ISSUE TITLE
Checkbox Button Group: buttons missing border when content wraps in narrow container

### ISSUE THREAD

**Issue by douglascayers** [salesforce-ux/design-system#517]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

https://codepen.io/DouglasCAyers/pen/JOMpNN/

![image](https://user-images.githubusercontent.com/4142577/32987337-4d2fb816-ccae-11e7-945d-d37b3c40dd22.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

A bug when checkbox button group's content (the buttons) continue beyond the width of their container.

The ensure that checkbox buttons in the checkbox button group wrap when in a narrow container then first step is to add `slds-wrap` to the `<div class="slds-checkbox_button-group">` . Although this achieves the effect of wrapping the checkbox buttons to fit within the container the bug is that each checkbox button does not display correct border.

The border is applied to the checkbox button group wrapping element, I think for this case the border should actually be applied at the checkbox button element so that the buttons have a border when they wrap in narrow containers.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

I tested with Base Checkbox Button Groups
https://www.lightningdesignsystem.com/components/checkbox-button-group

> Are any specific browsers impacted by this bug?

I've only tested in Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

> Which version of the Salesforce Lightning Design System are you using?

Winter '18 Lightning Components
SLDS v2.4.5 is used in the codepen example

> What steps and/or code are needed to reproduce this issue?

https://codepen.io/DouglasCAyers/pen/JOMpNN/

> What did you expect to happen?

I expected each checkbox button (`slds-checkbox_button`) to have its own border when the content wrapped to multiple lines.

> What actually happened?

The border is only applied to the `slds-checkbox_button-group` containing element so the checkbox buttons within the group that wrapped to multiple lines do not have complete borders.

**Comment by DouglasCAyers** [comment]
As workaround in my Lightning Component I'm applying these styles:

1. Add `slds-wrap` to the checkbox button group
`<div class="slds-checkbox_button-group slds-wrap">`

2. Declare each checkbox button with border classes
`<span class="slds-button slds-checkbox_button slds-border_top slds-border_right slds-border_bottom slds-border_left">`

3. Remove the border from the checkbox button group
```
.THIS .slds-checkbox_button-group {
    border: none;
}
```

**Comment by engai** [comment]
@DouglasCAyers As of now, checkbox button groups aren't a responsive component, so we do not currently support this pattern. Thank you, however, for your feedback. Our team will take this into consideration.

**Comment by DouglasCAyers** [comment]
Hi @engai,

Thanks for the follow up. Although I'm dissappointed in the response, why close the issue rather than leave it open labeled "feature-request"?

I understand that the component is not responsive, that is why I opened this issue.

Is there a different list of feature requests that the open source community can monitor?

I feel like you've simply shutdown my attempt to help the UX team improve the components they are providing to us developers. This discourages me from wanting to submit a pull request to help introduce this feature as suggested by @stefsullrew https://twitter.com/stefsull/status/933169619358982144

Thanks,

Doug

**Comment by engai** [comment]
@DouglasCAyers my apollogies for closing the issue. You’re completely right and we encourage you to contribute in the future. 

I’ve reopened the issue and will tag accordingly. We’ll keep you updated as we discuss as a team. 

Thanks!

**Comment by DouglasCAyers** [comment]
Thanks @engai !
