### ISSUE TITLE
Any plans for react-native version?

### ISSUE THREAD

**Issue by kbrandwijk** [salesforce-ux/design-system#518]
I have seen the iOS and Android versions, and was wondering if you have any plans to create React-native versions of the components?

**Comment by ButuzGOL** [comment]
+1

**Comment by kbrandwijk** [comment]
Update: as a first step, I have created an icon definition, for use with `react-native-vector-icons` for the SLDS icons font: https://www.npmjs.com/package/react-native-vector-icons-slds.

Demo here: https://snack.expo.io/@agartha/react-native-icons-slds-demo

This will also be used in the library I'm building: `react-native-lightning`
