### ISSUE TITLE
Lightning component head glitch

### ISSUE THREAD

**Issue by ackonsult** [salesforce-ux/design-system#525]
Im am experiencing a strange glitch in my Winter '18 Org.

At the first mouse move the text, it moves a bit left and doubles the last character, which is the cut off.

Example Screenshot:
<img width="342" alt="bildschirmfoto 2018-01-09 um 21 40 39" src="https://user-images.githubusercontent.com/999524/34742285-e8ef5e50-f585-11e7-8498-ecfedaae8344.png">

Tested with Safari on Mac Version 11.0.2 (12604.4.7.1.4). Not happening in Chrome.

**Comment by engai** [comment]
@ackonsult sorry to hear that you're having this issue. Could you please provide a Codepen (or something similar) with your issue reproduced?

**Comment by engai** [comment]
@ackonsult This likely an issue with the platform and localization, rather than the design system. Closing this, but feel free to re-open or comment if you feel that this is an issue with our styles.

Thanks!
