### ISSUE TITLE
slds-popover last-child global margin

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#526]
i think such style is very general and it applies to all last children (maybe using > is solution)
```
.slds-popover *:last-child {
    margin-bottom: 0;
}
```

https://github.com/salesforce-ux/design-system/blob/master/ui/components/popovers/base/_index.scss#L103

**Comment by engai** [comment]
Hi @ButuzGOL, we also noticed this when revisiting the popover component and agree that it is a very general selector. We'll look into this further to see how a change might affect our users. Thank you for pointing this out.

cc: @stefsullrew @brandonferrua
