### ISSUE TITLE
small button /small input field)

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#527]
it's me or [this button section](https://www.lightningdesignsystem.com/components/buttons/#content)

not have : 

```
Selector | .slds-button_small
Creates a smaller button style
.slds-button
```

please can one of your team check/be sure all current documented selectors exist/works a lot bugs exist

in same order: i think small input (compressed) to show more infos on screen, for accounting application  it is very important.

**Comment by engai** [comment]
Hi @istiti, thank you for pointing out this issue. `.slds-button_small` is a deprecated selector and we've made a change to make this apparent in the selector table. This should be available in the next release.

As for your feature request for a more compressed input, we'll discuss with the rest of the team and circle back. Thanks!

**Comment by istiti** [comment]
@engai to avoid open issue the awesome issue will be to add button on each section in documentation "Overview of CSS Classes" to report problem and add some text if needed to explain something special, like a review like a feedback, then you can check them without opening new issue on github. I mean something like : 

![image](https://user-images.githubusercontent.com/2789203/35032728-4061b272-fb68-11e7-80c9-400cc86d7ebf.png)



this will avoid numerous opened issues due to documentations not updated

thanks

**Comment by stefsullrew** [comment]
Hi @istiti ... `.slds-button_small` was deprecated a couple of years ago when all buttons were made the size of small buttons. We're even contemplating the idea of "even smaller buttons" now. ;)

Thanks for the suggestion about creating a way to post a bug from the docs. I'll pass that along. Cheers!
