### ISSUE TITLE
Issue with bower

### ISSUE THREAD

**Issue by black-signature** [salesforce-ux/design-system#528]
As mentioned in the lightning website, "bower install salesforce-lightning-design-system" is not fetching the latest 2.5.0 build, instead it is downloading 2.3.1

**Comment by engai** [comment]
Hi @black-signature, we've dropped support for bower as they no longer support themselves. We'll work on getting the bower command off of our website.

**Comment by engai** [comment]
@black-signature the bower command has been removed from our downloads page and we've updated our FAQ to address this.

Thank you for bringing this issue to our attention.
