### ISSUE TITLE
Add pagination component

### ISSUE THREAD

**Issue by awsomedesigner** [salesforce-ux/design-system#529]
Hello all

I would like to suggest one features request as I found it necessary in lightningdesignsystem.
As I know, in salesforce there are lots of data to show in data tables. so developer needs to add pagination in data tables. 
So please add pagination component in lightningdesignsystem.

Thank you

**Comment by engai** [comment]
@awsomedesigner thanks for the suggestion. We'll discuss as a team if this is a design pattern we'd like to follow.

**Comment by awsomedesigner** [comment]
Welcome, and is there any way I could help in designing, for example, HTML and CSS and all that stuff which are used in the design.
