### ISSUE TITLE
Datepicker - year dropdown markup question

### ISSUE THREAD

**Issue by djlimbs** [salesforce-ux/design-system#53]
I'm trying to implement JS for the datepicker, and looking at the preview for the New Lightning Experience in a Winter '16 org, it looks like the year dropdown is using a `<select>` where as the SLDS's markup uses a `<button>` tag. Which one do you recommend we use? Also, should we base the datepicker's behavior (what triggers it to open, where it focuses, how it closes) on the New Lightning Experience's behavior? Thanks

**Comment by srohde** [comment]
Can you please add more information and a screenshot?

**Comment by djlimbs** [comment]
Sure, attached are two screenshots - The first is of the "native" datepicker in Salesforce's New Lightning Experience. The second is of the datepicker guide for the Lightning Design System. In 1) the year dropdown is implemented as a <select>. In 2) it is implemented as a button without a dropdown (so we assumed it would be an SLDS picklist). How do you recommend the year dropdown in SLDS be implemented? Which of the two should we follow? Our first assumption is to mimic the native markup and functionality. 

<img width="1035" alt="screen shot 2015-10-19 at 3 13 01 pm" src="https://cloud.githubusercontent.com/assets/4561661/10590010/1c9b23e4-7674-11e5-8969-ee59ed9bc191.png">
<img width="886" alt="screen shot 2015-10-19 at 3 13 35 pm" src="https://cloud.githubusercontent.com/assets/4561661/10590021/1ea382d0-7674-11e5-8295-6fa802736f17.png">

**Comment by djlimbs** [comment]
Do you need any more info or screenshots for this question? Thank you.

**Comment by stefsullrew** [comment]
No, I see what you're saying, @djlimbs — looks to me like we need to update our implementation. Stay tuned.

**Comment by ankushsomani09** [comment]
Can anyone help me in implementing Lightning DatePicker in vf page.

**Comment by rapsacnz** [comment]
I'm pretty late to the party, but I have built one. Look at my blog here:
http://www.soliantconsulting.com/blog/2016/08/build-lightning-date-picker. Let me know if it works for you :)

**Comment by kaelig** [comment]
The reference implementation is the one in the Lightning Design System. Sorry if there was a difference in the Lightning UI.

And thank you @rapsacnz for sharing!

**Comment by akshay0606** [comment]
Hello Everyone,
I tried to use the date picker code from (https://www.lightningdesignsystem.com/components/datepickers/#content), however it doesnt work, do i need to modify something in the date picker code or i need to use a custom date picker from jquery in a visualforce page with lightning css Thanks in Advance!

**Comment by rapsacnz** [comment]
The datepicker is static html. To animate it, you can do this yourself or use something like my implementation -  http://www.soliantconsulting.com/blog/2016/08/build-lightning-date-picker.

**Comment by georgekenessey** [comment]
@akshay0606 here is another option:  http://aljs.appiphony.com/#!/datepickers

If you need a full Lightning Date picker then I would suggest: http://www.lightningstrike.io/#!/strikeDatepicker

In full disclosure, these are both open source projects we support at Appiphony
