### ISSUE TITLE
compound form error

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#530]
![image](https://user-images.githubusercontent.com/2789203/35215034-5bce7a82-ff63-11e7-8475-72a9cedbc0c1.png)

source: https://www.lightningdesignsystem.com/components/form-layout/#content

**Comment by engai** [comment]
@istiti Thanks for pointing this out. A fix will be coming in a future release.

cc: @brandonferrua

**Comment by engai** [comment]
This has been resolved with https://github.com/salesforce-ux/design-system/commit/42cb1d09dcfaec5d9db1f2f4971a23d8510d32d5#diff-f7673f8f4eb5c1e8baf58777b2189176
