### ISSUE TITLE
Lightning design grid is not compatible  in IE11

### ISSUE THREAD

**Issue by Artirobo** [salesforce-ux/design-system#531]
i have a problem in IE11 grid layout slds-size-** which is making a grid as bad way but in other browser is great all working fine ..

<div class="slds-card__body">
        <div class="slds-grid slds-wrap">
            <div class="slds-theme--default slds-size--1-of-1 slds-medium-size--6-of-6 slds-large-size--12-of-12" >
                <div class="slds-grid slds-wrap slds-grid--pull-padded">
                    <div class="slds-box slds-m-around--small slds-size--1-of-3 slds-medium-size--2-of-6 slds-large-size--3-of-12" 
                   >
                        <span class="slds-avatar slds-avatar--large slds-avatar--circle">
                          sample work
                        </span>
                        <h4> welcome</h4>
                        <a routerLink="album/{{album.id}}" class="slds-button slds-button--neutral">Album Details</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
so wat is wrong its only in IE11 not proper grid how can i solve this issue ??

Chrome  view
![chrome view](https://user-images.githubusercontent.com/25945813/35509060-d30ea4a2-051a-11e8-9b1b-fac0f915ad11.PNG)

IEView
![ieview](https://user-images.githubusercontent.com/25945813/35509061-d361f878-051a-11e8-9c2a-212aec8f44d0.PNG)

i have gone through this 
https://salesforce.stackexchange.com/questions/206063/lightning-components-styling-is-not-working-in-internet-explorer-11-but-work-fi

**Comment by engai** [comment]
@Artirobo Thanks for surfacing this. This likely due to known issues with IE11 and CSS Flexbox.

@brandonferrua do you have more insights on this?
