### ISSUE TITLE
Cards missing slds-card_boundary css

### ISSUE THREAD

**Issue by jmdohn** [salesforce-ux/design-system#532]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

The top level article element is missing the slds-card_boundary element to have the border rendered.
[Cards on lightningdesignsystem.com](https://www.lightningdesignsystem.com/components/cards)

This impacts the lightning base component:
<lightning:card title="test">
</lightning:card>

A case will be raised about the base component as well.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Affects existing component that is missing class for proper rendering in Spring '18.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

lightning:card

> Are any specific browsers impacted by this bug?

NA

> Which version of the Salesforce Lightning Design System are you using?

Spring '18

> What steps and/or code are needed to reproduce this issue?

<!--
e.g.

```<lightning:card title="test">
</lightning:card>
```

> What did you expect to happen?

Border to appear.

> What actually happened?

No border appears.

**Comment by engai** [comment]
Hi @jmdohn, our cards have borders by default via the `.slds-card` class. However, the current pattern we follow is that for cards nested within cards (and a few other elements), that style is removed.

The `.slds-card_boundary` modifier can be added via a class attribute if the border is needed. You can find the styling here: https://github.com/salesforce-ux/design-system/blob/master/ui/components/cards/base/_blame.scss#L37

**Comment by jmdohn** [comment]
I found the change in 2.4.1:

> Cards
>Added slds-card_boundary class to provide card-like look when component is inside a tabset

This is actually the case that I was writing about so I've added slds-card_boundary to each lightning:card via the class element.
