### ISSUE TITLE
LDS docs: New Accessibility Pattern Suggestion for truncated text

### ISSUE THREAD

**Issue by cliffordfajardo** [salesforce-ux/design-system#533]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

I'm loving the new [Accessibility Section in the LDS docs](https://www.lightningdesignsystem.com/accessibility/overview/)! 

![screen shot 2018-02-14 at 6 24 27 pm](https://user-images.githubusercontent.com/6743796/36238068-f9d1e1e8-11b4-11e8-9f42-7a29d22cffe0.png)

I have a suggestion for a new general pattern - text truncation. The docs already have an accessibility pattern for tooltips, so it feels natural to have text truncation added there, no?

I was trying to contribute a new page for text truncation (or truncated text), but I had trouble finding out if the [lightningdesignsystem.com](https://www.lightningdesignsystem.com) docs were open source.

The [tooltips](https://www.lightningdesignsystem.com/accessibility/patterns/tooltip) page serves as an excellent base template for the truncated text pattern (of course with modifications)

![screen shot 2018-02-14 at 6 36 22 pm](https://user-images.githubusercontent.com/6743796/36238205-0ebbc2ee-11b6-11e8-83ae-4fb03ad9704c.png)

**Comment by SiTaggart** [comment]
Thanks for your interest in accessibility patterns @cliffordfajardo!

I'm actually curious what exactly about truncation you would call out in an accessibility pattern. 

The patterns are a reflection of the major software UI patterns or Assistive Technology supported patterns, which form the majority of the ARIA specifications. So they are dedicated vehicles for accessibility. 

To me, truncation feels like a UI / UX approach to dealing with tight spaces, which would require some accessibility guidelines to make it correctly accessible? Unless I'm misunderstanding what you mean by text truncation?

**Comment by engai** [comment]
@SiTaggart Thanks for your response!

@cliffordfajardo any thoughts on Simon's comments?
