### ISSUE TITLE
Visual Picker Disabled State Unclear

### ISSUE THREAD

**Issue by JohnHeadIV** [salesforce-ux/design-system#534]
### Visual Picker Disabled State

Visual Picker component when an option is disabled provides no visual feedback of this state. Mouse overs provides feedback and the input is correctly disabled. I would suggest that a visual appearance should also be alternated to ensure clear understanding of the state of the option. I've attache a screen shot to demonstrate. 

![image](https://user-images.githubusercontent.com/18658298/36260943-d88382f4-1230-11e8-860c-870a4eab3b8f.png)

### Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
I would classify this as a log grade bug rather then a feature request but understand if its treated as a feature request.

###  Are any specific browsers impacted by this bug?
View in Chrome 64 on Win10.

###  Which version of the Salesforce Lightning Design System are you using?
View in Documentation site for 2.5.2 on 2/15/18. 

###  What steps and/or code are needed to reproduce this issue?
Utilize getslds.com site under VisualPicker component. Select Disable Option.

###  What did you expect to happen?
Visual change on inputs that are disabled. 
###  What actually happened?
No visual change to indicate state change.

**Comment by engai** [comment]
@JohnHeadIV Thanks for pointing this out. Our team will discuss different ways to better indicate the disabled state, and circle back to you.

**Comment by engai** [comment]
This is on the roadmap and should be available with Winter '19

**Comment by JohnHeadIV** [comment]
Might want to update state/bot and start using Roadmap or some other flag to identify open issues that are being worked on and thus shouldn't just be closed.

**Comment by engai** [comment]
@JohnHeadIV this has been resolved with https://github.com/salesforce-ux/design-system/commit/b135fdf1c78168d935e53ad95a607fc34a0c82ac
