### ISSUE TITLE
New Spring .slds-gutter class targets all child .slds-col elements

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#535]
![screen shot 2018-03-05 at 11 04 00 am](https://user-images.githubusercontent.com/8738640/36988723-297d2e7a-2065-11e8-9e3e-da67e513fad1.png)

I'm running into a bug where child grids are being affected by guttered-grids in their ancestry because the selectors for columns in a grid with gutters are too vague. They should only target immediate children of the grid, but they are currently targeting any child column in the DOM tree. This is problematic for nested grids.

In the screenshot, the highlighted column is not an immediate child of a guttered-grid, but it is still incorrectly receiving padding styles. These selectors should be more like the following:

`.slds-scope .slds-gutters_xx-small > .slds-col`

**Comment by kvizcarra** [comment]
We're also experiencing this issue. We can't just drop in a component that uses `.slds-col` into a component tree that has `.slds-gutters` at a higher level without having to make some tweaks.

**Comment by engai** [comment]
@kevinberonilla @kvizcarra thanks for sharing your concerns. You make a great point that the grid gutters classes should be more specific. My initial concern is the uncertainty around how such a change would impact features that unintentionally rely on the current specificity. Since these are such widely used utility classes, we'll discuss as a team & circle back with you.

**Comment by engai** [comment]
@kevinberonilla @kvizcarra We'll have new gutter classes available in Winter-19 to cover this use case. I'll be sure to let you know when those are released!

**Comment by engai** [comment]
Hey folks, this has been resolve with https://github.com/salesforce-ux/design-system/commit/9698af1a8b0391b9b786b50251e0c19f7eb9014a. There are now specific classes, `.slds-gutters_direct*` that target direct children only.
