### ISSUE TITLE
feature request : flex datatable

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#536]
Can we imagine the [datatable ](https://www.lightningdesignsystem.com/components/data-tables/#content) component in a flex way ?

**Comment by istiti** [comment]
cc @engai

**Comment by engai** [comment]
Hi @istiti, thanks for the feature request on data-tables. We'll discuss as a team and circle back with you.

cc: @brandonferrua @stefsullrew

**Comment by SiTaggart** [comment]
Generally speaking, updating the display property of a table element usually removes the "table" semantic from the element completely. This is especially problematic for screen reader users. We try to avoid it.

I know @cordeliadillon has experimented in the past with display flex tables, with limited success

**Comment by istiti** [comment]
I partially agree. Same (otherwise) more limits we get in <table> approach.  I think both should be available IMhO

Thanks for reply

Cc @SiTaghart

**Comment by cordeliadillon** [comment]
I had very limited success and would not recommend using `display: flex` on a table. Here's a pen from about a year ago showing my findings: https://codepen.io/cordelia/pen/bqKwVp 

That was a year ago, so some things may have changed, but generally I'm not optimistic.

**Comment by stefsullrew** [comment]
I'm on the same page as @cordeliadillon and @SiTaggart here. When a table is needed semantically, then a table should be used — but not with an override on the display property. Let's let the screen reader have all the semantic goodness that it gets from using the proper elements.

Cheers
