### ISSUE TITLE
Empty state assets (icons / images)

### ISSUE THREAD

**Issue by JAertgeerts** [salesforce-ux/design-system#537]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="830" alt="screen shot 2018-03-13 at 19 16 48" src="https://user-images.githubusercontent.com/2192516/37361424-27070cda-26f3-11e8-8e50-59467de62df3.png">

[https://lightningdesignsystem.com/guidelines/messaging/components/illustration-inline-text/](https://lightningdesignsystem.com/guidelines/messaging/components/illustration-inline-text/)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The icons / images referred to in the guidelines with regard to empty states are not included in the LDS. Can these be added for consistency?

**Comment by engai** [comment]
@JAertgeerts Thank you for pointing this out. We'll work on adding those assets and updating our guidelines.

**Comment by engai** [comment]
@JAertgeerts We now have an Illustration component with new Empty States - https://www.lightningdesignsystem.com/components/illustration/

**Comment by e02d96ec16** [comment]
@engai I see the system failure one didn't make it, and I'm sorely needing one. Was it intentional?
