### ISSUE TITLE
Brandband: Absolute background-image url does not allow usage in static resource

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#539]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="568" alt="Since it is required..." src="https://user-images.githubusercontent.com/1682504/37826003-28d4c484-2e92-11e8-9be0-de50e6646a85.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The new BrandBand component currently is [set to an absolute image path](https://github.com/salesforce-ux/design-system/blob/master/design-tokens/salesforce-skin/image-paths.yml#L10). This breaks when importing SLDS via a StaticResource or simply running above webroot, e.g. `github.io/lds/...`.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

BrandBand > Default

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

`2.5.2`

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

**Comment by engai** [comment]
Hey @fspoettel, we don't suggest bringing in SLDS as a static resource. But, in the case that you need to, the path above leads to the assets here: https://github.com/salesforce-ux/design-system/tree/master/assets/images/themes/oneSalesforce.

**Comment by fspoettel** [comment]
@engai Thank you for the response. I am aware of the suggestion and have moved our codebase to `apex:slds` which solved the problem in our Salesforce product. Since the URL is currently prefixed as an absolute path (`/`) in the npm distribution, the `BrandBand`component is not usable in some environments however. One use case that currently cannot be accomplished is documentation hosted on Github Pages since the url pattern for that is `user.github.io/repo/xxx`. See [here](https://propertybase.github.io/react-lds/?knob-Styled=true&knob-No%20background=false&knob-Cover%20background%20instead%20of%20contain=false&selectedKind=BrandBand&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) for an example where the BrandBand can not render due to the image 404ing.

Feel free to close the issue if you do not plan to support this use case, I can totally understand if that is the case.
