### ISSUE TITLE
Use @salesforce-ux/icons alone

### ISSUE THREAD

**Issue by andresgutgon** [salesforce-ux/design-system#540]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Hi, first of all congratulations for this project. It's amazing. I'm opening this issue because I don't know what's the right place to do this question. I could not find a Slack channel or something similar to do it.

Please close the issue as you considere. 

I will explain my question hopping you can help me :)

We use `design-system's` sprites and we would like to add some of our own to these sprites. I thought maybe we could reuse your scripts to rebuild those sprites + adding our icons. I saw you're using this package: https://www.npmjs.com/package/@salesforce-ux/icons

What happen is that I can not see this package in Github
![image](https://user-images.githubusercontent.com/49499/37874432-5a027152-302f-11e8-8682-bf19eb87822a.png)

It's a private repo? Can we see the scripts to generate those sprite and add some of our icons? 

I'm aware that maybe this project is not intended for using alone. Anyway it would be great if you can help us to understand if this is possible.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

No

> Are any specific browsers impacted by this bug?

No

> Which version of the Salesforce Lightning Design System are you using?

Latest

> What steps and/or code are needed to reproduce this issue?

Any

> What did you expect to happen?

I don't know :)

**Comment by andresgutgon** [comment]
Anyone can help here? Thanks 😺

**Comment by engai** [comment]
Hey @andresgutgon, this is the perfect place to ask your question. 

You are correct in that the repository mentioned above is private. At this time, we don't offer support for adding custom icons to our sprite sheet. 

@erlswtshrt do you have any additional insights on this?

**Comment by andresgutgon** [comment]
Thanks @engai  for your response 👏 
It would be great if we could be able to generate a custom sprite sheet or be that repo public. Thanks a lot

**Comment by engai** [comment]
@andresgutgon No worries!

At this time, we have a few concerns around making that repo public. Primarily, we currently have an internal process for iconography in our system, and in order to preserve design consistency, we want to prevent teams from customizing their own sprite sheets.

Closing this issue, but we'll be sure to reopen and comment if anything changes.

**Comment by andresgutgon** [comment]
No problem, thanks for the explanation 😄
