### ISSUE TITLE
Hello world demo

### ISSUE THREAD

**Issue by abelardolg** [salesforce-ux/design-system#541]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

I miss a "Hello world" step-by-step tutorial by newbies for newbies.

Excellent components!

**Comment by abelardolg** [comment]
I have executed 

> npm install @salesforce-ux/design-system --save

and pasted the html code showed [here](https://www.lightningdesignsystem.com/components/picklist/) but I miss a guide how to add the css styles.

**Comment by engai** [comment]
Hey @abelardolg, we actually have a [Design System Starter Kit](https://github.com/salesforce-ux/design-system-starter-kit). This is a simple environment that can get you started with our design system. For a quick tutorial, check out the one we introduced at a workshop at TrailheaDX. You can find a link to that on [this page](https://starter-kit-demo.herokuapp.com/).

For more info on where to find the css assets within the node_module, check out our [documentation on npm](https://www.npmjs.com/package/@salesforce-ux/design-system).

Let us know if you have any questions or still have issues getting started.

**Comment by engai** [comment]
Closing this issue. But, please let us know if you have any additional questions and feel free to reopen if necessary.
