### ISSUE TITLE
Unsafe attempt to load URL Issue with 42 API version and URLFOR($Assets.SLDS)

### ISSUE THREAD

**Issue by maximelets** [salesforce-ux/design-system#543]
Hey guys. Just fyi. When I create a page with API version 42 I facing with this issue.

> Unsafe attempt to load URL https://xxxxx-dev-ed.my.salesforce.com/_slds/assets/icons/utility-sprite/svg/symbols.svg from frame with URL https://xxxxx-dev-ed--csplay1.na50.visual.force.com/apex/ForTestingPage. Domains, protocols and ports must match.

Code attached.
`<apex:page>
    <apex:slds />
    <div xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <div class="slds-media__figure">
        <span class="slds-icon_container slds-icon-standard-contact">
            <svg class="slds-icon slds-icon_small" aria-hidden="true">
                <use xlink:href="{!URLFOR($Asset.SLDS)}/assets/icons/utility-sprite/svg/symbols.svg#office365"></use>
            </svg>
        </span>
    </div>
    </div>
</apex:page>`

PS: Everything FINE with API 41.

**Comment by mpsenn** [comment]
The URL path for $Asset.SLDS did change with API 42.0, so that the path no longer includes "/assets". I'm able to reproduce your issue.

To fix this, you should use the 2-parameter version of URLFOR, which will remove "/assets" automatically.

    <use xlink:href="{!URLFOR($Asset.SLDS, '/assets/icons/utility-sprite/svg/symbols.svg#office365')}"></use>

**Comment by maximelets** [comment]
@mpsenn Thanks a lot man! You pointed me to good solutions and I did find a workaround for some of my edge cases!
