### ISSUE TITLE
Broken link in lightning design system page.

### ISSUE THREAD

**Issue by intel352** [salesforce-ux/design-system#548]
When viewing [Tabs component](https://www.lightningdesignsystem.com/components/tabs/), scroll down to the Vertical Tabs subsection, and follow the link to view the Vertical Tabs component. Link is broken due to doubled `/component/` in URL.

<img width="753" alt="screen shot 2018-05-15 at 10 00 35 am" src="https://user-images.githubusercontent.com/77607/40061757-a6aa5522-5827-11e8-9c82-1f74b31bc545.png">

<img width="724" alt="screen shot 2018-05-15 at 10 00 17 am" src="https://user-images.githubusercontent.com/77607/40061767-aaadd478-5827-11e8-939e-b806c8c0a892.png">

**Comment by ayeshakmaz** [comment]
Thanks for catching this @intel352! This should be fixed now with our 2.6.1 release
