### ISSUE TITLE
install error: style-loader.git - Permission denied (publickey).

### ISSUE THREAD

**Issue by paul-lisamore** [salesforce-ux/design-system#551]
trying to install and getting errors, have followed the install guide but still no luck. my error is:

3146 verbose Darwin 17.5.0
3147 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3148 verbose node v8.11.2
3149 verbose npm  v5.6.0
3150 error Error while executing:
3150 error /usr/local/bin/git ls-remote -h -t ssh://git@github.com/webpack-contrib/style-loader.git
3150 error
3150 error git@github.com: Permission denied (publickey).
3150 error fatal: Could not read from remote repository.
3150 error
3150 error Please make sure you have the correct access rights
3150 error and the repository exists.
3150 error
3150 error exited with error code: 128

can you confirm if there is a solution? i am running high sierra.

**Comment by engai** [comment]
Hi @paul-lisamore, sorry you're experiencing this issue. I'm having trouble reproducing your error on High Sierra. I'm also running on node v8.11.2 and npm v5.6.0.

Do you have SHH keys set up? If not, I would suggest trying that out and rerunning `npm install`.

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Please let us know if that resolves you're error, we'll be sure to update our install guide if that is the case.

**Comment by engai** [comment]
@paul-lisamore  Any updates on this?

**Comment by engai** [comment]
Closing this. Feel free to comment or reopen if needed.
