### ISSUE TITLE
nesting section on vertical navigation

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#552]
feature request or howto

Im using v.2.6.1. I implement [Vertical Navigation](https://www.lightningdesignsystem.com/components/vertical-navigation/) but I need different level. 2 or 3 level nesting.  

How can I make this component deeply nested if not possible can we imagine it  like current [Tree component](https://www.lightningdesignsystem.com/components/trees/) have **Deeply nested branches** 

Something like (here i put tree component inside navigation to achieve it seems ok at first glance but not sure it's right way to do it because `slds-is-active` to highlight item is not working like in navigation component ):

![image](https://user-images.githubusercontent.com/2789203/40466842-af5a0b48-5f27-11e8-8ae9-5093c7a0fdfb.png)

here you can check really complete navigation menu https://ng.ant.design/components/menu/en

Appreciate..

**Comment by engai** [comment]
Hey @istiti, our pattern that we suggest is to use the tree component itself. A good example of this within the Salesforce product is the Setup application.

I think what you're pointing out though is that our styling for `slds-is-selected` in Tree, is not the same as `slds-is-active` in Vertical Navigation. I'll label this as a bug.

**Comment by istiti** [comment]
@engai please applogize can you link the things you mention because i don’t lnow what is setup application of salesforce :)

Then i want vertical navigation with sub level not tree or can you add in documentation the right way to achieve this in « navigation vertical component ». Just add others example of sublevel menu on this vertical navigation component thanks.

You can’t check the last link i linked you can see many example exist

Thanks

**Comment by istiti** [comment]
Because im not sure we can consider tree component as vertical navigation component this seems different.

**Comment by engai** [comment]
@istiti the setup application can be accessed via the Global Header in the Salesforce product. If you'd like to see it, please look into getting a free trial of Salesforce or creating a developer org.

The Trees component is our suggested pattern for most things that require deep nesting of branches. The markup there ensures that the nesting is semantic and accessible. For more info on this, see [Using Aria Trees](https://www.w3.org/WAI/GL/wiki/Using_ARIA_trees). The Vertical Nav on the other hand is optimized for single level navigation.

For a good example of an implementation of the Trees component with linking that would work for your use case, see our [lightning:tree]('https://developer.salesforce.com/docs/component-library/bundle/lightning:tree/documentation') component. Here, a handler is put on the custom element with `role="treeitem"` to handle the keyboard and click event.

Another possible option without Javascript could be replacing the <ul> with a <div> and the <li> with an <a>. This would give you both the keyboard and click linking for free.

Example
`
 <div class="slds-tree" role="tree" aria-labelledby="treeheading">
    <a role="treeitem" aria-level="1" tabindex="0" href="">
      <div class="slds-tree__item">
        <button class="slds-button slds-button_icon slds-m-right_x-small slds-is-disabled" aria-hidden="true" tabindex="-1" title="Expand Tree Item">
          <svg class="slds-button__icon slds-button__icon_small" aria-hidden="true">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#chevronright" />
          </svg>
          <span class="slds-assistive-text">Expand Tree Item</span>
        </button>
        <span class="slds-size_1-of-1">
          <span class="slds-tree__item-label slds-truncate" title="Tree Item">Tree Item</span>
        </span>
      </div>
    </a>
</div>
`

**Comment by engai** [comment]
@istiti Let me know your thoughts and if you have further questions regarding this.
