### ISSUE TITLE
login component

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#553]
Feature request:  login component like https://vmware.github.io/clarity/documentation/v0.11/login

**Comment by engai** [comment]
Thanks for the feature request @istiti. 

Unfortunately, the Salesforce login page is out of the scope of our team. For this reason, I don't see such a component being created in SLDS in the near future.

**Comment by engai** [comment]
Though, for helpful existing components that can be used for this use case. See our [Form Element](https://www.lightningdesignsystem.com/components/form-element/) and [Buttons](https://www.lightningdesignsystem.com/components/buttons/)
