### ISSUE TITLE
Builder Header example not styled in dev org

### ISSUE THREAD

**Issue by Lukvang** [salesforce-ux/design-system#555]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="185" alt="screenshot 2018-06-01 10 55 15" src="https://user-images.githubusercontent.com/5392659/40850510-62b75fe8-658a-11e8-9676-030ba56587f8.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Copied and Pasted Builder Header into lightning component, but there is no styling ( I am extending force:slds in test application )

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Builder Header

> Are any specific browsers impacted by this bug?

Only tested using Chrome v  66.0.3359.181

> Which version of the Salesforce Lightning Design System are you using?

I'm using the force:slds extension in a dev org, Spring '18 Patch 19.21, NA34

> What steps and/or code are needed to reproduce this issue?

Copy and Paste Builder Header Example, removing svg tags, into a new lightning application or component. View the application/component.

> What did you expect to happen?

Builder Header to be styled

> What actually happened?

Builder Header is not styled per example

**Comment by williambritt** [comment]
Could you provide the code you are using? I had a similar issue but it was related to not extending force:slds

**Comment by engai** [comment]
Hi @Lukvang, sorry you're experiencing this issue.

@ayeshakmaz do you have an insights on why the styles aren't being applied within a Lightning Component?

**Comment by brandonferrua** [comment]
> Could you provide the code you are using? I had a similar issue but it was related to not extending force:slds

That's probably the issue.

**Comment by Lukvang** [comment]
I'm certain I had the force:slds extended in my application, when testing this a couple weeks ago. But as of now it seems to be working, so i'll close this.
