### ISSUE TITLE
Different label sizes for groups of slds-radio and slds-checkbox

### ISSUE THREAD

**Issue by maiwald** [salesforce-ux/design-system#556]
I was wondering why there are different sizes for `slds-form-element__label` when used in `slds-radio` and in `slds-checkbox`. In particular, this was making me wonder: https://github.com/salesforce-ux/design-system/blob/913ef779187807018ea0d017efc3fde8fd418ffc/ui/components/radio-group/base/_index.scss#L33-L37

This is basically taken from the Docs and produces the following result: (https://codepen.io/anon/pen/oybPMw)

![screenshot from 2018-06-04 12-40-13](https://user-images.githubusercontent.com/355026/40913317-85d0e848-67f4-11e8-9181-17386066a7f0.png)

To me, this looks inconsistent or am I using it wrong? Are checkboxes not supposed to be used like this?

**Comment by stefsullrew** [comment]
I do believe you may have found a bug, thanks! We'll investigate.

**Comment by ayeshakmaz** [comment]
We've added a fix for this, thanks for catching it @maiwald!

**Comment by maiwald** [comment]
@ayeshakmaz Great, thank you!
