### ISSUE TITLE
CERT_UNTRUSTED -- Missing dependencies?

### ISSUE THREAD

**Issue by mmoo9154** [salesforce-ux/design-system#557]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

The issue arises before anything can be demonstrated in Codepen.  If there is a way to get Codepen to run `npm install`, I'm happy to make one.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

A bug where the initial install fails.  I have a straight Ubuntu 14.04 shell with npm version 1.3.10.

When I run npm install, there are dependencies that fail to download because they are not available.

For example:

Line 32 of package.json lists `"@salesforce-ux/instant-vrt": "2.0.0"` as a dependency.  But, [https://registry.npmjs.org/salesforce-ux/instant-vrt/2.0.0](url) returns a 404 status "Not found" response.

If this is not a required dependency, should we eliminate it or mark it as optional?

Here is the complete NPM debug log:

[npm-debug.log](https://github.com/salesforce-ux/design-system/files/2076383/npm-debug.log)

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

No.  It is a general error, or it is an error in the package.json file.

> Are any specific browsers impacted by this bug?

Not applicable.

> Which version of the Salesforce Lightning Design System are you using?

master branch.

> What steps and/or code are needed to reproduce this issue?

1) Click "Clone in Visual Stuio"  (I am certain git clone command line is equivalent)
2) cd to project directory (`D:\dev\salesforce-ux\design-system` in my case)
3) `npm install`
4) Observe failure

> What did you expect to happen?

I expected nom install to complete successfully so I could then `npm start`

> What actually happened?

`npm install` fails to complete.  See attached debug log.

[npm-debug.log](https://github.com/salesforce-ux/design-system/files/2076383/npm-debug.log)

**Comment by mmoo9154** [comment]
I believe this failure is due to the project's incompatibility with older versions of nmp/node.js.

I upgraded to node v10.4.0 and npm v6.1.0.  I also installed the Visual Studio build tools for Python 2.7.15

`npm install` now works -- with the following warnings:

`D:\dev\salesforce-ux\design-system>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 53581 packages in 21.922s
found 773 vulnerabilities (741 low, 22 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details`

I have not run `npm audit` yet, but I'm guessing fixing the 773 vulnerabilities (or at least the 10 critical) would be a feature request.

Unfortunately, `npm start` fails with an error in the gulp script:

`> design-system@2.6.1 gulp D:\dev\salesforce-ux\design-system
> babel-node ./node_modules/.bin/gulp "build"

D:\dev\salesforce-ux\design-system\node_modules\.bin\gulp:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\dev\salesforce-ux\design-system\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.6.1 gulp: `babel-node ./node_modules/.bin/gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\markm\AppData\Roaming\npm-cache\_logs\2018-06-06T16_44_43_500Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.6.1 build: `npm run gulp -- build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\markm\AppData\Roaming\npm-cache\_logs\2018-06-06T16_44_43_553Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.6.1 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\markm\AppData\Roaming\npm-cache\_logs\2018-06-06T16_44_43_613Z-debug.log`

Here is the referenced debug log:  
[2018-06-06T16_44_43_613Z-debug.log](https://github.com/salesforce-ux/design-system/files/2077294/2018-06-06T16_44_43_613Z-debug.log)

**Comment by mmoo9154** [comment]
I think the bottom line is that SFDS is not well tested on Windows 10.  I'm going to try again on a pure Ubuntu 17.10 VM.  I'll post how it goes.  Keeping my fingers crossed.

**Comment by engai** [comment]
Hi @mmoo9154 , sorry you're experiencing this issue. We're working on pushing a fix to this.

In the meantime, if you'd like to get going with our system as soon as possible, you can change line 161 in [package.json](https://github.com/salesforce-ux/design-system/blob/master/package.json#L161) to "gulp": "babel-node ./node_modules/gulp/bin/gulp.js",

This should allow you to run `npm start`. We'll be sure to let you know when the fixed is pushed up to our master branch.

**Comment by engai** [comment]
This should be resolved with https://github.com/salesforce-ux/design-system/commit/2a78a479eeab97a6f7e7a6c5bdabd19978aff250.

Closing, but please let us know if you run into further issues.
