### ISSUE TITLE
Summer Release 2018 Footer Issue

### ISSUE THREAD

**Issue by Sheing** [salesforce-ux/design-system#559]
> Funny Footer issue: Unable to remove the  footer being added to all lightning page layout in summer release. Please provide option for devs to get rid of thhis footer.

![](https://i.imgur.com/gxi2WwL.gif)

As of now, i found out the way to fix it is to change slds-brand-band's position to fix, however I am unable to manually override that class styling since vf page and lightning component is now encapsulated inside an iframe.

**Comment by engai** [comment]
Hi @Sheing, sorry you're experiencing this issue. From a framework perspective, we wouldn't be comfortable with making this change to cover a very specific corner case on the Brand Band.

Just to clarify on your title, are you saying that this is a new issue introduced in Summer 18'?

cc: @ayeshakmaz

**Comment by stefsullrew** [comment]
@Sheing I've been unable to reproduce this on our internal builds. Can you give us an example of a specific page type where we can see this? (Your movie doesn't show what kind of page this is.)

**Comment by Sheing** [comment]
One week after the initial summer 2018 release, this was fixed. My team were really confused with this since it was fixed a week later. Anyway, thanks for giving feedback, I will let you know if this ever occurs again.
