### ISSUE TITLE
Install issues Err code ELIFECYCLE after attempting to install chromedriver

### ISSUE THREAD

**Issue by mattflamm** [salesforce-ux/design-system#560]
I'm attempting to run the initial installation of SLDS.  

during install I receive the following error in the terminal:
```
ChromeDriver installation failed Error with http request: { 'content-type': 'text/html; charset=UTF-8',
  'content-length': '1489',
  connection: 'close',
  p3p: 'CP="CAO PSA OUR"',
  expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
  pragma: 'no-cache' }
```
and moments later after a few skipped optional dependencies:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.25.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.25.1 install script.
```
[The complete log file is available here.](https://docs.google.com/document/d/1HLFAvUe2jISzVZ9imi1yeOCqk9RPjDgrSXkr9NVoM_Q/edit?usp=sharing)
or attached here
[After npm install: 2018-06-13T15_04_07_581Z-debug.log](https://github.com/salesforce-ux/design-system/files/2099025/2018-06-13T15_04_07_581Z-debug.log)

If I then try and run npm start anyway, I get the error
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\code\design-system\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at C:\code\design-system\node_modules\babel-cli\lib\_babel-node.js:155:24
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.6.1 gulp: `babel-node ./node_modules/.bin/gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 gulp script.
```
[Here is THIS log file.](https://docs.google.com/document/d/1NJ9r3MzvWaPt6WM2THA6V_VeiGKLpbLh_pQeoU9VGX0/edit?usp=sharing)
or attached here
[After npm start: 2018-06-13T16_05_00_166Z-debug.log](https://github.com/salesforce-ux/design-system/files/2099028/2018-06-13T16_05_00_166Z-debug.log)

I have attempted to run again after deleting the node_modules folder (a few times), as well as delete the whole project and clone again (twice), but the issue continues unchanged.

I'm running:
Windows 10
Using Command Prompt as Admin
SLDS 2.6.1 (cloned June 12, 2018)
Node 8.11.2
npm 6.1.0

What is needed to be able to install and run?  Is there a workaround?  Am I doing something wrong?

**Comment by engai** [comment]
Hi @mattflamm , sorry you're experiencing this issue. We're working on pushing a fix to this.

In the meantime, if you'd like to get going with our system as soon as possible, you can change line 161 in [package.json](https://github.com/salesforce-ux/design-system/blob/master/package.json#L161) to "gulp": "babel-node ./node_modules/gulp/bin/gulp.js",

This should allow you to run `npm start`. We'll be sure to let you know when the fixed is pushed up to our master branch.

**Comment by engai** [comment]
This should be resolved with https://github.com/salesforce-ux/design-system/commit/2a78a479eeab97a6f7e7a6c5bdabd19978aff250.

Closing, but please let us know if you run into further issues.
