### ISSUE TITLE
Can't view site in Firefox

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#561]
When I go to http://www.lightningdesignsystem.com in Firefox, none of the code samples or icons appear. Here is an example:
<img width="1397" alt="screen shot 2018-06-18 at 10 10 36 pm" src="https://user-images.githubusercontent.com/1011888/41577995-dd00b44e-7344-11e8-80ef-ef0f6caa0b1e.png">

**Comment by istiti** [comment]
i use chrome and have some problems to display svg not when consulting documentation like you but whe 
 using static slds ressources (css) in my project with spirite svg (one file), i always think all browsers handle svg with many bugs.

**Comment by engai** [comment]
Hi @tylerzika, i'm unable to reproduce your issue on my end. Seems to be working on my end.

Which version of Firefox are you currently using?

**Comment by tylerzika** [comment]
@engai Weird! I can now see them. I wonder if it was just because I had an older version. I just upgraded to the latest and all is well.

**Comment by engai** [comment]
@tylerzika Great to hear! Please let us know if you run into any further issues.
