### ISSUE TITLE
NPM Build Errors

### ISSUE THREAD

**Issue by Biggisb** [salesforce-ux/design-system#562]
Hey,

we are trying to install salesforce-design-system on a Windows Server 2012 R2.
After Cloning the Project, we have build issues that we was not able to fix: 

node v8.10.0
npm  v6.1.0
Windows Server 2012 R2.

```
4461 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4     
(node_modules\fsevents):
4462 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: 
{"os":"win32","arch":"x64"})
4463 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4463 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4463 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4463 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4464 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 
(node_modules\watchpack\node_modules\fsevents):
4465 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: 
{"os":"win32","arch":"x64"})
4466 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4466 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4466 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4466 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4467 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 
(node_modules\sane\node_modules\fsevents):
4468 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: 
{"os":"win32","arch":"x64"})
4469   verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4469 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4469  verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4469 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4470  warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 
(node_modules\glob-watcher\node_modules\fsevents):
4471 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 
fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: 
{"os":"win32","arch":"x64"})
4472 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4472 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4472 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4472 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4473 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 
(node_modules\chokidar\node_modules\fsevents):
4474 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
4475 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4475 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4475 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4475 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4476 verbose stack Error: node-sass@4.5.2 postinstall: `node scripts/build.js`
4476 verbose stack Exit status 1
4476 verbose stack     at EventEmitter.<anonymous> (C:\Users\ASOL.Projects\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
4476 verbose stack     at emitTwo (events.js:126:13)
4476 verbose stack     at EventEmitter.emit (events.js:214:7)
4476 verbose stack     at ChildProcess.<anonymous> (C:\Users\ASOL.Projects\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4476 verbose stack     at emitTwo (events.js:126:13)
4476 verbose stack     at ChildProcess.emit (events.js:214:7)
4476 verbose stack     at maybeClose (internal/child_process.js:925:16)
4476 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
4477 verbose pkgid node-sass@4.5.2
4478 verbose cwd C:\xampp\htdocs\salesforge
4479 verbose Windows_NT 6.3.9600
4480 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ASOL.Projects\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
4481 verbose node v8.10.0
4482 verbose npm  v6.1.0
4483 error code ELIFECYCLE
4484 error errno 1
4485 error node-sass@4.5.2 postinstall: `node scripts/build.js`
4485 error Exit status 1
4486 error Failed at the node-sass@4.5.2 postinstall script.
4486 error This is probably not a problem with npm. There is likely additional logging output above.
4487 verbose exit [ 1, true ]
```

is the issue from my OS / Setup or is it in relation the the package?

**Comment by Biggisb** [comment]
i now installed the app on a windows 10 OS.
npm install had no problems but now npm start fails :( 

`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xampp\htdocs\salesforce\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at C:\xampp\htdocs\salesforce\node_modules\babel-cli\lib\_babel-node.js:155:24

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "--" "build"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! design-system@2.6.1 gulp: `babel-node ./node_modules/.bin/gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 gulp script 'babel-node ./node_modules/.bin/gulp "build"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the design-system package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./node_modules/.bin/gulp "build"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs design-system
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls design-system
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\salesforce\npm-debug.log

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! design-system@2.6.1 build: `npm run gulp -- build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 build script 'npm run gulp -- build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the design-system package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run gulp -- build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs design-system
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls design-system
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\salesforce\npm-debug.log

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! design-system@2.6.1 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.6.1 start script 'npm run build && npm run previewer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the design-system package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run previewer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs design-system
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls design-system
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\salesforce\npm-debug.log
`

**Comment by engai** [comment]
Hi @Biggisb, sorry you're experiencing this issue. We're working on pushing a fix to this as soon as possible. 

In the meantime, if you'd like to get going with our system as soon as possible, you can change line 161 in [package.json](https://github.com/salesforce-ux/design-system/blob/master/package.json#L161) to `"gulp": "babel-node ./node_modules/gulp/bin/gulp.js",`

This should allow you to run `npm start`. We'll be sure to let you know when the fixed is pushed up to our master branch.

**Comment by engai** [comment]
This should be resolved with https://github.com/salesforce-ux/design-system/commit/2a78a479eeab97a6f7e7a6c5bdabd19978aff250.

Closing, but please let us know if you run into further issues.
