### ISSUE TITLE
I am trying to install this in my Salesforce org, if that is what I need to do.  In order to get my Visualforce pages to be updated in Lightning.

### ISSUE THREAD

**Issue by nelle3223** [salesforce-ux/design-system#567]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

**Comment by engai** [comment]
Hi @nelle3223, for instructions on how to upgrade your visualforce pages, please see https://www.lightningdesignsystem.com/platforms/visualforce/

**Comment by engai** [comment]
Hi @nelle3223, I hope that our resources were helpful in getting you setup with our system in Visualforce.

Closing this now, but feel free to comment or reopen.
