### ISSUE TITLE
Underlined links in docs

### ISSUE THREAD

**Issue by ptrin** [salesforce-ux/design-system#568]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
<img width="755" alt="screen shot 2018-07-12 at 11 14 54 am" src="https://user-images.githubusercontent.com/383887/42642926-ea42b1f0-85c5-11e8-869f-34b4bf55efb0.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

In the docs, e.g. https://www.lightningdesignsystem.com/accessibility/patterns/overview/ there are a few accessibility issues:
- Links are identified by colour alone ([WCAG 1.4.1](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html))
- It would also be helpful (though not required) if links contrasted more with body text

To fix, please underline links.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.
- I've only noticed for docs, although it could apply elsewhere.

**Comment by engai** [comment]
Hi @ptrin, this was resolved in our 2.7.0 release. Closing this issue.
