### ISSUE TITLE
lightning:recordForm checkboxes displaying as disabled

### ISSUE THREAD

**Issue by charles-stevenson** [salesforce-ux/design-system#570]
I think the new lightning:recordForm is displaying checkboxes visually as if disabled (when they are not).

![recordform checkbox bug](https://user-images.githubusercontent.com/27965971/42934854-1cfa7676-8b40-11e8-8fbc-351bcd786559.png)

If I build a recordForm with a checkbox field and display it on a record page it displays (in view mode) the checkbox as greyed out - as if it was disabled.
The checkbox behaves correctly and appear correctly in edit mode.

`<aura:component implements="flexipage:availableForRecordHome,flexipage:availableForAllPageTypes,force:hasRecordId,force:hasSObjectName" access="global" >
    <aura:attribute name="recordId"        type="Id" default="" />
    <aura:attribute name="numCols"         type="String" default="1"/>
    <aura:attribute name="fieldsArray"     type="String[]" default="['New_Checkbox__c']" />
    
    <lightning:card title="simple recordForm" >
        <div class="slds-p-left_large slds-p-right_medium">
            <lightning:recordForm aura:id="recordForm"
                                  recordId="{!v.recordId}"
                                  objectApiName="Contact"
                                  fields="{!v.fieldsArray}"
                                  columns="{!v.numCols}"/>
        </div>
    </lightning:card>
</aura:component>`

The field New_Checkbox__c is editable and displays correctly on the details page layout

**Comment by engai** [comment]
Hi @charles-stevenson, thanks for sharing your concerns.

Semantically, having a disabled checkbox is correct in the case of recordForm since the user should not be able to toggle the checkbox when in view only mode. However, we do understand that there is a bit of variation in the implementation of the checkbox field within record detail and lighting:recordForm.

This isn't something we can change in our system, but will work with the teams that own these features to have better alignment.

**Comment by charles-stevenson** [comment]
@engai Thanks for the response, but I genuinely think it needs addressing for 2 reasons:

1. The 'disabled' appearance means (at least to me) that the user *is not allowed* to edit the value (whereas you are saying that the user is *not currently* editing - which is quite a different meaning)

Even if you are right, and decide that it is correct to continue using the disabled mode:
2. The disabled appearance is difficult to read at a glance.  On my screens I have to look quite carefully to see if it is checked / not checked - it maybe needs more contrast / some alternative visual cue.

Anyway - keep up the good work - Love the whole SLDS and the rollout of Lightning base components is great!

**Comment by adambadun** [comment]
For anyone else with this issue, this will make it look like a normal checkbox:

`.THIS .slds-checkbox [type=checkbox][disabled]+.slds-checkbox__label .slds-checkbox_faux
{
    background: rgb(255, 255, 255);
}
.THIS .slds-checkbox [type=checkbox][disabled]+.slds-checkbox__label .slds-checkbox_faux:after
{
	border-color: rgba(27, 82, 151, 1.0);
}`

**Comment by monikasingour** [comment]
> For anyone else with this issue, this will make it look like a normal checkbox:
> 
> .THIS .slds-checkbox [type=checkbox][disabled]+.slds-checkbox__label .slds-checkbox_faux
> {
> background: rgb(255, 255, 255);
> }
> 
> .THIS .slds-checkbox [type=checkbox][disabled]+.slds-checkbox__label .slds-checkbox_faux:after
> {
> border-color: rgba(27, 82, 151, 1.0);
> }

This will change the color of all the disabled checkboxes to same color, but I have a requirement with 2 checkboxes and their color will be dynamic and can be different based on certain conditions. How can I make this CSS class specific instead of applying it for all the checkboxes?
