### ISSUE TITLE
empty-state image for Most recent activity missing

### ISSUE THREAD

**Issue by wilsonmar** [salesforce-ux/design-system#571]
In the images/illustrations folder, there are three .svg files for "empty-state" events, tasks, and assistant. But there is no file for the "Most recent activity" pane: ???

![sf-most-recent-397x229-12868](https://user-images.githubusercontent.com/300046/43092872-bfb5d526-8e6b-11e8-926b-c7960d4cd33e.jpg)

**Comment by engai** [comment]
Hi @wilsonmar, moving forward, we are using the [Illustration component](https://www.lightningdesignsystem.com/components/illustration/?variant=base) for empty states. The Illustration you are looking for is called 'Open Road' under the 'No Data' section
