### ISSUE TITLE
Broken link markdown readme

### ISSUE THREAD

**Issue by tijmenvangurp** [salesforce-ux/design-system#572]
https://github.com/salesforce-ux/design-system-internal/wiki/Documentation-Styleguide 

All other selectors which are not @base/@variant/@modifier are considered child elements of a component.

For more information see the Full annotation docs <-- not working here

**Comment by engai** [comment]
@tijmenvangurp Thanks for surfacing this issue. We'll work to fix these urls and expose the info in our public wiki.

**Comment by engai** [comment]
@tijmenvangurp We've decided to just remove the links in these instances. You should see the fix in our next release.

**Comment by engai** [comment]
Hi @tijmenvangurp, this was revolved with https://github.com/salesforce-ux/design-system-internal/commit/bf75f472859320f0165c4a63de894e10b19ccecc

**Comment by engai** [comment]
Hi @tijmenvangurp, this was resolved with https://github.com/salesforce-ux/design-system/commit/bf75f472859320f0165c4a63de894e10b19ccecc
