### ISSUE TITLE
Activity Timeline Line Colors

### ISSUE THREAD

**Issue by jimpdx** [salesforce-ux/design-system#575]
Hello. We are implementing the activity timeline within our new mobile app and would like to incorporate SLDS icons related to various object records attached to an Account. However the implementation of the line color connecting the icons is only limited to the 4 colors (event, email, call and task). 

Do you recommend that we create custom CSS background color classess based on the icons we are using, or is there a more creative way to leverage the existing icon syntax?

<img width="1306" alt="screen shot 2018-09-06 at 5 30 38 pm" src="https://user-images.githubusercontent.com/867051/45231003-8bbfe580-b27f-11e8-8a5f-78f04d3d5f80.png">

**Comment by engai** [comment]
Hi @jimpdx, for your use case, I would recommend writing your own CSS to style the line color. With the current markup and icon system, I don't think there is a more creative or global method.

**Comment by jimpdx** [comment]
Thank you again @engai. We went with a solid grey line and it actually looks great. We considered a bunch of custom code to determine the icon color but decided it did not add enough value to justify the overhead.
