### ISSUE TITLE
How include custom svg sprites?

### ISSUE THREAD

**Issue by norwill** [salesforce-ux/design-system#578]
Hi guys, great job, exyst anyway to include custom svgs sprites?

Thanks

**Comment by engai** [comment]
Hi @norwill, unfortunately, we currently do not have a supported method to include custom svg sprites

**Comment by norwill** [comment]
> Hi @norwill, unfortunately, we currently do not have a supported method to include custom svg sprites

Thanks for your reply i found a way (i hope)...
I would to test and tell you if that works for me...

**Comment by engai** [comment]
@norwill Glad that you found a solution. Closing this issue, but feel free to comment if you'd still like to share your method. Thanks!
