### ISSUE TITLE
Select component: clicking arrows has no effect

### ISSUE THREAD

**Issue by abwlkb** [salesforce-ux/design-system#579]
Possible issue affecting SLDS select component:

**Issue**
The base select component contains two arrows on the right side. Clicking on these arrows does not open the menu - users have to click on the select element itself. 

Two of our users have recently tried to click on the arrows and were confused as to why a menu didn't appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38301516/45573591-e75f1580-b821-11e8-865a-d04a5af1ea7b.png)
![image](https://user-images.githubusercontent.com/38301516/45573685-40c74480-b822-11e8-8788-aaecc8e0342c.png)

**SLDS version**
We are importing SLDS in Visualforce in a Summer '18 org. However, the issue also exists in Winter '19. It can be reproduced in the example select component in the official SLDS guide: https://www.lightningdesignsystem.com/components/select/

**Browsers**
Tested and reproduced on latest Chrome & Firefox, as well as IE11.

**Comment by engai** [comment]
@abwlkb Thanks for bringing this to our attention. Filing this as a bug on our end. We'll let you know when our work will be released.
