### ISSUE TITLE
Tree is-open mistakenly rotating _all_ button icons within

### ISSUE THREAD

**Issue by chriscorwin** [salesforce-ux/design-system#58]
At: https://github.com/salesforce-ux/design-system/blob/winter-16/ui/components/trees/flavors/base/index.scss#L66

...we have: 

```
  .#{$css-prefix}is-open .#{$css-prefix}button__icon {
    transform: rotate(90deg);
  }
```

...which is causing _all_ button icons within an open branch to be rotated, even those in sub-branches that are not open.

Yikes!

![screenshot 2015-10-19 17 42 44](https://cloud.githubusercontent.com/assets/362417/10592247/dd045eb6-7688-11e5-821d-13f419c3c72f.png)

A very quick and may need more thought fix:

```
  .#{$css-prefix}is-open > .#{$css-prefix}tree__item > .#{$css-prefix}button > .#{$css-prefix}button__icon {
    transform: rotate(90deg);
  }
```

**Comment by srohde** [comment]
Awesome, thanks @chriscorwin, would you mind doing a PR?

**Comment by brandonferrua** [comment]
I'd prefer the specificity to be a bit lower, having the rotation of the icon attached to `.slds-is-closed` so it's associated to the specific tree thats open.

```
.slds-tree .slds-is-closed .slds-button__icon {
    transform: rotate(0deg);
}
```

**Comment by stefsullrew** [comment]
@chriscorwin - Are you working on this or do you want us to tackle it?

**Comment by chriscorwin** [comment]
I will do this tomorrow.

@brandonferrua Are you saying have an `.slds-is-closed` on all icons _except_ those that are to be shown as open?

If I understand that correctly... it feels... _backwards_. ?

**Comment by ashnur** [comment]
Is this resolved?

**Comment by kaelig** [comment]
@brandonferrua can you give an update on when the fix will be public?

**Comment by brandonferrua** [comment]
The tree component will be updated in our spring-16 release
