### ISSUE TITLE
horizontal form layout : put label right near input field

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#580]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Feature request. With "horizontal form" how can We correctly align label near input field, I mean instead left put them right like : 
![image](https://user-images.githubusercontent.com/2789203/45860788-67790400-bd69-11e8-8e32-96c508ccc5ac.png)
Currently I do some override but can we imagine something official and right way ? thanks

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

https://www.lightningdesignsystem.com/components/form-element/#Horizontal

> Are any specific browsers impacted by this bug?

all

> Which version of the Salesforce Lightning Design System are you using?

2.7.1

cc @engai

**Comment by brandonferrua** [comment]
This is by design. Horizontal forms changed in our winter-19 release. By using SLDS, you are opting into design updates.

**Comment by istiti** [comment]
@engai thanks can you just confirm `.slds-size_1-of-2` only let us have label take 100% we need add custom css "text-align:right" to get it working ? currently adding this class let me have this 
![image](https://user-images.githubusercontent.com/2789203/46057606-c0281280-c156-11e8-996b-7af6335dd489.png)
