### ISSUE TITLE
breaking change from 2.6.1 to 2.7.1

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#581]
i just udpate to 2.7.1 and I get all my webapp broken ! espeacially with input width !
In 2.6.1 If I want a static width for an input  I set width near `.slds-form-element__control w50px` class
Because I was thinking this was the correct way to set width static !! 

I hate breaking change from slds lib, it get me frustrated can you please tell me the correct way to set 50px of an input wihtout changing 33% of label and the rest of the input 

 thanks

**Comment by brandonferrua** [comment]
Please see https://github.com/salesforce-ux/design-system/blob/master/CONTRIBUTING.md#bug-reports on how to file bug reports.
