### ISSUE TITLE
Latest release causing issues with slds-input-has-icon_left-right

### ISSUE THREAD

**Issue by meruff** [salesforce-ux/design-system#582]
It seems that v2.7.0 and beyond has caused an issue with `slds-input-has-icon_left-right` in horizontal forms. I've got an input on my Visualforce page using the `<apex:slds/>` tag that is rendering the search icon to the far left above the form element label.

![screen shot 2018-09-21 at 8 44 08 am](https://user-images.githubusercontent.com/6045126/45892626-7c5f9280-bd7d-11e8-8072-9031616ce13a.png)

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Seems to be happening to Input tags

> Are any specific browsers impacted by this bug?

I've confirmed this is happening on Chrome 70, Safari 11.1.2, and Firefox 63. I'm currently running macOS High Sierra 10.13.6. However it _doesn't_ seem to be happening on mobile, smaller screens.

![screenshot_20180921-091636](https://user-images.githubusercontent.com/6045126/45893144-225fcc80-bd7f-11e8-89ff-223224bcfdcd.png)

> Which version of the Salesforce Lightning Design System are you using?

Latest, using `<apex:slds/>` in Winter '19 orgs only. 

> What steps and/or code are needed to reproduce this issue?

Not only have I double checked my code against the demo code in the docs, I've also copied/pasted the example from the docs directly into a fresh VF page and this was the result:

![screen shot 2018-09-21 at 9 13 34 am](https://user-images.githubusercontent.com/6045126/45893001-b5e4cd80-bd7e-11e8-9452-51afbebddfd1.png)

Example code used in the above screenshot (copied from https://www.lightningdesignsystem.com/components/input/#site-main-content)
``` html
<apex:page id="test">
    <apex:slds />

    <div class="slds-scope">
        <div class="slds-form slds-form_horizontal">
            <div class="slds-form-element">
                <label class="slds-form-element__label" for="text-input-id-1">Input Label</label>
                <div class="slds-form-element__control slds-input-has-icon slds-input-has-icon_left-right">
                    <svg class="slds-icon slds-input__icon slds-input__icon_left slds-icon-text-default" aria-hidden="true">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{!URLFOR($Asset.SLDS, '/assets/icons/utility-sprite/svg/symbols.svg#search')}"></use>
                    </svg>
                    <input id="text-input-id-1" class="slds-input" type="text" value="" />
                    <button class="slds-button slds-button_icon slds-input__icon slds-input__icon_right" title="Clear">
                        <svg class="slds-button__icon slds-icon-text-light" aria-hidden="true">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{!URLFOR($Asset.SLDS, '/assets/icons/utility-sprite/svg/symbols.svg#clear')}"></use>
                        </svg>
                        <span class="slds-assistive-text">Clear</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</apex:page>
```

**Comment by engai** [comment]
Hey @meruff, thanks for bringing this to our attention. We'll look into this and get back to you shortly.

cc: @brandonferrua

**Comment by engai** [comment]
@meruff I've looked into this further and it is indeed an issue. I've filed a bug on our end.

**Comment by filiprafalowiczpolsource** [comment]
@engai is there any ETA when this bug will be fixed?

**Comment by meruff** [comment]
@engai working in my Spring '19 box as well, thanks much!
