### ISSUE TITLE
2.7.2 flex-end on compound form ?

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#583]
I'm using static ressources

![image](https://user-images.githubusercontent.com/2789203/46081491-e83a6480-c19c-11e8-933e-91d9dadee20e.png)

The lattitude is flex-end instead start to be align ... is this bug, thanks ? 

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Link of doc https://www.lightningdesignsystem.com/components/form-element/#Horizontal-Alignment-2

> Are any specific browsers impacted by this bug?

all 

> Which version of the Salesforce Lightning Design System are you using?

2.7.2

> What steps and/or code are needed to reproduce this issue?
```
<fieldset class="slds-form-element slds-form_compound slds-is-editing">
   <legend class="slds-form-element__legend slds-form-element__label">Location</legend>
   <div class="slds-form-element__control">
      <div class="slds-form-element__group">
         <div class="slds-form-element__row">
            <div class="slds-form-element slds-has-error slds-size_1-of-2">
               <label class="slds-form-element__label" for="location-longitude-01">Longitude</label>
               <div class="slds-form-element__control"><input id="location-longitude-01" class="slds-input" type="text" value="10.283"></div>
               <div class="slds-form-element__help" id="error-message-unique-id">This field is required</div>
            </div>
            <div class="slds-form-element slds-size_1-of-2">
               <label class="slds-form-element__label" for="location-latitude-01">Latitude</label>
               <div class="slds-form-element__control"><input id="location-latitude-01" class="slds-input" type="text" value="54.293"></div>
            </div>
         </div>
      </div>
   </div>
</fieldset>
```

> What did you expect to happen?

latitude input must be aligned "start"

> What actually happened?

Latitude input is flex-end aligned

**Comment by engai** [comment]
Hi @istiti, thanks for raising this issue. This is indeed a bug, and should be resolved in a week or so with our next public patch release.

**Comment by engai** [comment]
@istiti Thanks again for raising this issue. It has been resolve with https://github.com/salesforce-ux/design-system/commit/3acb5c05b2a640f31a3daff002b90b7c54239f02

**Comment by istiti** [comment]
Awesome already fixed and merged without waiting 2/3years ... Does salesforce change his release strategy in 2018 or something new in 2019?  I was always thinking it is better if we can habe more release not 2/3 by years. Can you give us your roadmap for next couple of months thank you @engai
