### ISSUE TITLE
File with actions : long title goes out of context

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#584]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![image](https://user-images.githubusercontent.com/2789203/46453202-841d2f00-c7a0-11e8-8983-557bcd7531b7.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

A bug when file title is too long the actions buttons are hidden

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Files : [File with actions](https://www.lightningdesignsystem.com/components/files/#site-main-content)

> Are any specific browsers impacted by this bug?

Tried on Chrome 69

> Which version of the Salesforce Lightning Design System are you using?

2.7.1

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

Truncate file title when title is too long to see actions buttons.

> What actually happened?

File's title goes out of his context

**Comment by engai** [comment]
Hi @istiti, thanks for pointing this out. We'll investigate and get back to you.

cc: @brandonferrua @stefsullrew

**Comment by skreborn** [comment]
Giving `.slds-media` a `min-width` of `0` and `.slds-truncate` a `display` of `block` seems to resolve the issue.

**Comment by alexiscordova** [comment]
@skreborn sorry this has taken so long, but we've created a ticket for this and is on our road map. Thank you for bringing this to our attention!
