### ISSUE TITLE
Salesforce lightning button color not match lightning design system style guide

### ISSUE THREAD

**Issue by wxyudl** [salesforce-ux/design-system#585]
Hi, I am facing an odd issue.

I created a app page, which includes some lightning components, like input, buttons.
![image](https://user-images.githubusercontent.com/9672031/46652974-41f85100-cbd7-11e8-9345-fb386d49fcfb.png)
![image](https://user-images.githubusercontent.com/9672031/46653030-7d931b00-cbd7-11e8-9ff3-5f243fa3dc9e.png)

The button's background color is same as lightning design system, `background-color: #0070d2;`
Style guide: https://www.lightningdesignsystem.com/components/buttons/

**But after I created a lightning component tab from setup** include these components, which looks like this.
![image](https://user-images.githubusercontent.com/9672031/46653339-5be66380-cbd8-11e8-83b8-c56eec1597f2.png)

The button's background color changes to `background-color: #1b5297;`

I want to know how should I make all lightning components' UI in salesforce same as lightning design system style guide.

Thanks~

**Comment by engai** [comment]
Hi @wxyudl, looks like your component is leveraging the Themes & Branding feature in Lightning. #0070d2 is our SLDS standard color, but can be overridden by a organization's brand.

You can find these settings in Setup > User Interface (Under platform tools) > Themes & Branding

**Comment by wxyudl** [comment]
Thanks @engai , Let me check the settings.

**Comment by engai** [comment]
@wxyudl Closing this issue, but feel free to reopen if that did not answer your question.
