### ISSUE TITLE
show combobox dropdown outside modal content or outside slds-col having relative+overflow hidden

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#587]
Considering combobox inside modal: 

![image](https://user-images.githubusercontent.com/2789203/46720845-e6c76c80-cc71-11e8-8d01-1e3a12e0ba85.png)

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

It's related to Modal and Combobox component.

> Are any specific browsers impacted by this bug?

Chrome 69

> Which version of the Salesforce Lightning Design System are you using?

2.7.2

> What steps and/or code are needed to reproduce this issue?

https://jsfiddle.net/3o871eqf/

Or with vertical grid https://jsfiddle.net/c4k6g753/

> What did you expect to happen?

Shouldn't combobox dropdown be always displayed in front of all elements ? 

> What actually happened?

Combobox don't go out of context on modal. I realize when I split layout with two vertical grid (each slds-col has relative position with overflow:hidden) and combobox dont go out of his slds-col

Thanks @engai

**Comment by engai** [comment]
Hey @istiti, this issue has come up in the past (see https://github.com/salesforce-ux/design-system/issues/483). I believe that our stance is that the combobox should always respect the overflow properties of its container. In the case of a modal, since the container is scrollable, the combobox is technically not suppose to overflow out of the modal body. We believe this is the most scalable solution for a standard combobox. Of course, you may add additional styling yourself, or position the combobox absolutely to achieve your expected interaction.

**Comment by fspoettel** [comment]
@istiti Check out [Popper.js](https://github.com/FezVrasta/popper.js) if you want to implement this functionality in your code. It can be set to use `position: fixed` to position elements which elevates the element out of its native positioning context which is a simple solution for this problem. it is a popular, well-tested library that comes in at around ~7kb min/gzipped.

@engai I think that that is a reasonable stance. It might make sense to mention possible workarounds (see above) somewhere in the documentation as this is a common requirement for tooltips / dropdown overflows.

**Comment by matthewsouther** [comment]
I have been able to work around this issue by applying SLDS classes to a `select` element instead of an `input`.  I'm unable to achieve the exact SLDS styling on the dropdown, but it's not too bad.  The dropdown overflows the modal container as desired.

```html
<div class="slds-form-element">
    <label class="slds-form-element__label" for="DocType">
        Document Type
    </label>
    <br />
    <div class="slds-form-element__control slds-combobox_container slds-combobox">
        <div
            class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right"
            role="none"
        >
            <select
                name="DocType"
                id="DocType"
                class="slds-input slds-combobox__input"
                style="appearance: none;"
                onchange={handleFileChange}
            >
                <template
                    class="slds-dropdown slds-dropdown_fluid"
                    for:each={docTypeOptions}
                    for:item="option"
                >
                    <option
                        class="slds-text-color_weak slds-p-vertical_x-small"
                        key={option.value}
                        value={option.value}
                    >
                        {option.label}
                    </option>
                </template>
            </select>
            <span
                class="slds-icon_container slds-input__icon slds-input__icon_right"
            >
                <lightning-icon
                    icon-name="utility:down"
                    size="x-small"
                ></lightning-icon>
            </span>
        </div>
    </div>
</div>
```

**Comment by santiagorojasqt** [comment]
If anyone has this issue just set the dropdown-alignment="auto"  param in the lightning-combobox it'll work
![image](https://user-images.githubusercontent.com/12003125/106792900-bd8e2f80-6624-11eb-8bb6-36602248013f.png)

**Comment by srikanth4b9** [comment]
Any alternative approach if in case Combobox is dynamically loaded in LWC like record form.

**Comment by vc4u** [comment]
Is there any workaround for this when an InputField (Picklist datatype) is placed inside record-edit-form inside a Modal dialog? There is no menu-alignment option for this.
