### ISSUE TITLE
Disabled stateful button changes state on hover

### ISSUE THREAD

**Issue by interactivellama** [salesforce-ux/design-system#59]
Is this intentional? Seems misleading if it is.

![screen shot 2015-10-20 at 5 56 05 pm](https://cloud.githubusercontent.com/assets/1290832/10622204/db3c2908-7753-11e5-95b5-2b15273a30cb.png)

**Comment by stefsullrew** [comment]
Where are you seeing this @interactivellama?

**Comment by stefsullrew** [comment]
This is what the ones on the site look like when hovered: 
![image](https://cloud.githubusercontent.com/assets/676213/10624151/b523a3ee-774a-11e5-86ce-8bab1f604e87.png)

**Comment by interactivellama** [comment]
I don't think any of those are disabled on the site.

It's not a site issue. It's a CSS issue. This is in the JS controls that my
team Is working on. We add the disabled attribute to the button.

I'm asking what should the disable state look like--in the abstract.



-- 

*--*
STEPHEN M JAMES
Sr Front-End Engineer, User Experience Design Studio | salesƒorce
@tweetllama <http://twitter.com/tweetllama> :: sjam.es/linkedin
<http://linkedin.com/in/stephenmjames> :: sjames@salesforce.com ::
<sjames@salesforce.com>1-317-379-2814

**Comment by stefsullrew** [comment]
Ahh, this is why it helps to have more details when unable to inspect the DOM. ;)

So no, there is no [disabled] state for stateful buttons — it was not part of the spec. If they show, they're active and able to be manipulated. What would the situation for needing a disabled stateful button be? If there's a use case, we can discuss with them.

Cheers

**Comment by stefsullrew** [comment]
Ignore the above. It was a simple :not rule to fix it. It hurts nothing and I agree there shouldn't be a :hover state for anything disabled, regardless of specs. So this update will be in the next release.

Cheers.

**Comment by interactivellama** [comment]
Yeah, this probably isn't something a designer would ask for. No use case.

All buttons can be disabled though. I guess we could prevent the button
from being disabled if it was stateful as long as the UI dev didn't add the
disable attribute themselves.
>
> Then if they called `disable()` on it or the app state called for it be
disabled it wouldn't do anything and just ignore it and stay enabled.

I guess the larger question is are we limiting the design system CSS to
only things that would get implemented in Salesforce UIs?



-- 

*--*
STEPHEN M JAMES
Sr Front-End Engineer, User Experience Design Studio | salesƒorce
@tweetllama <http://twitter.com/tweetllama> :: sjam.es/linkedin
<http://linkedin.com/in/stephenmjames> :: sjames@salesforce.com ::
<sjames@salesforce.com>1-317-379-2814
