### ISSUE TITLE
Hi Is there any way or plan to support Salesforce packages?

### ISSUE THREAD

**Issue by jamesbook** [salesforce-ux/design-system#591]
Hi Is there any way or plan to support salesforce [triggers ](https://www.janbasktraining.com/blog/what-is-trigger-in-salesforce/)packages? 

I am happy to create a custom library step for Salesforce to perform the installation and deployment process if required.

**Comment by fspoettel** [comment]
@jamesbook Maybe I'm misunderstanding the question here, but I do not see how the _Lightning Design System_ is related to Apex triggers or can be used with them. The LDS applies to the frontend of Salesforce applications. It can be used in _Lightning Components_, _Visualforce_ or in external applications that render to HTML. Apex triggers are relevant when dealing with DML operations in backend code and do not render any user interface.

If you want to create a custom user interface that invokes DML operations and triggers, you will have to look into creating custom lightning components or Visualforce pages. There is documentation available on how to use the LDS in both of these technologies.

Hope this helps!

**Comment by Dottenpixel** [comment]
Hi @jamesbook, as the Lightning Design System offers HTML and CSS code for user interfaces, logic code, such as Triggers, falls outside the realm of our support. You would implement the Lightning Design System code to build the user interface in the Lightning components and Visualforce pages that work with Triggers, in line with the answer @fspoettel gives.

Thanks @fspoettel!
