### ISSUE TITLE
timeline styling for all standard icons

### ISSUE THREAD

**Issue by moshner** [salesforce-ux/design-system#593]
When using the [activity timeline](https://www.lightningdesignsystem.com/components/activity-timeline/#site-main-content) I noticed that only the four example icons are fully supported. 

![image](https://user-images.githubusercontent.com/3300206/49175376-11e34980-f30e-11e8-8963-95309f937ac9.png)

Would it be possible to add support for all the [standard icons](https://www.lightningdesignsystem.com/icons/#standard)?

I would be happy to make the changes and submit a pull request but I want to make sure that there isn't good reason not to do it myself.

**Comment by engai** [comment]
@moshner If the intention is to follow the current style pattern -- Though the solution is simple, adding a `slds-timeline__item` modifier for each color would add a lot of potentially unnecessary code to the framework, and in turn to the Salesforce product.

**Comment by moshner** [comment]
It sounds like you have to serve two masters here. First is the Salesforce product and secondly, the external community who uses the design system. For those of us using the design system outside of the Salesforce product it is very helpful to have support for these additional use cases but it WILL increase your code. I can see where it looks like bloat to you since the Saleforce product only uses four types of icons in the timeline. However, to me it is just something I expected to work when I selected a different icon.

In the end it comes down to what your philosophy is in making this open source. Do you code for maximum flexibility for the design system or keep it focused on the Salesforce product.

If you don't want all these slds-timeline__item background colors added to the code I'll understand. We'll just add a layer of custom code css in our implementation.

Thanks for considering our viewpoint. 

Nick

P.S. If you or someone could take a second and look at my [other open request](https://github.com/salesforce-ux/design-system/issues/589) that would really help us in the custom implementation.
