### ISSUE TITLE
way to compile static css without old BEM syntax

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#596]
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

After asking you (@ishakasliwal @ayeshakmaz @engai) here (https://github.com/salesforce-ux/design-system/issues/467, https://github.com/salesforce-ux/design-system/issues/486, https://github.com/salesforce-ux/design-system/issues/546) durning 1.5year to build  and add static css file without old BEM syntax which increases 2x slds.min.css file, can someone help me to make a build of last version without old BEM syntax ? 

> Which version of the Salesforce Lightning Design System are you using?

2.8.0

> What did you expect to happen?

as @engai say to support Salesforce platform we can still keep in Static zip  actual slds.min.css file, BUT in addition add in this build-zip slds-without-old-bem-syntax.min.css too

> What actually happened?

static css file is provided with old BEM syntax  to primary "support the Salesforce platform", I was thinking this support was only durning 18months... but not, what you think about idea ? and an someone help me to make css build without old syntax.

**Comment by alexiscordova** [comment]
@istiti Unfortunately we don't have the bandwidth to accommodate this request in the 2.x major release cycle. We will take this under advisement for future releases.

**Comment by istiti** [comment]
@alexiscordova thank you
Let me know how you take this under advisement if you close issue how you guys work 😎?

What are the reasons to not consider this as priority feat request while currently this make these major issues for all people (slds platform too):

- ide autocomplete both syntax and we lost time instead to be productive/fast
- we download  bigger size of slds lib 

I cant understand
Thank you

**Comment by istiti** [comment]
thank you @alexiscordova !

"We don't track this within Github." 
- ok thank you

"please consider writing regular expressions"
- this will only replace our current projet/file to new syntax it won't fix IDE autocomplete on .html css class name, in autocomplete of css class we always have both syntax this is more annoying/long than quick ! we spend a lot of time to select correct syntax,i wonder how you didn't get this issue

anyway i really hope this be fixed

**Comment by alexiscordova** [comment]
As I stated earlier, we do understand the issue but we have many other issues and initiatives we are prioritizing as well (not to mention issues that arise when removing the old BEM syntax that isn't being considered), and we simply do not have the capacity at this time to tackle this particular task.

If the IDE is pulling autocomplete suggestions from the source material, using PostCSS or regular expressions to strip out the old syntax from your installation of SLDS should work just fine. Worst case, you are free to fork this repository and make any changes you need.
