### ISSUE TITLE
Couldn't add new component in design system previewer

### ISSUE THREAD

**Issue by ika18** [salesforce-ux/design-system#597]
According to the [README](https://github.com/salesforce-ux/design-system#annotations) to add new component or utility, I add new folder under ```ui/components``` and restart the previewer. I found nothing change in the previewer page.
Then I took a deeper look into that, I found there is a dependency named ```@salesforce-ux/design-system-previewer``` that used a bundle file as previewer main script. That script is bundled from webpack and I didn't have any approach to config it.

So I'm wonder whether the package ```@salesforce-ux/design-system-previewer``` is open source or not? If it's not, how could I add new component in the previewer page?

Looking forward the answer and thanks in advanced!

**Comment by ika18** [comment]
So anyone can help this?

**Comment by brandonferrua** [comment]
You need the correct annotations for it to become available to the previewer. https://github.com/salesforce-ux/design-system/blob/master/guidelines/ANNOTATIONS.md

**Comment by ika18** [comment]
@brandonferrua Thanks for your help! That's it.
