### ISSUE TITLE
Responsive Spacing

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#60]
While the spacing classes prove useful for a number of situations, I feel it could be greatly improved with breakpoint affixes, just like how sizing works. This would be helpful in instances where you add margin/padding to an element contained in a column that changes sizing on breakpoints.

Suggested model: `.slds-large-m-top--medium`

**Comment by stefsullrew** [comment]
Thanks for the suggestion @kevinberonilla - We've discussed this numerous times. So you would expect it to work like sizing does? (Putting on more than one class when you want spacing to change at a breakpoint?)

**Comment by kevinberonilla** [comment]
Yes, I believe following the same paradigm would be best.

**Comment by kaelig** [comment]
@stefsullrew @jina are we planning to do something about this?

**Comment by kaelig** [comment]
Closing this as the feature-request is a year old and it hasn't seen activity or support requests from other customers.
