### ISSUE TITLE
Date Picker inside a table causes an overflow

### ISSUE THREAD

**Issue by junners** [salesforce-ux/design-system#600]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case. 

[Code Pen](https://codepen.io/anon/pen/gqgvwo#anon-login)

![xxxxx-image](https://user-images.githubusercontent.com/6131635/52050133-95c5e600-258a-11e9-8bd9-8026d4cf88f8.png)
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

a bug where putting a lightning:input type=date inside a table, when the date picker is open, you can see additional padding per column, what's more noticable is that the table body of the date picker has gone over the container

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Lightning input type=date

> Are any specific browsers impacted by this bug?

Tested on Chrome 71.0.3578.98
> Which version of the Salesforce Lightning Design System are you using?

SLDS - 2.8.1
> What steps and/or code are needed to reproduce this issue?

```
<table class="slds-table slds-table_cell-buffer slds-table_bordered">
  <thead>
    <tr>
      <td>
        Some Header
      </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <lightning:input type="date"
                         label="Some Date"/>
      </td>
    </tr>
  </tbody>
</table>
```

> What did you expect to happen?

The date picker table body shouldn't overflow from the container
> What actually happened?

The date picker table body overflowed from the container

**Comment by collinlee** [comment]
I'm a little new to this whole project, but it seems like however app.css is interfering with the style and whether the date picker object widget itself inserts a table-layout: fixed rule.  You may have to scope this in your component for now.

![screen shot 2019-02-01 at 12 46 20](https://user-images.githubusercontent.com/299502/52148854-d28fec80-261f-11e9-8f5d-8c1e1622d23d.png)

**Comment by junners** [comment]
Thanks @collinlee, adding the table-layout : fixed did the trick. I wonder if the slds folks release an official fix for this.
