### ISSUE TITLE
lightning-helptext not filling color

### ISSUE THREAD

**Issue by chandra2ravi** [salesforce-ux/design-system#603]
> What did you expect to happen?
lightning-helptext not fill green color like lightning-icon. we need that and add size property like  icon-size
2. Please add icon-variant success so we can use for "/img/msg_icons/confirm32.png" in classic

![image](https://user-images.githubusercontent.com/93057/53512413-53f46680-3a88-11e9-9b64-d7850fc1a73e.png)

**Comment by chandra2ravi** [comment]
@brandonferrua any alternative for this we need green color success?

**Comment by Alex-Popov** [comment]
Got the same problem. Component haven't any reaction to` icon-variant="inverse"`

**Comment by gfmmoreira** [comment]
I am also having the same issue, cannot set a success `icon-variant` for a `<lightning-helptext>` component. DAE knows if this is achievable by setting a `fill` property on the LWC CSS file?

**Comment by kflournoy-sf** [comment]
Update provided in https://github.com/salesforce-ux/design-system/issues/678
