### ISSUE TITLE
Generate "Brand-Based Color Palette" from "Brand Color"

### ISSUE THREAD

**Issue by jbverger** [salesforce-ux/design-system#609]
Are there any functions or documentations regarding the ability to generate the "Lightning Brand-Based Color Palette" from a "Brand Color" like in Salesforce Lightning?

![Salesforce Branding](https://user-images.githubusercontent.com/8539079/55100053-50f49200-5097-11e9-839b-d5a565f4d344.png)

Thanks,

**Comment by Dottenpixel** [comment]
Thank you for your post @jbverger. We will take this under consideration of feature requests. Have you checked out http://colorsafe.co?
