### ISSUE TITLE
SSL certificate expired on https://www.lightningdesignsystem.com/

### ISSUE THREAD

**Issue by JAertgeerts** [salesforce-ux/design-system#612]
https://www.lightningdesignsystem.com/
SSL cert is expired.
![image](https://user-images.githubusercontent.com/2192516/56583482-ee30e080-65d9-11e9-82aa-79864b88bfa4.png)

**Comment by zahnster** [comment]
The certificate was renewed and is currently valid.

![Screen Shot 2019-06-19 at 12 47 47 PM](https://user-images.githubusercontent.com/36438/59788093-9c7e9c80-9290-11e9-83e6-d5c9d1329e6d.png)
