### ISSUE TITLE
Background of html tag changed from #fafaf9 to #b0c4df 

### ISSUE THREAD

**Issue by Niondir** [salesforce-ux/design-system#616]
I updated from 2.8.3 to 2.9.2 and all my background changed color from #fafaf9 to #b0c4df

I guess it comes from https://github.com/salesforce-ux/design-system/blob/21b01368fc63db0cf53c077def1ebffd9bb4c64d/design-tokens/themes/oneSalesforce/global/palette-colors.yml

```
BRAND_BACKGROUND_PRIMARY:
    value: "#b0c4df"
```

**Comment by jgerigmeyer** [comment]
Any progress on this, or clarification on whether the change was intentional or not?

**Comment by stefsullrew** [comment]
It is intentional. The change happened where the background of platform is blue (and brandable by admins). Everything in it is in an .slds-card. So depending on where you're using this code, you can either put your components into cards like platform does, or override the background color.

Cheers

**Comment by Niondir** [comment]
Can you provide some migration path? I just have to put my whole page into a `.slds-card`?
