### ISSUE TITLE
Fresh Clone fails to build

### ISSUE THREAD

**Issue by TheBeachMaster** [salesforce-ux/design-system#618]
Similar to [this](https://github.com/salesforce-ux/design-system/issues?utf8=%E2%9C%93&q=build+error) 

> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
![slds1](https://user-images.githubusercontent.com/9129843/59961831-16f42a00-94e6-11e9-9829-12e195939f2c.png)
![slds2](https://user-images.githubusercontent.com/9129843/59961832-178cc080-94e6-11e9-9eba-292b3dbcf563.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Unable to install npm packages. Install step errors out at `node-sass` module.

> What steps and/or code are needed to reproduce this issue?

- `git clone https://github.com/salesforce-ux/design-system.git` 
- `npm install`
- `npm start`

> What did you expect to happen?

* Successful package install 
* Running preview

> What actually happened?

 

``` 
make: *** [binding.target.mk:127: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/thebeachmaster/git/design-system/node_modules/@salesforce-ux/scss-parser-aura/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/thebeachmaster/git/design-system/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.9-arch1-1-ARCH
gyp ERR! command "/usr/local/bin/node" "/home/thebeachmaster/git/design-system/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/thebeachmaster/git/design-system/node_modules/@salesforce-ux/scss-parser-aura/node_modules/node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thebeachmaster/.npm/_logs/2019-06-22T08_03_38_080Z-debug.log
``` 
> Attempts to fix 

Used Docker `node:8-alpine`  

Build still failed  

``` 
 thebeachmaster@thebeachmaster  ~  sudo docker logs 843c5aee4559                                                                                                       ✔  7687  11:25:57
[sudo] password for thebeachmaster: 

> design-system@2.9.3 start /usr/src/app
> npm run build && npm run previewer


> design-system@2.9.3 build /usr/src/app
> npm run gulp -- build


> design-system@2.9.3 gulp /usr/src/app
> babel-node ./node_modules/gulp/bin/gulp.js "build"

sh: babel-node: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! design-system@2.9.3 gulp: `babel-node ./node_modules/gulp/bin/gulp.js "build"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the design-system@2.9.3 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-22T08_24_35_721Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.9.3 build: `npm run gulp -- build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-system@2.9.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-22T08_24_35_770Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.9.3 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-system@2.9.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-22T08_24_35_817Z-debug.log 
``` 

I switched to `node:8.16.0-alpine` as per [this comment](https://github.com/salesforce-ux/design-system/issues/606#issuecomment-504063634) 

Still the same error. 

Note that it complains about `babel-node: not found` . 

I picked an idea from [this issue](https://github.com/salesforce-ux/design-system/issues/562)  

Running `npm install --save-dev  @babel/node` failed as `babel-node` requires `babel-core` `v7+` but `v6.24.0` found vide [#L40](https://github.com/salesforce-ux/design-system/blob/d08e33c74d52519f957ed1b61267515da40fdd90/package.json#L40) ...

**Help wanted** 

Suggestions :

Maybe a prebuilt preview app Docker image from the SLDS team will help.

**Comment by nktkarnany** [comment]
Facing a similar problem with the latest clone of this repo. Please suggest what are possible fixes for this.

**Comment by zahnster** [comment]
Hi @TheBeachMaster,

Looks like you have to install a slightly older version of Node on Mac than what was recommended in the related Linux issue. I run v8.11.1 locally, and this is known to be compatible with the 

Can you try things with that version?

SLDS is looking into updating our dependencies to resolve this version incompatibility.

**Comment by zahnster** [comment]
Hi @TheBeachMaster,

Looks like you have to install a slightly older version of Node on Mac than what was recommended in the related Linux issue. I run v8.11.1 locally, and this is known to be compatible with the codebase.

Can you try things with that version?

SLDS is looking into updating our dependencies to resolve this version incompatibility.

**Comment by megatimes** [comment]
@zahnster Confirmed that this solution ([and your original suggestion](https://github.com/salesforce-ux/design-system/issues/606#issuecomment-504063634)) worked for me on macOS after changing the Node version. Details: 
* Node v8.16.0 (nvm-managed)
* npm v6.4.1 (Brew-managed)
* macOS Mojave 10.14.5
