### ISSUE TITLE
Card missing border when included inside tab

### ISSUE THREAD

**Issue by firo** [salesforce-ux/design-system#619]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
The lightning-card misses the border only when included in the tab.

here you see an example of the missing border: on top, the same component has boarder (not included in the tab) and below another example of the same component without the border and included in the tab.

my HTML tag is <lightning-card  variant="Narrow"  title="Journey (2+)" icon-name="action:new_campaign" class="slds-card_boundary">

<img width="721" alt="Screenshot 2019-07-03 at 12 05 24" src="https://user-images.githubusercontent.com/471014/60583324-e8e6d380-9d8a-11e9-9271-3de417e8f811.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Affects existing component that is missing border when the component is included in the tab.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

lightning:card

> Are any specific browsers impacted by this bug?

NA

> Which version of the Salesforce Lightning Design System are you using?

Summer '19
> What steps and/or code are needed to reproduce this issue?

create card and than place the component in Tabs.

<lightning-card  variant="Narrow"  title="Journey (2+)" icon-name="action:new_campaign" class="slds-card_boundary">

> What did you expect to happen?

See the component's borders also when included in the Tab.

> What actually happened?

the component's border disappears and seeing two vertical lines on top and bottom of the component

**Comment by firo** [comment]
I noticed the solution could be adding style class to the following tag lightning-card, article, and header. However, article and header tags are automatically rendered. 

How can address the style enforcement to articles and header tags? 

- lightning-card class="related_list_card_border_top forceRelatedListCardDesktop"
- article class="slds-card_boundary related_list_card_border_top forceRelatedListCardDesktop"
- header class="slds-card__header slds-grid related_list_themed_border_top"

**Comment by Dottenpixel** [comment]
Thanks for your post @firo! Is there a code snippet you could share that would help us troubleshoot?

**Comment by Dottenpixel** [comment]
@firo Although I don't see it specifically speaking to tabs, in the Lightning Design System CSS there is a declaration in there to purposefully remove the Card border and drop shadow inside a tab content. In effect, it takes on the styling of a [Nested Card](https://www.lightningdesignsystem.com/components/cards/#Nested-Cards). [If you would like to retain the border and shadow](https://www.lightningdesignsystem.com/components/cards/#With-card-styling), apply the `slds-card_boundary` class to your `slds-card`.

We will look to add documentations speaking to Cards in Tabs

I'm still curious as to why you have those remnant vertical lines on top and bottom, so please send a code snippet or steps to reproduce if you can.

Thanks!

**Comment by sdieryck** [comment]
Hello I have the same problem as firo. And when I apply the slds-card_boundary class some strange lines appear (you can see them on the left side of the joined picture) and the proper lines are still invisible. The modal window inside has the same problem.
![image](https://user-images.githubusercontent.com/7486826/80813354-30680700-8bca-11ea-8069-a021296a887a.png)

![image](https://user-images.githubusercontent.com/7486826/80813844-1aa71180-8bcb-11ea-90f6-6cda7f04650b.png)

Here is a code snippet to reproduce the problem. One step to reproduce the problem is to use it inside a tab as the same code works great outside of tabs.
<template>
    
    <div class="slds-p-around_large">
        

        <lightning-card title={label.filters} class="slds-card_boundary" icon-name="standard:filter">
            <div class="slds-grid slds-gutters slds-p-around_small ">
                <div class="slds-col">
                    <lightning-input type="date" name="dateFrom" label={label.from} onchange={genericOnChange}
                                     value={dateFrom}></lightning-input>
                </div>
                <div class="slds-col">
                    <lightning-input type="date" name="dateTo" label={label.to} onchange={genericOnChange}
                                     value={dateTo}></lightning-input>
                </div>
            </div>
            <div class="slds-grid slds-gutters slds-p-around_small">
                <div class="slds-col">
                    <lightning-combobox
                            name="elChannel"
                            label={label.channel}
                            value={value}
                            placeholder={label.selectChannel}
                            options={channels}
                            onchange={genericOnChange}>
                    </lightning-combobox>
                </div>
                <div class="slds-col">
                    <lightning-combobox
                            name="elTopic"
                            label={label.topic}
                            value={value}
                            placeholder={label.selectTopic}
                            options={topics}
                            onchange={genericOnChange}>
                    </lightning-combobox>
                </div>
            </div>
        </lightning-card>


    </div>
</template>

**Comment by Damecek** [comment]
Hi guys the slds-card_boundary fix still does not work with card inside a tab.

**Comment by chrisabralse** [comment]
This fix no longer works and the docs do not explain how any variant might allow this to work.

We should be able to specify a lightning-card element and control whether it displays with a border or not without having to reimplement the card.
