### ISSUE TITLE
Drop- Down menu items do not disappear when touched 

### ISSUE THREAD

**Issue by ErikatUCI** [salesforce-ux/design-system#62]
I am using an slds-dropdown class with multiple menu items.  In a browser, the hover function works and I can click on one of the items in the list.  When I do so the action I clicked on takes place and the menu items collapse back into the header.  However, on a tablet or phone one touches the menu to open and then touches an item in the list.  The selected action takes place but the dropdown never closes.  Instead it lays on top of the new content in the page.

Is there any way to force the dropdown to close after an item has been selected?

**Comment by srohde** [comment]
The Design System does not provide any JavaScript. This has to be implemented.
