### ISSUE TITLE
Blocktester reporting Mixed Content error

### ISSUE THREAD

**Issue by alemieux3** [salesforce-ux/design-system#620]
I developed an app with the Custom Content Block SDK (https://github.com/vargasd/blocksdk/wiki/Using-the-Block-SDK:-Basic-Node.js-&-Heroku-Approach) and previously was able to test it in the blocktester.herokuapp.com tester. 

I am now getting Mixed Content errors in the blocktester. None of my code is pulling in external assets via http, as you can see here:

`<!DOCTYPE html>
<html lang="en">
	
	<head>
		
		<title>HTML5 Example</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" >
		
		<script src="js/blocksdk.js" type="text/javascript"></script>
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i&display=swap" rel="stylesheet">
		<style>
			body { font-family: 'Open Sans', sans-serif;
				font-size: 16px;
				line-height: 23px;
				color: #333;
			}
			h1 { text-transform: uppercase;
				font-size: 26px;
				letter-spacing: 1px; 
			}
			label { display: block; padding-bottom: .5em; }
			section { padding-top: 1em; padding-bottom: 1em; }
			input[type='text'] {
				width: 300px;
				padding: 5px;
				font-size: 16px;
				color: #333;
			}
			input[type='submit'] {
				background-color: #00aeef;
				border-color: #00aeef;
				padding: 10px 12px;
				color: #fff;
				border-radius: 2px;
				font-size: 16px;
				text-transform: uppercase;
			}
		</style>
		<script>
			var sdk = new window.sfdc.BlockSDK(null, null, true);

			function paintButton() {
				/* Change Button settings */
				var button_text = document.getElementById('button-text').value;
				var button_url = document.getElementById('button-url').value;
				var button_align = document.getElementById('button-align').value;
				sdk.setContent('<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td width="40">&nbsp;</td><td><table border="0" cellspacing="0" cellpadding="0" width="250" align="' + button_align + '"><tr><td height="48" align="center" bgcolor="#00aeef" valign="middle"><a href="' + button_url + '" style="font-size: 16px; line-height: 16px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; border: 1px solid #00aeef; display: block; text-transform: uppercase; font-weight: bold; vertical-align: middle;" target="_blank">' + button_text + '</a></td></tr></table></td><td width="40">&nbsp;</td></tr></table>');
			}
		</script>

	</head>

	<body>
		<main>
			<header>
				<h1>Custom Button Builder</h1>
			</header>
			<section>
				<label for="button-text">Button Text:</label>
				<input type="text" id="button-text" />
			</section>
			<section>
				<label for="button-url">Button URL:</label>
				<input type="text" id="button-url" />
			</section>
			<section>
				<label for="button-align">Button Alignment:</label>
				<select id="button-align">
					<option value="center">Center</option>
					<option value="left">Left</option>
				</select>
			</section>
			<section>
				<input type="submit" value="Change Button" onclick="paintButton();" />
			</section>
		</main>
	</body>

</html>`

My only guess is that the error might be related to the Lightning Design system. It's pulling in some fonts and assets with paths that might be causing the errors. 

Please help! I can't use the blocktester with these errors. 
![Screen Shot 2019-07-09 at 11 15 41 AM](https://user-images.githubusercontent.com/1919292/60919701-636c9300-a264-11e9-8266-b313396b44e6.png)

**Comment by Dottenpixel** [comment]
Hi @alemieux3, I'm not too familiar with Custom Content Block, but the fonts you're pulling in are from google and I don't see where you're using SLDS.
