### ISSUE TITLE
What js chart library is used/recommended by slds team?

### ISSUE THREAD

**Issue by sudhirjena** [salesforce-ux/design-system#621]
I just have a question for the slds team.
Although the design guidelines for charts are nicely illustrated on https://www.lightningdesignsystem.com/guidelines/charts/#site-main-content, but just wanted to know which js chart library was used or recommended to have charts like shown in the design guidelines for charts. 
![image](https://user-images.githubusercontent.com/1389495/60974279-cce9b180-a2f7-11e9-9dd7-57a3167ac5b7.png)
![image](https://user-images.githubusercontent.com/1389495/60974310-db37cd80-a2f7-11e9-9869-d2a88f99e910.png)

**Comment by Dottenpixel** [comment]
Thank you for your post, @sudhirjena! We don't endorse or consume any chart library on the lightningdesignsystem.com. The chart illustrations are design guidelines to show the recommended user interface-level look, feel and usage to achieve in your chosen chart library.
