### ISSUE TITLE
rewrite example code to use lightning:icon

### ISSUE THREAD

**Issue by davidrobertslogicom** [salesforce-ux/design-system#624]
I understand that lightning now uses Lightning:icon however, I find it difficult to rewrite the example code.
In "Focused Lookup" at https://lightningdesignsystem.com/components/lookups/
the snippet includes
```
<svg class="slds-icon slds-icon slds-icon_x-small slds-icon-text-default" aria-hidden="true">
                <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#search"></use>
              </svg>
```

which I've swapped for
`<lightning:icon iconName="standard:account" />`

but it doesn't look at all correct.

Is there documentation that is more specific to lightning?
Hard coding the list of companies as in the above example means a lot of thinking to use in a real situation where a list has been returned.

**Comment by Dottenpixel** [comment]
Thank you for your post, @davidrobertslogicom! Try the [Base Component documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning:icon/example) for `lightning:icon`. If you find you can't render the necessary icon variant to fit into the Lookup, please let us know.

Also. can you share a code snippet or screenshot of your result after swapping out the `<svg>`?

**Comment by davidrobertslogicom** [comment]
Hi @Dottenpixel 
![LightningIcon](https://user-images.githubusercontent.com/40492834/67471595-8f5f2900-f647-11e9-8130-fc6d4c89d507.jpg)
See attached image. The icon is offset from the search box.
The code snippet doesn't list the items, either. Very odd example.

Here's my substituted code:

`    
    
    <div class="slds-form-element">
        <div class="slds-form-element__control">
            <div class="slds-combobox_container">
                <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click" aria-expanded="false" aria-haspopup="listbox" role="combobox">
                    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" role="none">
                        <input type="text" class="slds-input slds-combobox__input" id="combobox-id-1" aria-autocomplete="list" aria-controls="listbox-id-1" autoComplete="off" role="textbox" placeholder="Search..." />
                        <span class="slds-icon_container slds-icon-utility-search slds-input__icon slds-input__icon_right">
                            
                            <lightning:icon iconName="standard:account" />
                        </span>
                    </div>
                    
                    
                    
                    
                     <div id="listbox-id-1" class="slds-dropdown slds-dropdown_length-with-icon-7 slds-dropdown_fluid" role="listbox">
          <ul class="slds-listbox slds-listbox_vertical" role="presentation">
            <li role="presentation" class="slds-listbox__item">
              <div id="option1" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                <span class="slds-media__figure slds-listbox__option-icon">
                  <span class="slds-icon_container slds-icon-standard-account">
                    
                      <lightning:icon iconName="standard:account" />
                  </span>
                </span>
                <span class="slds-media__body">
                  <span class="slds-listbox__option-text slds-listbox__option-text_entity">Burlington Textiles Corp of America</span>
                  <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Burlington, NC</span>
                </span>
              </div>
            </li>
            <li role="presentation" class="slds-listbox__item">
              <div id="option2" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                <span class="slds-media__figure slds-listbox__option-icon">
                  <span class="slds-icon_container slds-icon-standard-account">
                    
                      <lightning:icon iconName="standard:account" />
                  </span>
                </span>
                <span class="slds-media__body">
                  <span class="slds-listbox__option-text slds-listbox__option-text_entity">Dickenson plc</span>
                  <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Lawrence, KS</span>
                </span>
              </div>
            </li>
            <li role="presentation" class="slds-listbox__item">
              <div id="option3" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                <span class="slds-media__figure slds-listbox__option-icon">
                  <span class="slds-icon_container slds-icon-standard-account">
                    
                      <lightning:icon iconName="standard:account" />
                  </span>
                </span>
                <span class="slds-media__body">
                  <span class="slds-listbox__option-text slds-listbox__option-text_entity">Edge Communications</span>
                  <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Austin, TX</span>
                </span>
              </div>
            </li>
          </ul>
        </div>
                    
                    
                </div>
            </div>
        </div>
    
    </div>
    `

**Comment by Dottenpixel** [comment]
Thanks @davidrobertslogicom. It appears you have replaced the `utility:search` icon from the blueprint with a `standard:account` icon. The search box icon is also `x-small` in the blueprint, so that lightning component markup you'd want in there is:
```
<lightning:icon iconName="utility:search" size="x-small"/>
```

**Comment by davidrobertslogicom** [comment]
It did. Thank you.

**Comment by davidrobertslogicom** [comment]
It fixed the icon issue, which is great.
However, The list box still doesn't function.
It's supposed to list
Burlington Textiles Corp of America
and Dickenson plc.

Here's the revised code:

`        <div class="slds-form-element">
            <div class="slds-form-element__control">
                <div class="slds-combobox_container">
                    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click" aria-expanded="false" aria-haspopup="listbox" role="combobox">
                        <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" role="none">
                            <input type="text" class="slds-input slds-combobox__input" id="combobox-id-1" aria-autocomplete="list" aria-controls="listbox-id-1" autoComplete="off" role="textbox" placeholder="Search..." />
                            <span class="slds-icon_container slds-icon-utility-search slds-input__icon slds-input__icon_right">
                                
                                <lightning:icon iconName="standard:account"  size="x-small"/>
                            </span>
                        </div>
                        
                        
                        
                        
                        <div id="listbox-id-1" class="slds-dropdown slds-dropdown_length-with-icon-7 slds-dropdown_fluid" role="listbox">
                            <ul class="slds-listbox slds-listbox_vertical" role="presentation">
                                <li role="presentation" class="slds-listbox__item">
                                    <div id="option1" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                                        <span class="slds-media__figure slds-listbox__option-icon">
                                            <span class="slds-icon_container slds-icon-standard-account">
                                                
                                                <lightning:icon iconName="standard:account"  size="x-small"/>
                                            </span>
                                        </span>
                                        <span class="slds-media__body">
                                            <span class="slds-listbox__option-text slds-listbox__option-text_entity">Burlington Textiles Corp of America</span>
                                            <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Burlington, NC</span>
                                        </span>
                                    </div>
                                </li>
                                <li role="presentation" class="slds-listbox__item">
                                    <div id="option2" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                                        <span class="slds-media__figure slds-listbox__option-icon">
                                            <span class="slds-icon_container slds-icon-standard-account">
                                                
                                                <lightning:icon iconName="standard:account"  size="x-small"/>
                                            </span>
                                        </span>
                                        <span class="slds-media__body">
                                            <span class="slds-listbox__option-text slds-listbox__option-text_entity">Dickenson plc</span>
                                            <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Lawrence, KS</span>
                                        </span>
                                    </div>
                                </li>
                                <li role="presentation" class="slds-listbox__item">
                                    <div id="option3" class="slds-media slds-listbox__option slds-listbox__option_entity slds-listbox__option_has-meta" role="option">
                                        <span class="slds-media__figure slds-listbox__option-icon">
                                            <span class="slds-icon_container slds-icon-standard-account">
                                                
                                                <lightning:icon iconName="standard:account"  size="x-small"/>
                                            </span>
                                        </span>
                                        <span class="slds-media__body">
                                            <span class="slds-listbox__option-text slds-listbox__option-text_entity">Edge Communications</span>
                                            <span class="slds-listbox__option-meta slds-listbox__option-meta_entity">Account • Austin, TX</span>
                                        </span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
            
        </div>
      `
