### ISSUE TITLE
Provide ability to load SCSS for specific components

### ISSUE THREAD

**Issue by bekos** [salesforce-ux/design-system#625]
It would be nice to have a flag for each component that we don't want to use, similar to what `$slds-load-webfonts` does, but for each component.

This way, we don't have to load all the framework's CSS even if we use just few of the components.
Probably this can be handed at `scss/components/_index.scss` file.

**Comment by Dottenpixel** [comment]
Thank you for your post @bekos! As we enter the Web Components space, we will take this into consideration.
