### ISSUE TITLE
Static resource build exceeds 5MB limit of static resource

### ISSUE THREAD

**Issue by fspoettel** [salesforce-ux/design-system#626]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

--

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The static resource builds hosted on the [Downloads page](https://lightningdesignsystem.com/downloads/) exceeds the static resource size limit of 5MB.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

--

> Are any specific browsers impacted by this bug?

--

> Which version of the Salesforce Lightning Design System are you using?

2.10.0

> What steps and/or code are needed to reproduce this issue?

* Download static resource build from the website
* Add it as static resource to the org source
* Push to org via `sfdx`

> What did you expect to happen?

This specific build to work as a static resource (as advertised)

> What actually happened?

--

**Comment by fspoettel** [comment]
@Dottenpixel I do exactly that right now. I would assume that the provided _StaticResource build_ would actually fit into a StaticResource though. There is no point in choosing it over the normal release if it doesn't

**Comment by Nashle** [comment]
Hi Aloha,

The resource should be handy for adding it as a static resource in Salesforce effortlessly.

I am also faced with the problem of 5 MB. And I do not know which resource to delete, so I delete the images but alas, the display of my flow did not work properly.

The only solution that I find until you find another solution is to use version 2.8.3.

I suggest 2 solutions:

1. You find the way to reduce the archive below 5 MB by optimizing images and icons.
2. You ask Salesforce to increase the load capacity for static resources ;-)

Regards,
Brice

**Comment by fspoettel** [comment]
thank you for your response @Nashle. I'm currently blacklisting some of the image assets (`/carousel`, `/themes/classic`), the `.ttf` fonts and unminified CSS to stay below the limit. I suspect that this problem will only get worse with every release though.  Salesforce raising the static resource size limit would be awesome but we cannot count on that.

As mentioned previously, this issue mainly relates to the misleading copy on the Downloads page:

> If you still need to upload the Lightning Design System as a static resource, use the following zip that will meet the static resource requirements.

It's simply not true that that `.zip` meets the requirements in its current form. Given that there are still use cases where one needs to add the LDS as a static resource (usage inside `lightning:container` to name a recent example) I find this somewhat frustrating.

**Comment by Nashle** [comment]
Ok, thank you for your return.

Perhaps you should see with Salesforce to make this static resource a constant in Salesforce environments one way or another. I mean that this resource face integral part of the environments. This way no more need for admin or developers to load it.

Cordialy

**Comment by tfuda** [comment]
Four plus months, and this issue remains unassigned, and still problematic with the current version (2.11.3). Anyone from Salesforce watching?

**Comment by fspoettel** [comment]
still an issue

**Comment by fredboyle** [comment]
@fspoettel Is there a particular reason you need SLDS added as a static resource? SLDS is loaded as part of the Salesforce environment and is not needed as a static resource.

[See this FAQ for more info](https://lightningdesignsystem.com/faq/#how-do-i-link-to-lightning-static-resources-like-stylesheets-and-icons).

**Comment by fspoettel** [comment]
> @fspoettel Is there a particular reason you need SLDS added as a static resource? SLDS is loaded as part of the Salesforce environment and is not needed as a static resource.
> 
> [See this FAQ for more info](https://lightningdesignsystem.com/faq/#how-do-i-link-to-lightning-static-resources-like-stylesheets-and-icons).

My use case was a SPA that was hosted in a  `lighting:container`. As far as I know I cannot use `ltng:require` in there. There are other commenters, not sure about their use cases.

Besides that, the Downloads page specifically offers a static resource download that does not work as a static resource. That is a bit confusing.

**Comment by kirupa** [comment]
Hi Felix - thanks for letting us know about this. I'll follow-up and see what we can do here.

**Comment by tfuda** [comment]
My use case is similar. I've got a Single Page App (React-based) that is hosted in a Visualforce page and styled using LDS. I tried to use the npm package, but ran into issues trying to get the SVG icon sprites loaded properly (especially when used in conjunction with the Lightning Design System for React component library).

**Comment by fspoettel** [comment]
@tfuda We ran into that issue as well when using React inside a Visualforce page. We eventually managed to find a workaround that IIRC looked like this:

* Load SLDS via the `$Asset.SLDS` VF global
* Bind the path acquired from `!URLFOR($Asset.SLDS, '/assets')` (?not sure about assets, don't work on that codebase anymore) to a global on `window`
* We used our own React bindings (https://github.com/react-lds/react-lds) which exposed this global via an `AssetPathProvider` (https://github.com/react-lds/react-lds/pull/487/files#diff-b49ba36548447bd623bc7d8142ac1899R1-R26) to the Icon component (https://github.com/react-lds/react-lds/blob/master/src/components/Icon/IconSVG.js#L16-L20)

...that actually worked :joy:. Not sure if this is applicable to the official React component library

**Comment by tfuda** [comment]
Commenting to keep this issue alive.

**Comment by Ihor-Horchynskyi** [comment]
Commenting to keep this issue alive.

**Comment by Wayupblessed** [comment]
No fix yet? smh

I need to use it in aura component.

**Comment by kirupa** [comment]
> No fix yet? smh
> 
> I need to use it in aura component.

This is something we have in our backlog, but we haven't had bandwidth to get to address it. Does dottenpixel's advice above (https://github.com/salesforce-ux/design-system/issues/626#issuecomment-545724775) around stripping out parts of the bundle you don't need help reduce the file size to an acceptable limit?

Thanks,
Kirupa

**Comment by alexferrari88** [comment]
@kirupa we need to know what can be safely removed and what can't first

**Comment by Dottenpixel** [comment]
@alexferrari88 I just tried this: stripping out the icon PNGs. It re-zipped down to 3.4MB. This should work for those using only the icon SVGs, so hopefully most cases. 

1. Download and expand the Static Resource ZIP from getslds.com
2. Delete theses folders from the expanded folder:
    ```
    icons/utility
    icons/standard
    icons/action
    icons/custom
    icons/doctype
    ```
3. Re-zip expanded folder and upload to org

**Comment by tfuda** [comment]
> @alexferrari88 I just tried this: stripping out the icon PNGs. It re-zipped down to 3.4MB. This should work for those using only the icon SVGs, so hopefully most cases.
> 
> 1. Download and expand the Static Resource ZIP from getslds.com
> 2. Delete theses folders from the expanded folder:
>    ```
>    icons/utility
>    icons/standard
>    icons/action
>    icons/custom
>    icons/doctype
>    ```
> 3. Re-zip expanded folder and upload to org

Thank you for posting this. It may be helpful in my case. I find it sad that this surgery is necessary in the first place however. Surely, Salesforce could figure out a way to either provide this resource in every org, or, implement a mechanism to allow bypassing the 5 MB size limit for whitelisted content like the SLDS static resource bundle.

**Comment by fredboyle** [comment]
@tfuda It is on our lengthy to-do list and we haven't forgotten. One gentle reminder though is that if you're working in an Org in the Salesforce ecosystem SLDS is already included and requires no additional action to use it and access the styles and resources. So there's no need to load it a second time as a static resource.

**Comment by fredboyle** [comment]
For those of you that still want, or may need, a smaller ZIP file of the SLDS bundle [it is now available on our website](https://www.lightningdesignsystem.com/resources/downloads/).

It is under "Lightning Design System Static Resource", there is now a link to download a version without the icons which is a ZIP file under 3MB.

**Comment by fspoettel** [comment]
nice! thank you for fixing the issue :)
