### ISSUE TITLE
Doc Bug: Dueling Picklist Responsive 

### ISSUE THREAD

**Issue by mtetlow** [salesforce-ux/design-system#627]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![Screen Shot 2019-10-04 at 1 29 07 PM](https://user-images.githubusercontent.com/1168845/66234468-03db2380-e6ab-11e9-9af9-0b9bf249877c.png)
> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The header text here: https://www.lightningdesignsystem.com/components/dueling-picklist/#Responsive calls out two classes that aren't in the design system `slds-dueling-picklist__column_responsive` and `slds-dueling-picklist__column`

The implementation directly below it uses the correct classes:
`slds-dueling-list__column` and `slds-dueling-list__column_responsive`

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Related to the latest version of the docs site

> Are any specific browsers impacted by this bug?

All

> Which version of the Salesforce Lightning Design System are you using?

Latest

> What steps and/or code are needed to reproduce this issue?

Visit the link and compare the two strings

> What did you expect to happen?

I would expect the classes in the implementation to be called out in the header so I can copy paste like a nub.

> What actually happened?

I copy pasted the wrong classes like a nub and wondered if I was on a old version of the slds or what else I did wrong.

**Comment by Dottenpixel** [comment]
Thank you for your post @mtetlow. We will file a bug to fix that classname discrepancy in the documentation.
