### ISSUE TITLE
SLDS and Lightning UI: component styles are different

### ISSUE THREAD

**Issue by ErikatUCI** [salesforce-ux/design-system#63]
The Lightning UI components, such as UI:Button, use different styles and have different styling options that the Lightning Design System.  If I use the SLDS styles applied to native HTML tags, then the styling of the UI: components clash with SLDS.  I am forced to use native HTML input elements instead of the Lightning UI: components if I want to maintain consistency with the SLDS styles. This loses a lot of the functionality the UI: components offer.  Will the Lightning UI: components be retrofitted to use SLDS styles?

**Comment by jselis** [comment]
Hi ErikatUCI, I had exactly the same problem. The right solution would be to give us the option in Lightning Components to switch OFF the internal styles, so that SLDS can be applied without clashing.
However, there is an easy work-around (it worked for my up to now). See my answer on a similar remark on salesforce.stackexchange: http://salesforce.stackexchange.com/questions/93148/lightning-design-system-is-overridden-by-styles-from-app-css/96077#96077
It comes down to removing the stylesheet dynamically from the page before it is shown (the nice thing about Lightning Components/Aura is that it provides you the hooks needed to build that in).

**Comment by ErikatUCI** [comment]
Interesting work around.  I have a more complex app which creates a lot of components dynamically.  It will take some testing to see if this work around is a comprehensive solution.  I will give it a try.  Thanks for your suggestion.

**Comment by ErikatUCI** [comment]
Jan, I tried your suggestion which you have posted on the stackexchange link above.  It seemed to work fine in the browser but did not work on my Android phone.  The initial landing page rendered fine but when I swiped down to refresh the page I got an error "Looks like there's a problem. rerender threw an error in 'markup://aura:expression' : Cannot read property 'parentNode' of undefined".  And Salesforce1 froze.  I had to go into task manager, close and restart Salesforce1.  After deleting your suggested code the app functioned normally.  I guess this is not quite ready for a production app yet.
Thanks for the suggestion though.

**Comment by sdruckerfig** [comment]
Example of using <ui:input> with SLDS:

<div class="slds-form-element">
   <ui:inputText 
    aura:id="searchterm"
    label="Search Term(s)" 
    value="{! v.searchterm }"
    class="slds-input" 
    labelClass="slds-form-element__label"
  />
</div>

This technique generally works for everything except for the ui:inputRadio and ui:inputCheckbox. The markup output from those two ui components is too different from what SLDS is expecting.

**Comment by jselis** [comment]
Thanks sdruckerfig! I guess we should all give the message to the SLDS and Aura teams that people really expect Salesforce Lightning Components and Salesforce Lightning Design System are compatible and natural companions. Otherwize people start creating their own implementations and that is not the intention I guess.

**Comment by srohde** [comment]
Message heard, thanks @jselis!
Since this is not an issue tied to SLDS per se I'll close this for now but be assured that we know about the expectation.

**Comment by ErikatUCI** [comment]
Hi sdruckerfig.  You method works for may of the ui: controls.  One where it is a tradeoff between the appearance of the control verses the appearance of the text in the control is the ui:inputTextArea.  There the first line of text looks good but subsequent lines of text are double height which gives the appearance of a double-spaced document (see attached).  The Description field 
![inputtextarea control with slds styling](https://cloud.githubusercontent.com/assets/15222385/10897711/97473f88-8178-11e5-9771-64afbaa9f99b.JPG)
![inputtextarea control with slds styling](https://cloud.githubusercontent.com/assets/15222385/10897723/a583ce68-8178-11e5-9dea-54ee8bf61fc2.JPG)

has SLDS styling, the Contact Report Body field does not.
