### ISSUE TITLE
`dependencies/forms.scss` imported twice

### ISSUE THREAD

**Issue by burtek** [salesforce-ux/design-system#631]
`dependencies/forms.scss` is imported twice (lines 13 and 19). Not sure if bug or a feature

https://github.com/salesforce-ux/design-system/blob/5c93adca92bff1ac9f80f37e1b3ef65bbb390268/ui/dependencies/_index.scss#L13-L19

**Comment by fredboyle** [comment]
@burtek Thanks for bringing this to our attention. We'll file a bug to investigate this duplication and correct it if needed.

**Comment by burtek** [comment]
@fredboyle should be this marked as stale?

**Comment by zahnster** [comment]
Hi @burtek, 

We're making an internal ticket for this, and we'll plan to roll out our fix with our 2.12 release.

Thanks for bringing this to our attention!
