### ISSUE TITLE
slds-themes and lightning-accordion-section

### ISSUE THREAD

**Issue by jlyon-nlg** [salesforce-ux/design-system#632]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

A bug where slds-theme is not applied to svg fill for a lightning-accordion-section utility:switch svg icon.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Any lightning base components that implement lightning-primitive-icon.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

Winter 20 Salesforce Release

> What steps and/or code are needed to reproduce this issue?

```html
<lightning-accordion>
  <lightning-accordion-section
    class="slds-theme_error"
    name="sample"
    label="Sample Section" >

    <p>
      The section header text is white, but the utility:switch svg is not.
    </p>
  </lightning-accordion-section>
</lightning-accordion>
```

> What did you expect to happen?

The slds theme utility should be applied properly to the svg icon fill. Ex: for slds-theme_error, the svg should be white.

> What actually happened?

The slds theme utility is not applied to the svg icon within the accordion section, (lightning-primitive-icon).

**Comment by jlyon87** [comment]
Not clear if this is an slds or an lwc base component bug. 

But the lightning-accordion-section uses lightning-primitive-icon, and lightning-primitive-icon has the class slds-icon-text-default hard coded to it.

Current Behavior, as reported in the bug
![lighting-primitive-icon_text-default-on](https://user-images.githubusercontent.com/9729366/68687599-13b01800-0533-11ea-84db-53ac98f68aa4.png)

Disabling the slds-icon-text-default in chrome dev tools gives desired behavior
![lighting-primitive-icon_text-default-off](https://user-images.githubusercontent.com/9729366/68687619-1c085300-0533-11ea-9b22-7a8e364cae83.png)
