### ISSUE TITLE
What about starting templates?

### ISSUE THREAD

**Issue by smartm0use** [salesforce-ux/design-system#634]
Where I can find any starting template for a new web application?
I mean any layout sample in which I can start to create my own code blocks or use something from component blueprints?

I hope you can help me about this. Thank you.

**Comment by fredboyle** [comment]
@smartm0use This might be what you're looking for: https://starter-kit-demo.herokuapp.com. Hope it helps.

**Comment by smartm0use** [comment]
I have already seen it, but it only contains a couple of html templates:

> Included in the starter kit:
> 
> index.html:
>     the welcome screen
> example.html:
>     an example that showcases the possibilities offered by the starter kit
> blank.html:
>     a blank template ready to host your prototype!
> workshop.html:
>     a blank template ready to host your prototype!
> workshop-done.html:
>     what your prototype should look like when you’ve completed this workshop!

**Comment by smartm0use** [comment]
What about this?

https://trailhead.salesforce.com/sample-gallery

**Comment by fredboyle** [comment]
@smartm0use The sample gallery could be used as a starting point but those aren't specifically for SLDS if that's what you're looking for.

Since SLDS is a design system and all apps are different the Starter Kit repo is what we have available that is specific to SLDS.

If you have an example from another design system or framework you like please share so we can investigate and learn.

Thanks.

**Comment by smartm0use** [comment]
I mean something like this:

https://themes.getbootstrap.com
https://getmdl.io/templates
https://foundation.zurb.com/templates.html

**Comment by elvisbegovic** [comment]
Almost 4 years I've been requesting this feature, see my issue https://github.com/salesforce-ux/design-system/issues/281 on 26 Jul 2016 
4 years ago @kaelig posted starterkit link here https://github.com/salesforce-ux/design-system/issues/281#issuecomment-263725508 unfortunatly it hasn't really evolved.
Wonder if this can, now, be on 2020 roadmap what you think ?
/cc @brandonferrua

**Comment by aweibel** [comment]
Hey @smartm0use and @elvisbegovic, this has been on the design system team's roadmap for a bit. We agree that it's important to have resources to help get designers and developers up and running quickly. 

The challenge we have is around resources and prioritization. There are a lot of very impactful things we've been working on that affect more people in the Salesforce ecosystem than just designers and developers that have had precedence. 

It's still on the roadmap and as soon as we have more info we'll make sure and share it with you. Thanks for sharing your ideas and making sure we're on top of it!

**Comment by elvisbegovic** [comment]
@aweibel hi there any news here ? slds design is missing some reponsive sarting tempalte/layout since 5y, can we priorize it nowadays?

ps: about https://starter-kit-demo.herokuapp.com  I find the construction/position of header + .app-wrapper a little bit hacky and not beautiful

**Comment by kirupa** [comment]
Hi @elvisbegovic - this is still on our roadmap, but no new updates here. Are you building these prototypes to eventually turn into working pages on a Salesforcr org? Or are you building them to experiment and validate some ideas?
