### ISSUE TITLE
License: where to put copyright notice?

### ISSUE THREAD

**Issue by smartm0use** [salesforce-ux/design-system#635]
According to the [LICENSE](https://github.com/salesforce-ux/design-system/blob/master/LICENSE.txt) file...

> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
>     * Redistributions of source code must retain the above copyright
>       notice, this list of conditions and the following disclaimer.
>     * Redistributions in binary form must reproduce the above copyright
>       notice, this list of conditions and the following disclaimer in the
>       documentation and/or other materials provided with the distribution.
>     * Neither the name of the Salesforce.com nor the
>       names of its contributors may be used to endorse or promote products
>       derived from this software without specific prior written permission.

I am going to develop a web app that has nothing to do with Salesforce: I do not want to emulate Salesforce or give the impression that my app is affiliated with Salesforce. I just want to use the SLDS as a base for design for my web application.

So, to be compliant with the license, where and how do I have to put the copyright notice in my application?

**Comment by zahnster** [comment]
Hi @smartm0use, thanks for checking! The most straightforward place for the license to go is in the top of the SLDS css file that you publish. Hope that helps!
