### ISSUE TITLE
[Inquiry] - Checkbox component in view mode

### ISSUE THREAD

**Issue by classicmike** [salesforce-ux/design-system#636]
Hi,

Thanks for putting up your design system to open source. It's been great for getting some ideas and inspiration. 

Had a question about checkbox component view mode states: https://www.lightningdesignsystem.com/components/checkbox/#View-mode

- Did you guys get a chance of user testing those states with your end-users to validate your designs? 
- If yes, what interesting findings did you get from the results of these tests? 
- Were the designs that we see in the links a result from these user tests?

The reason why I'm asking this question is that we have similar requirements for our design system to represent view mode states for checkboxes and I just thought it would make sense to ask a group of people who have gone through that task on their experience.

Thanks.

**Comment by aweibel** [comment]
What's up Mike. Yes, we do research all patterns added to our design system. However, that information, including the tests, prototypes, and results are proprietary so we cannot share them. 

To help you find what you're looking for, you may want to scour the many articles on Medium where teams share their UX research techniques and design system research best practices. Those may help set you in the right direction. Good luck!

I'm going to close out this ticket. If you have any questions, please feel free to reach out to me directly at aweibel@salesforce.com

**Comment by classicmike** [comment]
@aweibel - Thanks for following up. I'll try to give articles a go and might send you an email for further clarifications.
