### ISSUE TITLE
Table styles to support react virtualized

### ISSUE THREAD

**Issue by ButuzGOL** [salesforce-ux/design-system#637]
I am building table based on 
https://github.com/bvaughn/react-virtualized

it builds table based on divs
i think it would be good if styles for table will be without direct connection to table html structure
what do you think ?

**Comment by jessebrack** [comment]
Hey @ButuzGOL, I haven't used react-virtualized but SLDS blueprints are guided by the principle of clarity so we would use semantic, easy to follow HTML (`table` structure in this case) over a combination of nested `div`.

The purpose of react-virtualized is also quite different than our blueprints so making a comparison is difficult.
