### ISSUE TITLE
Support for webcomponents

### ISSUE THREAD

**Issue by Luke1982** [salesforce-ux/design-system#638]
We're in the proces of implementing LDS into webcomponents. That lead us to the realization that CSS frameworks don't play nice with webcomponents, since the whole idea is to close off the internal CSS from the parent DOM.

At first, we attempted to load the entire LDS system into each and every component, which made the browser very slow. We now have a 'polyfill' that lets us work on the lightDOM while still using slots, but idealistically, webcomponents should self-contain their CSS.

Are there any plans for releasing the CSS in a way that will allow this, or are there any build processes that will allow us to grab the CSS for separate components?

**Comment by alexiscordova** [comment]
@Luke1982 Salesforce has recently announced [Lightning Web Components](https://lwc.dev/), which is an effort to create our Lightning Components as native web components. While we can't speak specifically on our future plans, definitely keep an eye out on this space.

That all being said, each of our components has separated SCSS files that you could hook into for your specific use case; however, those files do not have all the other dependencies such as font sizes, mixins, etc. so YMMV.

**Comment by Luke1982** [comment]
@alexiscordova Thanks, both of those are good news!
