### ISSUE TITLE
Working example of lookups

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#64]
Can we get a working example of lookups for jquery autocomplete? 
Problem is, that if I use standard jquery UI, it works, but when lookup is on modal, dropdown menu is not visible (stays behind modal). 
Second problem is, that standard jquery UI is not as good as new SLDS UI, but I can't  get new UI dropdown menu to work. 
Standard jquery dropdown menu is build like this:
`<ul>...<li>...</li>...</ul>`
new design system requires to have another <div> around with SLDS classes plus ul and li elements with SLDS classes like this:
`<div class="slds-lookup__menu" role="listbox"><ul>...<li>...</li>...</ul></div>`

Most of the time, I'm using lookups with jquery function autocomplete, where I can also send VFRemote query to controller class to make database select there for items I wish to search in my lookup. 

So how to make this work now? Do we have to manually open/close everything and also write our own select section of autocomplete function?

**Comment by srohde** [comment]
The Design System doesn't include any JavaScript.
