### ISSUE TITLE
npm install doing nothing

### ISSUE THREAD

**Issue by kushney** [salesforce-ux/design-system#640]
`npm install` returns this: 

> added 4833 packages from 1687 contributors and audited 952508 packages in 76.552s
> 
> 4 packages are looking for funding
>   run `npm fund` for details
> 
> found 96 vulnerabilities (40 low, 15 moderate, 40 high, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details

`npm start` just doesn't do anything.

node v12.14.0
npm v6.13.4
macOS 10.15.2

**Comment by alexiscordova** [comment]
@kushney unfortunately, some of our dependencies haven't been updated to support Node 12. Currently, we recommend using node v8.11.4, but I have used as high as 9.11.2 with success.
