### ISSUE TITLE
Link to open-sourced sample components in the ForceDotComLabs/sldsx project on GitHub is invalid

### ISSUE THREAD

**Issue by vazexqi** [salesforce-ux/design-system#647]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![Screen Shot 2020-03-02 at 11 00 07 AM](https://user-images.githubusercontent.com/54414/75708131-12873000-5c75-11ea-9a1c-2f55e2324831.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The link to https://github.com/ForceDotComLabs/sldsx on https://www.lightningdesignsystem.com/platforms/lightning/ no longer exists.

> What did you expect to happen?

It takes me to the right repo to see some open sourced sample components.

> What actually happened?

It directs me to a 404 not found. 
At https://github.com/ForceDotComLabs/ it tells me that this has moved to https://github.com/salesforcelabs but I wasn't able to find the sldsx repo.

**Comment by jessebrack** [comment]
Hi @vazexqi, thank you for finding and filing this issue! We'll get this checked out and corrected.

**Comment by veaux** [comment]
The sample repo is still missing

**Comment by kflournoy-sf** [comment]
Hi @veaux - sorry for the delay. This is going into the next release of the site, but if you want the link now, it's https://github.com/salesforce/base-components-recipes

Thanks again!
