### ISSUE TITLE
Popover input color is invisible

### ISSUE THREAD

**Issue by almonk** [salesforce-ux/design-system#648]
![Screenshot 2020-03-02 at 19 44 49](https://user-images.githubusercontent.com/51724/75713006-e4c7d880-5cc0-11ea-87a5-6846900466bf.png)

In the [popover example](https://www.lightningdesignsystem.com/components/popovers/#Prompt) (above) the input text color is invisible when the user starts typing.

**Comment by jessebrack** [comment]
Thank you @almonk for finding and creating this issue, we'll take a look and get this corrected.
