### ISSUE TITLE
What changed in version 2.11.5?

### ISSUE THREAD

**Issue by leifg** [salesforce-ux/design-system#649]
I saw that design-system recently pushed a new version to [npm](https://www.npmjs.com/package/@salesforce-ux/design-system).

I don't see any changes in master (or the other branches).

Is there anywhere I can see the changes?

**Comment by zahnster** [comment]
Hi @leifg 

We have published the release notes to the Design System Website:
https://lightningdesignsystem.com/release-notes/

2.11.5 includes updates to our documentation. There are no CSS or static asset changes for this release.
