### ISSUE TITLE
Bug with Lightning Design System slds-x-small-order class?

### ISSUE THREAD

**Issue by jselis** [salesforce-ux/design-system#65]
I have tried to apply the classes for changing the order of cols in a grid (with wrap), but for the slds-x-small-order--... and slds-small-order--... I found in the style sheet that they were only defined for order 1 and 2, whereas for for example slds-medium-order--... they were defined for all orders from 1 till 12. I guess this is a bug? BTW, I'm using SLDS version 092. 
(I also created a Case for this under the customer's org, which ended up somewhere in India, curious whether that is going to reach you)

**Comment by brandonferrua** [comment]
hey @jselis, thanks for pointing this out. The reason why that is currently happening is because the ordering is dynamically generated from a map that defines a maximum of 2 columns on a small device so that's as high as it goes. 

The breakdown is as such:

x-small: 1 column
small: 2 columns
medium: 6 columns
large: 12 columns

Curious, how many columns are you trying to reorder?

**Comment by jselis** [comment]
hello @brandonferrua, I would expect that the ordering always allows more columns than can be put on one row to be ordered, because the ordering is most useful when switching from large width to smaller width (e.g. when going from landscape to portrait). Also, the example in the SLDS guide (https://www.lightningdesignsystem.com/components/grid-system#order), there are three columns to be ordered, even in the small width.
My particular use case is where I have a 'previous page' button, content block and then a 'next page' button as my three columns. Then, when the page is 'big' (ie. wide) I put first the 'prev' button, then the content and then the 'next' button (all vertically below each other), but when the screen gets 'small' (i.e. narrow), I want to have the content first, and then the 'prev' and 'next' button in the second row below the content, next to each other to save screen real-estate.
So, via the order class, I can do that by changing the order when the screen becomes small. But it didn't work, because for the 'small' order, it didn't recognize the order=3.
I don't see why you would want to limit the number of columns that can be ordered for a small screen?
(BTW I'm not a CSS specialist and am happy that there is finally now something to help and guide me in styling pages in a professional and structured way).

**Comment by brandonferrua** [comment]
@jselis thanks for that descriptive scenario, looks like we need to get that support in.
