### ISSUE TITLE
Modifying design tokens on Visualforce

### ISSUE THREAD

**Issue by cabaird** [salesforce-ux/design-system#654]
This is less of a bug and more of a general search for guidance in using Lightning Design System within Visualforce.  Is there an easy way for us to change the values for the design tokens when using this?  I would like to add our brand colors, and modify some other values there without adding custom css.

Thank you,

-Christian

**Comment by liselatorre** [comment]
Hi Christian,
You may find what you need to know in the design tokens documentation here: https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_intro.htm?search_text=visualforce%20tokens
