### ISSUE TITLE
seeing a grid wrap issue in IE 11, doesn't seem to be present in any of the other major browsers

### ISSUE THREAD

**Issue by CSTufts** [salesforce-ux/design-system#655]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

issue in ie11 where the grid system seems to be ignored and the divs are being displayed in block format

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.
any item leveraging slds-grid

> Are any specific browsers impacted by this bug?
ie 11 only

> Which version of the Salesforce Lightning Design System are you using?
latest

> What steps and/or code are needed to reproduce this issue?

```html
<lightning-layout>
    <lightning-layout-item size="6">
        ITEM A
    </lightning-layout-item>

    <lightning-layout-item size="6">
      ITEM B
    </lightning-layout-item>
</lightning-layout>
```

> What did you expect to happen?

two side by side items 
ITEM A                   ITEM B

> What actually happened?
items are stacked

ITEM A
ITEM B

**Comment by CSTufts** [comment]
I can provide a screen shot if its not immediately reproducible

thanks

**Comment by CSTufts** [comment]
I am seeing the same thing happen when you use a standard use case of 

```
<div class="slds-grid slds-wrap">
  <div class="slds-col slds-size_6-of-12">
    <span>6</span>
  </div>
  <div class="slds-col slds-size_6-of-12">
    <span>6</span>
  </div>
</div>
```

**Comment by fredboyle** [comment]
@CSTufts Thanks for bringing this to our attention. We'll investigate and report back once we've had the opportunity to do so.
