### ISSUE TITLE
$A.util.toggleClass for Spinner element not working properly when user open record on new tab

### ISSUE THREAD

**Issue by wasimbeniwale** [salesforce-ux/design-system#658]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![slds-issue](https://user-images.githubusercontent.com/5242262/84108479-a0886900-aa63-11ea-9163-c9a40720061d.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?
- Found a bug related to $A.util.toggleClass() for spinner element.

**What I've built**
- I've aura component on a lightning record detail page which shows a spinner when the user opens a record details page and hides when the component is loaded.

**When I'm facing this issue**
- This works perfectly when the user opens a record on the same window.
- When the user opens a particular record on the new tab and then visits that tab, the spinner does not hide. I've added console logs that are getting executed so I can confirm the toggle code is getting executed by the browser.

**Where I'm facing this issue**
- In standard lightning record details page.

**Code I'm using**
```html
<!-- html code -->
<div class="exampleHolder">
    <lightning:spinner aura:id="spinnerElement" alternativeText="Loading" size="large" />
</div>
```

```javascript
// JS code
$A.util.toggleClass(spinner, "slds-hide");
```

**Workaround**
- By nesting spinner element inside aura if, like below:

```html
<aura:attribute name="doShowSpinner" type="Boolean" default="true" />

<aura:if isTrue="{!v.doShowSpinner}">
    <div class="exampleHolder">
        <lightning:spinner aura:id="spinnerElement" alternativeText="Loading" size="large" />
    </div>
</aura:if>
```

```javascript
// JS code
component.set("v.doShowSpinner", false);
```

**Comment by jessebrack** [comment]
Hey @wasimbeniwale, thanks for reaching out!

This repository is specific to the Salesforce Lightning Design System, your question is more Aura related.

But with that said, I hope I can help steer you in the right direction:
- Review the [developer documentation](https://developer.salesforce.com/docs/component-library/bundle/lightning:spinner/documentation) to double check your implementation
- Your workaround is generally the [preferred method](https://developer.salesforce.com/docs/component-library/bundle/lightning:spinner/example#lightningcomponentdemo:exampleSpinnerIf) and something worth pursuing
- If you're still stuck, I would visit the [Trailblazer Community](https://success.salesforce.com/)

Good luck!
