### ISSUE TITLE
Missing padding on custom svg icons?

### ISSUE THREAD

**Issue by jselis** [salesforce-ux/design-system#66]
I was trying to reproduce an svg icon the way it appeared in the SLDS documentation, namely new_custom4, using lightning components. However, it appeared with the svg too large inside its container.
I didn't have that problem when reproducing for example new_case, there it appeared correctly.
I used this code:
>        <div class="slds-col slds-grow-none slds-m-horizontal--small">
>            <span class="slds-icon__container slds-icon-custom-4" style="background-color: #ffc500;">
>                <c:svg class="slds-icon" xlinkHref="/resource/SLDS0101/assets/icons/action-sprite/svg/symbols.svg#new_custom4"/>
>            </span>
>        </div>

the c:svg is a custom lightning component that generates a svg tag with a renderer, but the class attribute is simply turned into the class for the svg element.
This will give an icon where the icon stretches to the edges of the container.
By the way, this is in SLDS v 092.

When I add a class slds-icon-custom-paddingfix (which I created in a separate CSS file and that simply adds "padding:6px;" , the icon looks as expected:
>        <div class="slds-col slds-grow-none slds-m-horizontal--small">
>            <span class="slds-icon__container slds-icon-custom-4" style="background-color: #ffc500;">
>                <c:svg class="slds-icon slds-icon-custom-paddingfix" xlinkHref="/resource/SLDS0101/assets/icons/action-sprite/svg/symbols.svg#new_custom4"/>
>            </span>
>        </div>

I found the same problem with other custom icons. 
Is there something missing in the stylesheet?

**Comment by stefsullrew** [comment]
Hi @jselis - the action icons used to be made like the standard icons (with space around them), but that changed recently. You're correct in that we're going to need to do some adjustment to them.

**Comment by stefsullrew** [comment]
Hi @jselis - There have been no changes in the way icons are made to this time. 

Action icons are meant to be used in the rounded containers.
Utility icons are meant to be used with no container.
Standard and Custom icons are meant to be used with background colors.

We need to clarify that in our documentation. I hope this helps you in implementation. I'm going to clise this. Cheers!
