### ISSUE TITLE
Why is SLDS inconsistent with Salesforce Lightning Pages

### ISSUE THREAD

**Issue by JodieM** [salesforce-ux/design-system#660]
I have tried to search for related issues but anything even remotely close seems to be closed as stale. 

I have created a post of the issues I'm seeing https://tddprojects.atlassian.net/wiki/x/twAfQg where a very simple LWC using LDS for data does not look like the similar component created with Related Record Components. 

![Component Display](https://user-images.githubusercontent.com/2966583/87273011-4de71480-c51b-11ea-91d7-a2a0bd365ad6.png)

1. Font of heading different.
2. (Functionality - not styling).
3. The RRC displays the fields nicely in in a line - if the text wraps further the white space above the line under Employees will grow. The lines will always align. At least the Account Phone field does not smush up to directly under the Employees field (like it does in Dynamic Forms and Dynamic Actions. 
4. WHY are the edit icons different in SLDS than in Salesforce - they are darker and larger and a different size, and are on the baseline rather than hovering a little above it. 
5. Why the different field names? Is this only on Standard Fields or is this only on these few random Account fields. The fields are named Rating and Phone in the Object Manager so why Account Rating and Account phone when you retrieve the field from @salesforce/schema/Account.Rating? 
6. (functionality issue - not styling) 
7. Why is the date format different? Is this something to do with the new ICU locale formats? This org had it enabled, so I disabled it and it went back to displaying 5:20 PM. Why does LWCs display the new format and standard records NOT display the new formats when the CRUC is enabled? 
8. Why do the LWCs display the link and the RRC doesn’t? Of course the link is better for mobile devices.  
9. Why are the lines shorter in the LWC? Probably because of the edit button being different. 

![Component Edit](https://user-images.githubusercontent.com/2966583/87273304-14fb6f80-c51c-11ea-8ebf-c6bc052a149c.png)

1. The field name is a little further away from the field box on the RRC
2. The content is cut off on the RRC - more content is displayed in the LWC. It looks like the font is bigger in the RRC but it’s not. 
3. The drop down arrow is not the same size. The field is shorter vertically in the RRC - it looks better in the LWC. 
4. Ah, that’s the reason the content is cut off, the fields are not the same size they are larger in the LWC.

![ComponentDropDown](https://user-images.githubusercontent.com/2966583/87273355-365c5b80-c51c-11ea-885d-c8a72d46cf0c.png)

1. The LWC has a very different check mark.
2. The list sits below the field, not covering it like the RRC does. The LWC looks better in that regard.

Why are these inconsistencies there? 
Is it SLDS trying to change standards and base Lightning devs haven’t got around to changing their styles yet? 
Or is it just a lack of attention to detail? Why? 
Why do I have to try to explain to my users why things look a little weird between different components on the page? 

NOTE: I need to address this with the team for Dynamic Forms which is standard Salesforce functionality but it looks more like SLDS with a few differences (eg the line height is all over the place in Dyanamic Forms), but I am sure they will just come back with "well that's what the SLDS looks like". But Dynamic Forms is a standard feature and should look like Salesforce. But LWCs should look like Salesforce and SLDS should look like Salesforce? Why the inconsistencies? 

For more information here is the specifics about the random field misalignment in Dynamic Forms https://trailblazers.salesforce.com/0D53A00004usX2x.

**Comment by kirupa** [comment]
Hi Jodie! Thanks for the very detailed feedback :-)

What you are seeing are indeed inconsistencies, and we have them on our roadmap across the appropriate teams to fix. The reason these are here is partly due to SLDS adoption. We are actively working to improve SLDS adoption across all our UIs - via UI/UX guidance, partnership with other teams, technical implementation, tools, and more.

I'd be happy to setup a call with you and walk you through some of our initiatives here in greater detail. Let me know if that would be something you would be interested in.

Thanks,
Kirupa

**Comment by JodieM** [comment]
Hi @kirupa I have emailed you. I would love to chat.

**Comment by Dottenpixel** [comment]
Thanks again for you input, Jodie! I know you spoke with Greg, Kirupa, and Vin this week. We’ll be looking at this with them moving forward.
