### ISSUE TITLE
Input Field - Read Only State has blue border on focus and miss the bottom line

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#661]
source: https://www.lightningdesignsystem.com/components/input/#Read-Only
Actual:
![image](https://user-images.githubusercontent.com/55927613/90710522-fbfd8100-e274-11ea-8985-c96b9ee5c393.png)

Expected:

![image](https://user-images.githubusercontent.com/55927613/90710546-06b81600-e275-11ea-9089-781f3637e67d.png)

**Comment by fredboyle** [comment]
@AllanOricil Thanks for reaching out to us. Would you please provide additional information as to the origin of the expected state you've provided? Thanks again.

**Comment by AllanOricil** [comment]
> @AllanOricil Thanks for reaching out to us. Would you please provide additional information as to the origin of the expected state you've provided? Thanks again.

@fredboyle 
I just compared with the other inputs that have the "readonly/view mode" state. All of them have the line below the input and don't show the blue box when on focus.


Checkbox:
https://www.lightningdesignsystem.com/components/checkbox/#View-mode

Text Area:
https://www.lightningdesignsystem.com/components/textarea/#Read-only

**Comment by kflournoy-sf** [comment]
Hi @AllanOricil - thank you so much for filing this issue! We have created an internal ticket to investigate and add new styling as appropriate, and we will update this issue once that work is done.

**Comment by AllanOricil** [comment]
> Hi @AllanOricil - thank you so much for filing this issue! We have created an internal ticket to investigate and add new styling as appropriate, and we will update this issue once that work is done.

No problem

**Comment by laurensuh** [comment]
Hi @AllanOricil we will be closing this issue as we have created a work backlog to address this. If you have any questions/comments please feel free to reach out! Thanks again for logging the issue. 😄 Cheers!
