### ISSUE TITLE
Remove margin when buttons are siblings

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#662]
The following CSS rule is adding margin when two buttons are siblings inside the same DIV. 

```css
.slds-button+.slds-button {
    margin-left: .25rem;
}
```

If I add the buttons in a div with "d-flex flex-column" the second button will always have a margin added to it. Then I have to add a class just to remove this margin. I know I should not be mixing design systems but Im only using the flex system from Bootstrap 4 which It would not impact in the above css rule. This problem would happen in the slds-grid too, since the rule is just considering a button sibling of a button.

```html
<div class="d-flex flex-column">
<button class="slds-button"/>
<button class="slds-button"/> <!-- this button has margin left -->
</div>
```

![image](https://user-images.githubusercontent.com/55927613/90822858-71b42c00-e30b-11ea-9f84-9eca14d6e6fe.png)

I think it is better if we add a button group wrapper class to add this margin,  like `<div class="slds-button-group">...</div>`. Then the new rule to add the left margin would be `slds-button-group slds-button:not(:first-child)`. What do you guys think?

The Problem:
The user/developer has to add `margin-left: 0px` in all the sibling buttons or wrapp each button in another div.

**Comment by alexiscordova** [comment]
Hi @AllanOricil,

Thanks for your feedback. SLDS doesn't currently support this kind of stacked, full-width buttons without some kind of wrapper element; buttons like this are designed to flow horizontally, hence the built-in space between them. I'll pass this along to our UX design team, but for now the best way to achieve this is to put each button in a wrapping element.

**Comment by AllanOricil** [comment]
> Hi @AllanOricil,
> 
> Thanks for your feedback. SLDS doesn't currently support this kind of stacked, full-width buttons without some kind of wrapper element; buttons like this are designed to flow horizontally, hence the built-in space between them. I'll pass this along to our UX design team, but for now the best way to achieve this is to put each button in a wrapping element.

What is the class I have to use from the design system to stack buttons?

**Comment by AllanOricil** [comment]
> Hi @AllanOricil,
> 
> Thanks for your feedback. SLDS doesn't currently support this kind of stacked, full-width buttons without some kind of wrapper element; buttons like this are designed to flow horizontally, hence the built-in space between them. I'll pass this along to our UX design team, but for now the best way to achieve this is to put each button in a wrapping element.

Thanks @alexiscordova
