### ISSUE TITLE
Remove Padding from Panel Body

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#663]
The Panel component has a class called `slds-panel__body` which we can use to wrapp the panel body's content. This class has a padding of 0.75rem which I don't think it is good because inner divs, in a component composition based approach, would not be able to remove the parent's padding. 

Example in Vue Js:
```html
//slds-panel component
<template>
   <div class="slds-panel">
      <div class="slds-panel__header">
        <slot name="header"/> 
     </div>
      <div class="slds-panel__body">
         <slot name="body"/>
      </div>
   </div>
</template>

//using slds-panel
<slds-panel>
   <template v-slot:body> <!-- this would come with a padding and the child "slds-tab" would not be able to remove it -->
      <slds-tab></slds-tab>
   </template>
</slds-panel>
```

I think the divs inside of this wrapper class are the ones that should apply the padding or not. In the image bellow I used a Tab component inside of a Panel component and from the tab component I can't remove the Panel's padding. 

![image](https://user-images.githubusercontent.com/55927613/91075477-8565d800-e614-11ea-9d95-f2e8835ba150.png)

There is actually a way to remove it, but it is not good. It would require the developer to remove it manually every time, and the component would have to also be changed.

```html
//slds-panel component
<template>
   <div class="slds-panel">
      <slot name="header" class="slds-panel__header"/>
      <slot name="body"  class="slds-panel__body"/>
   </div>
</template>

//using slds-panel
<slds-panel>
   <template v-slot:body style="padding:0px 0px"> <!-- This time the developer can remove the Padding, but it is really bad having to do that. And this is the reason I think it is better to remove the padding of the body-->
      <slds-tab></slds-tab>
   </template>
</slds-panel>
```

**Comment by alexiscordova** [comment]
Hi @AllanOricil,

The way to think about this is that `slds-panel__body` provides the padding while its children should have no padding, as you can see in [this example](https://www.lightningdesignsystem.com/components/panels/#Panels-for-Filtering). This is done intentionally.

The best way to have the body child elements be flush to the panel is to use negative margins. I would suggest something like the following:

```html
<div class="slds-panel">
  […]
  <div class="slds-panel__body">
    <div class="your-wrapper">…</div>   
   </div>
</div>
```

```css
.your-container {
  margin: 0 -0.75rem;
}
```

Hope that helps.
