### ISSUE TITLE
Add cursor Pointer when hovering over the region of a checkbox

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#664]
I think it is good to change the cursor for a checkbox to a pointer because it is a clickable item, like a button. If the cursor is hovering on top of any part of the div of the checkbox, change the cursor to a pointer.

**Comment by alexiscordova** [comment]
Hi @AllanOricil,

`cursor: pointer` is designated for link elements, not interactive or clickable elements. You can see here that default checkboxes do not change their cursor https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

**Comment by AllanOricil** [comment]
> Hi @AllanOricil,
> 
> `cursor: pointer` is designated for link elements, not interactive or clickable elements. You can see here that default checkboxes do not change their cursor https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

But why the [`slds-button`](https://www.lightningdesignsystem.com/components/buttons/)have pointer as a cursor? According to what you said they should not change the cursor too. It is really weird to hover over a checkbox and not see and indication it is clickable, when it is, like a button.
