### ISSUE TITLE
Css customizer page link is broken

### ISSUE THREAD

**Issue by sudhirjena** [salesforce-ux/design-system#666]
I wanted to customize the slds css a bit. So I navigated to https://tools.lightningdesignsystem.com/css-customizer from https://www.lightningdesignsystem.com/tools/overview/ but the link https://tools.lightningdesignsystem.com/css-customizer seems to be broken.

**Comment by kflournoy-sf** [comment]
Hi @sudhirjena - sorry about that, we're having some site issues right now and a few of our subdomains are unavailable. Please check back again in a few days and the link should be working again!

**Comment by alexiscordova** [comment]
@sudhirjena give it a try now https://tools.lightningdesignsystem.com/css-customizer
