### ISSUE TITLE
Does IE 11 support lightningdesignsystem with LWC ( Salesforce Lighting Web Component ) ?

### ISSUE THREAD

**Issue by narendrasinghrathore** [salesforce-ux/design-system#667]
[lightning design system  ](https://www.lightningdesignsystem.com/) CSS classes styling not working on IE11

Below is the screenshot, left side chrome and the right one is IE11.

Is something we are missing to support IE11 or 
Is it something that .slds classes of [lightning design system  ](https://www.lightningdesignsystem.com/) doesn't support IE11?

Does lighting design system work on CSS grid, variables, flexbox, etc and IE11 doesn't support that?

Can you please confirm?

Thanks

![image](https://user-images.githubusercontent.com/4208015/93166281-cba5e700-f73b-11ea-8165-1fb145bcab19.png)

**Comment by alexiscordova** [comment]
Hi, @narendrasinghrathore,

This is quite strange! While IE 11 has only partial support for Flexbox, it's surprising to see certain components here completely collapsed. A few questions:

1. When did you notice this behavior occurring? Did it work in the past but suddenly stopped working, or is this the first time you're noticing this?
2. Would it be possible for you to provide a link where we could view this in the browser to help diagnose the problem?
3. If not, would you be able to supply the HTML you're using?

Thanks!

**Comment by narendrasinghrathore** [comment]
@alexiscordova  I can see from salesforce official documentation that they will end support for IE11 by Dec 2020. So is it advisable to use IE11 with lighting design system?


1. We haven't tried on IE11, so this is our first time only we found this issue.
2. We cannot provide a link, as it works on client VM. policies and stuff.
3. Will try to get the HTML only.


Also, it would be helpful if could share more information, like what are the changes we need if we want to support IE11.
We are using CSS classes of salesforce lightning design system only **(95%)** and few customs CSS classes **(5%)**

**Important: We are using salesforce LWC**

**Comment by Dottenpixel** [comment]
@narendrasinghrathore @alexiscordova the use of LWC could be the answer there. I don't have any working knowledge of LWC in IE11, but from reading the docs I'm wondering if this app is in an [unsupported experience](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_started_supported_experiences) where the [polyfills](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_started_supported_browsers) are not being activated?

**Comment by kflournoy-sf** [comment]
@narendrasinghrathore - just following up, were you ever able to figure out your issue here?

**Comment by narendrasinghrathore** [comment]
> @narendrasinghrathore - just following up, were you ever able to figure out your issue here?

@kflournoy-sf It was because of css grid not supported and partial support for flex  on IE11

**Comment by narendrasinghrathore** [comment]
@kflournoy-sf Any update here?

**Comment by narendrasinghrathore** [comment]
> @narendrasinghrathore Are you seeing this issue using a lightning web component, or just the design system HTML from the blueprint?

@kflournoy-sf Design system HTML from the blueprint.

**Comment by Dottenpixel** [comment]
@narendrasinghrathore are you able to provide an example chunk of markup that reproduces the issue in the SLDS blueprint portion of the markup?

**Comment by kflournoy-sf** [comment]
@narendrasinghrathore - just checking in, are you able to provide the code sample as @Dottenpixel requested above?

**Comment by narendrasinghrathore** [comment]
@Dottenpixel  & @kflournoy-sf Apologies for delay in reply, as now I am working on different project and framework, I cannot provide the markup also it was on client VM machine, so no access.
