### ISSUE TITLE
[Feature] Add Tool Box Icon

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#668]
Could you add an icon that resambles a tool box, such as this one below.

![image](https://user-images.githubusercontent.com/55927613/94377963-62e84280-011d-11eb-9c16-730cb9d3da65.png)

I got it for free from Fontawesome: https://fontawesome.com/icons/toolbox?style=solid

I was using one that had a gear box in a button that when clicked would open a Toolbar menu, but did not looked ok because Gear icons are more suitable for configuration menus. This one can be used for any situation where the user needs acess to a menu with a  set of tools to create something. If not, could you tell me which one would be closer to what I need from the official set of icons?
Thank you.

**Comment by Dottenpixel** [comment]
@AllanOricil thank you for the suggestion! 

@aweibel do you have any thoughts on an alternative, or possible icon request consideration?

**Comment by kflournoy-sf** [comment]
Hi @AllanOricil - we have a wrench in the official set of icons, will that work for your needs?

![custom_apps](https://user-images.githubusercontent.com/53910308/98312836-85813d00-1fa0-11eb-913a-1652fba4f949.png)

**Comment by AllanOricil** [comment]
Not that much, because I have a menu called Toolbox.
Look, I'm building a schema builder using the lighting design system:
https://elastic-kare-6bcddf.netlify.app/builder/

When the user clicks on the toolbox, the menu opens/closes.

**Comment by aweibel** [comment]
@AllanOricil The schema builder looks great! Nice work.

We'll add your toolbox icon suggestion to our icon backlog. If there's any further interest, we can prioritize creating one. 

In the meantime, you may want to use an SVG of the toolbox icon you shared from FontAwesome so you can move forward with your app and not let us slow down your schema builder progress.

<img width="663" alt="Screen Shot 2021-01-22 at 4 49 40 PM" src="https://user-images.githubusercontent.com/1750832/105563164-ec75de80-5cd1-11eb-801d-66e0c6f0eba2.png">

**Comment by kflournoy-sf** [comment]
@AllanOricil per @aweibel 's comment above, I'm going to close this issue. Please do keep sending in suggestions!
