### ISSUE TITLE
Jaggy font rendering in Chrome / Windows 7

### ISSUE THREAD

**Issue by enjoylife** [salesforce-ux/design-system#67]
Great stuff, and a nicely designed font, but when running with the latest chrome on windows, the font renders poorly. Seems to be a known issue in general for fonts on windows so not specific to  Salesforce Sans.

![image](https://cloud.githubusercontent.com/assets/877194/10673431/ac1441c6-78aa-11e5-8db3-54f1c8759e99.png)

**Comment by kaelig** [comment]
@enjoylife thank you so much for the feedback, do you remember what version of Windows this screenshot was made with?

**Comment by enjoylife** [comment]
Probably a very unique edge case, so feel free to close if un reproducible, but I was running windows 7 on a laptop connected by remote desktop to another windows 7 machine. Additionally when changing the css to use standard font family properties, the page rendered correctly.

**Comment by kaelig** [comment]
Thank you again, @enjoylife. We care about all platforms so we'll be investigating this during the beta period and will make sure text rendering is optimal across supported platforms for the launch.

**Comment by stefsullrew** [comment]
@enjoylife - Have you tried changing your ClearType setting? https://www.winhelp.us/change-font-smoothing-in-windows.html

**Comment by kaelig** [comment]
Closing this as it has been open for about a month. Please reopen if it happens again.
