### ISSUE TITLE
broken links in Builder Canvas page

### ISSUE THREAD

**Issue by m-rio** [salesforce-ux/design-system#670]
Many links under https://www.lightningdesignsystem.com/guidelines/builder/canvas/ are returning "Cannot GET..."

example: https://www.lightningdesignsystem.com/guidelines/builder/canvas/nodes

**Comment by kflournoy-sf** [comment]
Hi @m-rio - thank you for letting us know! I've made these changes, and they'll go live with the next site release. Appreciate the help!

**Comment by kflournoy-sf** [comment]
@m-rio These should be all good now - thanks again!
