### ISSUE TITLE
[Feature] Create Data Table specification like the Bootstrap one

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#672]
The user wants a data table that behaves like bootstrap table because he does not like to have an empty space when the data table column is resized. When the user resizes the columns look the space that is left on the right side of the datatable.

![image](https://user-images.githubusercontent.com/55927613/98364416-ad1be800-2028-11eb-892c-6fe7c0c08526.png)

![image](https://user-images.githubusercontent.com/55927613/98364530-de94b380-2028-11eb-8527-63625d19a3db.png)

This is really weird if we compare with other design systems. Every list view on SF uses the same styles for displaying data in a table and they all leave behind this empty margin to the right of the table.

![image](https://user-images.githubusercontent.com/55927613/98364989-a93c9580-2029-11eb-95a2-c77b619941c0.png)

Bootstrap has a nice data table implementation where if we resize one column there is not empty space left behind:

https://examples.bootstrap-table.com/#extensions/resizable.html

**Comment by kflournoy-sf** [comment]
Hi @AllanOricil - thank you for the feedback! I will share this with our Product Manager and we will discuss adding this to future versions of the design system. Cheers!
