### ISSUE TITLE
Documentation leads to unsupported repository

### ISSUE THREAD

**Issue by az-oolloow** [salesforce-ux/design-system#673]
On this page on SLDS the link takes the user to a repo that is outdated by 2 years and that also says that it is no longer being maintained:

https://www.lightningdesignsystem.com/platforms/ios/#swift-usage

Repo: 

https://github.com/salesforce-ux/design-system-ios

Is there a replacement, and if not, should this perhaps be removed from original documentation?

**Comment by kflournoy-sf** [comment]
Hi @az-oolloow ! While this repo is not being maintained, there is no replacement at this time, and so we have been keeping it in our documentation as it may still be useful information for anyone following this path. Thanks for the keen eye though!
