### ISSUE TITLE
docs: Incorrect selector name for Datepicker

### ISSUE THREAD

**Issue by zaki-yama** [salesforce-ux/design-system#674]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![SS 2020-11-10 at 1 30 26](https://user-images.githubusercontent.com/1001444/98568348-577b6000-22f4-11eb-83b1-4a877e9fbd2b.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I'm sorry if it's not the appropriate place to report a bug in the document.
But I found an incorrect CSS selector for Datepicker while reading the document.

https://www.lightningdesignsystem.com/components/datepickers/#CSS-Class-Overview
There's `.slds-datepicker__month_filter` selector, but actually it's `.slds-datepicker__filter_month`.

--

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Datepicker

> Are any specific browsers impacted by this bug?

No

> Which version of the Salesforce Lightning Design System are you using?

Current release: Winter ’21 (SLDS 2.13.7)

> What steps and/or code are needed to reproduce this issue?

Nothing. It's about the document only.

> What did you expect to happen?

The document says there's `.slds-datepicker__month_filter` selector.

> What actually happened?

Actually it's `.slds-datepicker__filter_month`.

**Comment by kflournoy-sf** [comment]
Hi @zaki-yama ! Yup, that's a typo on our part - we'll get it fixed in the next release of the site. Good eye!
