### ISSUE TITLE
Support for spinner variant which doesn't force itself to top of z-index stack

### ISSUE THREAD

**Issue by jimmydief** [salesforce-ux/design-system#675]
![Screen Shot 2020-11-09 at 6 30 29 PM](https://user-images.githubusercontent.com/4480230/98620194-ab1c8800-22b9-11eb-83c9-198f2c3c6da4.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

In Analytics, our UI makes use of card loading states as described in the [SLDS "Loading" design guidelines](https://www.lightningdesignsystem.com/guidelines/loading/). Since card contents are customizable per user and performance of these cards varies based on data, query, and visualization complexity, different cards often have significant deltas in loading time and we don't want to block interaction with the rest of the UI over a single slow-to-load card.

As such, it's possible to get in a state where a modal opened through a user interaction appears overlaid over a card which is still loading. There doesn't appear to currently be a spinner variant meant for this use case. [Currently](https://www.lightningdesignsystem.com/design-tokens/#category-z-index), the spinner's z-index of 9050 wins out over everything aside from toasts.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

This is specific to the spinner component.

> Are any specific browsers impacted by this bug?

All browsers.

> Which version of the Salesforce Lightning Design System are you using?

2.13.0

> What steps and/or code are needed to reproduce this issue?

Our specific example is fairly complex but this can be reproduced with a spinner and a modal on the same page.

> What did you expect to happen?

Developers can make use of a spinner variant which doesn't force itself into the foreground. I had thought that `.slds-spinner_inline` might do this but it appears not to.

> What actually happened?

Overriding the z-index of a spinner requires overriding styles both on the container element and on the spinner itself.

**Comment by jessebrack** [comment]
Heya @jimmydief, thanks for reaching out. Without seeing your code, you most likely want to look into how you are handling your [stacking context ](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). You'll want to define a context for the container of the spinner.

Going to close this issue since this repo is meant for external issues, feel free to reach out to us on Chatter if you have more questions!
