### ISSUE TITLE
slds-page-header__col-title incorrectly listed as slds-page-header__col_title

### ISSUE THREAD

**Issue by dana-hughes** [salesforce-ux/design-system#676]
The class **.slds-page-header__col-title** is used in all [Page Header examples](https://www.lightningdesignsystem.com/components/page-headers/). However, at the bottom of the page in the master list of classes, the class is shown as **.slds-page-header__col_title** (underscore between col and title instead of a dash).

This seems like a mistake. The SLDS Validator extension in VS Code thinks **.slds-page-header__col_title** is the correct version and throws an Invalid/Deprecated Class error when using what I believe is the correct class **.slds-page-header__col-title**. 

**In examples:**
![image](https://user-images.githubusercontent.com/17728114/99152981-69059480-2673-11eb-953f-af6a61ff804c.png)

**In docs:**
![image](https://user-images.githubusercontent.com/17728114/99152993-7cb0fb00-2673-11eb-9306-0227a4db498f.png)

**Comment by jessebrack** [comment]
Hey @dana-hughes! Thank you surfacing this issue, I've logged it as a bug with our team.

**Comment by kflournoy-sf** [comment]
@dana-hughes This bug has been fixed and will go out in SLDS 2.15. Thanks again for your keen eye!
