### ISSUE TITLE
Tree Grid Chevron displaying weird Black Border

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#677]
@Yasir-Sheriff

As discussed here https://github.com/salesforce/lwc/issues/2101 there is a weird black border appearing on the chevron when the user clicks on the spot I highlighted in red in the picture below.

![image](https://user-images.githubusercontent.com/55927613/99957961-69dbac00-2d80-11eb-9d73-b3f7112622b3.png)

The user has to click on this region.

![image](https://user-images.githubusercontent.com/55927613/99958123-b6bf8280-2d80-11eb-8027-a57e3ff7c66e.png)

When there is no chevron button appearing the situation is worse. The user can click anywhere in the region to the left of the label and the weird black border appears.
![image](https://user-images.githubusercontent.com/55927613/99958916-15393080-2d82-11eb-9942-7015a3c312c4.png)

> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

**Comment by kflournoy-sf** [comment]
Hi @AllanOricil - I'll comment over in the LWC repo also, for transparency. We actually have this bug already identified, and it's on the appropriate team's roadmap to address. Thanks for the report though, please do keep sending in things like this!
