### ISSUE TITLE
@brandonferrua any alternative for this we need green color success?

### ISSUE THREAD

**Issue by chandra2ravi** [salesforce-ux/design-system#678]
@brandonferrua any alternative for this we need green color success?
@stefsullrew

_Originally posted by @chandra2ravi in https://github.com/salesforce-ux/design-system/issues/603#issuecomment-468892196_

**Comment by chandra2ravi** [comment]
Please fix this, we need this feature.

**Comment by kflournoy-sf** [comment]
Hi @chandra2ravi - our apologies for the delay in answering your question, thank you for posting again!

Unfortunately at this time, [lightning-helptext](https://developer.salesforce.com/docs/component-library/bundle/lightning-helptext/documentation) only supports the following states (colors): 

- bare - This is the default variant and doesn't need to be specified.
- error - Provides a red fill for the icon
- inverse - Same as the bare variant
- warning - Provides a yellow fill for the icon

There is a ticket on the specific team's roadmap to address icon colors across components, however that is not in place right now.

You may want to investigate the icon [Styling Hooks in the design system](https://www.lightningdesignsystem.com/platforms/lightning/styling-hooks/) to see if this might be a path forward for your project at this time.
