### ISSUE TITLE
Salesforce Sans characters don't get read by VoiceOver in Safari

### ISSUE THREAD

**Issue by bcronin2** [salesforce-ux/design-system#679]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

Repro page (done with a GitHub page; I wasn't able to get custom fonts to work in a codepen environment): 
https://bcronin2.github.io/sf-sans-contenteditable/
GIFs are included at the end of the issue.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

When moving the caret in `contenteditable` regions in Safari and using the VoiceOver screenreader, characters rendered in the Salesforce Sans font face do not get read out by the screenreader. 

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

The [Salesforce Sans](https://github.com/salesforce-ux/design-system/tree/master/assets/fonts/webfonts) web fonts.

> Are any specific browsers impacted by this bug?

Safari (14.0.2 at least; likely others) on MacOSX.

> Which version of the Salesforce Lightning Design System are you using?

I believe it's whatever the latest is (the issue was observed with the latest version of the fonts).

> What steps and/or code are needed to reproduce this issue?

Any contenteditable HTML element whose text is rendered with the Salesforce Sans font face seems to reproduce the issue:

```html
<div contenteditable="true">Editable Text</div>
```

Open a page with the contenteditable element in Safari, activate VoiceOver (CMD+F5), and move the cursor through the editable text using left/right arrows.

> What did you expect to happen?

VoiceOver should read out each character it encounters.

> What actually happened?

VoiceOver reads out "edit text" for each character it encounters.

-------

Two GIFs are included below showing the difference in VoiceOver readout in the Salesforce Sans case and the default font case.

Default (characters get read out):
![default case](https://user-images.githubusercontent.com/6960884/103688827-4b53fd80-4f47-11eb-8ed8-ad71c4dd849d.gif)

Salesforce Sans (characters do not get read out; VoiceOver just repeatedly says "edit text"):
![salesforce sans case](https://user-images.githubusercontent.com/6960884/103688821-48f1a380-4f47-11eb-921d-3d257d26f0d4.gif)

**Comment by jessebrack** [comment]
Heya @bcronin2, thanks for filing the issue. Since this was originally raised internally (and we're discussing and tracking it there) and this repo is for the open-source version of SLDS, I'm going to close this issue, so we're not creating duplicates. But this write-up is excellent, and we'll be using it for our investigation.
