### ISSUE TITLE
SVG Image Optimization

### ISSUE THREAD

**Issue by loadedsith** [salesforce-ux/design-system#683]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="740" alt="Screen Shot 2021-03-12 at 2 02 16 PM" src="https://user-images.githubusercontent.com/1950785/110992466-91f51800-833b-11eb-8e7f-d7b7efcbc8af.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I've noticed that many of the icons in this page could be optimized better. Just little stuff really, removing whitespace, editor comments ```<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->``` and ids like this one ```id="Layer_1"``` These examples are from: action/add_contact.svg.

You can call this low priority, but it's low effort too. Before being minfied, lines with "Adobe" in them could be removed with a find expression like this (warning untested):

    name '*.svg' -exec sed -i ''  '/Adobe/d;' {} \;

At the very least, new icons should be optimized before being added to the pack.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Icons.

> Are any specific browsers impacted by this bug?

All.

> Which version of the Salesforce Lightning Design System are you using?

The assets were the currently available icons on https://lightningdesignsystem.com/icons/

> What steps and/or code are needed to reproduce this issue?

Open any SVG in a text editor, or run them through an optimizer like SVGO

> What did you expect to happen?

I expect SVGs (and all images) for serving on the web to be optimized.

> What actually happened?

SVGs are not optimized.

**Comment by alexiscordova** [comment]
Hi @loadedsith,

Thanks for bringing this to our attention. We usually pass along whatever we get from our icon designers, but you're right; we can definitely look into adding a build step that optimizes our SVGs. I'll pass this along to the relevant teams. Thanks again!

**Comment by jessebrack** [comment]
Apologies @loadedsith, it was unintentional, thank you for pointing it out. I'm labeling and reopening the issue so we can continue to track it 👍 .

**Comment by kflournoy-sf** [comment]
@loadedsith - heads up that we're working on it! :)

**Comment by kflournoy-sf** [comment]
Hi @loadedsith - just an FYI that we are pushing out optimization for existing icons in our next release, and have made changes to the process so that any new icons will be following these specifications. Thanks again for weighing in, we appreciate it!
