### ISSUE TITLE
input with slds-input-has-fixed-addon is not correctly align to left (maybe double padding left 33% is applied) and input align depend on label's length

### ISSUE THREAD

**Issue by elvisbegovic** [salesforce-ux/design-system#684]
> Are any specific browsers impacted by this bug?

all browser but i tried on last chrome version  Version 89.0.4389.114 (Build officiel) (64 bits)

> Which version of the Salesforce Lightning Design System are you using?
current Site: Version 1.2.28 | Framework: Version 2.14.3. Last Updated on March 30th 2021, 12:05 pm.

I tried on site https://lightningdesignsystem.com/components/form-element/#Horizontal-Alignment-2

Here is screenshot :
![image](https://user-images.githubusercontent.com/2789203/114428491-902da700-9bbc-11eb-8487-6eff68f8ff25.png)

> What steps and/or code are needed to reproduce this issue?

Add this input in all your form, you will see alignement problem 
```
<div class="slds-form-element slds-form-element_horizontal ">
	<label class="slds-form-element__label" for="text-input-id-1" id="fixed-text-label">Input with addon</label>
	<div class="slds-form-element__control slds-input-has-fixed-addon">
		<span class="slds-form-element__addon" id="fixed-text-addon-pre">$</span>
		<input type="text" id="text-input-id-1" placeholder="Placeholder text…" aria-labelledby="fixed-text-label fixed-text-addon-pre fixed-text-addon-post" class="slds-input">
			<span class="slds-form-element__addon" id="fixed-text-addon-post">euro</span>
		</div>
	</div>
```

> What did you expect to happen?

align left at 33% like other independent of label length 

> What actually happened?

it seems with slds-input-has-fixed-addon  another padding left of 33% is added and the position always depend of label lenght... annoying

**Comment by elvisbegovic** [comment]
What you think about dat my friend @engai ?

**Comment by kflournoy-sf** [comment]
@elvisbegovic Yup, that doesn't seem to work, does it? Am I correct in assuming you'd want to see something like this?

<img width="921" alt="Screen Shot 2021-04-12 at 3 59 01 PM" src="https://user-images.githubusercontent.com/53910308/114453918-07a50b80-9ba8-11eb-84d2-9c3c504ad11d.png">

**Comment by kflournoy-sf** [comment]
@elvisbegovic I didn't, I just hacked an existing example I had to make sure I was understanding your issue. Let me pull together some actual code for you.

**Comment by elvisbegovic** [comment]
cc/ @kflournoy-sf ?

**Comment by elvisbegovic** [comment]
any input here

**Comment by stefsullrew** [comment]
Hi @elvisbegovic — big apologies for dropping the ball on this one. 😬 This is definitely a bug based on flexbox. I've created an internal ticket to have the team take a look. Thank you for your report! Cheers

**Comment by laurensuh** [comment]
Hi @elvisbegovic just an update, we are still on track to have this addressed. If you need help with a temporary fix let us know. I will go ahead and close this as this is now in our work backlog. Thanks!
