### ISSUE TITLE
Inline spacing styling hooks for slds-button variants do not inherit from the default slds-button hooks

### ISSUE THREAD

**Issue by mblase75** [salesforce-ux/design-system#687]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![Screen Shot 2021-07-15 at 11 56 42 AM](https://user-images.githubusercontent.com/1172660/125827438-1a8493e8-e55d-4f1d-9aed-380117a51583.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Styling hooks for button left/right padding (inline spacing) don't inherit properly for variants. If the styling hooks for a button variant are not specified, the styles for that button variant fall back to `--lwc-spacingMedium` instead of the default button styling hooks.

For instance, say I want to alter the padding of all buttons on my site. Left/right padding styles are determined using the following styles:

```
.slds-button_outline-brand {
    padding-left: var(--sds-c-button-outline-brand-spacing-inline-start, var(--lwc-spacingMedium,1rem));
    padding-right: var(--sds-c-button-outline-brand-spacing-inline-end, var(--lwc-spacingMedium,1rem));
}
.slds-button {
    padding-left: var(--sds-c-button-spacing-inline-start, 0);
    padding-right: var(--sds-c-button-spacing-inline-end, 0);
}
```
If `--sds-c-button-outline-brand-spacing-inline-start` isn't set (which it's not by default), it will fall back to `--lwc-spacingMedium`, or 1rem. Setting a value for `--sds-c-button-spacing-inline-start` will be ignored entirely, which doesn't appear to be the intended outcome. This applies to all variants of `slds-button` (inverse, neutral, etc.) on both left and right sides (`inline-start`, `inline-end`).

It would be more appropriate for the variant to inherit from `--sds-c-button-spacing-inline-start` before `--lwc-spacingMedium`:

```
.slds-button_outline-brand {
    padding-left: var(--sds-c-button-outline-brand-spacing-inline-start, var(--sds-c-button-spacing-inline-start, var(--lwc-spacingMedium,1rem)));
    padding-right: var(--sds-c-button-outline-brand-spacing-inline-end, var(--sds-c-button-spacing-inline-end, var(--lwc-spacingMedium,1rem)));
}
```

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

This applies to [all of the `slds-button_*` variant classes](https://www.lightningdesignsystem.com/components/buttons/#CSS-Class-Overview).

> Are any specific browsers impacted by this bug?

Issue is not browser-specific and affects all browsers that support custom variables.

> Which version of the Salesforce Lightning Design System are you using?

Release 2.15.8

> What steps and/or code are needed to reproduce this issue?

In a theme or lwc css file, set `--sds-c-button-spacing-inline-start` and/or `--sds-c-button-spacing-inline-end` to a new value and add a `<button class="slds-button slds-button_outline-brand">Sample</button>` or any `<lightning-button>` with a variant specified. The left/right padding will not change, because the variant styling hooks override the default button styling hooks.

> What did you expect to happen?

When `--sds-c-button-outline-brand-spacing-inline-start` is not set, then the button should inherit its `padding-left` from `--sds-c-button-spacing-inline-start`. Likewise for `padding-right` using `--sds-c-button-outline-brand-spacing-inline-end` and `--sds-c-button-spacing-inline-end`.

> What actually happened?

When `--sds-c-button-outline-brand-spacing-inline-start` is not set, `padding-left` falls back to `--lwc-spacingMedium` and `--sds-c-button-spacing-inline-end` is ignored entirely. Likewise for `padding-right`, `--sds-c-button-outline-brand-spacing-inline-end` and `--sds-c-button-spacing-inline-end`.

**Comment by alexiscordova** [comment]
Hi @mblase75, apologies for the delay! When this issue was filed we were not yet using CSS Custom Property reassignment, but in our next release, we will be addressing this. Thanks for bringing this to our attention! If after we release our next version this still doesn't work, please reach out.
