### ISSUE TITLE
Trojan virus detected in node_modules

### ISSUE THREAD

**Issue by Chrinov** [salesforce-ux/design-system#689]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

![image](https://user-images.githubusercontent.com/48407575/129066308-b4cc9a39-85cf-4f98-b0c6-cfffbf51e9ed.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I have downloaded the repository and executed npm install command.
During execution, Bitdefender Total Security  threw a warning about an infected file (warning attached)

I don't know if it's a false positive but it's better to be safe than sorry.
> Bitdefender Total Security build:

25.0.23.81

> Which version of the Salesforce Lightning Design System are you using?

v2.15.9

> What steps and/or code are needed to reproduce this issue?

0. Use an antivirus software (Bitdefender? I haven't checked with other security programs)

1. Clone or download the Salesforce Lightning Design System repo
2. Run npm install within the root of the project directory

> What did you expect to happen?

Not having a potential trojan horse detected with the repo

> What actually happened?

Gen:Heur.JS.Downloader.3 trojan horse was detected in one of the modules

**Comment by alexiscordova** [comment]
@Chrinov thanks for bringing this to our attention; however, I ran a virus scan on my end and came up empty. Did you run this on a fresh install? Would you mind running `npm ci` (which'll wipe out your existing node_modules directory) and scanning again? Thanks

**Comment by alexiscordova** [comment]
@Chrinov have you happened to try this with any other virus scanners? I don't think we have access to Bitdefender, but we can try this on Windows somehow. So far I'm not seeing this virus on our end but I'll keep looking into it

**Comment by alexiscordova** [comment]
Unfortunately, we have not been able to reproduce this, so I'm going to close out this issue. Please reopen if you run into further issues.
