### ISSUE TITLE
Need example for applying animations

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#69]
There's a set of named animations listed here:
http://www.lightningdesignsystem.com/design/motion

However, there's no documentation as to their class names, or how to apply them.

**Comment by rickschmoo** [comment]
Thank you for the request. This is on our roadmap.

**Comment by rickschmoo** [comment]
Thank you for the request. This is on our roadmap.

**Comment by kaelig** [comment]
Closing this as animation class names haven't made it into the codebase in the past year.
