### ISSUE TITLE
New SLDS UI Kit - Adobe Creative Suite (Adobe XD)

### ISSUE THREAD

**Issue by bransonsmall** [salesforce-ux/design-system#697]
Hey Trailblazers!

I've noticed there are UI Kits for Sketch, Figma, and Framer [_Salesforce UI Kits_](https://www.lightningdesignsystem.com/tools/overview/#UI-Kits-Resources) but haven't seen anything mentioned for the Adobe Creative Suite, specifically Adobe XD.

I think including Adobe XD would be a great addition to the UI Kits, here's my quick rational:

1. Sketch - Only available to MacOS users
2. Adobe XD - Allows for interactive prototyping, animations - seamlessly connecting to the rest of the Adobe Creative Suite
3. Adobe XD - Has a new Library system for sharing components, cloud based
4. Adobe XD - Available on both MacOS and Windows

I'm a passionate UX Designer and I'd be happy to assist on the project! I've recreated a few components in the past and would love a comprehensive library in XD. 

Best regards!
Branson

**Comment by aweibel** [comment]
Hey @bransonsmall, Adobe XD is great. We don't have many customers that use it currently so it hasn't been a priority to create just yet. We support libraries for [Figma](https://www.figma.com/@salesforce), [Sketch](https://www.lightningdesignsystem.com/tools/sketch/), and [Framer](https://github.com/framer/salesforce-lightning.framerfx). You can always import those libraries into XD.
