### ISSUE TITLE
Salesforce Orgs are missing --lwc-cardColorBorder

### ISSUE THREAD

**Issue by AllanOricil** [salesforce-ux/design-system#698]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

This causes the deploy problem described here

https://github.com/forcedotcom/cli/issues/1197

**Comment by jessebrack** [comment]
Hey @AllanOricil, I responded to the original issue you linked. I'm closing this one to keep the discussion within the original thread.
