### ISSUE TITLE
Missing Component in Documentation

### ISSUE THREAD

**Issue by markjackson92** [salesforce-ux/design-system#7]
Under the Design tree on the "Displaying Data" page there seems to be missing component. The "Discussion Feed" mentioned on this page is not featured under the Components tree. How would I implement something like the "All Updates" discussion feed in my app?

https://www.lightningdesignsystem.com/design/displaying-data#role=regular&status=all

**Comment by topherauyeung** [comment]
Hi Mark! So glad to hear that you're reading our documentation. As of today, the Discussion Feed hasn't been built yet, but it's on our backlog of components to add to the system. If you're like to implement something like the Discussion Feed in your app, you can currently make use of our [CSS Utilities](https://www.lightningdesignsystem.com/components/utilities), the [Media Object](https://www.lightningdesignsystem.com/components/media-objects) and [Grid System](https://www.lightningdesignsystem.com/components/grid-system), and the [Design Tokens](https://www.lightningdesignsystem.com/resources/tokens) to replicate the Lightning styles.

**Comment by brandonferrua** [comment]
Added component for 0.10.0
