### ISSUE TITLE
SLDS in Visualforce - Some common.css rules are not being overridden

### ISSUE THREAD

**Issue by djlimbs** [salesforce-ux/design-system#70]
I'm running some prototype JS code for SLDS inside of a Visualforce page using the "salesforce-lightning-design-system-vf" CSS file and am finding that common.css is still adding CSS that breaks the visual design. I attached a screenshot of common.css' "ul li" rule that adds padding when SLDS does not need it.

<img width="1564" alt="screen shot 2015-10-23 at 10 57 41 am" src="https://cloud.githubusercontent.com/assets/4561661/10698130/05afebfc-7975-11e5-9f6d-c8b44bc9f3fb.png">

**Comment by stefsullrew** [comment]
I'm working on a fix for this now... thanks for the heads up.

**Comment by kyleheddon** [comment]
Are there any updates on this? I'm also experiencing this using version 2.0.3

**Comment by kaelig** [comment]
Thank you for getting back to us on this, @kyleheddon. Looks like our fix needs additional specificity. We'll look into it shortly.

cc @stefsullrew

**Comment by stefsullrew** [comment]
It appears to me that this component isn't scoped? We cannot get rid of common.css, but scoping should raise the specificity and override things that need to be overridden. 

@kyleheddon - can you give us an example of how you're creating your components in VF?

**Comment by kaelig** [comment]
Closing this as the discussion hasn't seen any activity. Feel free to reopen if further details and findings come up!
