### ISSUE TITLE
Invalid link in Getting Started documentation

### ISSUE THREAD

**Issue by technicallynick** [salesforce-ux/design-system#713]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.
![image](https://user-images.githubusercontent.com/24781863/154574906-072150d7-76e4-42f5-a6fd-79d12251956a.png)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

The "lightning" link found in the [Getting Started Guide](https://www.lightningdesignsystem.com/getting-started/) subsection "Lightning" leads to a 403 Forbidden error from an NGINX server. I suspect that this link is supposed to point to https://www.lightningdesignsystem.com/platforms/lightning/overview/ instead of https://www.lightningdesignsystem.com/platforms/lightning/

**Comment by laurensuh** [comment]
Hi @technicallynick thanks for letting us know this issue! You'd be happy to know this was recently addressed and will be fixed in our next site release. Cheers!
