### ISSUE TITLE
Combobox Width Shrinks/Grows to Fit Content (was previously fixed)

### ISSUE THREAD

**Issue by Danny-Salvadori** [salesforce-ux/design-system#714]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

It seems that as of Spring '22, the width of comboboxes has changed from static to responsive based on the selected option: 
![combobox-width-2](https://user-images.githubusercontent.com/61005919/154700886-8092fc11-051f-4dda-ae8b-58226dc2cb6e.jpg)

This can have weird implications for GUIs that were reliant on them having a fixed width:
![consequences](https://user-images.githubusercontent.com/61005919/154700572-054ac121-5045-4f87-a4f8-02a62e336e9c.jpg)

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

Change was first observed after Spring '22 release. Not sure if it's a bug or intentional change, but couldn't find any mention of it in release notes. 

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Only observed with \<lightning-combobox>.

> Are any specific browsers impacted by this bug?

Unknown. Identified on Chrome (94.0.4606.71)

> Which version of the Salesforce Lightning Design System are you using?

Not sure about version. Using \<lightning-combobox> in LWC components (no VF page), Spring '22 org.

> What steps and/or code are needed to reproduce this issue?

Just create \<lightning-combobox>.

> What did you expect to happen?

The combobox width is static

> What actually happened?

The combobox width is responsive to the width of the option selected.

**Comment by owenschoppe** [comment]
Thanks for identifying this. Yes, the behavior of the input changed when we updated the markup for accessibility reasons in 2.16.0 You're right that the release notes don't specifically call out the change in sizing behavior.
https://www.lightningdesignsystem.com/release-notes/

> ### Release 2.16.0 - August 12, 2021
> In accordance with ARIA 1.2 guidance, the input was replaced with button within these components that contain select-only comboboxes:
> Datetime Picker
> Docked Composer
> Dynamic Menu
> Expression
> Global Header
> List builder
> Lookups
> Picklist
> Rich Text Editor
> Timepicker
> 

Our general recommendation for the new comboboxes is to utilize a `.slds-size_x-of-y` class on the parent to set the width. In this particular case of expressions, I'll get this flagged for the team. As a temporary solution if you set `flex-basis: 100%` on the question and choice columns in each row you'll be able to keep the combobox widths aligned.

**Comment by laurensuh** [comment]
Hey @Danny-Salvadori we have added this to our backlog and thank you for bringing this to our attention. Im going to go ahead and close this issue out as @owenschoppe has provided you a temporary fix until this is fully addressed. Please comment here if you have any further questions. Thanks again.
