### ISSUE TITLE
Bug: Accordion component SASS fails to compile with Angular

### ISSUE THREAD

**Issue by sfbrafkind** [salesforce-ux/design-system#716]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/93352262/158229815-813cd0cd-677a-4b40-9c3a-ac0e03223a71.png">

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

A bug where importing the SASS styles leads to a compilation error due to an undefined operation with the accordion component.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Yes, the accordion component.

> Are any specific browsers impacted by this bug?

n/a

> Which version of the Salesforce Lightning Design System are you using?

2.17.5

> What steps and/or code are needed to reproduce this issue?

Initialize an Angular project including the design=system library. Then add the following line to a project .scss file `@import 'node_modules/@salesforce-ux/design-system/scss/index';` and finally run `ng serve` to build the project.

> What did you expect to happen?

Successful compilation.

> What actually happened?

> ./src/app/sidebar/sidebar.component.scss?ngResource - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Undefined operation "0.75rem * -1".
>    ╷
> 43 │     #{$spacing-small} * -1)));
>    │     ^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   node_modules/@salesforce-ux/design-system/scss/components/accordion/base/_index.scss 43:5  @import
>   node_modules/@salesforce-ux/design-system/scss/components/_index.scss 40:3                 @import
>   node_modules/@salesforce-ux/design-system/scss/index.scss 14:9                             @import
>   src/app/sidebar/sidebar.component.scss 1:9                                                 root stylesheet

Looks like the multiplication would work if it was moved inside the curly braces like `#{$spacing-small * -1}`

**Comment by laurensuh** [comment]
Hi 👋 @sfbrafkind thanks for submitting this issue. We will look into this and update you as soon as we can. Cheers!

**Comment by gbutt-tr** [comment]
I am running into the exact same issue with the exact same dependencies as specified by andrewvasilchuk. Does anyone have a good workaround?

**Comment by Dottenpixel** [comment]
@sfbrafkind @gbutt-tr what version of `sass` is being installed into your `node_modules` when you run `npm install`?

**Comment by Dottenpixel** [comment]
@sfbrafkind @gbutt-tr what version of `sass` is being installed into your `node_modules` when you run `npm install`?

**Comment by gbutt-tr** [comment]
@Dottenpixel I use sass 1.49.9 in package.json, but I am seeing 1.49.11 in package-lock.json

**Comment by sfbrafkind** [comment]
Sass v1.49.0

**Comment by Dottenpixel** [comment]
@sfbrafkind thanks! Try and install an older Sass version to see if this clears the error for you `npm install sass@1.35.2  --save-dev`. 

This is the version in the lock file. I've just recently encountered this error as well and also had `1.49.x` installed in `node_modules`. There is a coming update in the package.json that sets the `sass` to `1.35.2` rather than `^1.35.2`.

**Comment by Dottenpixel** [comment]
@sfbrafkind thanks! Try and install an older Sass version to see if this clears the error for you `npm install sass@1.35.2  --save-dev`. 

This is the version in the lock file. I've just recently encountered this error as well and also had `1.49.x` installed in `node_modules`. There is a coming update in the package.json that sets the `sass` to `1.35.2` rather than `^1.35.2`.

**Comment by gbutt-tr** [comment]
@Dottenpixel thanks this worked like a charm.

**Comment by sfbrafkind** [comment]
> There is a coming update in the package.json that sets the `sass` to `1.35.2` rather than `^1.35.2`.

Instead of restricting the version, wouldn't it be better to fix the expression by moving the multiplication inside the curly braces?

**Comment by Dottenpixel** [comment]
@sfbrafkind not at the moment, unfortunately.  We have some downstream consumers of the Sass files that we deal with that would need to be updated first. When that work is done, we'll look to update the `sass` version in the project here too.

**Comment by Dottenpixel** [comment]
@sfbrafkind not at the moment, unfortunately.  We have some downstream consumers of the Sass files that we deal with that would need to be updated first. When that work is done, we'll look to update the `sass` version in the project here too.

**Comment by Dottenpixel** [comment]
Thank you @sfbrafkind @gbutt-tr for bringing this problem to light. I'm closing this issue as the Sass version change looks to be the fix. I'll look to prioritize the `sass` version restriction we've made internally for release here.
