### ISSUE TITLE
Line height tokens

### ISSUE THREAD

**Issue by carlotademier** [salesforce-ux/design-system#721]
Good morning,

I am contacting you to get some help on how line height tokens are build. I checked that you can send this message to the team, this is not actually a bug.

You have 4 line height tokens in your design system and I would like to know what is the formula because this is my understanding for these two:

$line-height-heading 👉🏼 any heading font size * 1,25
$line-height-text 👉🏼 any heading font size * 1,5

I am the owner of a design system and my idea is to create one line hight token that works for all sizes. We have strict guidelines and don't need more at them moment. This is the formula: 

**$line-height-base:** any font-size * 1.15;

I would like you to share with me how your line height tokens work and if my formula can apply please.

I am looking to hear from you.

Regards,

Carlota

--

**Comment by laurensuh** [comment]
Hi @carlotademier , the 1.5 or 1.25 numbers referenced by our variables are unitless. 
However these tokens are reserved to be used for line-height. For ex. `line-height: $line-height-text (translates to value of 1.5)` as referenced in our [doc site](https://www.lightningdesignsystem.com/design-tokens/#category-line-height).

If you wanted to add your own design token you can do so and not use the ones provided by us.
