### ISSUE TITLE
Radio buttons do not work on iOS

### ISSUE THREAD

**Issue by jimpdx** [salesforce-ux/design-system#73]
Radio buttons can not be selected in iOS 9 in either the Chrome or Safari browser

**Comment by stefsullrew** [comment]
Hi @jimpdx - which version of SLDS are you using? iOS9 introduced a CSS selector bug with UIWebView (The bug doesn't seem to exist in Safari or in WKWebView). I have filed it with Apple. Meanwhile, we added a fallback into our codebase as of our 0.10.1 release last week. If you don't have that, I would suggest migrating to it. Cheers!

**Comment by jimpdx** [comment]
Hi @stefsullrew we upgraded to 10.1 last week, as soon as it came out. Is this included in the Visualforce stylesheet?

**Comment by dsanvita** [comment]
@stefsullrew @jimpdx We are using the slds0101 unmanaged package in a winter 16 dev org, in a visualforce page running as a quick action inside the SF1 iOS (9.1) app.  Clicking on checkboxes or radio buttons does not select them.  They are selected properly on Chrome desktop (simulating an iOS device in the debugger), and on Android 5 SF1.

**Comment by jimpdx** [comment]
@stefsullrew I sent you an email about this issue (assuming srewis@ is your SFDC email).
