### ISSUE TITLE
Additional body styles added in Lightning are causing us layout problems. 

### ISSUE THREAD

**Issue by Andykennedy** [salesforce-ux/design-system#74]
The styles in question only take affect in Lightning and are coming from: AuraAlohaContentFrame.css

Scroll bars appear in our apps due to overflwo:auto. 

The additional padding is pushing some of our larger apps slightly off their page.

```
html body.sfdcBody {
    font-family: 'Helvetica';
    color: #3c3d3e;
    background: none transparent;
    margin: 0;
    padding: 10px 20px 0 20px;
    height: 100%;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
}
```

Are these the final styles we can expect in Lightning or can / will they be changed moving forwards?

**Comment by stefsullrew** [comment]
Hi @Andykennedy - the AuraAlohaContentFrame.css is not related to the Lightning Design System's CSS. I'm unsure of whether that may change or not.

**Comment by chuyler** [comment]
@Andykennedy did you get to the bottom of this?  We just started testing in Lightning and the extra padding around the body of our VisualForce pages is not necessary.  I didn't know if there was a specific setting to turn this off.  I tried setting applyBodyTag="false" on the page but it didn't change anything.

**Comment by bikrambhuyan** [comment]
Hello Guys,

We are running into the exact same issue. Could anyone suggest what is the suggested solution for this problem?

Appreciate your help.

Thanks,
Bikram.

**Comment by stefsullrew** [comment]
Though this is not from the design system and I can't test, you _could try_ adding: `box-sizing: border-box;` to the `body` element (if you can control that area of the page). Without it, it's likely the padding is being added to the 100% height, causing scrolling.

**Comment by nawlbergs** [comment]
```
<apex:page standardController="Account">
  <apex:canvasApp applicationName="SuccessPro_Widget" height="300px" width="100%" parameters="{sfObjectName:'Account', sfObjectId:'{!Account.id}'}"/>
</apex:page>
```
When we create this visual force page in lightning ... i has massive amounts of padding around it when the visual force page is added to a layout.

Adding the following tags... did remove SOME of the padding... but it is still an issue and looks bad.
```
<apex:page standardController="Account" showHeader="false" sidebar="false" standardStylesheets="false" applyHtmlTag="false" applyBodyTag="false">
  <apex:canvasApp applicationName="SuccessPro_Widget" height="300px" width="100%" parameters="{sfObjectName:'Account', sfObjectId:'{!Account.id}'}"/>
</apex:page>
```

When we create the pages ... add them to layouts in the non-lightning ui... these issues do not occur... i currently have two vf-pages in an account layout.. one created in lighting and one in old ui...  the lighting one has the padding issue.

**Comment by nawlbergs** [comment]
@stefsullrew how ... in my example... would i add that style? the apex page does not allow style tags.
