### ISSUE TITLE
Popover Expected Markup/Interactions

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#75]
Is there any additional information on the expected markup/interactions on popovers like what you have for modal documentation? I imagine there are aria attributes that will need to be set when they are shown and dismissed.

I would also like to know whether or not clicking away from the popover will close it, and if only one popover is allowed to be open at any given time.

**Comment by kevinberonilla** [comment]
I see the latest release has this documented. You can close this issue if there is nothing more to add.

**Comment by stefsullrew** [comment]
Thank you @kevinberonilla! :)
