### ISSUE TITLE
Unable to download the libraries using the Sketch Plugin

### ISSUE THREAD

**Issue by lakpriyad** [salesforce-ux/design-system#755]
Unable to continue onboarding on Lightning design system plugin with Sketch. I can see the relevant libraries being added to the library list in Figma (figure 1) but, it keeps on spinning the "update" icons in the plugin window and the "Done" CTA button is disabled. (figure 2) 

I cannot continue to end the onboarding process (on the plugin) and use the plugin window as shown in the youtube video.
https://www.youtube.com/watch?v=bm1ZhGoNIG4

please advise. 

I'm using Sketch Version 97.2 (173315)

Figure 1
<img width="586" alt="Figure 1" src="https://github.com/salesforce-ux/design-system/assets/142733716/bba8ed78-df10-4aa8-a0c8-a292ddfe3c95">

Figure 2
<img width="450" alt="Figure 2" src="https://github.com/salesforce-ux/design-system/assets/142733716/0ca69220-62a2-4461-8b50-b89809695945">

**Comment by Dottenpixel** [comment]
Thanks for your post @lakpriyad. Unfortunately, the Sketch plugin is [no longer supported](https://github.com/salesforce-ux/design-system-sketch/blob/master/README.md).
