### ISSUE TITLE
Salesforce helpOrbs missing from Object fields

### ISSUE THREAD

**Issue by Andykennedy** [salesforce-ux/design-system#76]
When viewing the fields on an object in Lightning, we've noticed the Salesforce helpOrbs are not displaying. 

When hovered over, the helpOrbs provide a tooltip which contains help text for that field.  

![helporb](https://cloud.githubusercontent.com/assets/15361057/10823856/86486f84-7e55-11e5-8ade-2b35eeb0c4e5.png)

Were they removed on purpose for Lightning / will they be added back moving forward?

**Comment by Andykennedy** [comment]
Just found the following in the release notes:

>Field-level help isn’t widely available in this release. You can’t define custom help text or add field-level help for fields in custom objects.

Which I'm assuming is in reference to our helpOrbs.

http://releasenotes.docs.salesforce.com/en-us/winter16/release-notes/lex_gaps_limitations_data_access.htm

**Comment by stefsullrew** [comment]
Hi @Andykennedy — I believe your question is actually for Lightning Components rather than the Lightning Design System... is that correct?

**Comment by kaelig** [comment]
Closing this as it is a month old. @Andykennedy: feel free to reopen the issue if you require further assistance.
