### ISSUE TITLE
Broken links on release notes page

### ISSUE THREAD

**Issue by jimpdx** [salesforce-ux/design-system#77]
The links under "New Components" for 0.10.0 are broken (should be relative to /)

http://www.lightningdesignsystem.com/release-notes

**Comment by FabienTaillon** [comment]
There is another minor broken link in the "Getting Started" page for Visualforce in the following section:
"When using the component sample code from this site, be sure to replace all static resource paths with the Visualforce URLFOR syntax, as summarized in the FAQ".

*FAQ* is an hyperlink that seems correct (http://www.lightningdesignsystem.com/faq#how-do-i-link-to-visualforce-static-resources-like-stylesheets-and-icons), however when the page opens, an additional **/** is added to the url between *faq* and *#* (http://www.lightningdesignsystem.com/faq/#how-do-i-link-to-visualforce-static-resources-like-stylesheets-and-icons) which breaks the redirect.
That's so minor that I didn't open an issue for that, but as there is one now, just adding this to the list :)

**Comment by brandonferrua** [comment]
Thanks for the headsup

**Comment by stefsullrew** [comment]
The Release notes links are fixed (thanks @jimpdx)... I'm investigating the link to the FAQ.

**Comment by kaelig** [comment]
Looks like the links in the faq all work (tested in the latest version of Chrome). Thanks again for reporting this and feel free to reopen in case these issues reappear.
