### ISSUE TITLE
Build support for Windows

### ISSUE THREAD

**Issue by cosminnicula** [salesforce-ux/design-system#78]
Are there any plans to support Windows as dev environment?

**Comment by stefsullrew** [comment]
What kind of trouble are you running into?

**Comment by cosminnicula** [comment]
All the npm tasks are pointing to .sh files. Is there a way to make them run under Windows?

**Comment by kaelig** [comment]
@cosminnicula thank you for asking. There is no plan to support Windows in the near future. In the mean time, I suggest running it using Linux in a virtual machine. Let me know how this goes for you.
