### ISSUE TITLE
currentSelection for Menu.List and PickList

### ISSUE THREAD

**Issue by cosminnicula** [salesforce-ux/design-system#79]
In the ```Menu``` -> ```PickList``` example (https://github.com/salesforce-ux/design-system/blob/winter-16/ui/components/menus/flavors/picklist/index.react.example.jsx), the ```Menu.Item``` tells to its parent via ```context``` (either to the ```Menu.List```, or if it does not exist, to the ```PickList```) to store inside the state the ```currentSelection```. In order to get the ```currentSelection```, one must look either into the ```Menu.List``` or into the ```PickList```, which is a bit cumbersome especially if more parents can host the ```Menu.Item```. Is this the code design that you'll rely on for the rest of the components?

**Comment by stefsullrew** [comment]
Our site runs on React, but the components are not made to use in this state. There are some other projects that I hope will make that available at some point. Is that what you're asking for?

**Comment by cosminnicula** [comment]
I'm particularly interested in using the React components in my private projects and I'm curios to find if Salesforce wrote the React components for evolving them so that companies or individuals would use them in their own projects outside Salesforce. Assuming that you want to make these React components production ready, I just posted the previous question on `currentSelection` to see if this was the intended design, or maybe there are some better alternatives.

Also can you explain a bit what the "other projects" are all about? Does this mean that Salesforce will loose interest in the design-system project and it's underlying React implementation? Are the "other projects" a replacement for the React components?

**Comment by stefsullrew** [comment]
No, no... not losing interest. Quite the opposite. We'll write you directly.

Cheers!

**Comment by rickschmoo** [comment]
This type of interaction is not supported by SLDS.
