### ISSUE TITLE
Lookups - Single Select populated input functionality?

### ISSUE THREAD

**Issue by djlimbs** [salesforce-ux/design-system#82]
We are implementing Lookups and would like to know the intended functionality when the icon or label of a selected item in the lookup's input (the underlined "Pied Piper" and icon to its left in the example):

<img width="1047" alt="screen shot 2015-11-02 at 3 29 11 pm" src="https://cloud.githubusercontent.com/assets/4561661/10894861/81c9725e-8176-11e5-8517-c701cc0e3a0b.png">

From what we understand when comparing it with the New Lightning Experience, only clicking the "X" removes the item. Is this correct? Thanks

**Comment by brandonferrua** [comment]
Correct
