### ISSUE TITLE
Support relative paths to static assets

### ISSUE THREAD

**Issue by mbeard** [salesforce-ux/design-system#83]
Currently, the compiled CSS `salesforce-lightning-design-system.css` assumes that static files (icons, fonts, images) reside under an `/assets` directory.

Can these references be updated to relative paths instead of absolute paths to allow more flexibility in how these files are hosted in consuming apps.

For example
src: url("../fonts/webfonts/SalesforceSans-Light.woff2")
 
instead of 
src: url("/assets/fonts/webfonts/SalesforceSans-Light.woff2")

**Comment by cosminnicula** [comment]
+1

**Comment by kaelig** [comment]
Thank you for your patience, this was just fixed in the latest version of the Lightning Design System!

See full release notes: https://www.lightningdesignsystem.com/release-notes/
