### ISSUE TITLE
Problem with slds-scrollable--x on iPhone 5s

### ISSUE THREAD

**Issue by bearman17** [salesforce-ux/design-system#84]
I created a component that uses the slds-scrollable--x style. On my iPhone 5s device, the area to which this class is applied is truncated and no scroll bar appears. This is not a problem on the Desktop. (To test this on the Desktop, I shrank the max-width applied to the area and confirmed that the scroll bar appeared.)

I saw similar complaints on the Stack Exchange. For example:

http://salesforce.stackexchange.com/questions/81959/scrollbars-in-lightning-components

Thank you,
Andrew

**Comment by brandonferrua** [comment]
Could you provide a screenshot of the issue?

**Comment by bearman17** [comment]
Hi Brandon,
Thank you for responding. Here is a screenshot of the component. It is meant to display the days of the week. On my iPhone 5s, the display is truncated and no scrollbar appears.

Thank you,
Andrew

![scrollable_component](https://cloud.githubusercontent.com/assets/8472182/11001328/937e3dbc-845b-11e5-9977-9f115e939c10.PNG)

**Comment by bearman17** [comment]
I updated my copy of the salesforce-lightning-design-system.css file. And now I do get a scrollbar! Here is an updated screenshot:

![new_screenshot](https://cloud.githubusercontent.com/assets/8472182/11227224/99b1b38a-8d39-11e5-942a-b11f7e3f2691.PNG)

Unfortunately, I can't use it to scroll on my iPhone.

Thank you

**Comment by bearman17** [comment]
Salesforce has created a "Known Issue" for this problem. Please click the "This Issue Affects Me" button if you're interested:

https://success.salesforce.com/issues_view?id=a1p30000000ePVNAA2

**Comment by kaelig** [comment]
Thank you @bearman17.

Note that this issue is a duplicate of #81
