### ISSUE TITLE
SLDS Menus -> PickList: selected DropdownItem style

### ISSUE THREAD

**Issue by cosminnicula** [salesforce-ux/design-system#88]
I want to change the styling of this...

![image](https://cloud.githubusercontent.com/assets/582616/10968972/d8e9b68a-83cd-11e5-8163-0a3c40462d91.png)

...into this:

![image](https://cloud.githubusercontent.com/assets/582616/10968987/116664d6-83ce-11e5-9bdf-c505a27de2d7.png)

You can achieve this by overriding the following CSS classes:

```
.slds-dropdown__item > a {
  padding-left: 0px;
}

.slds-dropdown__item .slds-icon {
  height: 0px;
  width: 0px;
}

.slds-dropdown__item.slds-is-selected {
  background-color: #30afd6;
  font-weight: 400;
}
```

Even though you visually hide the `SVG`s within each `li`, the HTML `SVG` markup is still there and by hiding it through CSS feels a bit hacky.

Is there a better way to do this? Also, would you consider refactoring the code for `DropdownItem` so that it would be more flexible?

**Comment by stefsullrew** [comment]
Hi @cosminnicula - Since you're in control of your DOM, I'd recommend removing the SVG altogether if you're not going to use it. 

Once you delete it, you'll only need to override our `.slds-is-selected` styling to get the look you want.

Cheers
