### ISSUE TITLE
SLDS Menus -> PickList: keep focus after selecting an Item

### ISSUE THREAD

**Issue by cosminnicula** [salesforce-ux/design-system#89]
Related to #87

When the PickList is focused, I want to have a glowing border like below:

![image](https://cloud.githubusercontent.com/assets/582616/10969347/84aea6cc-83d0-11e5-8f46-bc6c1e763da1.png)

When the PickList is opened and I select an Item from the DropdownList, normally the DropdownList should collapse and the focus should be kept on the PickList. I can achieve this through the following code:

```
import React from 'react';
import ReactDOM from 'react-dom';
import PickList from 'ui/components/picklists/index.react';
const PT = React.PropTypes;

class MyPickList extends PickList {
  constructor(props) {
    super(props);
  }
  itemSelected (item) {
    super.toggleHidden();
    super.itemSelected(item);
    ReactDOM.findDOMNode(this).firstChild.focus();
  }
}

module.exports = MyPickList;
```

The only problem with this approach is that, when you select an Item the focus is lost from the PickList and then programmatically focused back, which causes a short flickering.

Same questions: is there a better way to achieve this? Would you consider a refactor to make this more flexible?

**Comment by rickschmoo** [comment]
These components are not intended for consumption outside the SLDS website.
