### ISSUE TITLE
Label verses Data Value Proportional Spacing 

### ISSUE THREAD

**Issue by ErikatUCI** [salesforce-ux/design-system#90]
The space occupied between a label and an input field is 1/3 for the label and 2/3's for the input field.  The same is true between a horizontal-label and a horizontal-detail.  Can this proportion be adjusted to something like 1/2 : 1/2, or even 2/3 : 1/3?  If not that would be a nice enhancement.  Especially in columns of data where a relatively long label is next to a small number.

**Comment by kaelig** [comment]
Thank you @ErikatUCI for asking. We'd appreciate a prototype or a mock up of what you are trying to achieve to make the use-case easier to understand. Can you please do that?

**Comment by ErikatUCI** [comment]
This example below shows an slds-card, one of several on a page.  The labels such as "Lifetime Total Fundraising" are long and wrap to a second line.  The data values such as "$127,004.00" are short and leave almost half the width of the card blank.  This is because the slds-dl--horizontal__label takes 1/3 of the space while the slds-dl--horizontal__detail takes 2/3's of the space.  I would like to use the space on the second half of the card so that the labels would not have to wrap.  To do so the label would take 2/3's of the space and the values only 1/3 of the space.
![giving summary](https://cloud.githubusercontent.com/assets/15222385/11591556/816a74ee-9a4d-11e5-8ada-434599faf2fe.JPG)
![giving summary code](https://cloud.githubusercontent.com/assets/15222385/11591829/7ab59c8a-9a4f-11e5-84ff-69d2cc5b3460.JPG)

**Comment by kaelig** [comment]
Thank you @ErikatUCI, this is much clearer.

Let me assign @brandonferrua to your case and let him take it from here.

**Comment by stefsullrew** [comment]
Hi @ErikatUCI. Our default pattern is a 1/3 to 2/3 division. However, I can certainly see the differing needs. I have just revised the code (which will be updated in the next release) so that you can either place a sizing helper on the `<dt>` or write an override class. If you go with the override, I would suggest placing a class on the `<dl>` and then using a descendant selector.

```.foo dt {
   width: 66%;
}```
