### ISSUE TITLE
SLDS Menus -> PickList: more screen reader accessibility

### ISSUE THREAD

**Issue by cosminnicula** [salesforce-ux/design-system#92]
Screen reader accessibility is more or less about `aria-` and `role` attributes.

A) There is a category of attributes that could be implemented both by the consumer or by the library:
* implemented by the consumer (example for `aria-owns`):
```
'use strict';

import React from 'react';
import Menu from 'ui/components/menus/index.react';
import PickList from 'ui/components/picklists/index.react';
import componentUtil from 'app_modules/ui/util/component';
const pf = componentUtil.prefix;
const PT = React.PropTypes;

class App extends React.Component {
  constructor(props) {
    super(props);
    this.menuId = "menu-01";
  }
  render() {
    return (
      <div className='demo-only demo-only--dropdown' style={{height: '240px'}}>
        <PickList ref="refPickList" label="Select an Option" aria-expanded={false} aria-owns={this.menuId}>
          <Menu ref="refMenu" className={pf('dropdown--left')} id={this.menuId}>
            <Menu.List ref="refMenuList">
              <Menu.Item href="#">Option A</Menu.Item>
              <Menu.Item href="#">Option B</Menu.Item>
              <Menu.Item href="#">Option C</Menu.Item>
              <Menu.Item href="#">Option D</Menu.Item>
              <Menu.Item href="#">Option E</Menu.Item>
              <Menu.Item href="#">Option F</Menu.Item>
              <Menu.Item href="#">Option G</Menu.Item>
              <Menu.Item href="#">Option H</Menu.Item>
              <Menu.Item href="#">Option I</Menu.Item>
              <Menu.Item href="#">Option J</Menu.Item>
              <Menu.Item href="#">Option K</Menu.Item>
              <Menu.Item href="#">Option L</Menu.Item>
            </Menu.List>
          </Menu>
        </PickList>
      </div>
    );
  }
}
module.exports = App;
```
* implemented by the library (example for `aria-owns`):
as a consumer, you only need to specify the `Id` for the `PickList`, and the `PickList` will take care for you to properly set the `aria-owns` attribute and it's corresponding `Menu` id. This approach is more convenient for the consumer.

B) There is another category of attributes that make more sense to be implemented by the library. For example, `aria-activedescendant` reflects the focused `DropdownItem`, which is tightly related maybe to the state of the `DropdownList`.

Of course, there are a lot of attributes that need to be took into consideration for a PickList (Dropdown): `aria-owns`, `role`, `aria-busy`,  `aria-activedescendant`. Take a look here http://www.w3.org/WAI/PF/aria-practices/#combobox

Is this something that will be considered in terms of future developments and PRs?

**Comment by rickschmoo** [comment]
We are always looking to enhance accessibility. Please let us know if you have specific suggestions.
