### ISSUE TITLE
"PickList" component not available in the release version 0.11.0

### ISSUE THREAD

**Issue by santosharigi** [salesforce-ux/design-system#94]
The component "pick-list" is removed from the Lightning Design System in release 0.11.0, which was earlier available in pre 0.10.0 releases.
Does this mean that the "pick-list" component  would not be provided as a part of salesforce LDS package any more ?  Please confirm .

**Comment by stefsullrew** [comment]
Hi @santosharigi - You'll see in the release notes that picklist and dropdowns have been consolidated under menus. I think you'll find what you need there.

Cheers
