### ISSUE TITLE
Popover header unstyled

### ISSUE THREAD

**Issue by mbeard** [salesforce-ux/design-system#97]
With version 0.11.0, the popover header is unstyled.

Here's an example of the markup I'm using:
```
<div class="slds-popover slds-nubbin--left" role="dialog">
    <div class="slds-popover__header">Header</div>
    <div class="slds-popover__body">Sit nulla est ex deserunt exercitation anim occaecat. Nostrud ullamco deserunt aute id consequat veniam incididunt duis in sint irure nisi.</div>
</div>
```

And here's a screenshot of the rendered component:
![screenshot 2015-11-12 09 22 17](https://cloud.githubusercontent.com/assets/467352/11120592/e06c87f6-891e-11e5-8084-c09f8e4c38b6.png)

**Comment by brandonferrua** [comment]
This was an incomplete spec so it was removed in favor of the popover preview panel.  

https://www.lightningdesignsystem.com/components/popovers#panels, which is the complete spec.

**Comment by mbeard** [comment]
@brandonferrua ah, ok.  it might be worth updating the docs [here](https://github.com/salesforce-ux/design-system/blob/winter-16/ui/components/popovers/flavors/base/index.react.example.jsx#L21) and remove this to avoid confusion.
