### ISSUE TITLE
Typo in directory path on https://www.lightningdesignsystem.com/getting-started/heroku/

### ISSUE THREAD

**Issue by CookingWithCode** [salesforce-ux/design-system#98]
Shown as: $ touch pubilc/index.html
Should be: $ touch public/index.html

see screenshot :)

![image](https://cloud.githubusercontent.com/assets/11881230/11124564/8b484d40-891a-11e5-856e-3f16ec1d3677.png)

**Comment by kaelig** [comment]
Good catch, @CookingWithCode, thank you very much for taking the time to report this typo.

We've amended the text, it should be visible on the website very soon.
